### ISSUE TITLE
BOM cannot read spotify paths - "handle is invalid"

### ISSUE THREAD

**Issue by az8712** [spicetify/spicetify-cli#1160]
I've recently started getting this issue, where the config and pref paths aren't being read. I changed the config and copy pasted the required paths, but they still don't get read. 
`PS C:\Users\MyUser> spicetify apply`
`spicetify v2.7.0`
`BOM: read C:\Users\MyUser\AppData\Roaming\Spotify: The handle is invalid.`
`PS C:\Users\MyUser>`

*MyUser is replaced with my user name.

**Comment by TheGeeKing** [comment]
Any update @az8712?
