### ISSUE TITLE
Installed spicetify the for the first time but dropdown menu is completely dark

### ISSUE THREAD

**Issue by hiw0** [spicetify/spicetify-cli#1177]
## ℹ Computer information

- Spotify version: 1.1.70.610.g4585142b
- Spicetify version: 2.7.1

## 📝 Provide detailed reproduction steps (if any)
Well I don't think there is any I just installed spicetify but everything I right click is extremely dark

### ✔️ Expected result
I'm hoping it registers the text as white so I am able to read it
_What is the expected result of the above steps?_

### ❌ Actual result
Its completely dark unless I hover over the setting
_What is the actual result of the above steps?_

## 📷 Screenshots

_Are there any useful screenshots?_
![image](https://user-images.githubusercontent.com/28155642/137650625-dd4e4e32-f17e-4e40-9f00-61349c5e7fcd.png)

**Comment by afonsojramos** [comment]
This may be a CSS map error, but first, what theme are you using, etc?
