### ISSUE TITLE
Change to dark mode

### ISSUE THREAD

**Issue by fiqryq** [spicetify/spicetify-cli#1181]
how to change to dark mode?

![Screen Shot 2021-10-20 at 13 37 18](https://user-images.githubusercontent.com/25787603/138040718-9cfb2d8f-d1cc-4c6f-a657-39293810be61.png)

**Comment by HypedDomi** [comment]
You need to change the Theme or the color scheme. [Here](https://github.com/khanhas/spicetify-cli/wiki/Customization) is the wiki for this

**Comment by meteorsquare** [comment]
Just in case you didn't know, in the latest Spicetify version, the folder for the Spicetify Themes and config has been changed. It's at the hidden folder ".config"

~/.config/spicetify, not anymore on ~/spicetify-data

Unless this only occurs on mine.

**Comment by ririxidev** [comment]
> Just in case you didn't know, in the latest Spicetify version, the folder for the Spicetify Themes and config has been changed. It's at the hidden folder ".config"
> 
> Finder > Go (at the menu bar) > Go To Folder... > type in _~/.config/spicetify_ (it's not _~/spicetify-data_ anymore)
> 
> Unless this only occurs on mine.

That's indented change that will stay. So yes, it changed.

> Someone please fix the SpicetifyDefault theme 🙏

meh
