### ISSUE TITLE
Cannot detect Spotify "prefs" file location. Please manually set "prefs_path" in config-xpui.ini

### ISSUE THREAD

**Issue by ubuntupunk** [spicetify/spicetify-cli#1182]
## ℹ Computer information

- Spotify version 1.1.68.632.g2b11de83, Copyright (c) 2021, Spotify Ltd
- Spicetify version: 
spicetify v2.7.1
- OS: Ubuntu 20.04

## 📝 Provide detailed reproduction steps (if any)

1.The directory where spotify is installed:
 
```
sudo chmod a+wr /usr/share/spotify
sudo chmod a+wr /usr/share/Apps -R
```

2 `spicetify backup apply enable-devtool`
prints version and an error message.

```
spicetify v2.7.1
error Cannot detect Spotify "prefs" file location. Please manually set "prefs_path" in config-xpui.ini

```
3.
```
 cd ~ 
find | grep "spotify/prefs$"
```
returns nothing

4. `sudo spicetify backup apply enable-devtool`
returns spicetify not found

5. 

```
spicetify -c
/home/<user>/config/spicetify/config-xpui.ini
```

**Comment by slrgt** [comment]
@afonsojramos the instructions are no longer there and the instructions you listed dont say how to check where the correct location is
