### ISSUE TITLE
Theme "___" not found.

### ISSUE THREAD

**Issue by nelsonjmorris** [spicetify/spicetify-cli#1186]
## ℹ Computer information

- Spotify version: Spotify for macOS (Intel)
1.1.70.610.g4585142b
- Spicetify version: 2.7.1

## 📝 Provide detailed reproduction steps (if any)

1. Install spicetify using the steps
2. Apply themes

### ✔️ Expected result

I am able to apply different themes with spicetify

### ❌ Actual result

I get the error  "Theme ___ not found."

## 📷 Screenshots

<img width="650" alt="image" src="https://user-images.githubusercontent.com/63315007/138549183-5a120137-eeb3-4e08-8fe3-f4863d31517f.png">
<img width="696" alt="image" src="https://user-images.githubusercontent.com/63315007/138549218-3249de28-46c7-4da9-824a-46ce16d19598.png">

**Comment by Turbo0005** [comment]
I encountered this problem when working on the spaceship theme...
