### ISSUE TITLE
Folder Colours

### ISSUE THREAD

**Issue by Nerxxy** [spicetify/spicetify-cli#1188]
I don't suppose there is a way to change the colour or maybe add a slight border around folders and only folders?

Just a little ease of life thing for me since when I'm looking through my playlists and folders I don't always see the little arrow showing that its a folder.

I found [href="/folder/ (numbers and letters) ]

but I don't know if there is a way to reference all "/folder", maybe /folder/*** or something like that?

**Comment by machinemessiah** [comment]
If you want to target the anchor/link then this CSS selector will apply to all folder links in the navbar `[href^="/folder"]`
alternatively you could use `[href*="/folder"]`

For future reference, check out the full documentation for attribute selectors which you can browse [here](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors)
