### ISSUE TITLE
Home config is not persistent

### ISSUE THREAD

**Issue by Rajbir98** [spicetify/spicetify-cli#1396]
## ℹ Computer information

Windows v6.1.7601
Spotify: v1.1.76.447
Spicetify: v2.8.4
Dribbblish: v4.1.1-0e50a92

## 📝 Provide detailed reproduction steps (if any)

1. Click "Home config" button in profile menu
2. Rearrange sections as you wish
3. Click the button again to finish

### ✔️ Expected result

Config is maintained while using Spotify.

### ❌ Actual result

Even if I rearranged some sections, Spotify returns to the previous state after some minutes of usage.

**Comment by Rajbir98** [comment]
from #1284

**Comment by Rajbir98** [comment]
I lowered the greeting part of home but it still comes up

**Comment by francescoaracu** [comment]
> I lowered the greeting part of home but it still comes up

Can confirm; I think it could be a CSS-related issue, maybe some classes were changed from the previous build to the latest. In the previous one, Home config would remain intact.
