### ISSUE TITLE
Issues with FAD + Lyrics-Plus integration

### ISSUE THREAD

**Issue by stpnwf** [spicetify/spicetify-cli#1399]
## ℹ Computer information

Spotify version: 1.1.72.439.gc253025e
Spicetify version: 2.8.3
Theme name: Dribbblish

## 📝 Issues

1. Text in the Lyrics Plus + FAD integration is not very legible with some Album covers (per screenshot)
2. Pressing the Hotkey(F12) to display Lyrics Plus when Full App display window is active will make it so you are unable to click anything in Spotify. Reopening the app fixes it.

## 📷 Screenshots
![Screenshot from 2022-01-09 21-38-35](https://user-images.githubusercontent.com/81482539/148708185-80635997-b2e0-42ee-abbf-317d09f5839e.png)

**Comment by afonsojramos** [comment]
So I suppose there are two different issues present here. Not sure anything can be made about 1) as I suppose it depends on your theme right?

**Comment by afonsojramos** [comment]
@CharlieS1103 Can you help here?

**Comment by stpnwf** [comment]
> So I suppose there are two different issues present here. Not sure anything can be made about 1) as I suppose it depends on your theme right?

Yes, it is two different issues. I corrected my post to reflect it.

Well, judging by the screenshots in the v2.8.3 release and my daily use, it seems that this is not dependent on the user theme. I think the problem is that the color chosen when the album cover is dark is also a dark one(?). Legibility hasn't been an issue for me with light album colors.
