### ISSUE TITLE
Lyrics plus - add lyrics translation

### ISSUE THREAD

**Issue by GGreyCat** [spicetify/spicetify-cli#1411]
## 📝 Provide a description of the new feature
Add a foreign lyrics display translation button
The screenshot below is from the Netease music application

![y](https://user-images.githubusercontent.com/60751934/149651723-044a4193-e3b3-4302-81ed-da78d00a52b1.png)

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by afonsojramos** [comment]
How would this be implemented? If we chose to use a translation API of sorts, we would need to translate line by line, right?

**Comment by ajiou** [comment]
Netease does provide translation to Chinese.
And Musixmatch provides translation to some other language, but every user would need an API key since it's official API, and does have usage limit.

**Comment by DananaBanana** [comment]
Doesn't have to be standard, can just be an option to opt-into.

**Comment by RobinFaq** [comment]
> ## 📝 Provide a description of the new feature
> 
> Add a foreign lyrics display translation button
> 
> The screenshot below is from the Netease music application
> 
> 
> 
> ![y](https://user-images.githubusercontent.com/60751934/149651723-044a4193-e3b3-4302-81ed-da78d00a52b1.png)
> 
> 
> 
> ---
> 
> 
> 
> If you'd like to see this feature implemented, add a 👍 reaction to this post.
> 
> 

Yep

**Comment by RobinFaq** [comment]
I actually never added a comment. Not before today. Wtf man

**Comment by ChickChuck2** [comment]
API of Google translator it's a good idea? (API free)

**Comment by lixiao189** [comment]
<img width="1590" alt="image" src="https://user-images.githubusercontent.com/44799572/211440952-174dcd65-77ca-4314-9c62-b1d890906838.png">

I found that the netease API could also fetch the lyrics translation in `tlyric.lyric`. Apart from that, the translation also have time stamp. I think that just show this translation on UI can solve this problem.

**Comment by code-IM-perfect** [comment]
Was this implemented? Cuz at least for me the Translation Provider is always 'none', there is no other option.

**Comment by Aragorn-E** [comment]
It's a bit disappointing that we don't have that yet. @afonsojramos Is this still technically impractical to add?
