### ISSUE TITLE
Better prefs checking.

### ISSUE THREAD

**Issue by ohitstom** [spicetify/spicetify-cli#1461]
## 📝 Description of the new feature
Well, there are many issues myself and others have noticed with the pref checking on initial install. Most of which seem to be because the prefs file simply doesnt exist at the time of install.

I propose that if spicetify cannot find the prefs file it should open spotify in the background and check for the creation of the prefs file every x milliseconds, until its found and can be set. This is because many users come off a fresh install of spotify when installing spicetify and therefore havent given spotify enough time being open to actually create the prefs file (as its not created on install but actually from initial launch).

OR 

For the windows platform, use a static path to the prefs file regardless of if it is or isnt created, im not sure this would work as the cli depends on spotifys version and the other information in the preference file to apply themes etc, but this could be a good fallback option and then also jog the user to open spotify a bit longer before applying.

These are just some of my ideas as ive seen a lot of users in the spicetify support server with this issue and looking at some of the code it only really checks if the path exists and doesnt have any fall-back other than manual user interaction.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by CharlieS1103** [comment]
Why not just have it check for a prefs path on the running of "spicetify apply" instead of background checking and fancy stuff.

**Comment by ririxidev** [comment]
I think we can close this issue since somewhat it has been resolved in https://github.com/spicetify/spicetify-cli/commit/c68ca669ff9a18222e80b1d2d961747a8c53f4db. It is enough for now.
