### ISSUE TITLE
New/missing css colors

### ISSUE THREAD

**Issue by JulienMaille** [spicetify/spicetify-cli#1468]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```markdown
- Spotify version: 1.1.78.765.g5ea20b00
- Spicetify version: 2.9.0
```

### 📝 Description

It looks like latest Spotify has added new colors which are not "spicetified".
Namely `--background-highlight` and `--background-press`

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/182520/153677385-9d539895-4873-4fc9-ab5a-7574e2c2a52d.png)

**Comment by xerta555** [comment]
This kind of thing can happen, i've also seen it with these CSS selectors. You can set their values like this in your `user.css` theme file:

.encore-dark-theme .encore-bright-accent-set
{
  --background-highlight: yourcolor !important;
  --background-press: your color !important;
}
