### ISSUE TITLE
Themes are not being read CORRECTLY [macOS]

### ISSUE THREAD

**Issue by ObviouslyPurplee** [spicetify/spicetify-cli#1470]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```markdown
- Spotify version: Latest
- Spicetify version: Latest
```

### 📝 Description

I'm on macOS *latest version*
The 2.9 Spicetify seems to not be working correctly, It's not reading the "Themes" right, whatever I do it turns into a dark purple. Tried reinstalling and restoring, backing up, and more. Previous versions are blank and don't function! 

### 📸 Screenshots

![Screen Shot 2022-02-12 at 8 16 51 PM](https://user-images.githubusercontent.com/96754035/153734177-b79fc9bf-8c2c-44d3-b7a3-b9b4fd83a0f5.png)

**Comment by huhridge** [comment]
Are you installing themes manually or using marketplace?
If manually, did you add the theme to config, and made sure that the theme is present in the `.config/Themes` folder?

**Comment by Firnschnee** [comment]
I have the same problem. After updating spicetify to 2.9 my old manual installed theme did not work anymore. 
The theme was present at the themes folder and added in the config, just like before the update. 

The themes from the marketplace work just fine though.

**Comment by ObviouslyPurplee** [comment]
> 

I'm doing this manually, yes the theme name is correct in `.config/Themes`
Oh, there are themes in the marketplace? I had no idea about that. How does that work?

**Comment by CharlieS1103** [comment]
@ObviouslyPurplee I believe that there's a brief description of how it works in the readme but more or less it just removes the default user css and replaces it with one fetched from the installed theme (along with the color.ini)

**Comment by huhridge** [comment]
> I have the same problem. After updating spicetify to 2.9 my old manual installed theme did not work anymore. The theme was present at the themes folder and added in the config, just like before the update.
> 
> The themes from the marketplace work just fine though.

huh, very weird, I am also on macOS, and every thing seems to work fine for me

**Comment by afonsojramos** [comment]
I believe this is related to the `current_theme` variable in the config, no? 🤔

**Comment by ObviouslyPurplee** [comment]
As you can see, the `color_theme` is right, I personally wanted Ziro, light-green. But since that didn't work, I tried to use a different theme. That one didn't work either, It still turned Dark Purple! 

![Screen Shot 2022-02-14 at 3 24 50 PM](https://user-images.githubusercontent.com/96754035/153940761-0dd20e3d-51bc-47e2-8205-3d4826f717e5.png)

**Comment by ririxidev** [comment]
U sure you edit config in `~/.spicetify` folder?

**Comment by CharlieS1103** [comment]
@ObviouslyPurplee  odds are you have a theme installed on marketplace and simply need to uninstall it, if you're still struggling with this issue feel free to leave another comment.
