### ISSUE TITLE
[shuffle+] Forbidden error on shuffle, but on one computer only

### ISSUE THREAD

**Issue by lowgos** [spicetify/spicetify-cli#1472]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```markdown
- Spotify version: 1.1.77.643.g3c4c6fc6
- Spicetify version: 2.9.0
```

### 📝 Description

# Bug

When clicking on "Play with Shuffle+" I get a 403 ForbiddenError

![Screenshot from 2022-02-15 12-03-50](https://user-images.githubusercontent.com/22097902/154050002-0046cced-c01b-474b-9afe-d4cb35007ad0.jpg)

# Expected

The playlist should start and a toast saying "Shuffle x items!" should show.

![image](https://user-images.githubusercontent.com/22097902/154050412-2ed54f4b-6546-4da7-9bbb-4e32404a5e21.png)

# Details

I'm on Arch Linux with Gnome as my DE. Both are up-to-date.

I've had the problem before in previous versions (and other people too as the error came in some other issues).
But the problem has been fixed through updates (thanks for that btw).

The real problem is that right now I've just setup a new computer with the same configuration and the bug has reappeared.

## Timeline

The timeline goes has following:

- Setup my laptop spicetify-cli (in 2021 I think), no problem
- Updated my laptop Spotify and spicetify-cli, problem appeared for the first time
- Updated spicetify-cli later, problem disappeared
- Bought and setup a new desktop computer (2022), instantly setup spicetify-cli, bug comes back

## What I've tried

:heavy_check_mark: I used the latest spicetify-cli
:heavy_check_mark: I used the latest Spotify flatpak
:heavy_check_mark: it matches the version I use on my laptop (which still works)
:heavy_check_mark: I re-installed the Spotify flatpak
:heavy_check_mark: I rebooted
:heavy_check_mark: I tried with the spotify aur package
:heavy_check_mark: I tried a `spicetify-cli restore backup apply` on both machines and the problem persists only on the desktop

### 📸 Screenshots

# Versions on my desktop

![spicetify-versions-tiptop](https://user-images.githubusercontent.com/22097902/154048804-35be7da5-0614-4670-98c5-f2a39353212d.png)

# Versions on my laptop

![spicetify-versions-taptop](https://user-images.githubusercontent.com/22097902/154048980-52db7daa-0c4b-4283-ace6-54e37f6c3146.png)

**Comment by huhridge** [comment]
when does this specifically happen, or does this happen every time you try to play something with shuffle+? also are you on discord? it makes the communication a bit easier imo

**Comment by lowgos** [comment]
On my desktop it happens everytime I try to use the button for Shuffle+.
I just join the Discord as you asked. Though I will try to write up the solution here if we find one for posterity 😉

**Comment by afonsojramos** [comment]
This seems like something that changed from `1.1.77` to `1.1.78`, however, there is not much we can do here as the solution will likely be to wait for the new version on aur.

**Comment by lowgos** [comment]
I don't have the `1.1.78` :sweat_smile: neither on my laptop nor my desktop as stated in the screenshots and the version summary.

**Comment by itsmeow** [comment]
You can try downgrading spicetify to 2.8.x until you find a version that works. You can also [download older versions](https://github.com/khanhas/spicetify-cli/commits/master/Extensions/shuffle%2B.js) of shuffle+.js and replace them in your install manually.

**Comment by lowgos** [comment]
I will try that when I find time for it thanks!

**Comment by lowgos** [comment]
I've found what was the problem and it is linked to the shuffle+ code I think @huhridge 

After some time without reproducing the issue I thought it was fixed by an update.

I had the problem today and the problem seem to be that when trying to Shuffle+ a playlist without having played anything before (an empty/null Spotify queue) then the 403 error triggers.

Playing something normally and then shuffling+ work wonders !
