### ISSUE TITLE
Custom apps non-functional

### ISSUE THREAD

**Issue by TheMayhem6328** [spicetify/spicetify-cli#1480]
### 🔍 Have you checked Spicetify.app page for your issue?

- [x] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```markdown
- Spotify version: 1.1.79.763.gc2965cdf | On Windows 11 Build 22000.527
- Spicetify version: 2.9.0 | Also tried with vDev built from #1476
```

### 📝 Description

I can't use custom apps like lyrics or new releases. Screenshot gives out nothing useful, but upon opening any custom app, this comes up in console:
 
```
TypeError: Cannot read properties of undefined (reading 'History')
    at Module.spicetify-routes-new-releases (spicetify-routes-new-releases.js:13:17)
    at Function.o (xpui.js:1:1670258)
a @ xpui.js:1
onError @ xpui.js:1
componentDidCatch @ xpui.js:1
Ua.o.componentDidCatch.n.callback @ vendor~xpui.js:29
Vi @ vendor~xpui.js:29
ji @ vendor~xpui.js:29
Rs @ vendor~xpui.js:29
t.unstable_runWithPriority @ vendor~xpui.js:29
hi @ vendor~xpui.js:29
Cs @ vendor~xpui.js:29
gs @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
t.unstable_runWithPriority @ vendor~xpui.js:29
hi @ vendor~xpui.js:29
yi @ vendor~xpui.js:29
gi @ vendor~xpui.js:29
bs @ vendor~xpui.js:29
Un @ vendor~xpui.js:29
```

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/56154436/154663441-b8dd337d-4ce6-4338-94e4-c9d983e9b7fa.png)

**Comment by hetnialoevr48** [comment]
Just came here to say I have the exact same issue

**Comment by qzeos** [comment]
i have the same issue too

**Comment by CharlieS1103** [comment]
Run spicetify upgrade (keep in mond a few custom apps may need updates to restore full functionality)

**Comment by aqilrryn** [comment]
im experiencing the same issue too

**Comment by aqilrryn** [comment]
> Run spicetify upgrade (keep in mond a few custom apps may need updates to restore full functionality)

![image](https://user-images.githubusercontent.com/78351464/154796987-7e2102ff-9222-4fba-97ee-e1ccc76e8123.png)

**Comment by ImQrispy** [comment]
updating to 2.9.1 fixed this for me. make sure to run this: spicetify restore backup apply

**Comment by guttitto** [comment]
I get "Something went wrong" specifically after trying to click on a release or playlist both on New Releases and Reddit custom apps

**Comment by afonsojramos** [comment]
This has been fixed in https://github.com/spicetify/spicetify-cli/pull/1510 and https://github.com/spicetify/spicetify-cli/pull/1511, however, we have not made a new release with the fixes yet. Expect it soon.
