### ISSUE TITLE
Home screen and playlists won't load

### ISSUE THREAD

**Issue by SoCoolMuchGitHub** [spicetify/spicetify-cli#1483]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [x] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Latest | Windows 10
- Spicetify version: Latest
```

### 📝 Description

After updating both Spotify and Spicetify, none of the UI will actually load.

### 📸 Screenshots
![Screenshot 2022-02-18 154928](https://user-images.githubusercontent.com/59752651/154759351-1d1ab837-7b97-4b10-ac5f-69e5b1bc3d0e.png)

**Comment by machinemessiah** [comment]
Could one of you open the devtools (ctrl+shift+i) and post whatever appears in the console here?

**Comment by PhantomOffKanagawa** [comment]
It appears that for one reason or another the Comfy theme is leading to the under-main-view having a display: none; css
My hotfix was to add the below code (copied from the css causing it to disappear, replacing none with block) to my user.css
```css
.Root__main-view > div:first-of-type > div, .desktoproutes-homepage-takeover-ad-hptoComponent-parentContainer {
    display: block;
}`

**Comment by ITzERI** [comment]
thx phantom

**Comment by SoCoolMuchGitHub** [comment]
Thank you very much for this fix, Phantom.
