### ISSUE TITLE
Blank experimental features

### ISSUE THREAD

**Issue by IamNickerson** [spicetify/spicetify-cli#1485]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.87.612
- Spicetify version: 2.10.1
```

Description:

Step 1: Install Spotify to the latest Version.
Step 2: Install Spicetify.
Step 3: After installing and running Spicetify go to Spotify and go to the context menu of Spotify and you will see a text written experimental features click on that. 

**Result:**  It will be a blank screen and it will show only the title showing Experimental features.

Recording of the Result:

https://user-images.githubusercontent.com/61643704/174284422-01dfb5f0-af99-40ec-b2fd-b538fbf86192.mov

Screenshot of the Result:

![image](https://user-images.githubusercontent.com/61643704/154783852-98c7cbae-59ee-4c3b-bb2d-c1d93d5b30bc.png)

**Comment by huhridge** [comment]
anybody who knows how to fix this here: 
1.1.78 xpui.js file, the methods are there,

![Screenshot 2022-02-20 at 14 35 32](https://user-images.githubusercontent.com/67046436/154835742-1531d9e2-46f8-4177-a84b-4a7f5bc04f4e.jpg)

in 1.1.79 xpui.js, the methods are not hooked into (or maybe they have changed no clue),

![Screenshot 2022-02-20 at 14 35 48](https://user-images.githubusercontent.com/67046436/154835765-c708bc34-7393-49bd-88bc-d14bc8d58174.jpg)

**Comment by davimaiaa** [comment]
still waiting for a solution 🥺

**Comment by IamNickerson** [comment]
We just have to wait it needs a lot of time to fix.

**Comment by davimaiaa** [comment]
that's reasonable i'm okay

**Comment by IamNickerson** [comment]
Ok How long are we getting the fix @huhridge ?

**Comment by IamNickerson** [comment]
(Because this is taking a lot of time than we anticipated )

**Comment by Mahas1** [comment]
Same error occurring on my installation on macOS 12.2.1 - It works on Windows 11, though

**Comment by MRoiban** [comment]
still waiting for a solution,  any news on a fix?

**Comment by IamNickerson** [comment]
Nope

**Comment by IamNickerson** [comment]
> still waiting for a solution,  any news on a fix?

I feel like they are gonna remove it when the next spicetify version comes.

**Comment by Mcfly2340** [comment]
> > still waiting for a solution,  any news on a fix?
> 
> I feel like they are gonna remove it when the next spicetify version comes.

if so, than the fix enhance extension won't work anymore any i really wanted that one to work

**Comment by IamNickerson** [comment]
> > > still waiting for a solution,  any news on a fix?
> > 
> > 
> > I feel like they are gonna remove it when the next spicetify version comes.
> 
> if so, than the fix enhance extension won't work anymore and i really wanted that one to work

Okay

**Comment by afonsojramos** [comment]
The experimental features are something that comes from Spotify. We just activate it with Spicetify, but at the moment we are not being able to.

**Comment by fernandossmm** [comment]
Spotify has a list of "Things we're working on", which they have in the code but are not shown to the general public. Spicetify used to take that list and change what you could activate in your local machine, but Spotify seems to have disabled it (maybe because of Spicetify? who knows).

**Comment by IamNickerson** [comment]
Oh Okay.

**Comment by ririxidev** [comment]
I believe they did the same with experimental features like with DevTools. They probably just took it out from stable builds and only are enabled in dev builds from my guessing.

**Comment by afonsojramos** [comment]
I've found these on the Local Storage... Might these be related? 🤔 

![image](https://user-images.githubusercontent.com/19473034/165201353-745d19ab-48fc-4a05-b92d-095136de6978.png)

**Comment by IamNickerson** [comment]
They look like keys for isEnached

**Comment by JamesGordonII** [comment]
has anyone got this working for 1.1.84.716.gc5f8b819

**Comment by IamNickerson** [comment]
Didn't check make sure you making an issue if your spicetify is not working with that version

**Comment by Mcfly2340** [comment]
Has anyone ever experienced this icon on pc? I'm using dribbblish theme and playing a playlist with enhanced enabled on my phone, but i've never got this icon on pc before.


![image](https://user-images.githubusercontent.com/71077562/173080631-83f8de66-4aa8-4ac8-b010-1ebb80ae02d1.png)

**Comment by IamNickerson** [comment]
Make an issue of this in the spicetify themes repository not here

**Comment by IamNickerson** [comment]
> IMO, if Spotify did remove their feature toggle list, the option should be taken out from Spicetify too and close this issue. It's been marked as stale too many times and there's no fix in sight, is there?

There will be some fix it just needs a lot of time i don't get it why they still have the experimental features tab if they remove it i will close this issue.

**Comment by Mcfly2340** [comment]
> Make an issue of this in the spicetify themes repository not here

Wasn't I talking about an experimental feature? Enhance isn't available normally, right?

**Comment by IamNickerson** [comment]
But you mention it is happening because of theme right?

**Comment by IamNickerson** [comment]
> So, we are going to disable injecting JavaScript that enabled experiments for time on in next release. Sorry that we didn't find any clues yet to make it working again.

👍

**Comment by kyrie25** [comment]
Experimental Features are back! (#1865) And it seems to work on as far back as `1.1.84`. Expect it in the nearest future release :)

**Comment by IamNickerson** [comment]
Yup it is back on the latest Version of Spotify
![image](https://user-images.githubusercontent.com/61643704/186131698-d8507c02-c4ee-470c-a009-c57a3db04371.png)

**Comment by kyrie25** [comment]
> Yup it is back on the latest Version of Spotify

**Comment by kyrie25** [comment]
> Yup it is back on the latest Version of Spotify

Latest version of Spicetify, and it should work on supported Spotify versions of that release also.

**Comment by IamNickerson** [comment]
Okay
