### ISSUE TITLE
When i use the  "spicetify backup apply",it stucked.

### ISSUE THREAD

**Issue by SuperLangdon** [spicetify/spicetify-cli#1486]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: v1.1.78.765.g5ea20b00
- Spicetify version:2.9.1
Windows 11
```

### 📝 Description

When i use the 
> spicetify backup apply

It stuck on
>Fetching remote CSS map for newer compatible tag version: master

What should i do？

### 📸 Screenshots

![Snipaste_2022-02-19_18-57-11](https://user-images.githubusercontent.com/21187253/154798092-d7157889-435b-4da7-bf2b-da0840f8dca4.png)

**Comment by ohitstom** [comment]
Commented so that i can get updated as this progresses, interested in what the problem is.

**Comment by SuperLangdon** [comment]
> Commented so that i can get updated as this progresses, interested in what the problem is.

by the way
I used ur [spicetify-easyinstall](https://github.com/ohitstom/spicetify-easyinstall),but the error same.

**Comment by ohitstom** [comment]
Yeah if its a spicetify problem then it wont change using the installer, theres a limit to what failsafes i can realistically implement, and as theres no errors or really any information to go off this is one of those limits xd

If you find out what is causing it i'll add that fail safe though!

**Comment by afonsojramos** [comment]
I'm pretty sure this will end up being a DNS problem or you using a VPN that blocks github or something.

**Comment by BreakingTV** [comment]
Hey, got the same error...
checked DNS,
checked the code and got the URL from where it should fetch the CSS road-map "https://raw.githubusercontent.com/spicetify/spicetify-cli/master/css-map.json"

I can Curl it, I can open it in a browser but still the script is stuck at that point...
