### ISSUE TITLE
Home Menu always fails to load on first launch

### ISSUE THREAD

**Issue by rlaphoenix** [spicetify/spicetify-cli#1492]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 2.9.1
- Spicetify version: Spotify for Windows 1.1.79.763.gc2965cdf

Windows 11 64-bit
```

### 📝 Description

Begin with no config, no backups, empty Extracted folder.

1. Install Spotify `1.1.79.763`.
2. Open Spotify and Login.
3. `spicetify backup apply`
4. Spotify gets closed and reopened, and you will be greeted by the screenshot seen below.
6. Clicking reload page fixes it, until you close it.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/17136956/154874327-70af9d8a-5d21-43c5-b7e8-1c21c9e086aa.png)

**Comment by afonsojramos** [comment]
Unfortunately, we cannot continuously support previous versions of Spotify, and even though it should work, since you are using Spicetify `v2.9.0`, I have not seen any reports of this happening in the current version. As such, I'd recommend upgrading both Spotify and Spicetify and checking if the bug still persists.

**Comment by rlaphoenix** [comment]
I've updated to `v2.9.1` and to 1.1.79.x and it still happens.

**Comment by rlaphoenix** [comment]
If you install the adblock extension within Spicetify Marketplace, then no matter what the home page never ever loads, ever. You can click reload as many times as you want and it keeps erroring.

**Comment by rlaphoenix** [comment]
This still happens.

**Comment by afonsojramos** [comment]
Can you update to the latest version and check?

**Comment by ririxidev** [comment]
Can't reproduce on latest version (v2.9.5). 
Closing this issue since we didn't get response from original issue author.

---
Environment:
```markdown
- spotify 1.1.81.604.gccacfc8c
- Windows 11 Pro Insider Preview Build 22593.1
- spicetify v2.9.5
```

**Comment by afonsojramos** [comment]
@ririxidev the bot is automatically closing these, but thanks anyway!

**Comment by rlaphoenix** [comment]
This doesnt happen to me anymore after a fully fresh install, including completely deleting anything spicetify-related. It may have been caused by an extension not by a theme or spicetify itself.
