### ISSUE TITLE
Webnowplaying.js still not working with Spicetify

### ISSUE THREAD

**Issue by ZacheryMcLaughlin** [spicetify/spicetify-cli#1494]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Feb 2022 version
- Spicetify version: v2.9.1
```

### 📝 Description

webnowplaying.js is not working with the spicetify client/Monstercat visualizer. The name of the song and the song photo appear, but the audio information is not being collected to be used by, say, an audio visualizer. Not sure exactly what is causing the issue besides newer versions of Spotify messing things up.

**Comment by HerrKnarz** [comment]
I also have that issue with the monstercat visualizer but for me the artist/song information and album cover aren't showing either. Webnowplaying.js isn't working for me since the spotify 1.1.79 update. I just updated to spicetify 2.9.1 and it's still the same. The old workaround with commenting out a line in webnowplaying.js isn't working any more. It has to be something else then I guess.

**Comment by rbond6002** [comment]
Same issue, and like HerrKnarz said, commenting out that one bit doesn't seem to fix it. No info at all is received (song title, song progress, album art) and playback controls don't work
Spotify Version: 1.1.79.763.gc2965cdf
Spicetify: 2.9.1

**Comment by zeeropatience** [comment]
hey i had the same issue as well and i've managed to fix it. im currently on spotify 1.1.79.763 and spicetify 2.9.1. what i did was edit the whole webnowplaying.js file with this code: https://github.com/spicetify/spicetify-cli/issues/983#issuecomment-912990783 

it didn't fix the issue, however after deleting and reinstalling monstercat visualizer again, **every** feature works fine. hope this info helps somehow. i don't really know what i'm doing.

**Comment by ThisIsSesco** [comment]
Yeah, Webnowplaying.js has stopped working for me again this morning. I'm on the latest versions of both Spicetify and Spotify. Tried running "spicetify apply backup" but with no luck. Could it possibly be connected to the error of "Cannot find symbol for Custom app React symbols"?

**Comment by afonsojramos** [comment]
Well, for sure that at the moment it is. Check #1514 for the updates!

**Comment by uzervlad** [comment]
I believe, 2.9.2 has fixed the issue

**Comment by afonsojramos** [comment]
Awesome, glad it is fixed. Will close it now!
