### ISSUE TITLE
Crossfade not working in Spicetify

### ISSUE THREAD

**Issue by davimaiaa** [spicetify/spicetify-cli#1497]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.79.763
- Spicetify version: 2.9.1
- Windows 11
```

### 📝 Description

Crossfade function is not actually working since I upgraded Spicetify to the current version. When I try to put it to 5s and get the page refreshed, a random number shows up rather than 5s and the crossfade simply doesn't work, as if it's not enabled.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/67204261/155046919-3eb09f25-9841-4e75-9092-315bec475d3b.png)

**Comment by afonsojramos** [comment]
Can you run `spicetify restore` and replicating the process to see if it still happens?

**Comment by davimaiaa** [comment]
> 

I just did, but unfortunately it continues to happen :( 
![image](https://user-images.githubusercontent.com/67204261/155195892-6dac779e-ce6c-409c-8ae3-13f1a4e5a22a.png)

**Comment by afonsojramos** [comment]
If after the `spicetify restore` it continues to happen, then for sure that it is not Spicetify's fault. Maybe it is you platform or something, try reinstalling Spotify.
