### ISSUE TITLE
spicetify: command not found

### ISSUE THREAD

**Issue by jamescastells** [spicetify/spicetify-cli#1498]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for macOS (Intel)
1.1.79.763.gc2965cdf
- Spicetify version: 2.9.1
- macOS Monterrey 12.2.1 (21D62)
```

### 📝 Description

1. Open a terminal and run:

`curl -fsSL https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.sh | sh`

2. The next output is shown:

DOWNLOADING    https://api.github.com/repos/khanhas/spicetify-cli/releases/latest
DOWNLOADING    https://github.com/khanhas/spicetify-cli/releases/download/v2.9.1/spicetify-2.9.1-darwin-amd64.tar.gz
######################################################################## 100.0%-######################################################################## 100.0%
EXTRACTING     /Users/jamescastells/.spicetify/spicetify.tar.gz
REMOVING       /Users/jamescastells/.spicetify/spicetify.tar.gz

spicetify was installed successfully to /Users/jamescastells/.spicetify/spicetify

Please restart your Terminal to have spicetify in your PATH.
Then you can run:
'spicetify --help' to get started

3. Restart the terminal.

4. Type `spicetify`

5. `-bash: spicetify: command not found`

**Comment by TheMayhem6328** [comment]
Have you tried adding it to PATH manually? While this is supposed to automatically happen, adding it manually can act as a band-aid solution.

**Comment by afonsojramos** [comment]
@zlederman @jamescastells What is your rc file? Do you not have `.bashrc` in `~`? Also, why do you use bash on MacOS?

**Comment by jamescastells** [comment]
Changing to zsh instead of bash solved the problem. I never had changed it and this machine has been upgraded various times through different versions of macOS. Previous versions used bash as default; if the machine is upgraded, it still uses bash, even though new versions on clean installs use zsh.

To change to zsh, visit: https://support.apple.com/en-us/HT208050

**Comment by afonsojramos** [comment]
Either way, it is weird, because, in theory, we already add to the path of the `.bashrc`... Anyway, glad it is solved!

**Comment by jatin0jha** [comment]
same here guys
sh: line 52: spicetify: command not found

and i am doing it in zsh

**Comment by soyab-mostofa** [comment]
simply pasting the command in another terminal window worked for me.

**Comment by SizemoreSystem** [comment]
> `export PATH=$PATH:/home/user/.spicetify`

error Could not detect "prefs" file location
success Default config-xpui.ini generated
error Cannot detect Spotify "prefs" file location. Please manually set "prefs_path" in config-xpui.ini

**Comment by afonsojramos** [comment]
I think it is clear what you need to do @SizemoreSystem.
You can find more info [here](https://spicetify.app/docs/advanced-usage/installation).

**Comment by SizemoreSystem** [comment]
> I think it is clear what you need to do @SizemoreSystem.
> You can find more info [here](https://spicetify.app/docs/advanced-usage/installation).

Even when I can get it to work, Discord's listen along button says it's not found.
