### ISSUE TITLE
When using crossfade every second song is getting skipped

### ISSUE THREAD

**Issue by spati-hub** [spicetify/spicetify-cli#1512]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.79.763.gc2965cdf
- Spicetify version: 2.9.1
- RTX 2070S, Ryzen 5 3600, 16gb ram, win 11,
```

### 📝 Description

When using crossfade it skips every second song I tried with and without hardware acceleration and I would like to know if there is some kind of log to check if its a extension causing it.

I have following extensions installed:
-Queue Tme
-Toggle Lyrics Plus
-Volume Percentage
-WikiFly
-Spicetify-Hid-Podcasts
-Full App Display modiefied

Theme:
-Comfy

### 📸 Screenshots

![6nHdwUEa](https://user-images.githubusercontent.com/73031269/155993226-661123ec-e711-4828-b577-023e1241ca2e.png)

**Comment by spati-hub** [comment]
Forgot to ad that the song plays for ~20sec and then skips

**Comment by afonsojramos** [comment]
I'm going to say that it probably is the result of **Queue Time**.

**Comment by spati-hub** [comment]
thank you it is working now :).
