### ISSUE TITLE
Spotify update broke spicetify!

### ISSUE THREAD

**Issue by JamesGordonII** [spicetify/spicetify-cli#1516]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows 1.1.80.699.gc3dac750
- Spicetify version: 2.9.1
```

### 📝 Description

I updated my spotify like normal and went to re-apply my spicetify theme like normal and when it tried it says the custom apps retract symbols are missing

### 📸 Screenshots

![Screenshot_23](https://user-images.githubusercontent.com/82000305/156658630-44097a30-37f2-4ad0-8bab-135dd76890b5.png)

**Comment by krystofkrticka** [comment]
Duplicate of #1514
