### ISSUE TITLE
Devtools doesn't work

### ISSUE THREAD

**Issue by CharlieS1103** [spicetify/spicetify-cli#1518]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version 1.80
- Spicetify: Latest
Computer - mac catalina
```

### 📝 Description

Unfortunately for those of us on mac and Linux devices, there is no workaround, is it possible to fix? What's the strategy here?

**Comment by CalebJohnathen** [comment]
This is also the case on Windows, no idea about Linux but I'd assume so

**Comment by afonsojramos** [comment]
Can confirm that it happens on all platforms.

**Comment by CalebJohnathen** [comment]
> Can confirm that it happens on all platforms.

I just tried on Linux and it works, what distro and installation method are you using

**Comment by afonsojramos** [comment]
> I just tried on Linux and it works

Dank farrik 😂  I tested on MacOS only ahaha

**Comment by itsmeow** [comment]
My workaround (copied from #1517)
> Install Cheat Engine, attach to Spotify.exe, hit "Add Address Manually", enter `016525fd`, set value to `255`. This will enable devtool when activated. It will likely stop working on the next Spotify update. Further investigation will be necessary to create a long-term solution. The way this works is by directly modifying the memory of the Spotify executable browser and enabling the developer mode flag in Chromium Embedded Framework. I determined this address by disassembling and analyzing Spotify.exe using Ghidra, and determined this was the data location used to store the true/false value for developer mode.

**Comment by afonsojramos** [comment]
@CalebJohnathen just to check... Which version are you on?

**Comment by CalebJohnathen** [comment]
> @CalebJohnathen just to check... Which version are you on?

Whatever version is in the APT repository

**Comment by CalebJohnathen** [comment]
> @CalebJohnathen just to check... Which version are you on?

I just checked and the latest version on the APT repo is 1.72, its outdated

**Comment by FlafyDev** [comment]
Reloading Spotify (with `window.location.reload()`) crashes the application.
Could be that this and the developer mode flag aren't working because of a bug in Spotify with Chrome v98.0.4758.102.

**Comment by CharlieS1103** [comment]
Copied from Th3ANT in the discord:
```
- add --remote-debugging-port=9222 flag to Spotify shortcut (and maybe --no-default-browser-check... not sure)
- restart spotify (to be sure)
- open chrome (normal web browser)
- go to chrome://inspect/
- list of remote targets should appear with Spotify - Web Player entry
- click inspect
```

**Comment by misspent** [comment]
> Copied from Th3ANT in the discord:
> 
> ```
> - add --remote-debugging-port=9222 flag to Spotify shortcut (and maybe --no-default-browser-check... not sure)
> - restart spotify (to be sure)
> - open chrome (normal web browser)
> - go to chrome://inspect/
> - list of remote targets should appear with Spotify - Web Player entry
> - click inspect
> ```

When will this be fixed properly? In the meantime, I don't mind doing that, so thankyou.

**Comment by CharlieS1103** [comment]
I'm really unsure but there's a solid chance it won't be fixed properly.

**Comment by amd64fox** [comment]
Seems like they wanted to enable developer mode via settings, but something went wrong
<details>
<summary><small>Screenshot</small></summary><p>

![Снимок экрана 2022-03-11 130447](https://user-images.githubusercontent.com/62529699/157846970-9135bbfe-d227-4684-a204-fcccff917797.jpg)


</small></summary><p>

</details>

**Comment by misspent** [comment]
That's interesting, amd64fox. I never thought they'd do that, and If they were to do that, you'd think it'll be locked behind something. I'm hoping this is fixed soon.

**Comment by itsmeow** [comment]
@amd64fox How did you get that menu to show? I can't see that aside from in the source.

**Comment by amd64fox** [comment]
@itsmeow
in `xpui.js` find and delete this `if(!ye(t))return null;`

**Comment by CharlieS1103** [comment]
would it be possible to see what the setting is doing when enabled and try to patch that or something?

**Comment by xerta555** [comment]
>  in xpui.js find and delete this if(!ye(t))return null;

I confirm that it works, but it don't unlock the DevTools.
Waiting for a fix/update.

**Comment by amd64fox** [comment]
@CharlieS1103 
If this option is enabled, `app.enable-developer-mode=true` line is added to the prefs file, but the developer tools still don't work.
I'm not good with `JS`, maybe this can be fixed.

**Comment by CharlieS1103** [comment]
I mean this is a gamble but it'd be rather funny if a Spotify update fixed this issue.

**Comment by amd64fox** [comment]
this was not fixed in version `1.1.81.604.gccacfc8c`

**Comment by amd64fox** [comment]
yep

**Comment by xerta555** [comment]
> My workaround (copied from #1517)
> 
> > Install Cheat Engine, attach to Spotify.exe, hit "Add Address Manually", enter `016525fd`, set value to `255`. This will enable devtool when activated. It will likely stop working on the next Spotify update. Further investigation will be necessary to create a long-term solution. The way this works is by directly modifying the memory of the Spotify executable browser and enabling the developer mode flag in Chromium Embedded Framework. I determined this address by disassembling and analyzing Spotify.exe using Ghidra, and determined this was the data location used to store the true/false value for developer mode.

Hi, maybe you would have the memory address of DevTools for the last version of Spotify?
I ask you that because the method of using an other Chromium Devtools (https://github.com/spicetify/spicetify-cli/issues/1518#issuecomment-1060407424) is usefull, but is works partially for some stuff...

**Comment by amd64fox** [comment]
Maybe someone did not notice, but you can also enter devtools like this:
- click "log out" and close the client.
- start the client, enter via right click in devtools and minimize it.
- Enter your credentials and log in to the client.

**Comment by xerta555** [comment]
> Maybe someone did not notice, but you can also enter devtools like this:
> 
>     * click "log out" and close the client.
> 
>     * start the client, enter via right click in devtools and minimize it.
> 
>     * Enter your credentials and log in to the client.

Wow nice found it works! 👍🏻

**Comment by itsmeow** [comment]
@xerta555 

Guide to finding address for devtools:
- Open Spotify.exe with Ghidra, Analyze on default settings (this will take quite a while)
- Search -> Memory -> "app.enable-developer-mode"
- Right click address of start of string
- References -> Show References to Address
- One of the references (usually first one) will have a line in its decompiled source that looks like this:

```c
  cVar3 = FUN_00cd09a3(PTR_s_app.enable-developer-mode_011b1ac0);
  if (cVar3 != '\0') {
    FUN_00499d77(1);
  }
```

- click on FUN_00499d77 (the method inside the if statement)

Method will look like this:

```c
void FUN_00499d77(undefined param_1)
{
  DAT_0170b73e = param_1;
  return;
}
```

The address is `0170b7e3e` for Spotify 1.1.81.

**Comment by xerta555** [comment]
> The address is 0170b7e3e for Spotify 1.1.81.

Curiously in my Cheat Engine, i can't assign the `255` value for the `0170b7e3e`, i have open one of the Spotify process, but when i add the address i have the `=` symbole and ??? string but i can't set the value in it.

Would you have an idea on what happen?

**Comment by itsmeow** [comment]
Okay, so, update. I have done some more reverse engineering to figure out what has changed with the devtool access. It seems that now it **makes a web request to Spotify's account servers upon login** and checks if

1. You are an employee
2. You are an app developer

If not, it disables devtools. This logic is within Spotify.exe itself, and cannot be patched without something like Cheat Engine or a modified executable. Unfortunately, it seems there is no long term solution to this problem. Modifying the exe when spicetify applies is not possible, because the exe is signed. Any changes to it will result in Windows throwing a security error.

I can't interpret the code very well, there may be another solution, but reverse engineering compiled binaries is *extremely* hard and I'm a beginner. From the debugger breakpoints and memory analysis I found, that is all I can guess is happening.

If someone could get the app running in a sandbox and use something like MITMProxy to intercept the TLS traffic and read the requests it makes, that would be great (requests made within Spotify.exe are not viewable in DevTools network tab)

**Comment by itsmeow** [comment]
As of now, it seems the devtool will not be fixable, and Cheat Engine / logging out will be the only way to access it.

**Comment by LeCrush** [comment]
> 

As far as I understand it, getting registered as an app developer takes up 5min of your time and costs absolutely nothing. Can we get access to the dev tools through that as it would check box no. 2 of the conditions you mentioned?
(btw. I just started looking into the features and use cases of the api and they are INSANE, got lots of ideas for spicetify)

**Comment by xerta555** [comment]
> I have mistyped the address. It is 0170b73e. Be sure to select "Byte" as the size.

Effectivly with this new address i can apply the `255` value, but when i enable the custom address change in Cheat Engine, the DevTools of Spotify don't open itself.

> Okay, so, update. I have done some more reverse engineering to figure out what has changed with the devtool access. It seems that now it makes a web request to Spotify's account servers upon login and checks if

    You are an employee
    You are an app developer

>If not, it disables devtools. This logic is within Spotify.exe itself, and cannot be patched without something like Cheat Engine or a modified executable. Unfortunately, it seems there is no long term solution to this problem. Modifying the exe when spicetify applies is not possible, because the exe is signed. Any changes to it will result in Windows throwing a security error.

>I can't interpret the code very well, there may be another solution, but reverse engineering compiled binaries is extremely hard and I'm a beginner. From the debugger breakpoints and memory analysis I found, that is all I can guess is happening.

>If someone could get the app running in a sandbox and use something like MITMProxy to intercept the TLS traffic and read the requests it makes, that would be great (requests made within Spotify.exe are not viewable in DevTools network tab)

I think that we will found an other way to enable it in futur, yes the difficulty level has been get +1, but i don't think that it will be impossible to do.

**Comment by itsmeow** [comment]
@xerta555 It also shows up here.
![image](https://user-images.githubusercontent.com/10366817/161203591-adeef2ab-9a66-4b7c-8e9a-53d7853e694e.png)

**Comment by itsmeow** [comment]
@LeCrush I believe the "app developer" referred to in code is not a Spotify API developer, but an actual developer OF the Spotify App, that works for Spotify.

**Comment by ririxidev** [comment]
There is no request that checks that you are developer or tester. Since it's electron app, debug build just have devtools enabled, release build has devtools disabled. That's how it works. There's no need for any request anyway. You can't change it unless spotify gives option in config files. You need to use Memory Writer (e.g. Cheat Engine) that will change it.
```cpp
#include <windows.h>
#include <iostream>
#include <conio.h>

HANDLE process;
HWND hWnd;
int main()
{
	hWnd = FindWindowA(0, "Spotify Premium");
	if (!hWnd) {
        std::cerr << "hWnd not found." << std::endl;
    	} else {
        std::cout << "Found process" << std::endl;
	}

	DWORD pid;
	GetWindowThreadProcessId(hWnd, &pid);
	process = OpenProcess(PROCESS_ALL_ACCESS, FALSE, pid);
	if(!process) {
        std::cerr<<"Process error."<<std::endl;
	} else {
	  int address = 0x170B73E;
	  int value1 = 255;
	  int result = WriteProcessMemory(process, (LPVOID*)address, &value1, (DWORD)sizeof(value1), NULL);
	  if(result>0x00) {
                std::cout<<"Result: Success."<<std::endl;
            } else {
                std::cerr<<"Result: Error."<<std::endl;
            }
	  CloseHandle(hWnd);
	  return 0;
	} getch();

	return 0;
}
```
This cpp code will allow you to enable dev tools, don't thank me. I maybe will upload binaries with it soon.

**Comment by zjeffer** [comment]
@ririxidev I tried translating your code for use on my Linux system (using my quite limited C++ experience). The code runs successfully, but ctrl+shift+i or right click doesn't show the devtools. 

```cpp
#include <iostream>
// open
#include <fcntl.h>
// ptrace
#include <sys/ptrace.h>
// waitpid
#include <sys/types.h>
#include <sys/wait.h>

#include <vector>
#include <string>

int main() {
	// pgrep
	FILE *p;
	
	p = popen("pgrep spotify", "r");
	if (p == NULL) {
		printf("Failed to run command\n" );
		return -1;
	}

	char ch;
	std::vector<std::string> pids = {};
	while ((ch = fgetc(p)) != EOF){
		std::string id = "";
		while (ch != '\n' && ch != EOF) {
			id += ch;
			ch = fgetc(p);
		}
		pids.push_back(id);
	}
	pclose(p);

	for (int i = 0; i < pids.size(); i++) {
		char file[128];
		int pid = std::stoi(pids[i].c_str());
		sprintf(file, "/proc/%ld/mem", (long)pid);
		int fd = open(file, O_RDWR);

		if (ptrace(PTRACE_ATTACH, pid, 0, 0) < 0) {
			perror("Failed to attach to process");
			exit(EXIT_FAILURE);
		}

		if (waitpid(pid, 0, 0) < 0) {
			perror("Failed to wait for process");
			exit(EXIT_FAILURE);
		}

		off_t addr = 0x170B73E;
		int value = 255;
		if (pwrite(fd, &value, sizeof(value), addr) < 0) {
			std::cout << "Write failed" << std::endl;
		}
		std::cout << "Write success for pid = " << pid << std::endl;

		ptrace(PTRACE_DETACH, pid, 0, 0);
		
		close(fd);
	}
	
	return 0;
}
```

The output:

```
Write success for pid = 1919975
Write success for pid = 1919978
Write success for pid = 1919979
Write success for pid = 1919996
Write success for pid = 1920008
Write success for pid = 1920013
Write success for pid = 1920120
```

Am I doing something wrong?

**Comment by itsmeow** [comment]
@zjeffer the address included only works on Windows. Linux would require an alternate address to be engineered from the executable.

**Comment by itsmeow** [comment]
@ririxidev It is not an Electron app. It is Chromium Embedded Framework.

**Comment by zjeffer** [comment]
> @zjeffer the address included only works on Windows. Linux would require an alternate address to be engineered from the executable.

Following your guide with Ghidra, the memory address for my spotify installation on linux (version `1.1.80.699.gc3dac750`) seems to be `04514b90`. 
I tried this value in my script but it doesn't seem to work. Is something supposed to happen once the memory is written? Right click or ctrl+shift+i still doesn't work.

**Comment by itsmeow** [comment]
Press the three dots in the top left, Develop should show up as an option.

**Comment by zjeffer** [comment]
Hmm, I don't have those three dots, even with the default theme.

**Comment by itsmeow** [comment]
If Ctrl+Shift+I isn't working then either your memory location is wrong or your code is not functional.

**Comment by ririxidev** [comment]
> @ririxidev It is not an Electron app. It is Chromium Embedded Framework.
> 
> Also, there IS some type of additonal check, before it was just a preference load, now it checks something else, not sure if it's web based or not.

My bad, I was writing it very late. Still, there's no such a request since I was checking with proxy.

**Comment by ririxidev** [comment]
> ```c++
>  spotify
> ```

You should write to a window process only, not whole bunch of them.
I kinda don't know what can be wrong, maybe wrong address or something? I don't have much a knowledge with linux in this way.

**Comment by zjeffer** [comment]
While analysing with Ghidra, I did notice one difference:

```cpp
cVar2 = FUN_03da5900(uVar5,PTR_s_app.enable-developer-mode_03ff10a0);
if (cVar2 != '\0') {
    FUN_02003850(1);
}
```
The variable is `cVar2` instead of `cVar3`, and the `FUN_03da5900` has two arguments instead of one (see https://github.com/spicetify/spicetify-cli/issues/1518#issuecomment-1081698501).  Does this have any significance?

**Comment by ririxidev** [comment]
tbh, it will be easier to patch binaries on macOS & Linux than modifying it in memory. I will today try to patch it on macOS. I don't have access to linux atm so will not be able to do it.

**Comment by ririxidev** [comment]
Got it working with signature, no need to update address every update now:
sig is: `\xA0\x00\x00\x00\x00\xC3\xA1\x00\x00\x00\x00`, mask is: `x????xx????`
```cpp
#include <iostream>
#include "sigscan.h"

int main()
{
	LPCSTR Signature = "\xA0\x00\x00\x00\x00\xC3\xA1\x00\x00\x00\x00";
	LPCSTR Mask = "x????xx????";

	SignatureScanner SigScanner;
	if (SigScanner.GetProcess("Spotify.exe")) {
		std::cout << "Process found" << std::endl;
		module mod = SigScanner.GetModule("Spotify.exe");
		DWORD AppDeveloperMode = SigScanner.FindSignature(mod.dwBase, mod.dwSize, Signature, Mask) + 1;
		int scan = SigScanner.ReadMemory<int>(AppDeveloperMode);
		int newValue = 255;
		int result = SigScanner.WriteMemory(scan, newValue);
		if(result>0x00) {
                std::cout <<"Writed to memory." << std::endl;
            } else {
                std::cerr <<"Failed to write to memory." << std::endl;
            }
	} else {
		std::cerr << "Process not found." << std::endl;
	}

	return 0;
}
```
This code requires `sigscan.h` that I included in this comment as zip with this code.
[spotify-enabledevtools.zip](https://github.com/spicetify/spicetify-cli/files/8403400/spotify-enabledevtools.zip)

**Comment by itsmeow** [comment]
@zjeffer No significance, Ghidra will produce varying outputs since decompilation is an inexact science. Try setting the value to 1 instead of 255.

**Comment by zjeffer** [comment]
Setting it to one has the same result, sadly.

**Comment by amd64fox** [comment]
@ririxidev 
Thank you, is there any instruction on how to use this for Windows?

**Comment by fosam** [comment]
> My workaround (copied from #1517)
> 
> > Install Cheat Engine, attach to Spotify.exe, hit "Add Address Manually", enter `016525fd`, set value to `255`. This will enable devtool when activated. It will likely stop working on the next Spotify update. Further investigation will be necessary to create a long-term solution. The way this works is by directly modifying the memory of the Spotify executable browser and enabling the developer mode flag in Chromium Embedded Framework. I determined this address by disassembling and analyzing Spotify.exe using Ghidra, and determined this was the data location used to store the true/false value for developer mode.

I have like 6 Spotify processes, does it matter which one i choose?

**Comment by xerta555** [comment]
> > My workaround (copied from #1517)
> > > Install Cheat Engine, attach to Spotify.exe, hit "Add Address Manually", enter `016525fd`, set value to `255`. This will enable devtool when activated. It will likely stop working on the next Spotify update. Further investigation will be necessary to create a long-term solution. The way this works is by directly modifying the memory of the Spotify executable browser and enabling the developer mode flag in Chromium Embedded Framework. I determined this address by disassembling and analyzing Spotify.exe using Ghidra, and determined this was the data location used to store the true/false value for developer mode.
> 
> I have like 6 Spotify processes, does it matter which one i choose?

You can choose anyone of Spotify's processes as it have CEF, you will inject the change to the specified data with Cheat Engine and the Chromium process will execute it in the whole Spotify client.

**Comment by fosam** [comment]
Ok, so i tried one random process, but i have no idea how to get this to work?

https://user-images.githubusercontent.com/52612348/162597902-6f098696-b94e-48a8-bd78-85b1f6a23f6f.mp4

**Comment by xerta555** [comment]
> Ok, so i tried one random process, but i have no idea how to get this to work? **1.1.81.604.gccacfc8c**

When you get the red text in Value column, it happen because you enter a wrong memory address.
As we said [here](https://github.com/spicetify/spicetify-cli/issues/1518#issuecomment-1083776698) and [here](https://github.com/spicetify/spicetify-cli/issues/1518#issuecomment-1084185514), for the last Spotify version, it's `0170b73e`.

**Comment by fosam** [comment]
OK, so i did that, but it doesn't work for me, i have no idea if i'm doing it correctly?

<details>
<summary>Screenshot</summary>
<img src=https://user-images.githubusercontent.com/52612348/162624739-93415f52-fc66-4f03-98c3-c87e472d3c19.png>
</details>

**Comment by xerta555** [comment]
> 

Now you just have to check the checkbox under "Active" 👍🏻

**Comment by fosam** [comment]
Oh it was already in the 3 dots menu, but what i was actually looking for was the inspect elements, maybe there is no way to show this option?

**Comment by xerta555** [comment]
> Oh it was already in the 3 dots menu, but what i was actually looking for was the inspect elements, maybe there is no way to show this option?

The little menu of the right click?

**Comment by fosam** [comment]
Yes

**Comment by xerta555** [comment]
> Yes

We can't, it's bugged in the pre-last and in the last version.
Maybe in the next(s) version(s) it will be fixed.

**Comment by fosam** [comment]
> Edit: You can have it with the disconnect method.

I'm not aware of this method, do you know it?

**Comment by xerta555** [comment]
> I'm not aware of this method, do you know it?

[Here](https://github.com/spicetify/spicetify-cli/issues/1518#issuecomment-1079924087)

**Comment by fosam** [comment]
To enable this, right?

<details>
<summary>Screenshot</summary>
<img src=https://user-images.githubusercontent.com/52612348/162626174-27913659-3174-45cd-af52-ff1996aeabf3.png>
</details>

**Comment by SaberAkiyama** [comment]
Mine was ```vendor~xpui.js.map``` connection error
![Screenshot 2022-04-22 101659](https://user-images.githubusercontent.com/48464326/164583437-80eec031-8df6-4e1f-9aa8-d5276565fd4c.png)

**Comment by itsmeow** [comment]
1.1.83 Windows Address: `016acc3d`

**Comment by ririxidev** [comment]
> 1.1.83 Windows Address: `016acc3d`

Sig is the same, and probably today I will upload exe that will not require using Cheat Engine etc.

**Comment by xerta555** [comment]
> 1.1.83 Windows Address: `016acc3d`

So I assume it will be possible to open devtools without Spicetify?

**Comment by itsmeow** [comment]
> > 1.1.83 Windows Address: `016acc3d`
> 
> So I assume it will be possible to open devtools without Spicetify?

I am not sure what you mean. This address is for other programs that modify memory. Spicetify cannot open devtools at the moment.

**Comment by xerta555** [comment]
> > > 1.1.83 Windows Address: `016acc3d`
> > 
> > 
> > So I assume it will be possible to open devtools without Spicetify?
> 
> I am not sure what you mean. This address is for other programs that modify memory. Spicetify cannot open devtools at the moment.

I just saw your update to the latest version, thanks for that, I'll be able to compile the exe.

Sorry for my question, i read too fast, thanks also for the memory address.

**Comment by ririxidev** [comment]
> > 1.1.83 Windows Address: `016acc3d`
> 
> Sig is the same, and probably today I will upload exe that will not require using Cheat Engine etc. edit: nvm it isn't from what I see.

Like I promised, I'm delivering exe that is enabling DevTools in Spotify. Program isn't based on SigScanner anymore since Sig that is generated for this version's address can be used to find other addresses as well, it isn't ideal. Program source-code will be released on my github and will update it every Spotify update.
For now please use exe that I attached in zip and have fun :D
ps. 2mb in size because of libs
![image](https://user-images.githubusercontent.com/9348108/164791826-b7f49b61-0301-461e-a323-db6cb5e5a8c6.png)
**[spotifyEnableDevTools.zip](https://github.com/spicetify/spicetify-cli/files/8543988/spotifyEnableDevTools.zip)**

**Comment by xerta555** [comment]
> [spotifyEnableDevTools.zip](https://github.com/spicetify/spicetify-cli/files/8543999/spotifyEnableDevTools.zip)

https://www.virustotal.com/gui/file/d56ababc97e23832e90c7d8a4809e0f6a859c5a752e81b4e86ea6c583b42bf2c?nocache=1

**Comment by ririxidev** [comment]
You really going to believe some antiviruses that I never even heard of? It's called false positive since: I patch memory with this program and it's not signed.

**Comment by xerta555** [comment]
> You really going to believe some antiviruses that I never even heard of? It's called false positive since: I patch memory with this program and it's not signed.

It's just for info for anyone wich would like to use your exe.

**Comment by ririxidev** [comment]
I'm going to release src in a bit so no need for vt

**Comment by xerta555** [comment]
> I'm going to release src in a bit so no need for vt

It will be a good point.

**Comment by amd64fox** [comment]
@ririxidev 
Thank you, it works

**Comment by ririxidev** [comment]
I made it smaller with MVSC but you may visual c++ redistributables 2015-2022 to run it. https://github.com/ririxidev/spotifyEnableDevTools/releases/tag/v1.0.0

**Comment by ririxidev** [comment]
> Any ideas for mac/linux

Will do on days for macOS 👌

**Comment by ririxidev** [comment]
1.1.84 address: https://github.com/ririxidev/spotifyEnableDevTools/blob/e55ce6065cc67fb3d9f7b7377bd4b11a25acad5f/spotify.cpp#L52 (016A597C)

**Comment by ririxidev** [comment]
Resolved by https://github.com/spicetify/spicetify-cli/commit/8af0be5a8d850b27447e230c3e33f5335cbf4718

**Comment by xerta555** [comment]
> Resolved by [8af0be5](https://github.com/spicetify/spicetify-cli/commit/8af0be5a8d850b27447e230c3e33f5335cbf4718)

I have compile myself spicetify with your fix for devtools, sadly it don't works, what i did:
- compile spicetify.exe
- remplace spicetify.exe file by the new one
- spicetify restore backup
- spicetify backup apply
- spicetify enable-devtools
- `Ctrl + SHIFT+I`
- DevTools won't open

**Comment by ririxidev** [comment]
> > Resolved by [8af0be5](https://github.com/spicetify/spicetify-cli/commit/8af0be5a8d850b27447e230c3e33f5335cbf4718)
> 
> I have compile myself spicetify with your fix for devtools, sadly it don't works, what i did:
> 
> * compile spicetify.exe
> * remplace spicetify.exe file by the new one
> * spicetify restore backup
> * spicetify backup apply
> * spicetify enable-devtools
> * `Ctrl + SHIFT+I`
> * DevTools won't open

Sadly works fine for me (macOS, Windows) and charlie (macOS). My program still will be available.

**Comment by xerta555** [comment]
> > > Resolved by [8af0be5](https://github.com/spicetify/spicetify-cli/commit/8af0be5a8d850b27447e230c3e33f5335cbf4718)
> > 
> > 
> > I have compile myself spicetify with your fix for devtools, sadly it don't works, what i did:
> > 
> > * compile spicetify.exe
> > * remplace spicetify.exe file by the new one
> > * spicetify restore backup
> > * spicetify backup apply
> > * spicetify enable-devtools
> > * `Ctrl + SHIFT+I`
> > * DevTools won't open
> 
> Sadly works fine for me (tested on macOS, Windows) and charlie (tested on macOS). My program still will be available.

Your `devtools.go` script file must exist in the `spicetify-cli` folder or is it in the `spicetify.exe` file?

**Comment by ririxidev** [comment]
Use 2.9.7

**Comment by xerta555** [comment]
> Use 2.9.7

I have test this new version, sadly DevTools won't open.
Full fresh install?

**Comment by ririxidev** [comment]
Check for offline.bnk in %localappdata%\Spotify and check if it has Chinese gibberish or xml stuff

**Comment by xerta555** [comment]
> Check for offline.bnk in %localappdata%\Spotify and check if it has Chinese gibberish or xml stuff

My [offline.zip](https://github.com/spicetify/spicetify-cli/files/8550354/offline.zip) file

**Comment by ririxidev** [comment]
Mate, don't send it. It has stuff that you wouldn't want to publish on internet. Just tell me if it has Chinese giberrish or has xml file in it

**Comment by xerta555** [comment]
> Check for offline.bnk in %localappdata%\Spotify and check if it has Chinese gibberish or xml stuff

it has Chinese gibberish

**Comment by ririxidev** [comment]
Delete this file and relaunch Spotify, and leave it for some time opened. Check file content again for xml stuff, then do "spicetify enable-devtools"

**Comment by xerta555** [comment]
> Delete this file and relaunch Spotify, and leave it for some time opened. Check file content again for xml stuff, then do "spicetify enable-devtools"

Same problem, my file have xml stuff

**Comment by ririxidev** [comment]
Try again later then. I can't really help in this situation. It works for everyone that I asked for to test it.

**Comment by xerta555** [comment]
> Try again later then. I can't really help in this situation. It works for everyone that I asked for to test it.

I have make a complete fresh install of Spotify and Spicetify setup, same issue, the DevTools won't open itself.
Method of memory hijack works.

**Comment by ririxidev** [comment]
I don't know what to tell you. I recommend asking on discord server and when I will have time I can help you with that.

**Comment by xerta555** [comment]
> I don't know what to tell you. I recommend asking on discord server and when I will have time I can help you with that.

Ok, we could check my problem tomorrow tonight if you have free time..
I'm pretty sure that it's due to a wrong config.

**Comment by huhridge** [comment]
> Delete this file and relaunch Spotify, and leave it for some time opened. Check file content again for xml stuff, then do "spicetify enable-devtools"

Thank you! In `spicetify -h`, it says `enable-devtool` instead of `enable-devtools`, so maybe fix it :)

**Comment by ririxidev** [comment]
I forgot to change it in help 💀

**Comment by amd64fox** [comment]
@xerta555 
Try manually changing `offline.bnk `

find it `<app-developer>0</app-developer>`  replace this with `<app-developer>2</app-developer>`

After each client reboot, the file will return the original value, so you can add a `read-only` attribute to it to prohibit changing it.

**Comment by amd64fox** [comment]
I don’t quite understand what does the %appdata%\Spotify directory have to do with it
Devtools worked with manual fix?

**Comment by ririxidev** [comment]
Address for 1.184 is in my repo of my program. Aka 0x16A597C

**Comment by afonsojramos** [comment]
@ririxidev @amd64fox just making sure I understand. In that case, the current implementation will continue working (unless Spotify changes something again), right? Since we are simply looking for the `app-developer` reference and changing it accordingly. As such, this address you are talking about only concerns your implementation @ririxidev, right?

**Comment by ririxidev** [comment]
Yes will. No matter what version. It edits remote configuration cache file and because of it, Spotify randomly downloads it after some time and it disables devtools again, that's why you need to enable them again with spicetify etc. nothing to worry

**Comment by xerta555** [comment]
> this address you are talking about only concerns your implementation

This does not concern any particular implementation.
The method i'm using of changing memorry address can works for anyone.

**Comment by amd64fox** [comment]
For me, the new `enable-devtools` did not work, so I wrote a small [script for windows](https://github.com/amd64fox/Enable-devtools-Spotify), maybe it will help someone

**Comment by xerta555** [comment]
> For me, the new `enable-devtools` did not work, so I wrote a small [script for windows](https://github.com/amd64fox/Enable-devtools-Spotify), maybe it will help someone

Good idea and good job, you replace each time the `offline.bnk` file by editing it's `app-developer` value 0 to 2 and launch Spotify.

I just try it, it works on my side on 1.1.84.716 version.
Well, the Powershell syntax is really annoying (Microsoft never knew how to export their system commands easily), but it works.

**Comment by ririxidev** [comment]
It’s the same thing like in spicetify but it edits xml variable. I will add it someday to spicetify so it will edit both.

**Comment by xerta555** [comment]
> It’s the same thing like in spicetify but it edits xml variable. I will add it someday to spicetify so it will edit both.

It would be a good idea yeah.

**Comment by JustAnEric** [comment]
Honestly, Spicetify not work, so I just started Spotify from command prompt with a few little arguments which allow me to track the window inside Google Chrome.
