### ISSUE TITLE
SHA mismatch on new update

### ISSUE THREAD

**Issue by cobcobs** [spicetify/spicetify-cli#1520]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.80.699
- Spicetify version: 2.9.1
```

### 📝 Description

```
brew upgrade
# or
brew install khanhas/tap/spicetify-cli
```

Similar error to #1127 

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/44166162/156693607-20152c8a-5a76-40cc-8494-bdf5a31c992f.png)

**Comment by Moquent** [comment]
run the `spicetify upgrade` command, maybe that'd work

**Comment by cobcobs** [comment]
Can confirm that it works. Thanks @Moquent!

**Comment by afonsojramos** [comment]
@itsmeow is this expected? 🤔

**Comment by itsmeow** [comment]
Did you change the build process in your release changes? Brew works by building an exact copy and comparing the SHA256.

**Comment by afonsojramos** [comment]
I did release the same tag more than once, which sent the GET request more than once, might that be it?

**Comment by lor1x** [comment]
Same issue here

**Comment by itsmeow** [comment]
(this has been fixed on our side as well now)
