### ISSUE TITLE
Spotify dont load

### ISSUE THREAD

**Issue by Rajbir98** [spicetify/spicetify-cli#1522]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.79.763.gc2965cdf
- Spicetify version: 2.9.2
```

### 📝 Description

Spicetify won't load after the Spicetify update.
it's stuck in loading.
I also tried using the default theme but it didn't work.
pressing spacebar in keyboard while loading starts playing song. 
Spotify in default state works fine

### 📸 Screenshots
In Spicetify 2.9.2
============================

![image](https://user-images.githubusercontent.com/84771149/156785165-194c7058-4f94-4816-afd5-8a97c1a14b2c.png)

In Spicetify 2.9.1
============================

![image](https://user-images.githubusercontent.com/84771149/156788244-c0511f68-6c07-4f89-8f30-71b3fb3265a2.png)

**Comment by afonsojramos** [comment]
Spicetify 2.9.2 is for `1.1.80` only!

**Comment by ll931217** [comment]
> Spicetify 2.9.2 is for `1.1.80` only!

So I tried using 2.9.2 for 1.1.80 but it didn't work for me, this is what I got:

```bash
# Ran the following command
spicetify config extensions dribbblish.js
spicetify config current_theme Dribbblish color_scheme nord-dark
spicetify config inject_css 1 replace_colors 1 overwrite_assets 1
spicetify apply
```

![image](https://user-images.githubusercontent.com/12750413/163961053-fb4d26bd-2fd6-4525-8723-c42241b38038.png)

I am on PopOS
