### ISSUE TITLE
The latest update borked theming

### ISSUE THREAD

**Issue by Chr1s70ph** [spicetify/spicetify-cli#1524]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify version 1.1.72.439.gc253025e, Copyright (c) 2021, Spotify Ltd
- Spicetify version: 2.9.2
```

### 📝 Description

After installing the latest update, applying the themes did not work. Even after reinstalling everything and retrying, no results. The Spotify window just displays the themes background color. Running `spicetify restore` at least brings back the normal Spotify Client, but applying any theme breaks the window again.

The Media keys still work, so obviously this must be a visual bug, since all the functionality is still there.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/29735603/156876150-db2e0e63-6731-46d1-ac86-133b93c4457f.png)

> **This is not just a picture of one solid color, this is what the Spotify-Client looks like**

**Comment by rien333** [comment]
I'm seeing something very similar — I didn't upgrade in a while, and just  upgraded to `1.1.80.699.gc3dac750, Copyright (c) 2022` (which, on arch linux, is the newest).

Now, running `spicetify apply` gives me:

```
spicetify vDev
Overwriting themed assets:
OK
Transferring user.css:
OK
Applying additional modifications:
**error** Cannot find symbol for Custom app React symbols
OK
Transferring extensions:
OK
success Spotify is spiced up!
```

**Comment by rien333** [comment]
I'm seeing something similar, though on 1.1.80.699.gc3dac750 (which just  released on arch linux). `spicetify` is on the latest commit (so it's not related to https://github.com/spicetify/spicetify-cli/issues/1514) . 
![2022-03-05-1646475302](https://user-images.githubusercontent.com/10417027/156878930-616d7159-6599-45ae-943d-bf5151c84a37.jpg)

Perhaps I should open a different bug report, though, because for me the media keys and the like don't work anymore.

**Comment by afonsojramos** [comment]
The latest version of spicetify (`2.9.2`) is only targeted to the latest version of Spotify. I'd recommend using [v2.8.3](https://github.com/spicetify/spicetify-cli/releases/tag/v2.8.3).
