### ISSUE TITLE
"Something went wrong" when pressing buttons with LyricsPlus and Reddit

### ISSUE THREAD

**Issue by NotDudidude** [spicetify/spicetify-cli#1527]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.80.699.gc3dac750
- Spicetify version: v2.9.2
- OS: Windows 11
```

### 📝 Description

Whenever I press the settings button on the LyricsPlus window it shows the something went wrong page.
Same thing when I press the filter dropdowns on the Reddit window.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/54620172/156888932-a1edeb99-3c9b-4b40-b999-e676b54d4298.png)
![image](https://user-images.githubusercontent.com/54620172/156889009-cd7a13b4-3620-4304-a8a7-610454cee06c.png)
![03 Sunday 06 14 20](https://user-images.githubusercontent.com/54620172/156922865-15900b3e-b7f2-442a-b5ed-d2ea8c417ad7.gif)

**Comment by Mahas1** [comment]
Happens to me too, when I press on 
![image](https://user-images.githubusercontent.com/82939599/156910477-f414286f-49bb-4470-89e0-b9f13cf8f9a2.png)
This button in lyrics-plus

OS: macOS Monterey 12.2.1
Spicetify and Spotify are on their latest versions as of now

**Comment by NotDudidude** [comment]
> Happens to me too, when I press on ![image](https://user-images.githubusercontent.com/82939599/156910477-f414286f-49bb-4470-89e0-b9f13cf8f9a2.png) This button in lyrics-plus
> 
> OS: macOS Monterey 12.2.1 Spicetify and Spotify are on their latest versions as of now

yep, that one

**Comment by CharlieS1103** [comment]
This is due to the menu hook being broken, referenced in https://github.com/spicetify/spicetify-cli/issues/1514.
