### ISSUE TITLE
Spotify Not Loading when using Any Theme

### ISSUE THREAD

**Issue by bibanez** [spicetify/spicetify-cli#1528]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.77.643 (flatpak)
- Spicetify version: 2.9.2
- Operating System: Linux (Fedora)
```

### 📝 Description

Installed Spicetify using the default install.sh script, but when I apply a theme spotify does not load at all.
Current theme `onepunch` (default doesn't work either).
After applying `spicetify restore` it can revert to normal.

### 📸 Screenshots

![Screenshot from 2022-03-06 23-06-22](https://user-images.githubusercontent.com/47608777/156944100-e7710190-fd7a-4673-8e49-5270ca73e821.png)

**Comment by Hdz** [comment]
Having the exact same issue with this Spotify version : 
1.1.80.699.gc3dac750 on Windows 10.

Doesn't work with 2.9.2, although a restore does the trick to get spotify back to normal.

**Comment by PrincessAkira** [comment]
Can confirm.
using Fluent Theme. Also not loading. 
Atleast i can start music over the windows Modal xD

**Comment by sagars007** [comment]
Can confirm. I'm using the SpicetifyDefault theme and it doesn't load in. Returns a blank spotify
https://imgur.com/a/Gq4UKPr

Might be a related issue: https://github.com/spicetify/spicetify-cli/issues/1505

**Comment by cooliochill** [comment]
Can confirm. Using Sleek theme, not loading. Even config_xpui.txt has most css and theme settings disables, it still shows a blank Spotify.

**Comment by outp1** [comment]
Can confirm 
All Themes, Spicetify: 2.9.2, Spotify version 1.1.72.439.gc253025e
![2022-03-09_16-43](https://user-images.githubusercontent.com/81954928/157462529-a4d9551f-8eec-4ba6-8462-b56778e08f44.png)

**Comment by PrincessAkira** [comment]
Reverting to 2.9.1 did fix the issue. Latest Spotify, Win 11

**Comment by JamesGordonII** [comment]
ik what yall are having happen but in on windows 11 with the latest spotify and spicetfiy and I haven't had this problem. i am using comfy with custom colors though so that might be why?

**Comment by helium18** [comment]
I'm facing the same issue.
Spicetify 2.9.2
Flatpak 1.11.2
Spotify 1.11.21.1.77.643.g3c4c6fc6

**Comment by majci237** [comment]
Spicetify 2.9.2
Spotify: 1.1.72

DevTools Console:
xpui.js:1 Uncaught SyntaxError: Unexpected token ','

**Comment by afonsojramos** [comment]
I mean, I guess we broke backwards compatibility, but that is expected as we are only targetting `1.1.80` with our last version. However, we are not fully stable with 1.1.80 yet, so if you want full functionality, please do downgrade spotify and spicetify.

**Comment by PrincessAkira** [comment]
> I mean, I guess we broke backwards compatibility, but that is expected as we are only targetting `1.1.80` with our last version. However, we are not fully stable with 1.1.80 yet, so if you want full functionality, please do downgrade spotify and spicetify.

Im using 2.9.1 with 1.1.80 fine.
Its just 2.9.2 tho

**Comment by mutageneral** [comment]
Same problem
![Capture d’écran de 2022-03-12 12-53-36](https://user-images.githubusercontent.com/62779748/158029265-2e07ebcf-e3e4-4d77-9a1f-9358e85ba3e3.png)
Spotify 1.1.77.643.g3c4c6fc6
Flatpak 1.12.6
Spicetify 2.9.2

**Comment by cooliochill** [comment]
> I mean, I guess we broke backwards compatibility, but that is expected as we are only targetting `1.1.80` with our last version. However, we are not fully stable with 1.1.80 yet, so if you want full functionality, please do downgrade spotify and spicetify.

Thanks! I'll be rocking v2.9.1 while awaiting anxiously for the next stable version :)

**Comment by bibanez** [comment]
Ok. Flathub repositories haven't updated the current spotify version but I'll try searching for a way to install it! I'll close this issue as a compatibility problem.

**Comment by PrincessAkira** [comment]
Still same issue on 2.9.3 so dont bother updating.

**Comment by cooliochill** [comment]
Confirmed. Same issue on 2.9.3 as well

**Comment by CharlieS1103** [comment]
@cooliochill @PrincessAkira This issue is happening because your spicetify and spotify versions are mismatched, either downgrade your spicetify or upgrade your spotify.

**Comment by PrincessAkira** [comment]
Im on latest spotify on scoop.
just using 2.9.1 again

**Comment by cooliochill** [comment]
@CharlieSS1103 Yes, can confirm. That's my bad.

Uninstalling spicetify & Spotify, then reinstalling Spotify and spicetify
from scratch (after saving my themes folder) fixed the issue. I am now
working on the latest version of both Spotify and spicetify.

**Comment by afonsojramos** [comment]
Just released 2.9.4, it should be more retrocompatible for everyone on this thread.

**Comment by PrincessAkira** [comment]
Works now

**Comment by Gregman-js** [comment]
For me work 2.9.1. 2.9.4 not working still

**Comment by ilhamisbored** [comment]
Can confirm, still not working.

**Comment by fcancelinha** [comment]
Not working on Manjaro KDE with spotify or spotify-adblock :( using a custom gruvbox theme

**Comment by anglo331** [comment]
I have the same problem with spicetify  v2.14.3
spotify v1.1.84.716.gc5f8b819
flatpak v1.12.7
