### ISSUE TITLE
New releases infinite loading on singles

### ISSUE THREAD

**Issue by lolihikikomori** [spicetify/spicetify-cli#1530]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
OS: Windows v10.0.19041
Spotify: v1.1.80.699
Spicetify: v2.9.2
Dribbblish: v4.1.1-0e50a92
```

### 📝 Description

For a few weeks already, legacy version of New Releases didn't work at all, just showed a loading icon. After updating to cli and tweaking with settings, I found out why. If I only select to fetch Albums it works, but if I select to fetch Singles and EPs it just infinitely loads, maybe the problem is with a particular Single or EP and it breaks New Releases completely?

**Comment by TheMayhem6328** [comment]
It works for me btw (I had a similar problem too; #1501 ), so it's probably what you're suggesting

(Win 11 - Spotify 1.1.80.699.x - Spicetify 2.9.2)

**Comment by lolihikikomori** [comment]
> It works for me btw (I had a similar problem too; #1501 ), so it's probably what you're suggesting

I probably should've demonstrated it before, so I'll do it now [here](https://lolihikikomori.s-ul.eu/naXbXuQP)
My problem is a bit different as it's just infinitely loading, but with albums it works fine It broke only recently, singles/eps worked fine before. It's probably a particular single/artist that breaks it.

**Comment by guttitto** [comment]
For me it's loading indefinitely even after disabling singles / EPs

**Comment by b3rk** [comment]
I have same problem too. When I click only podcasts I can see but when I click also singles and albums, I cannot see anything. I just see loading icon. 

Spotify for Windows 1.1.81.604.gccacfc8c
Spicetify: v2.9.2
