### ISSUE TITLE
Playlist banners not syncing

### ISSUE THREAD

**Issue by WeirdoSam** [spicetify/spicetify-cli#1531]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.80.699
- Spicetify version: 2.9.2
```

### 📝 Description

I've recently installed various themes to see what works but I've noticed that most of them have a problem where the playlists on the side aren't syncing with the theme (according to screenshots) and are instead showing the default photo for the specific playlist. I've looked up this issue to see if there were any fixes and have seen similar issues however no solutions that currently apply.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/101609116/158284774-617c1f4c-16cc-4197-b593-371c6a8adca6.png)

**Comment by fallsimply** [comment]
This looks like it might be a theme issue. What theme are you using?

**Comment by WeirdoSam** [comment]
> This looks like it might be a theme issue. What theme are you using?
Using comfy in this pic but also was happening with dribbbilish, retroblur and a few others.
