### ISSUE TITLE
Spicetify won't cannot detect file spotify location, even though the pathway is correct (and additionally I made it worse)

### ISSUE THREAD

**Issue by CoiloverCat** [spicetify/spicetify-cli#1532]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.80.699.gc3dac750
- Spicetify version: v2.9.2
```

### 📝 Description

I've recently been playing around with rainmeter, and I linked spicetify up with spotify so a music visualizer I use can get the song information and display it. I know I can install spicetify, because I've done it before. The first tutorial I watched was this one: https://youtu.be/2oebhJBfoIs?t=185

I decided that I wanted themes as well, and uninstalled spotify so I could reinstall it and install spicetify properly this time, with the tutorial posted on the spicetify website. When I did it this way, after pasting in the commands in this pastebin (from a video) https://pastebin.com/qSWubGh9 it gave me an error message saying "error Cannot detect Spotify location. Please manually set "spotify_path" in config-xpui.ini"

I redid it the way spicetify intends (after uninstalling spotify from my system yet again) and got the same error message.

Then, I went into the config file that the error message stated, only to find that the stated path is "C:\Users\ChenKids\AppData\Roaming\Spotify"

after seeing if deleting the .spicetify would help, I found that it only made things worse, because once I reinstalled spicetify, the .spicetify folder didn't reappear.

So despite spicetify having the correct file location, it still didn't detect it. (also, I thought it would be worth mentioning that upon installing it, it will spit out the same message twice, and it can detect the prefs folder)

Edit: I restored the .spicetify folder from my recycle bin

**Comment by DLADAnaconda** [comment]
How do I fix this issue?
