### ISSUE TITLE
CosmosAsync Error - Resolver not found on `1.1.81` (only for hermes `hm://` requests)

### ISSUE THREAD

**Issue by huhridge** [spicetify/spicetify-cli#1537]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.81.604.gccacfc8c
- Spicetify version: 2.9.2
```

### 📝 Description

1. Lyrics-plus and my extension with colorExtractor don't work (shows black color)
2. Try `Spicetify.CosmosAsync.get(hm://colorextractor/v1/extract-presets?uri=spotify:track:4PyMK7JTcu6l30D8KogokR&format=json`

Error: `xpui.js:1 Uncaught (in promise) Error: GET request to hm://colorextractor/v1/extract-presets?uri=spotify:track:4PyMK7JTcu6l30D8KogokR&format=json request failed with error code -1 (Resolver not found!)`

On more sleuthing around, I have figured out that requests to `hm://` fail. For example, 
1. `Spicetify.CosmosAsync.get("hm://lyrics/v1/track/6ZnADW4eHl0Sc3rRlnGi33")`
2. ```Spicetify.CosmosAsync.get(`hm://album/v1/album-app/album/2F1xmiVxAOHMIPOWcK97gg/desktop`)```
and so on, all fail.
Requests like `"sp://core-collection/unstable/@/list/tracks/all?responseFormat=protobufJson"` still work, so must be `hm://` related somehow.

Note: This problem is only on 1.1.81

**Comment by lhvy** [comment]
Is this issue actually resolved? I've noticed this same problem in a few third party extensions now and I was wondering if there is a solution, something being worked on or a nice alternative to swap to.

**Comment by huhridge** [comment]
There is no way to "fix" the issue, it's been deprecated on Spotify's backend. The only possible thing is to find alternative method to request the same things.

**Comment by afonsojramos** [comment]
Which has been done in #1543 for example!
