### ISSUE TITLE
Black background on Lyrics Plus

### ISSUE THREAD

**Issue by hetnialoevr48** [spicetify/spicetify-cli#1538]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows
1.1.81.604.gccacfc8c
- Spicetify version: 2.9.2
```

### 📝 Description

I used to have random coloured backgrounds on Lyrics Plus, but now they're all black for some reason. I think this started happening about 1/2 days ago. I didn't turn off the coloured background option in the lyrics plus config

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/25375434/159068424-72b828ad-966b-4192-ab90-e791fbe70675.png)
![image](https://user-images.githubusercontent.com/25375434/159068569-a23a8af2-2bff-4e4c-a9a7-5a7c480820f6.png)

**Comment by pafase** [comment]
same thing happening to me 
![image](https://user-images.githubusercontent.com/51797598/159121277-1321648e-2ff5-4307-ad9a-89f5150048e5.png)

**Comment by huhridge** [comment]
This has already been [reported](https://github.com/spicetify/spicetify-cli/issues/1537). The request are not fulfilled due to CosmosAsync being messed up rn due to the update.
