### ISSUE TITLE
Custom app - New Releases Infinite Loading

### ISSUE THREAD

**Issue by guttitto** [spicetify/spicetify-cli#1539]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.81.604.gccacfc8c
- Spicetify version: 2.9.4
- OS: Windows 10.0.19044.1586
- Theme: Spicetify Default
```

### 📝 Description

**New Releases** custom app is loading indefinitely.

**Comment by afonsojramos** [comment]
Check it out on the new version, I think it should have been fixed now! Re-open if that is not the case 🤞

**Comment by Mcfly2340** [comment]
> Check it out on the new version, I think it should have been fixed now! Re-open if that is not the case 🤞

it has not been fixed in Spicetify: v2.9.4
still infinite loading in new releases. Can't say for the reddit app because i don't use it

**Comment by CharlieS1103** [comment]
I'd be willing to bet this is because the viewport selector is no longer valid

**Comment by guttitto** [comment]
I will test it later today

**Comment by guttitto** [comment]
Reddit wasn't infinite loading I only got errors with menu hooks, if they were fixed then probably the issue is just with New Releases

**Comment by grasmanek94** [comment]
I have the same issue:

![image](https://user-images.githubusercontent.com/595329/160591797-dd05e110-7e00-4a4f-970b-cfcbbe58fda4.png)

Unfortunately, enabling developer tools doesn't work. I can't open them.

**Comment by th3an7** [comment]
New Releases infinite loading issue is due to `hm://` protocol changes...

Since it was removed (or depreciated?), it can't fetch necessary data
![image](https://user-images.githubusercontent.com/13398380/160623242-edb7a0ea-672a-40fb-b571-d1f05d5910a0.png)

**Comment by th3an7** [comment]
> Do you think this can even be fixed after this change?

It should, yes - there is already [PR for `shuffle+` extension](https://github.com/spicetify/spicetify-cli/pull/1559/commits/1c14c2de5d5481bcac6efbdd5493a98d17603ba3) that also fetches artist data...

I'm actually testing if this also works for `New Releases` custom app :D

**Comment by th3an7** [comment]
I've managed to partly fix it by looking at that PR I've mentioned above... it works (kinda) but I'm pretty sure it doesn't show all releases for all artists...

[here is my edited code](https://github.com/th3an7/spicetify-cli/commit/dfa29b900c33edf79c85d0b3638e0bdc68db4d6b) - not sending PR yet as it probably can be fixed by someone smarter than me...

**Comment by Mcfly2340** [comment]
> I've managed to partly fix it by looking at that PR I've mentioned above... it works (kinda) but I'm pretty sure it doesn't show all releases for all artists...
> 
> [here is my edited code](https://github.com/th3an7/spicetify-cli/commit/dfa29b900c33edf79c85d0b3638e0bdc68db4d6b) - not sending PR yet as it probably can be fixed by someone smarter than me...

this actually fixed it for me! thanks for the fix!

**Comment by th3an7** [comment]
> > I've managed to partly fix it by looking at that PR I've mentioned above... it works (kinda) but I'm pretty sure it doesn't show all releases for all artists...
> > [here is my edited code](https://github.com/th3an7/spicetify-cli/commit/dfa29b900c33edf79c85d0b3638e0bdc68db4d6b) - not sending PR yet as it probably can be fixed by someone smarter than me...
> 
> this actually fixed it for me! thanks for the fix!

Hey, glad to hear that :D

Could you also please test my latest changes made in https://github.com/th3an7/spicetify-cli/commit/604b2ddca77a9ad48d9aa5b365dd72bd7f9b49f0?

If you have big library of followed artists (655+ in my case), this should return more data before it errors out - you'll still miss some releases from couple artists, but not to that degree as in previous fix.

###### This note is just to add notification in https://github.com/spicetify/spicetify-cli/issues/1530

**Comment by vvirtues** [comment]
![image](https://user-images.githubusercontent.com/81705406/161110655-b051e4ef-89b0-48c2-ae65-80d77371e0a1.png)
same issue, ill try fix hold on

**Comment by th3an7** [comment]
> EDIT: lmao just realized the pr hasnt merged yet

You can just replace file manually and then do `spicetify apply` - should work - just check if you're copying updated file :D

**Comment by SIMULATAN** [comment]
I don't know if this is related or not but my spotify app doesn't load at all. I tried to clear the backups to get a vanilla install of spicetify (if that makes sense) but it always kept displaying the gray screen that is visible when starting. I could start music with media keys tho.

**Comment by Mcfly2340** [comment]
> I don't know if this is related or not but my spotify app doesn't load at all. I tried to clear the backups to get a vanilla install of spicetify (if that makes sense) but it always kept displaying the gray screen that is visible when starting. I can start music with media keys tho.

i had this twice before and had to reinstall spotify and spicetify twice too. but it seems like the issue was with one of the extensions or snippets so i just installed less of them. hope this helps

**Comment by SIMULATAN** [comment]
Will try that, thanks @Mcfly2340!

**Comment by vvirtues** [comment]
> > EDIT: lmao just realized the pr hasnt merged yet
> 
> You can just replace file manually and then do `spicetify apply` - should work - just check if you're copying updated file :D

Worked, thank you 👍
