### ISSUE TITLE
When no lyrics are found in the "Full app Display" extension hide the lyrics element

### ISSUE THREAD

**Issue by RUGMJ** [spicetify/spicetify-cli#1540]
### 📝 Provide a description of the new feature

When there are no lyrics found, instead  of showing the (._.) face, center the title, and album cover

**Comment by huhridge** [comment]
My extension does that. Here -> https://github.com/huhridge/huh-spicetify-extensions/tree/main/fullAppDisplayModified
It is on marketplace also.

**Comment by ForlornWolf** [comment]
The extension does not work for me. Still no lyrics, image moves to the left making space for lyrics but they do not appear.
