### ISSUE TITLE
Playlist sidebar scroll bugged

### ISSUE THREAD

**Issue by channer72** [spicetify/spicetify-cli#1544]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.81.604.gccacfc8c
- Spicetify version: v2.9.2
```

### 📝 Description

About halfway through my playlist list on the sidebar, the bottom of the bar gets filled with blank space as you scroll down. The scroll animation also becomes janky as it skips back and forth when scrolling.
Happens on every theme I've tried so far (currently using SpicetifyDefault) but it doesn't happen on my restored Spotify version.

### 📸 Screenshots

![spice1](https://user-images.githubusercontent.com/38873298/159418584-fc2713e2-4aca-4255-8de7-52aae8997039.png)
^ top of list
![spice](https://user-images.githubusercontent.com/38873298/159418256-2fc50468-1f7e-49ef-9884-52b8c656e920.png)
^ about 3/4 of the way down the list

**Comment by Goodly58** [comment]
I have the same issue!

**ENVIRONMENT / COMPUTER INFO:**
Spotify for Windows
1.1.98.691.gf759311c
Spicetify v2.14.2

![image](https://user-images.githubusercontent.com/63460148/203393701-f9c1b435-a125-423d-bd67-3d6243adcbc1.png)

I only have these extensions:
![image](https://user-images.githubusercontent.com/63460148/203393951-7c1e0754-2631-40a6-99e3-703aee5a52ae.png)
as well as Shuffle+ and GoToSong. 

It doesn't matter which theme I use, the problem remains.

Removing Spicetify fixes this problem.
