### ISSUE TITLE
Spotify Desktop App Window Blank

### ISSUE THREAD

**Issue by NachosOfficial** [spicetify/spicetify-cli#1549]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 
Spotify for Windows
1.1.81.604.gccacfc8c

- Spicetify version: 
2.9.3 || Windows 64
```

### 📝 Description

I run 'spicetify backup apply' as well as 'spicetify restore backup apply' and both have resulted in the same problem.

Have reinstalled spotify desktop app and still have the same problem where none of the UI comes up

### 📸 Screenshots

![2022-03-26](https://user-images.githubusercontent.com/102419736/160241297-5037100f-af11-4098-b3bf-1a12bd5a5cbb.png)

**Comment by ririxidev** [comment]
![image](https://user-images.githubusercontent.com/9348108/160243218-7ef84340-55f1-4cb1-82a2-09e923537a83.png)
says why. You use spicetify 2.5.0 when 2.9.3 is latest one.

**Comment by NachosOfficial** [comment]
> ![image](https://user-images.githubusercontent.com/9348108/160243218-7ef84340-55f1-4cb1-82a2-09e923537a83.png) says why. You also use spicetify 2.5.0 when 2.9.3 is latest one.

Oh I see, I downloaded and extracted 2.9.3 but its using an old version of it for some reason, I'll reinstall and see if that fixes it

**Comment by NachosOfficial** [comment]
RESOLVED ISSUE:

Reinstalled Spicetify to run newer version, ran 'spicetify restore backup apply' it restored Spotify App UI and works with Rainmeter apps, Thank you
