### ISSUE TITLE
Songs seem to glitch at the beginning

### ISSUE THREAD

**Issue by rycerzes** [spicetify/spicetify-cli#1550]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.81.604.gccacfc8c
- Spicetify version:2.9.2
- OS: Windows 11
```

### 📝 Description

The songs start to glitch at the beginning sometimes and repeat a segment twice or thrice. And also when the lyrics-plus configuration tool is clicked it says "Something went wrong, try reloading the page" as shown below
![image](https://user-images.githubusercontent.com/59965507/160251181-b835f12e-b943-47b4-bad3-24a7525dbfe9.png)

My config file is as shown below:
![image](https://user-images.githubusercontent.com/59965507/160251263-1b5b125c-6d0c-49ab-9e83-33671284ac77.png)

Please help
Thanks

**Comment by CharlieS1103** [comment]
@rycerzes Song glitch at beginning is a spotify issue, not spicetify related I believe, and I patched the other issue, we just need to wait for a new release to be made.
