### ISSUE TITLE
Error / bug help please

### ISSUE THREAD

**Issue by UltimateBoi** [spicetify/spicetify-cli#1551]
### 🔍 Have you checked Spicetify.app page for your issue?

- [x] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Latest
- Spicetify version: Latest
```

### 📝 Description

error in console:
```
error C:\Users\Ultimate\AppData\Local\Packages\SpotifyAB.SpotifyMusic_zpdnekdrzrea0\LocalState\Spotify\prefs does not exist or is not a valid path. Please manually set "prefs_path" in config-xpui.ini to correct path of "prefs" file.
error C:\Users\Ultimate\AppData\Local\Packages\SpotifyAB.SpotifyMusic_zpdnekdrzrea0\LocalState\Spotify\prefs does not exist or is not a valid path. Please manually set "prefs_path" in config-xpui.ini to correct path of "prefs" file.
```

basically just trying to install it dosent work

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/63293118/160255801-47e386b8-3ed0-4221-99a8-e8cf577928d6.png)

**Comment by afonsojramos** [comment]
As it says, please manually set "prefs_path"! Check the FAQ for more info!

**Comment by UltimateBoi** [comment]
I dont know how to do that @afonsojramos

**Comment by UltimateBoi** [comment]
and i also dont know what to set it to

**Comment by UltimateBoi** [comment]
where is config.ini?

**Comment by UltimateBoi** [comment]
![image](https://user-images.githubusercontent.com/63293118/160274856-99676e4f-6386-42ef-829d-396e4fba1a55.png)
also thats what happens when i try to do it thats why i checked the i did check faq option...

**Comment by UltimateBoi** [comment]
@afonsojramos

**Comment by UltimateBoi** [comment]
I tried everything there... Still dosent work

**Comment by afonsojramos** [comment]
Please show your config file.

**Comment by UltimateBoi** [comment]
Where can i get it?

**Comment by UltimateBoi** [comment]
ok
