### ISSUE TITLE
Marketplace - Theme type button not functioning 

### ISSUE THREAD

**Issue by ObviouslyPurplee** [spicetify/spicetify-cli#1552]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Latest 
- Spicetify version: Latest (2.9.3)
```

### 📝 Description

In the last update, 2.9.2, the marketplace had completely stopped working, it would work at random times but it would also break a lot asking to reload the page. 

Now... with 2.9.3 the marketplace functions again, however, the theme type button, for example, Ziro isn't functioning at all, reloaded the app, quit the app and nothing fixed it. 

I'm on macOS Monterey! 
Mac Mini (M1, 2020) 
Chip: Apple M1
Memory: 16GB 

Thank you, hope to see the marketplace fixed and all great again. 

### 📸 Screenshots

https://user-images.githubusercontent.com/96754035/160257586-0150bae2-8552-457c-b882-2424f05978d5.mov

**Comment by afonsojramos** [comment]
Should be fixed on latest version! Thanks!
