### ISSUE TITLE
autoupdate

### ISSUE THREAD

**Issue by laatenci** [spicetify/spicetify-cli#1555]
### 📝 Provide a description of the new feature

since spicetify update to what it looks right now we can see 
this update thing
![image](https://user-images.githubusercontent.com/102475930/160288217-4b675a58-d44e-48cd-9013-7a8c8f4dcb75.png)
and we know many peoples is lazy so I guess it would be a good thing for client to have
also idk almost anything about coding so i only post the idea
ty for client <3

**Comment by afonsojramos** [comment]
I believe this is a feature of the dribblish theme, right?

**Comment by ririxidev** [comment]
Closing since no response and I kinda don't understand what author meant by `autoupdate`.
