### ISSUE TITLE
Crooked playlist buttons when dragging songs over them

### ISSUE THREAD

**Issue by skipster1337** [spicetify/spicetify-cli#1556]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [x] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1:1.1.80.699-1
- Spicetify version: 2.9.4
- Running Arch Linux x86_64
```

### 📝 Description

The "liked songs" and "create playlist" buttons move in a crooked way when dragging a song over them (without dropping). It happens without any themes installed, but themes do not appear to make a difference.

### 📸 Screenshots

![Screenshot_2022-03-27_21-19-41](https://user-images.githubusercontent.com/91155070/160295382-dc410f6f-d3cd-46f7-979a-02bc34ffbd95.png)

**Comment by sidevesh** [comment]
This issue should be reopened, this still happens with latest spicetify and also, even when not dragging and dropping,
for me the Create Playlist gets crooked on its own after a while.

**Comment by kyrie25** [comment]
> This issue should be reopened, this still happens with latest spicetify and also, even when not dragging and dropping, for me the Create Playlist gets crooked on its own after a while.

You're using an incompatible Spicetify version with your current Spotify version.

**Comment by sidevesh** [comment]
thanks @kyrie25, how do I change the spicetify version to the compatible version then ? I tried spicetify upgrade but that shows that I am on the latest version,
is it rather my Spotify flatpak that is out of date ?

**Comment by kyrie25** [comment]
> thanks @kyrie25, how do I change the spicetify version to the compatible version then ?

Refer to the release notes and manually downgrade Spicetify.

> is it rather my Spotify flatpak that is out of date ?

Spotify has long abandoned Linux builds.
