### ISSUE TITLE
Spicetify stops working when Spotify is closed and reopened

### ISSUE THREAD

**Issue by lonelychicken** [spicetify/spicetify-cli#1557]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows 1.1.81.604.gccacfc8c
- Spicetify version: 2.9.4
```

### 📝 Description

Whenever I close Spotify and open it back up, Spicetify is not effecting Spotify (no theme, no marketplace, song info on Monstercat Visualizer shows N/A). However when I do `spicetify apply` in Powershell, then it works again, with all my themes and song info working.

**Comment by afonsojramos** [comment]
This is very weird. Are you sure it isn't updating when you close it?

**Comment by lonelychicken** [comment]
Yes, I made sure

**Comment by dreparnn** [comment]
It's mentioned in the FAQ if I'm not mistaken, I had the same issue and solved it by adding "spicetify auto" in the executable path of the Spotify client shortcut. That way Spicetify applies everything just before Spotify starts - works like a charm.
![Screenshot 2022-04-02 155903](https://user-images.githubusercontent.com/101642446/161386689-0b50a195-20a0-48a8-95bf-275cad1ce2b5.png)

**Comment by afonsojramos** [comment]
It is still weird that it was disregarding your Spicetify every time you launched it. But since it never happened to anyone else I guess we can close this. Let's allow the bot to mark it as stale and close it by itself.

**Comment by lonelychicken** [comment]
This worked like a charm! I didn't realize that my issue was covered in that section of the FAQ. Thank you guys!

**Comment by universe32** [comment]
so the same thing happended to me

**Comment by universe32** [comment]
what can i do like how can i get the properties thing
