### ISSUE TITLE
blank screen and error

### ISSUE THREAD

**Issue by Mikoq4** [spicetify/spicetify-cli#1564]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: latest
- Spicetify version: 2.9.4
```

### 📝 Description

how to fix it?!?!

![Screenshot from 2022-03-31 20-52-48](https://user-images.githubusercontent.com/77680260/161128635-5d2eb8cc-3454-4960-8e69-1488f1f6c5bf.png)

**Comment by TheKleopiNetwork** [comment]
same issue here

**Comment by theRealPadster** [comment]
I have a feeling that it might be cause my the Linux version often being behind the windows version, so it might not be working. What version of spotify do you have?

**Comment by Mikoq4** [comment]
idk. how can i check it?

**Comment by theRealPadster** [comment]
> idk. how can i check it?

Probably `spotify --version` or check the package version in your package manager.

**Comment by HeartofGalaxies** [comment]
In the top left corner, there are three dots. Click them, then Help, then About Spotify and it'll be the second line. I'm personally experiencing this issue on v1.1.81.604.gccacfc8c, but I also experience it on other versions.

**Comment by Mikoq4** [comment]
Spotify version 1.1.72.439.gc253025e, Copyright (c) 2021, Spotify Ltd

**Comment by Mikoq4** [comment]
nvm fixed

i used flatpak and working
