### ISSUE TITLE
[✨ Extensions Idea] add 'Liked by' near every song

### ISSUE THREAD

**Issue by KorayUlusan** [spicetify/spicetify-cli#1565]
### 📝 Provide a description of the new feature

 While searching/browsing/etc displays the profile picture of a user (possibly multiple users) if a followed user has that song in their public playlists. Since the green heart's aren't public this is the closest we got. 

### ➕ Additional Information

Implementation: Probably adding every song in all their playlists to a cache/small database is the best option.

#### Here is my super sick gimp skills:

<img width="1063" alt="Screen Shot 2022-04-01 at 2 06 32 PM" src="https://user-images.githubusercontent.com/65815347/161252082-2d90ddc0-fbaf-4d05-a213-76e9a478e6ed.png">

**Comment by afonsojramos** [comment]
Yeah... I can't really see this working imo as it would require a massive amount of queries... And even if we had a database for it, we would NEED a database for it, which just by itself would increase the complexity and for sure go out of scope in terms of `spicetify-cli`. 

Post this on Discord if someone wants to pick it up, but I'll close it from here.
