### ISSUE TITLE
Spotify Lyrics seems to be not working (Lyrics Plus and Popup)

### ISSUE THREAD

**Issue by francescoaracu** [spicetify/spicetify-cli#1566]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.81.604.gccacfc8c
- Spicetify version: 2.8.4
```

### 📝 Description

Even if Spotify is the first option on my Lyrics Plus, my client always retrieves Netease lyrics instead. I also tried disabling all the options but Spotify, but the result is as you see in the screenshots.
The only difference is that Popup Lyrics shows "No lyric".

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/48188510/161255499-6e248ad2-f5d6-47d6-b7f0-bcc625b486c6.png)
![image](https://user-images.githubusercontent.com/48188510/161255752-622aa584-3e42-4347-be87-8d1c849f9d2c.png)
![image](https://user-images.githubusercontent.com/48188510/161255692-8304005c-0d01-46c5-8b34-d46b04cdecd5.png)

**Comment by userliluzibert** [comment]
Only lyrics that work for me is Genius. I hope there's a fix for this. I'm running the current versions of everything.

**Comment by afonsojramos** [comment]
MusicXMatch may need to be reviewed.

Nonetheless, something we need to change, for sure, is to update the Spotify lyrics URL, since it is still using a `hm://` link, which has now been deprecated!

**Comment by lolifuta** [comment]
> MusicXMatch may need to be reviewed.
> 
> Nonetheless, something we need to change, for sure, is to update the Spotify lyrics URL, since it is still using a `hm://` link, which has now been deprecated!

and you just need to change the "hm://" to "wg://" in "C:\Users\natsuko\spicetify-cli\CustomApps\lyrics-plus\Providers.js"

**Comment by afonsojramos** [comment]
@lolifuta if that works I'm happy to apply that change!

**Comment by ririxidev** [comment]
> @lolifuta if that works I'm happy to apply that change!

Tested. Works with `wg://` protocol.

**Comment by th3an7** [comment]
> > MusicXMatch may need to be reviewed.
> > 
> > Nonetheless, something we need to change, for sure, is to update the Spotify lyrics URL, since it is still using a `hm://` link, which has now been deprecated!
> 
> and you just need to change the "hm://" to "wg://" in "C:\Users\username\spicetify-cli\CustomApps\lyrics-plus\Providers.js"

How did you found out about `wg://` protocol? I wonder if there are any new endpoints or if they just changed it from `hm://` without adding anything else...

**Comment by lolifuta** [comment]
> > > MusicXMatch may need to be reviewed.
> > > Nonetheless, something we need to change, for sure, is to update the Spotify lyrics URL, since it is still using a `hm://` link, which has now been deprecated!
> > 
> > 
> > and you just need to change the "hm://" to "wg://" in "C:\Users\username\spicetify-cli\CustomApps\lyrics-plus\Providers.js"
> 
> How did you found out about `wg://` protocol? I wonder if there are any new endpoints or if they just changed it from `hm://` without adding anything else...

![image](https://user-images.githubusercontent.com/76212473/163720670-6739a361-f8c5-4c62-be22-add55d734543.png)
sorry，i don't know why it‘s useful, just tried this

**Comment by ririxidev** [comment]
> > > > MusicXMatch may need to be reviewed.
> > > > Nonetheless, something we need to change, for sure, is to update the Spotify lyrics URL, since it is still using a `hm://` link, which has now been deprecated!
> > > 
> > > 
> > > and you just need to change the "hm://" to "wg://" in "C:\Users\username\spicetify-cli\CustomApps\lyrics-plus\Providers.js"
> > 
> > 
> > How did you found out about `wg://` protocol? I wonder if there are any new endpoints or if they just changed it from `hm://` without adding anything else...
> 
> ![image](https://user-images.githubusercontent.com/76212473/163720670-6739a361-f8c5-4c62-be22-add55d734543.png) sorry，i don't know why it‘s useful, just tried this

This url makes everything clear, wow. Grats for finding it 👍
