### ISSUE TITLE
Blank screen on Linux

### ISSUE THREAD

**Issue by Celibistrial** [spicetify/spicetify-cli#1570]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
❯ spotify --version
spotify: /usr/lib/libcurl-gnutls.so.4: no version information available (required by spotify)
Spotify version 1.1.80.699.gc3dac750, Copyright (c) 2022, Spotify Ltd

❯ spicetify -v
Dev
```

### 📝 Description

After running ```sudo -E spicetify apply```  Spotify loads up with a black screen 

tried multiple versions of spoitfy from the aur  [spotify-snap](https://aur.archlinux.org/packages/spotify-snapstore) [spotify](https://aur.archlinux.org/packages/spotify)

Other people in the discord server also seem to have the same issue

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/82810795/161555287-adccc401-3ec7-4bd4-844d-f258a29f7a28.png)
![image](https://user-images.githubusercontent.com/82810795/161555877-6918a1ba-e944-4650-8896-aeb6ee0505e5.png)

**Comment by Mikoq4** [comment]
same problem on ubuntu

**Comment by theRealPadster** [comment]
Yeah, I have the same spotify/spicetify version and it's a blank screen. Maybe the latest changes to get it working after a Spotify update don't work on 1.1.80.699. Idk.

**Comment by theRealPadster** [comment]
If I connect via remote debugging, I can see this in the console: 
`Uncaught SyntaxError: Unexpected token ','`
![image](https://user-images.githubusercontent.com/1565883/161634671-042afefb-ac66-4a10-a5b4-e977fb86fa6a.png)

**Comment by theRealPadster** [comment]
Searching for the regex used (`=(?:\w+=>|function)(?:\{let|\(\w+\)\{var \w+,\w+=\w+.children,\w+=\w+.icon)(?:\{children:\w+,icon:\w+)?`) in my xpui.js (before and after `spicetify apply`) gives me 11 results. Is it supposed to find 11 of them? @CharlieS1103

**Comment by outofink** [comment]
I can confirm this appears to be the source of the issue. I bisected and found that the issue arose starting in commit a93d83369ae1aafb5a56886927707cff332ad839, a commit which is part of v1.9.2.

**Comment by awaited101** [comment]
Same thing here with Debian(Kali-rolling)

**Comment by theRealPadster** [comment]
Is it possible to have the apply.go file detect the Spotify version? Or does the regex need to be backwards compatible?

@itsmeow

**Comment by itsmeow** [comment]
> Is it possible to have the apply.go file detect the Spotify version? Or does the regex need to be backwards compatible?
> 
> @itsmeow 

You can detect the version, but we could use a more long term solution here imo

**Comment by theRealPadster** [comment]
> You can detect the version, but we could use a more long term solution here imo

How about something like the CSS map but for hooks, dependent on the spotify version?

**Comment by Not-Storm** [comment]
same issue on Deepin(rolling)

**Comment by irls-svg** [comment]
Not Linux but macOS, think I might be getting a similar issue?
Running spicetify v2.9.5, Spotify 1.1.83. Restore fixes the issue.
<img width="1241" alt="image" src="https://user-images.githubusercontent.com/48498350/163659268-1116ba29-6e52-4c14-ba21-89115910abf1.png">

**Comment by Gingeh** [comment]
I have a blank window on Linux Mint 20.2 with Spotify 1.1.72 and Spicetify 2.9.5. Restoring from backup fixes it.

**Comment by nils-kt** [comment]
Same on Windows with version 1.1.83.956.gbe7ea9a7

**Comment by despawnedd** [comment]
Had the same issue, but manually getting the Spotify .deb helped (https://github.com/spicetify/spicetify-cli/issues/1577#issuecomment-1098920889).

**Comment by kotx** [comment]
I get this issue on macOS 12.3.1 on Spicetify version 2.9.5 and Spotify for macOS (Apple Silicon) 1.1.83.956.gbe7ea9a7 as well. After `spicetify apply`, the app opens to a blank screen. *However*, the menu items in "Playback" in the menu bar all work. Everything else- log out, etc. doesn't. No keybinds, just a blank screen.
DevTools doesn't work, I had to manually use `--remote-debugging-port=9222`. Here's the console output for that:

[xpui.app.spotify.com-1650564967416.log](https://github.com/spicetify/spicetify-cli/files/8534046/xpui.app.spotify.com-1650564967416.log)

It seems `/Applications/Spotify.app/Content/xpui.js` is incorrectly formatted or something. This error doesn't occur on a untouched Spotify installation (`spicetify restore` or similar). So, here's that:
[xpui.js](https://github.com/spicetify/spicetify-cli/files/8534066/xpui.js.txt)

Here's `/Applications/Spotify.app/Contents/Resources/Apps/xpui/vendor~xpui.js`:
[vendor~xpui.js](https://github.com/spicetify/spicetify-cli/files/8534068/vendor.xpui.js.txt)

**Comment by itsmeow** [comment]
@irls-svg @nils-kt See #1598 / fix #1600

**Comment by itsmeow** [comment]
> > You can detect the version, but we could use a more long term solution here imo
> 
> How about something like the CSS map but for hooks, dependent on the spotify version? Like have it store/look up the different regexes and use whichever ones it needs.

This would create a risk for remote arbitrary code execution, very insecure. We would have to bundle the hooks into the program at distribution time, not web-time. We could create a large JSON mapping of hooks and read that from the filesystem.

**Comment by ririxidev** [comment]
I think we can close this issue since it's about 1.1.80 that isn't supported by spicetify. 1.1.83 should work fine on v2.9.6. I recommend using old version of spicetify (2.9.3) if you want to stick to old versions of spotify.

**Comment by Celibistrial** [comment]
![image](https://user-images.githubusercontent.com/82810795/164874852-84f55078-69ad-41d0-9fab-6009b045aff3.png)
version 2.9.3 also results in a blank screen 
❯ spicetify -v
2.9.3
❯ spotify --version
spotify: /usr/lib/libcurl-gnutls.so.4: no version information available (required by spotify)
Spotify version 1.1.80.699.gc3dac750, Copyright (c) 2022, Spotify Ltd

**Comment by nils-kt** [comment]
@Celibistrial update your Spotify to 1.1.83.

**Comment by ririxidev** [comment]
> ![image](https://user-images.githubusercontent.com/82810795/164874852-84f55078-69ad-41d0-9fab-6009b045aff3.png)
> version 2.9.3 also results in a blank screen
> ❯ spicetify -v
> 2.9.3
> ❯ spotify --version
> spotify: /usr/lib/libcurl-gnutls.so.4: no version information available (required by spotify)
> Spotify version 1.1.80.699.gc3dac750, Copyright (c) 2022, Spotify Ltd
> EDIT: tried 2.92 as well same result

Remove backup folder and try again

**Comment by Celibistrial** [comment]
> @Celibistrial update your Spotify to 1.1.83.

cant , the spotify aur package is version 1.1.80 and spotify does not support arch (could use debtap to install spotify.deb but it has messed up my system in the past)

**Comment by Celibistrial** [comment]
> > ![image](https://user-images.githubusercontent.com/82810795/164874852-84f55078-69ad-41d0-9fab-6009b045aff3.png)
> > version 2.9.3 also results in a blank screen
> > ❯ spicetify -v
> > 2.9.3
> > ❯ spotify --version
> > spotify: /usr/lib/libcurl-gnutls.so.4: no version information available (required by spotify)
> > Spotify version 1.1.80.699.gc3dac750, Copyright (c) 2022, Spotify Ltd
> > EDIT: tried 2.92 as well same result
> 
> Remove backup folder and try again

![image](https://user-images.githubusercontent.com/82810795/164910244-578fc933-e8af-4454-8c18-79e2d843b631.png)
clearing backup also does not fix the issue

**Comment by ririxidev** [comment]
I mean it downloads CSS map from master so maybe that's why I guess.

**Comment by theRealPadster** [comment]
Is there a deb file for 1.1.83? I thought that version only had a snap package? I was considering making an AUR package that fanagles the snap package into an arch package when I get the time actually.

**Comment by ririxidev** [comment]
> Is there a deb file for 1.1.83? I thought that version only had a snap package? I was considering making an AUR package that fanagles the snap package into an arch package when I get the time actually.

There is no deb file for 1.1.83, only 1.1.80, 1.1.72.

**Comment by nils-kt** [comment]
@ririxidev Snapcraft -> latest/edge -> 1.1.83.954.gd226dfe8

**Comment by ririxidev** [comment]
It's snap package, not deb package. Padster asked specifically for deb package.

**Comment by nils-kt** [comment]
I know. But it's maybe a workaround.

**Comment by theRealPadster** [comment]
I'm working on a "spotify-edge" AUR package. Stay tuned.

**Comment by theRealPadster** [comment]
@nils-kt Here you go! https://aur.archlinux.org/packages/spotify-edge

**Comment by nils-kt** [comment]
@theRealPadster I don't need it, I'm a Windows user. 😅

**Comment by theRealPadster** [comment]
> @theRealPadster I don't need it, I'm a Windows user. 😅

Oh lol, well I'm gonna use it myself regardless

**Comment by Celibistrial** [comment]
does the spotify-edge package work with spicetify?

**Comment by ririxidev** [comment]
There already is spotify-snapstore package that actually installs spotify from `snap` file so I guess spotify-edge isn't necessarry since it does the same like yours. @theRealPadster

**Comment by theRealPadster** [comment]
> 

Yes. I tested it when I was setting it up. 

> There already is spotify-snapstore package that actually installs spotify from `snap` file so I guess spotify-edge isn't necessarry since it does the same like yours. @theRealPadster

Wow, somehow I missed it when searching initially 🙃

**Comment by Celibistrial** [comment]
> > does the spotify-edge package work with spicetify?
> 
> Yes. I tested it when I was setting it up.
which version of spicetify did u use?

**Comment by theRealPadster** [comment]
> which version of spicetify did u use?
I believe it was 2.9.6 when I tried it.

**Comment by jkmpariab** [comment]
I'm using spotify flatpak and there is no 1.1.80 atm
Current spotify version on flatpak is 1.1.80.699.gc3dac750
I have no idea if there is a edge/beta package on flatpak (now checking flatpak cli and don't see ant flag or command to specify installing from edge/beta channel)
BTW i hate snap and that's why i'm using flatpak

**Comment by TheOmegaSystem** [comment]
Having the same issue, latest Spotify as of writing, spicetify version 2.9.8
Latest MacOS

**Comment by ririxidev** [comment]
Remove `Backup` folder from `.spicetify`, then reinstall Spotify (1.1.83+) and do `spicetify backup apply`. Will work.

**Comment by AntServiceApps** [comment]
Since a few days I also had a blank screen on windows. Decided to reinstall both and yeah it works. It sucks that you have to download all your playlists & update settings all over again but for some reason it just works.

**Comment by itsmeow** [comment]
> Since a few days I also had a blank screen on windows. Decided to reinstall both and yeah it works. It sucks that you have to download all your playlists & update settings all over again but for some reason it just works.

You probably just needed to force your Spotify to update.

**Comment by erdemozdemir98** [comment]
Same issue here. I'm using the latest spotify version from AUR (1.1.84) with spicetify 2.9.8. I tried removing `Backup` folder, reinstalling spotify and running `spicetify backup apply` and it didn't work.

**Comment by TheOmegaSystem** [comment]
> > > which version of spicetify did u use?
> > 
> > 
> > I believe it was 2.9.6 when I tried it.
> 
> just tried it out with 2.9.6 and still a blank screen (I did clear the backup folder)

Update, latest is 2.9.8

**Comment by Celibistrial** [comment]
> > > > which version of spicetify did u use?
> > > 
> > > 
> > > I believe it was 2.9.6 when I tried it.
> > 
> > 
> > just tried it out with 2.9.6 and still a blank screen (I did clear the backup folder)
> 
> Update, latest is 2.9.8

still a blank screen

**Comment by rernars** [comment]
v2.9.8 blank screen

**Comment by leon-sm** [comment]
Why is this closed? Spotify 1.1.85.895.g2a71e1b8 and v2.9.8 and still having a blank screen when loading any theme

**Comment by TheOmegaSystem** [comment]
It’s a known issue, just wait

**Comment by wael444** [comment]
i am on 1.1.84.716.gc5f8b819 and spicetify 2.9.8, this issue still occurs

**Comment by TheLastZombie** [comment]
Still happens with 2.10.0 (with 1.1.84.716.gc5f8b819).

**Comment by wael444** [comment]
~~ayo calamus wtf u doing here~~
