### ISSUE TITLE
Add musixmatch to lyrics-plus

### ISSUE THREAD

**Issue by vvirtues** [spicetify/spicetify-cli#1572]
### 📝 Provide a description of the new feature

add musixmatch to lyrics plus to add more lyrics functionality, since it's more popular among the common society

### ➕ Additional Information

Already a Spotify internal feature

**Comment by xXChampionsXx** [comment]
That is already implemented though?
![image](https://user-images.githubusercontent.com/60485613/162138911-7f7e6002-c0ed-44b2-b12c-3c2dae8e703c.png)

**Comment by afonsojramos** [comment]
Yup, already implemented!
