### ISSUE TITLE
install.sh can't specify which Spicetify version to download

### ISSUE THREAD

**Issue by FlafyDev** [spicetify/spicetify-cli#1576]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Not related
- Spicetify version: Not related
master branch
```

### 📝 Description

Since the restructure of install.sh (a82586b1aa371ab345f7e31648c5cb5997980e67) you can no longer specify which version of Spicetify to download.

**Comment by afonsojramos** [comment]
I was afraid that this was the case...
