### ISSUE TITLE
I dont find config-xpui.ini

### ISSUE THREAD

**Issue by zNexusonMK** [spicetify/spicetify-cli#1580]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: latest
- Spicetify version: 2.9.4
```

### 📝 Description

I install this on my pc, and then i downloaded too in my laptop but in my laptop i had spotify from the microsoft store and then i uninstalled it and download it again from spotify site, but i followed the guide in the faq issue, but i dont have the config-xpui.ini file so i dont know how to solve this

**Comment by zNexusonMK** [comment]
Ok i solved i googled and found the config-xpui.ini file

**Comment by zuifiti** [comment]
> Ok i solved i googled and found the config-xpui.ini file

plzz help mee
