### ISSUE TITLE
Expand-archive not found, OS windows 8.1

### ISSUE THREAD

**Issue by ProBoi990** [spicetify/spicetify-cli#1586]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Latest
- Spicetify version: 2.9.5
- Windows 8.1 OS
- Amd A6 9225 
- 4GB Ram
```

### 📝 Description

Something went wrong. Try reloading the page

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/91060300/163321928-63bbf375-f330-4e94-aff6-c754afe58981.png)

**Comment by ririxidev** [comment]
Please give us more logs since I can't reproduce the issue.

---
Environment:
```markdown
- spotify 1.1.81.604.gccacfc8c
- Windows 11 Pro Insider Preview Build 22593.1
- spicetify v2.9.5
```

**Comment by afonsojramos** [comment]
The title doesn't even match the issue itself. Please provide more info and we can reopen it.
