### ISSUE TITLE
Spotify keeps on reinstalling

### ISSUE THREAD

**Issue by idknameso69** [spicetify/spicetify-cli#1591]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.83.956.gbe7ea.9a7
- Spicetify version: v2.9.4
```

### 📝 Description

Spotify keeps reinstalling whenever I try to open the shortcut at random times. I also tried searching for a solution and according to this post (https://community.spotify.com/t5/Desktop-Windows/Why-does-spotify-re-install-every-time-I-open-it-for-the-past-40/td-p/1131948) I need to make SpotifyLauncher.exe shortcut. But the problem is I did that but it still keeps on reinstalling. And whenever it reinstalls the spicetify isn't applied anymore. I tried working things out myself but I can't do it, sorry for the inconvenience.

**Comment by amd64fox** [comment]
Do you want to block Spotify updates?

An easy way.

- Press `Win + R`

- Enter `%localappdata%\Spotify`

- Create a file named `Update` without the extension

- Go to its properties and activate the `Read-only` checkbox

Done, the update is blocked, If you need to unlock updates, just delete this `Update` file.

**Comment by ririxidev** [comment]
Sorry, but it's not related to spicetify :/. Spicetify injects javascript code to Spotify and it can't interfere with update process. Spicetify isn't applied anymore since spotify is being reinstalled. You need to apply it "every update". Anyway, can't reproduce it.

Environment: 
```
- Spotify 1.1.81.604.gccacfc8c
- Windows 11 Pro Insider Preview (OS Build 22598.100)
- Spicetify v2.9.5
```

**Comment by nozeuq** [comment]
Any solution for this? I have been recently coming across this issue as well; I have my Spotify on startup maybe that's an issue? If someone could clarify or advise any tips that would be useful that would be great!
