### ISSUE TITLE
Permission denied in MacOS

### ISSUE THREAD

**Issue by root-daemon** [spicetify/spicetify-cli#1596]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 
Spotify for macOS (Apple Silicon)
1.1.71.560.gc21c3367
- Spicetify version:2.9.5
```

### 📝 Description

1. Open Terminal
2. Run `spicetify apply`
3. Displays permission denied error 

### 📸 Screenshots

<img width="864" alt="image" src="https://user-images.githubusercontent.com/47695678/164606035-61031a4b-545b-4ae2-8472-37b7485f7854.png">

**Comment by ririxidev** [comment]
`sudo spicetify apply` should help :D
