### ISSUE TITLE
updating spotify bricks spicetify

### ISSUE THREAD

**Issue by whyredow** [spicetify/spicetify-cli#1598]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [x] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows 1.1.83.956.gbe7ea9a7
- Spicetify version: 2.9.5
- Windows 10 & 11
```

### 📝 Description

updating spotify makes it stuck on blank screen
and i have noticed, that three-dot context menu is changed
tried removind .spicetify, re-applying and reinstalling spotify

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/102296008/164684645-34d6166d-642d-49a1-a277-606d5c6a00e4.png)
![image](https://user-images.githubusercontent.com/102296008/164684747-54eebf02-d3bc-4df7-9838-e05bcc62b40c.png)
![image](https://user-images.githubusercontent.com/102296008/164684868-728ae149-9447-474f-911b-4997691d74b0.png)

**Comment by xilissium** [comment]
i have the same issue on W10 since the spotify update

**Comment by t0ry003** [comment]
I can confirm the issue is up. The spotify app is bricked once the spicetify is loaded.

### 📷ScreenShot
![image](https://user-images.githubusercontent.com/80108119/164689456-29720dd9-1aa9-40cb-a7dd-0bbe0e470661.png)
