### ISSUE TITLE
Keep getting `error Cannot backup app files. Reinstall Spotify and try again.` even after reinstalling spotify on fedora linux

### ISSUE THREAD

**Issue by ImDedInside-git** [spicetify/spicetify-cli#1601]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:
~ ❯ spotify -v                                    
Version: 1.1.80.699.gc3dac750_amd64.deb
Note: This is installed on Fedora Linux 35 with lpf [https://docs.fedoraproject.org/en-US/quick-docs/installing-spotify/]


- Spicetify version:
~ ❯ spicetify -v
2.9.5
```

### 📝 Description

Running `spicetify backup apply` gives this error.  
```Markdown
error Cannot backup app files. Reinstall Spotify and try again.
```

First time installing spicetify using curl commands 
```Markdown
curl -fsSL https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.sh | sh
curl -fsSL https://raw.githubusercontent.com/spicetify/spicetify-marketplace/main/install.sh | sh
```
Reinstalling spotify made no difference

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/67794677/164720376-665a2986-88f4-4773-a443-8a7b80934935.png)

**Comment by ririxidev** [comment]
spotify 1.1.80 isn't supported by v2.9.5.

**Comment by theRealPadster** [comment]
You may need to change permissions on the folder that spotify is installed to

**Comment by Lalit64** [comment]
Hey @ImDedInside-git I am getting the same error on macOS arm64 `spicetify backup apply enable-devtool`spicetify backup apply enable-devtool`

<img width="1686" alt="Screenshot 2022-04-29 at 12 02 21" src="https://user-images.githubusercontent.com/79628080/165924350-f4c08955-0942-4f51-9bf1-aa36089b7dd0.png">


And My Config:
<img width="1686" alt="Screenshot 2022-04-29 at 12 03 21" src="https://user-images.githubusercontent.com/79628080/165924501-d8bf7102-e6f7-46b5-b43a-3422797f1443.png">

**Comment by xerta555** [comment]
> Permissions.

If this issue really come from permissions, i think it could be a good idea to specifying wich perms the folder and files must have

**Comment by ririxidev** [comment]
Check your permissions, closing issue.

**Comment by Lalit64** [comment]
> Permissions.

I am using sudo now. It says the same thing.

**Comment by Lalit64** [comment]
<img width="1630" alt="Screenshot 2022-05-19 at 13 15 12" src="https://user-images.githubusercontent.com/79628080/169280926-6f42243e-e5de-4fd2-9f5e-7aa15ae00721.png">

**Comment by finnole12** [comment]
Getting the same error, any progress made here?

**Comment by mathdenduper** [comment]
@Lalit64 @ImDedInside-git @finnole12

Hey guys, although I'm very late, I have found a solution to this very annoying problem!

I had the exact same problem as you guys and was trying to find an answer.

You cannot set your spotify_path to just ```/Users/[username]/Applications/Spotify.app``` it must be set to ```/Users/[username]/Applications/Spotify.app/Contents/Resources``` like explained [here](https://spicetify.app/docs/getting-started).

Use this command ```spicetify config spotify_path "$HOME/Applications/Spotify.app/Contents/Resources"
``` for Linux/MacOS, or type ```spicetify path``` in the terminal, open the file ```config-xpui.ini```, and manually set your spotify_path, and make sure to include /Contents/Resources in the path.

I hope this helps!
