### ISSUE TITLE
Spotify stuck on starting when updated to 2.9.6

### ISSUE THREAD

**Issue by ps13g** [spicetify/spicetify-cli#1603]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for macOS (Apple Silicon) 1.1.81.604.gccacfc8c
- Spicetify version: 2.9.6
```

### 📝 Description

1. Upgrade to Spicetify 2.9.6
2. Run `restore backup apply`
3. Wait till Spotify restarts

### 📸 Screenshots

<img width="1512" alt="Screen Shot 2022-04-22 at 5 54 39 PM" src="https://user-images.githubusercontent.com/84423124/164829547-af6580a0-8ade-4aae-88f8-9e32b18a1785.png">

**Comment by ps13g** [comment]
Update: The new Spicetify Version still does not work even with Spotify being upgraded to 1.1.83.956.gbe7ea9a7

**Comment by theRealPadster** [comment]
2.9.6 is also not working for me on 1.1.83 macOS arm64. 
`Uncaught SyntaxError: Unexpected number` in xpui.js:1

**Comment by cdtinen** [comment]
> 2.9.6 is also not working for me on 1.1.83 macOS arm64. `Uncaught SyntaxError: Unexpected number` in xpui.js:1
> 
> The loading wheel is Dribbblish, btw. It's probably stuck there because xpui.js (Spotify itself) is broken. I don't have Dribbblish and just get a blank screen.

Same error for me, W10, 2.9.6 on Spotify 1.1.83.956.gbe7ea9a7.

**Comment by DAMIOSKIDEV** [comment]
Same issue on Windows 11 Insider 22598, Spicetify 2.9.6, Spotify 1.1.83.956.gbe7ea9a7

**Comment by ririxidev** [comment]
Please all of you just remove Backup and completely reinstall Spotify. (for macOS use AppCleaner).
It works perfectly fine on 1.1.83.956.gbe7ea9a7 after deleting spicetify backup and even reinstalling Spotify.
Please check again since it seems that it isn't on our end.

**Comment by ps13g** [comment]
Still does not work after removing the backup and reinstalling Spotify it just gives me the same loading issue on 2.9.6

**Comment by ririxidev** [comment]
Okay, could you open DevTools (check this comment; https://github.com/spicetify/spicetify-cli/issues/1518#issuecomment-1060122063) and show us console errors?

**Comment by ps13g** [comment]
> Okay, could you open DevTools (check this comment; [#1518 (comment)](https://github.com/spicetify/spicetify-cli/issues/1518#issuecomment-1060122063)) and show us console errors?

Got it to work after a few hours of debugging all that I needed to do was to clear the backup before deleting and reinstalling Spotify and after that it managed to work

**Comment by ririxidev** [comment]
That's what I told you to do. 
> Please all of you just remove Backup and completely reinstall Spotify

Anyway, good that you got it working 👍  Closing.
