### ISSUE TITLE
config-xpui.ini file doesnt get created

### ISSUE THREAD

**Issue by K0ha1** [spicetify/spicetify-cli#1608]
### 🔍 Have you checked Spicetify.app page for your issue?

- [x] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: latest
- Spicetify version: latest
```

### 📝 Description

basically just doesnt create the config-xpui.ini file and i dont know how to make one since i havent rlly found any templates for it

### 📸 Screenshots

![Screenshot from 2022-04-24 11-32-28](https://user-images.githubusercontent.com/69011302/164970015-e098db54-0a82-417e-a638-fa5051270098.png)

**Comment by Exhigh** [comment]
could you in your terminal type "spicetify config-dir"

**Comment by ririxidev** [comment]
your account has perms to even create it tho?
