### ISSUE TITLE
Folder switches are not working correctly

### ISSUE THREAD

**Issue by amd64fox** [spicetify/spicetify-cli#1609]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.84.716.gc5f8b819
- Spicetify version: 2.9.6
```

### 📝 Description

I tested only [1.1.84](https://cutt.ly/8EH6NuH), but I think the same problem will be on previous versions.
Maybe the problem is in this [regex](https://github.com/spicetify/spicetify-cli/blob/7e81937e7c1584ab56b62831ba13b5afdf89d525/src/preprocess/preprocess.go#L244)

### 📸 Screenshots

<details>
<summary><small>Original Spotify</small></summary><p>

![no_bug](https://user-images.githubusercontent.com/62529699/164980924-a4d3686b-f359-45af-8272-504ae65204e1.gif)

</small></summary><p>

</details>

<details>
<summary><small>Patched Spicetify</small></summary><p>

![bug](https://user-images.githubusercontent.com/62529699/164980967-0e5a30f9-515f-4a3f-b948-a37f7543d1b5.gif)

</small></summary><p>
</details>

**Comment by itsmeow** [comment]
If you disable RTL removal in the spicetify config, does that stop this from happening?

**Comment by amd64fox** [comment]
> If you disable RTL removal in the spicetify config, does that stop this from happening?

Yes this fixes the problem.

Moreover, it is enough to fix only the very first RTL rule that I specified.

**Comment by amd64fox** [comment]
not fixed

**Comment by itsmeow** [comment]
literally someone just comment the line
