### ISSUE TITLE
spotify not loading after update

### ISSUE THREAD

**Issue by nimsandu** [spicetify/spicetify-cli#1611]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows 1.1.83.956.gbe7ea9a7
- Spicetify version: 2.9.6
```

### 📝 Description

after updating Spotify a black ui appeared and it didn't load
i reinstalled spotify and then it worked
after applying spicetify the same issue occurred
this is not specific to any theme cuz i tried three themes 
i also re installed spicetify
and also waited more than one hour to see whether it loads

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/57834844/164988228-c717b293-7048-4c5c-9ad9-02f8a7f873d2.png)

**Comment by slh-git** [comment]
Same issue here

**Comment by DaBantableGamer** [comment]
Same issue on macOS Monterey 12.3.1, Spotify for macOS (Apple Silicon) 1.1.83.956.gbe7ea9a7

**Comment by ririxidev** [comment]
Remove `Backup` folder from `.spicetify`, then reinstall Spotify and do `spicetify backup apply`. Will work.

**Comment by teddybloat** [comment]
run spicetify upgrade in powershell

it will upgrade to 2.9.7

then backup apply

fixed it for me

**Comment by zjeffer** [comment]
The above two solutions didn't work for me.

* Spicetify-cli version `2.9.7-1`
* Spotify version `1:1.1.80.699-1`

On Arch Linux, both packages downloaded from AUR.

**Comment by ririxidev** [comment]
Please use higher Spotify version. 1.1.80 isn't supported

**Comment by zjeffer** [comment]
@ririxidev Thanks. Is the normal `spotify` AUR package out of date, or has Spotify just not released a non-snap version of the latest client?

**Comment by ririxidev** [comment]
Normal spotify package is out to date because Spotify releases the latest ones only to Snap store. There is no latest version outside snap store as I'm aware

**Comment by zjeffer** [comment]
Thanks, it now works with your fix: https://github.com/spicetify/spicetify-cli/issues/1611#issuecomment-1107890992

**Comment by JamesGordonII** [comment]
This is still happening to me, i use the comfy theme but removing it doesn't change anything, only the colors.

**Comment by GuessWhatBBQ** [comment]
> Normal spotify package is out to date because Spotify releases the latest ones only to Snap store. There is no latest version outside snap store as I'm aware

By latest I'm assuming you mean the latest/edge as from what I can see the latest/stable on both the aur and the snap store, as of now, is 1.1.80.699. Or am I missing something ?

**Comment by ririxidev** [comment]
I'm closing this issue since issue is tbh resolved and it's not because of spicetify bug. Please use this solution if you have this issue: https://github.com/spicetify/spicetify-cli/issues/1611#issuecomment-1107890992

**Comment by h7mshin** [comment]
> run spicetify upgrade in powershell
> 
> it will upgrade to 2.9.7
> 
> then backup apply
> 
> fixed it for me

It fixed thanks
