### ISSUE TITLE
Spicetify only showing the body elements after most recent spotify update

### ISSUE THREAD

**Issue by JamesGordonII** [spicetify/spicetify-cli#1619]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows
1.1.83.956.gbe7ea9a7
- Spicetify version:2.9.7
```

### 📝 Description

After the Spotify update spicetify only shows the body element, I currently use the comfy theme, But even when removing the theme and using the default one it still only displays the body element. i have tried removing the backup folder and nothing changes. i have no idea what changed backend, maybe a API call is falling or a path changed. anyways hop someone can help me with this

P.S. this is not a duplicate of the other bank body error because they where using a older version of spicetify.

### 📸 Screenshots

![Screenshot_39](https://user-images.githubusercontent.com/82000305/165191056-38d20400-a546-43cd-8327-6994dc6b0964.png)

**Comment by JamesGordonII** [comment]
I can comferm that spotify is running tho because the webplayer shows that I can play using the app and it works, just no UI elements are loading

**Comment by afonsojramos** [comment]
Can you try to:
1. Remove Backup folder from `.spicetify`
2. Reinstall Spotify 
3. Run `spicetify backup apply`.

**Comment by JamesGordonII** [comment]
In .y post I said I already did, but it doesn't no anything

**Comment by TheMayhem6328** [comment]
I am also having the same issue:
| Entity | Info |
| --- | --- |
| OS | Arch Linux x86_64 |
| DE | plasma-desktop 5.24.4-1 |
| Spotify | 1:1.1.80.699-1 (AUR) (Yes I chmodded necessary directories) |
| Spicetify | 2.9.7-1 (Still AUR) |

Config:
```ini
[Preprocesses]
disable_ui_logging    = 1
remove_rtl_rule       = 1
expose_apis           = 1
disable_upgrade_check = 1
disable_sentry        = 1

[AdditionalOptions]
home_config           = 1
experimental_features = 1
extensions            = dribbblish.js|fullAppDisplay.js|spotifyLyrics.js|popupLyrics.js
custom_apps           = new-releases|lyrics-plus|spicetify-marketplace
sidebar_config        = 1

[Patch]

[Setting]
color_scheme            = purple-light
replace_colors          = 1
overwrite_assets        = 0
spotify_launch_flags    = 
spotify_path            = /opt/spotify
prefs_path              = /home/mayhem6328/.config/spotify/prefs
current_theme           = Dribbblish
inject_css              = 1
check_spicetify_upgrade = 0

; DO NOT CHANGE!
[Backup]
version = 1.1.80.699.gc3dac750
with    = 2.9.7

```

**Comment by xerta555** [comment]
> I am also having the same issue:
> Entity 	Info
> OS 	Arch Linux x86_64
> DE 	plasma-desktop 5.24.4-1
> Spotify 	1:1.1.80.699-1 (AUR) (Yes I chmodded necessary directories)
> Spicetify 	2.9.7-1 (Still AUR)
> 
> Config:
> 
> ```ini
> [Preprocesses]
> disable_ui_logging    = 1
> remove_rtl_rule       = 1
> expose_apis           = 1
> disable_upgrade_check = 1
> disable_sentry        = 1
> 
> [AdditionalOptions]
> home_config           = 1
> experimental_features = 1
> extensions            = dribbblish.js|fullAppDisplay.js|spotifyLyrics.js|popupLyrics.js
> custom_apps           = new-releases|lyrics-plus|spicetify-marketplace
> sidebar_config        = 1
> 
> [Patch]
> 
> [Setting]
> color_scheme            = purple-light
> replace_colors          = 1
> overwrite_assets        = 0
> spotify_launch_flags    = 
> spotify_path            = /opt/spotify
> prefs_path              = /home/mayhem6328/.config/spotify/prefs
> current_theme           = Dribbblish
> inject_css              = 1
> check_spicetify_upgrade = 0
> 
> ; DO NOT CHANGE!
> [Backup]
> version = 1.1.80.699.gc3dac750
> with    = 2.9.7
> ```

You have to updating your Spotify version :)

**Comment by ZurgP** [comment]
I have also the same issue .
![image](https://user-images.githubusercontent.com/101988094/165308288-dcfe9a27-9e84-4b48-baec-a09d3d7e53fc.png)
Just nothing, but i can still lisen to music . only if i guess where is the pause button

**Comment by SiamionRalionak** [comment]
Having the same issue:
| Entity | Info |
| --- | --- |
| OS | Manjaro Linux 5.17.4 x86_64|
| DE | i3 |
| Spicetify | 2.9.7-1 |
| Spotify | 1.1.80.699 |

Config:
```ini
[Setting]
overwrite_assets        = 1
check_spicetify_upgrade = 0
prefs_path              = /home/xxx/.config/spotify/prefs
replace_colors          = 1
color_scheme            = nord-dark
inject_css              = 1
spotify_launch_flags    = --autostart|--app-icon-overlay|--enable-audio-graph|--experimental-network
spotify_path            = /opt/spotify
current_theme           = Dribbblish

[Preprocesses]
disable_sentry        = 1
disable_ui_logging    = 1
remove_rtl_rule       = 1
expose_apis           = 1
disable_upgrade_check = 1

[AdditionalOptions]
extensions            = keyboardShortcut.js|fullAppDisplay.js|shuffle+.js|trashbin.js|loopyLoop.js|popupLyrics.js|dribbblish.js|historyShortcut.js|copytoclipboard2.js|romaji.mjs|bookmark.js
custom_apps           = new-releases|lyrics-plus|reddit
experimental_features = 1
sidebar_config        = 1
home_config           = 1

[Patch]
xpui.js_find_8008 = ,(\w+=)32,
xpui.js_repl_8008 = ,${1}56,

[Backup]
version = 1.1.80.699.gc3dac750
with    = 2.9.7
```
![2022-04-26-170208_1970x1045_scrot](https://user-images.githubusercontent.com/65658208/165317576-e42759ef-f6c3-4584-be88-b90020eb7e1d.png)

**Comment by ririxidev** [comment]
> Having the same issue:
> 
> Entity	Info
> OS	Manjaro Linux 5.17.4 x86_64
> DE	i3
> Spicetify	2.9.7-1
> Spotify	1.1.80.699
> Config:
> 
> ```ini
> [Setting]
> overwrite_assets        = 1
> check_spicetify_upgrade = 0
> prefs_path              = /home/xxx/.config/spotify/prefs
> replace_colors          = 1
> color_scheme            = nord-dark
> inject_css              = 1
> spotify_launch_flags    = --autostart|--app-icon-overlay|--enable-audio-graph|--experimental-network
> spotify_path            = /opt/spotify
> current_theme           = Dribbblish
> 
> [Preprocesses]
> disable_sentry        = 1
> disable_ui_logging    = 1
> remove_rtl_rule       = 1
> expose_apis           = 1
> disable_upgrade_check = 1
> 
> [AdditionalOptions]
> extensions            = keyboardShortcut.js|fullAppDisplay.js|shuffle+.js|trashbin.js|loopyLoop.js|popupLyrics.js|dribbblish.js|historyShortcut.js|copytoclipboard2.js|romaji.mjs|bookmark.js
> custom_apps           = new-releases|lyrics-plus|reddit
> experimental_features = 1
> sidebar_config        = 1
> home_config           = 1
> 
> [Patch]
> xpui.js_find_8008 = ,(\w+=)32,
> xpui.js_repl_8008 = ,${1}56,
> 
> [Backup]
> version = 1.1.80.699.gc3dac750
> with    = 2.9.7
> ```
> 
> ![2022-04-26-170208_1970x1045_scrot](https://user-images.githubusercontent.com/65658208/165317576-e42759ef-f6c3-4584-be88-b90020eb7e1d.png)

You have old spotify. Download 1.1.83, it's under `spotify-snapstore`/`spotify-edge` in aur.

**Comment by SiamionRalionak** [comment]
@ririxidev worked for me, thanks!

**Comment by lor1x** [comment]
Same issue on macOS 12.3.1 with Spotify `1.1.83.956.gbe7ea9a7`, spicetify `v.2.9.7`
Already reinstalled both, spicetify and Spotify

**Comment by ririxidev** [comment]
> Same issue on macOS 12.3.1 with Spotify `1.1.83.956.gbe7ea9a7`, spicetify `v.2.9.7` Already reinstalled both, spicetify and Spotify

Remove .backup folder from `.spicetify` or `.config/spicetify` I don't remember now where it is, then reinstall spotify and do `spicetify backup apply`

**Comment by lor1x** [comment]
@ririxidev I did a reinstall of both, I always remove any file that they had anywhere they are on the drive.

**Comment by ririxidev** [comment]
removed spotify with AppCleaner?

**Comment by lor1x** [comment]
yup, i double checked the `~/Library` folder too just in case

**Comment by lor1x** [comment]
> Already reinstalled both, spicetify and Spotify
@ZurgP did not help on my end

**Comment by ps13g** [comment]
> > Already reinstalled both, spicetify and Spotify
> 
> @ZurgP did not help on my end

attempt to do `spicetify clear backup` and then uninstall spotify and reinstall it and then do `spicetify apply` it should work

**Comment by fernamp** [comment]
2.9.7 Works for me now in Spotify 1.1.83.956, BUT, there's a new version of Spotify out now: 1.1.84.716. I will gladly wait to the new version of Spicetify before updating ;)

**Comment by xerta555** [comment]
> 2.9.7 Works for me now in Spotify 1.1.83.956, BUT, there's a new version of Spotify out now: 1.1.84.716. I will gladly wait to the new version of Spicetify before updating ;)

We can suppose that you have already try to make a fresh install of Spotify and Spicetify?

**Comment by ririxidev** [comment]
Didn't have any problems on 1.1.84 with spicetify

**Comment by ririxidev** [comment]
Closing this issue since “issue” doesn’t exist. If you need more help please contact us on our discord server 👍
