### ISSUE TITLE
Spicetify marketplace huge extension tiles

### ISSUE THREAD

**Issue by craxycat** [spicetify/spicetify-cli#1620]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.83.956.gbe7ea9a7
- Spicetify version: 2.9.7
```

### 📝 Description

Marketplace items have 100% width in marketplace.

### 📸 Screenshots

![2022-04-27_02-17-59](https://user-images.githubusercontent.com/1554726/165346285-b57f96b0-1b76-415b-9900-62f775be42ba.png)
![2022-04-27_02-17-22](https://user-images.githubusercontent.com/1554726/165346295-4fd4f992-ebcc-407f-9f91-db5de1df441c.png)

**Comment by CharlieS1103** [comment]
Update marketplace.
