### ISSUE TITLE
Blank colored screen with Dribbblish theme

### ISSUE THREAD

**Issue by Passeriform** [spicetify/spicetify-cli#1621]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.80.699.gc3dac750
- Spicetify version: 2.9.7
```

### 📝 Description

I recently updated my spicetify from 2.9.5 to 2.9.7 and I am getting a blank, background-colored screen when I run:
```
$ spicetify restore backup apply
```
The blank screen occurs on Dribbblish theme and not on Default theme. I am using the current master code at [Spicetify-Themes](https://github.com/spicetify/spicetify-themes/) which worked fine with 2.9.5 version.

__colors.ini__
```ini
[custom]
text               = dad2d2
sidebar-text       = 241e26
subtext            = AA9FA2
main               = 241e26
sidebar            = 748690
player             = 748690
button             = 938A91
card               = AA9FA2
selected-row       = AA9FA2
button-active      = AA9FA2
tab-active         = AA9FA2
button-disabled    = 241e26
shadow             = 241e26
notification       = C2D935
notification-error = E22134
misc               = BFBFBF
```
__config-xpui.ini__
```ini
[AdditionalOptions]
extensions            = dribbblish.js
custom_apps           = 
sidebar_config        = 1
home_config           = 1
experimental_features = 1

[Patch]

[Setting]
prefs_path              = /home/passeriform/.config/spotify/prefs
color_scheme            = custom
spotify_launch_flags    = 
spotify_path            = /opt/spotify
current_theme           = Dribbblish
inject_css              = 1
replace_colors          = 1
overwrite_assets        = 1
check_spicetify_upgrade = 1

[Preprocesses]
disable_sentry        = 1
disable_ui_logging    = 1
remove_rtl_rule       = 1
expose_apis           = 1
disable_upgrade_check = 1

; DO NOT CHANGE!
[Backup]
version = 1.1.80.699.gc3dac750
with    = 2.9.7

```

Please let me know if I should open the issue on the theme repository instead.

### 📸 Screenshots

**Versions**
![versions](https://user-images.githubusercontent.com/32395996/165388650-ab4e89ba-7da2-4157-9bdc-bcc5a21818cf.png)
**Spicetify apply**
![spicetify](https://user-images.githubusercontent.com/32395996/165388646-5a35d2ee-c5d4-495a-b473-d649b0dd9332.png)
**Running spotify from cli**
![log](https://user-images.githubusercontent.com/32395996/165388636-6abff33a-2469-4fb8-b91c-b839ff47cbba.png)
**Blank screen window**
![ui](https://user-images.githubusercontent.com/32395996/165388647-bda27246-6a97-4288-8013-781ada31f8a1.png)

**Comment by Passeriform** [comment]
I ran spotify with remote debugger and opened devtools with `chrome://inspect` method:
```bash
$ spotify --remote-debugging-port=9222
```

Console logs:
![consolelogs](https://user-images.githubusercontent.com/32395996/165392142-63288e5a-93a9-4126-b10f-aff76854caf3.png)

I formatted `/opt/spotify/Apps/xpui/xpui.js` to get the error location:
![formattedlogs](https://user-images.githubusercontent.com/32395996/165392411-eaef4636-0215-436a-95f8-c373c5b48caa.png)
![editor](https://user-images.githubusercontent.com/32395996/165392801-d8764063-eca2-49f2-b8db-c6243cc93e1e.png)
![editor2](https://user-images.githubusercontent.com/32395996/165393168-d1e09834-ce9a-43a2-a753-8a1042e11b89.png)


But I don't think its helpful to track it this way. I can better test it with source maps but I don't know how to enable it.

**Comment by ririxidev** [comment]
Duplicate, solution here: https://github.com/spicetify/spicetify-cli/issues/1611#issuecomment-1107890992

**Comment by Passeriform** [comment]
@ririxidev Sorry I have a linux system.
The AUR package goes only upto 1.1.80. If there exists a link for v1.1.83, can you please point me to it.
Also the solution you linked didn't work for me.

**Comment by ririxidev** [comment]
Use spotify-edge or spotify-snapstore package from aur

**Comment by Passeriform** [comment]
Yup that does it. Thanks!
