### ISSUE TITLE
Can't enable dev-tools on (Arch) Linux

### ISSUE THREAD

**Issue by theRealPadster** [spicetify/spicetify-cli#1622]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.84.716.gc5f8b819
- Spicetify version: v2.9.7
```

### 📝 Description

I've got Spotify installed via the [spotify-edge](https://aur.archlinux.org/packages/spotify-edge) AUR package, and spicetify-cli on AUR

```
> spicetify enable-devtools
spicetify v2.9.7
Can't find the offline.bnk file!
```
Config file may be relevant
```ini
[Setting]
spotify_path            = /opt/spotify
replace_colors          = 1
check_spicetify_upgrade = 0
spotify_launch_flags    = 
prefs_path              = /home/padster/.config/spotify/prefs
current_theme           = better-default
color_scheme            = matte
inject_css              = 1
overwrite_assets        = 0
```

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/1565883/165427509-fd7ee63f-df8d-41a5-9476-2829b93577c0.png)

**Comment by ririxidev** [comment]
Fixed in https://github.com/spicetify/spicetify-cli/commit/cb299665913727a2dcc5c79bf1e56a8a110c02bf.
Instead of .cache I did .config for some reason.
