### ISSUE TITLE
key-value delimiter not found: ELF>@�@X

### ISSUE THREAD

**Issue by Guiki18** [spicetify/spicetify-cli#1624]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify version 1.1.72.439.gc253025e
- Spicetify version: spicetify v2.9.7
```

### 📝 Description

Hello, i was recently installed spicetify on my pc, but for some reason, when i execute the `spicetify backup apply`that's show an error:

```bash
luis@Linux:~$ spicetify backup apply
spicetify v2.9.7
key-value delimiter not found: ELF>@�@X
luis@Linux:~$ 
```
someone know the error?

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/72317733/165562246-10ba4a7d-11e1-4915-aaf7-99734c726bf4.png)

**Comment by Guiki18** [comment]
Forgeted to put some information about the pc

```
luis@Linux:~$ neofetch
           `.:/ossyyyysso/:.               luis@Linux 
        .:oyyyyyyyyyyyyyyyyyyo:`           ---------- 
      -oyyyyyyyodMMyyyyyyyysyyyyo-         OS: Kubuntu 22.04 LTS x86_64 
    -syyyyyyyyyydMMyoyyyydmMMyyyyys-       Host: HP 255 G7 Notebook PC 
   oyyysdMysyyyydMMMMMMMMMMMMMyyyyyyyo     Kernel: 5.15.0-27-generic 
 `oyyyydMMMMysyysoooooodMMMMyyyyyyyyyo`    Uptime: 4 hours, 53 mins 
 oyyyyyydMMMMyyyyyyyyyyyysdMMysssssyyyo    Packages: 2118 (dpkg), 5 (flatpak), 12 (snap) 
-yyyyyyyydMysyyyyyyyyyyyyyysdMMMMMysyyy-   Shell: bash 5.1.16 
oyyyysoodMyyyyyyyyyyyyyyyyyyydMMMMysyyyo   Resolution: 1366x768 
yyysdMMMMMyyyyyyyyyyyyyyyyyyysosyyyyyyyy   DE: Plasma 5.24.4 
yyysdMMMMMyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy   WM: KWin 
oyyyyysosdyyyyyyyyyyyyyyyyyyydMMMMysyyyo   Theme: [Plasma], Breeze [GTK2/3] 
-yyyyyyyydMysyyyyyyyyyyyyyysdMMMMMysyyy-   Icons: [Plasma], breeze-dark [GTK2/3] 
 oyyyyyydMMMysyyyyyyyyyyysdMMyoyyyoyyyo    Terminal: konsole 
 `oyyyydMMMysyyyoooooodMMMMyoyyyyyyyyo     CPU: AMD Ryzen 3 3300U with Radeon Vega Mobile Gfx (4) @ 2.100GHz 
   oyyysyyoyyyysdMMMMMMMMMMMyyyyyyyyo      GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Series 
    -syyyyyyyyydMMMysyyydMMMysyyyys-       Memory: 3930MiB / 5878MiB 
      -oyyyyyyydMMyyyyyyysosyyyyo-
        ./oyyyyyyyyyyyyyyyyyyo/.                                   
           `.:/oosyyyysso/:.`                                      


luis@Linux:~$ 
```

**Comment by afonsojramos** [comment]
Additionally your Spicetify version is not for the Spotify version you are running!

**Comment by Guiki18** [comment]
That's true, but, for some reason, i solve it running `luis@Linux:~$ spicetify config prefs_path ~/.config/spotify/prefs`
i forget to set the config path of spotify

**Comment by Guiki18** [comment]
I just test some theme to see if it working

**Comment by Guiki18** [comment]
![image](https://user-images.githubusercontent.com/72317733/165728700-bc0cfc6a-303d-48ab-bb08-0a54936b6526.png)
Well that's working now, not showing some icons and text but i will try resolve it alone

thanks for help @afonsojramos @ririxidev

**Comment by afonsojramos** [comment]
Likely due to the Spotify version. I'd suggest getting it from somewhere else

**Comment by Guiki18** [comment]
![image](https://user-images.githubusercontent.com/72317733/165735864-f937c7c7-1b1a-491b-b1e9-beff58ae496e.png)
solve the problem of invalid characters, and for now everything was working
