### ISSUE TITLE
Black screen after applying [linux]

### ISSUE THREAD

**Issue by grugabyte** [spicetify/spicetify-cli#1625]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify version 1.1.80.699.gc3dac750 (aur package)
spicetify version: 2.9.7 (also aur package)
OS: Manjaro kernel 5.16
```

### 📝 Description

Hi there, I was trying to install spicetify on my computer and it seems I have run into a bug. I have tried to look at other bugs that are similar to mine but the solutions did not appear to fix my problem. I tried to apply spicetify by using `spicetify backup && spicetify apply` and the command executed with success. However when I boot into Spotify I found that the screen is entirely blank. Using my media keys on my keyboard can play media however I cannot interact with the program. I am somewhat of a Linux newbie and any help would be appreciated, thanks.

### 📸 Screenshots

![spotify](https://user-images.githubusercontent.com/98688177/165736117-7120472e-b14c-47f1-9bb8-1cdbcbae8ed1.png)

**Comment by ririxidev** [comment]
Duplicate,

https://github.com/spicetify/spicetify-cli/issues/1621#issuecomment-1110304501

https://github.com/spicetify/spicetify-cli/issues/1621#issuecomment-1110324360
