### ISSUE TITLE
Make spicetify update against dev-tools update commit

### ISSUE THREAD

**Issue by Guiki18** [spicetify/spicetify-cli#1626]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify version 1.1.72.439.gc253025e, Copyright (c) 2021, Spotify Ltd
- Spicetify version: 2.9.7
```

### 📝 Description

This is not really an error, but a failure in the spicetify update.

I had a problem, that when I installed spotify and tried to run `spicetify enable-devtools` an error appeared saying:
```
luis@Linux:~$ spicetify enable-devtools
spicetify v2.9.7
Can't find the offline.bnk file!
```
With a bit of investigation, I discovered that the error came from a small issue that was resolved in a commit: #1618

Now, I have downloaded all the files including this commit, since the current version of spicetify has not received this update yet, I did my compilation and it solved this error,

My problem would be in relation to other users who are having the same error, from `Can't find the offline.bnk file!`
Couldn't they update a new release/build to solve this problem?

**Comment by ririxidev** [comment]
Rebuild then or wait for next release. It’s not worth for us to make release just for it.
