### ISSUE TITLE
"Remove from this playlist" not working with Shuffle+ extension

### ISSUE THREAD

**Issue by Arikabeth** [spicetify/spicetify-cli#1628]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows 1.1.84.716.gc5f8b819
- Spicetify version: 2.9.7
- System: Windows 10 64 bit, 19043 build
```

### 📝 Description

1. Go to a playlist made by your profile (which you have the right to edit)
2. Click the ( . . . ) below the playlist title, (or right click on the playlist name in the lefthand playlist/folder list) and select "Play with Shuffle+"
3. Right click on the name of the currently playing track in the bottom left under the album art, and click on "Remove from this playlist".
4. Check if the track is removed from the playlist or not (in my case it ends up not being removed when I tested).

P.S. I'm sorry if this is not exactly a "bug" if I misunderstand what the shuffle+ extensions actually does when it is used on the playlist since I don't quite understand if the shuffle+ plays from the playlist and thus if it's even possible to "fix" this bug...

### 📸 Screenshots

![play with shuffle](https://user-images.githubusercontent.com/87768397/165928085-1c92d551-606b-4b9b-8e38-f3b4d8b3d416.png)
![remove from this playlist](https://user-images.githubusercontent.com/87768397/165928091-971829bb-f999-431f-b3a8-e0fd20061afc.png)

**Comment by Arikabeth** [comment]
What does it mean when the issue is marked as stale anyway? Does it happen with all issues where no one has posted in them for a while?

**Comment by Muriciod** [comment]
It doesn't work because Shuffle+ doesn't play directly from the playlist; it only creates a queue with all the songs. You're not listening directly from the playlist. Shuffle+ creates a queue with its own shuffle method to make it work; if you want to remove a song, you have to do it manually
