### ISSUE TITLE
Sidebar Config

### ISSUE THREAD

**Issue by RazerFlick** [spicetify/spicetify-cli#1629]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.84.716.gc5f8b819
- Spicetify version: 2.9.8
```

### 📝 Description

**Sidebar config** and **home config** is not available anymore after I updated to v2.9.8. And after I installed the **"PlaylistIcons"** extension I see no images in the playlist sidebar. Basically the  whole sidebar has changed and clumsy now. Before it had "Create Playlist", "Liked Songs", "Your Episodes" in the form just icons and compact. Now its all big again. I use the Comfy-Shadow theme which used to look so good now it doesn't open the friends list on hover anymore.
The **"Queue Time"** extension is also bugged and doesn't show the time in the queue list.
The **"Toggle Friends List"** extension also doesn't work for me.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/93324953/165953589-3758d824-8a9d-4ae2-911f-e2257d9dc7b2.png)
![image](https://user-images.githubusercontent.com/93324953/165953595-435c4528-5145-4359-b78b-780d10907997.png)
![image](https://user-images.githubusercontent.com/93324953/165954874-1ee75731-042a-4a9d-8bfe-c2d7652f6a2a.png)

**Comment by Bopzer** [comment]
I'm using Dribbblish theme but I have the same (and other similar) problems. Hope they fix it soon.

**Comment by RazerFlick** [comment]
@Bopzer Yes even in Dribbblish there are no playlist icons

**Comment by arDrag0n** [comment]
same here
