### ISSUE TITLE
theme change is broken

### ISSUE THREAD

**Issue by Vuschi** [spicetify/spicetify-cli#1634]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.84.716.gc5f8b819
- Spicetify version:v2.9.8
```

### 📝 Description

1. open Marketplace tab,
2. go to themes tab in marketplace
3. next to cog wheel click theme (if using Onepunch theme the default option should be "dark")
4. tab to change theme is blank

this happens to not only the Onepunch theme but every theme ive tried that has multiple variations, I thought it was just because i had a new install of spicetify/spotify and had to put the themes into the themes folder, but adding them did not work.  pic(s) related, one with dribblish and one with Onepunch, can provide more examples if needed

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/64656080/165996411-21965897-5f0a-4bd3-a639-47cd5752c649.png)
![image](https://user-images.githubusercontent.com/64656080/165996468-fff86c77-59cb-4062-b24a-3205ecaed65c.png)

**Comment by ririxidev** [comment]
It's more about marketplace custom app than spicetify, but from what I know that hook is broken for that, so, if you want to open issue here - you can only report about hook, other stuff related to marketplace on https://github.com/spicetify/spicetify-marketplace
