### ISSUE TITLE
[Lyrics Plus] At the end of some Genius lyrics it says "undefinedundefined"

### ISSUE THREAD

**Issue by samanft** [spicetify/spicetify-cli#1635]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows
1.1.84.716.gc5f8b819
- Spicetify version: 2.9.8
```

### 📝 Description

Not really a big deal but I thought I'd still report it

It doesn't happen on every song but it's pretty common

### 📸 Screenshots
Here's some examples of what I mean
![image](https://user-images.githubusercontent.com/25375434/166058160-0f5a9c2d-ca69-4b1b-8ed7-9c4352301e1a.png)
![image](https://user-images.githubusercontent.com/25375434/166058763-ddbdbc24-e243-48fd-b3dd-3405f663f9f3.png)

**Comment by ririxidev** [comment]
@kyrie25 I bet it's something with commits that you did.

**Comment by kyrie25** [comment]
> @kyrie25 I bet it's something with commits that you did.

Yeah ik, the PR earlier was to address this. Since it was merged, this should be resolved.

**Comment by ririxidev** [comment]
> > @kyrie25 I bet it's something with commits that you did.
> 
> Yeah ik, the PR earlier (#1630) was to address this. Since it was merged, this issue has been resolved.

ah, makes sense.

**Comment by ririxidev** [comment]
fixed.
