### ISSUE TITLE
spicetify auto does not start spotify anymore

### ISSUE THREAD

**Issue by fabianf1** [spicetify/spicetify-cli#1638]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.84.716.gc5f8b819 - Windows Store
- Spicetify version: 2.9.8
```

### 📝 Description

Usually "spicetify auto" would start Spotify if is not open yet, but after I upgraded from Spicetify 2.9.5 to 2.9.8 Spotify does not start any more using that command.
However, if I start Spotify first and then run "spicetify auto", Spotify is restarted and the changes from Spicetify are applied.
I would guess that #1623 has changed the behaviour of "spicetify auto".

**Comment by ririxidev** [comment]
Yeah it doesn't. This is behavior that we wanted to achieve.

**Comment by JamesGordonII** [comment]
uh, spotify has a open on start up future already, y u need spicetify to do it?
