### ISSUE TITLE
"permission denied" and "cannot detect prefs location" [Arch Linux / Spotify Flatpak and Spicetify latest]

### ISSUE THREAD

**Issue by Gwynsav** [spicetify/spicetify-cli#1640]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.84.716.gc5f8b819 (Flatpak)
- Spicetify version: 2.9.8
```

### 📝 Description

Install the Spotify Flatpak from the Discover application in KDE Plasma, downloads latest version, 1.1.84.716.gc5f8b819. Proceed to install spicetify-cli through yay (`yay spicetify-cli`). 

Once installed, run `spicetify backup apply`, returns: 
`fatal unlinkat /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify/Apps/login.spa: permission denied` 

Run `sudo spicetify backup apply`, returns:
`Cannot detect Spotify "prefs" file location. Please manually set "prefs_path" in config-xpui.ini`. 

Navigate to /home/gwynsav/.config/spicetify/config-xpui.ini, and set:
prefs_path              = /home/gwynsav/.var/app/com.spotify.Client/config/spotify/prefs
Rerun commands, returns same respectively.
Run `find | grep "spotify/prefs$"` from bash, returns:
```
./.config/spotify/prefs
./.var/app/com.spotify.Client/config/spotify/prefs
```
I've attempted reinstalling both Spotify and Spicetify, but the issue persists, even if I delete the config files along with them.

**Comment by ririxidev** [comment]
```bash
sudo chmod a+wr /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify
sudo chmod a+wr -R /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify/Apps
```
It's explained on our docs what to do in this situation - https://spicetify.app/docs/advanced-usage/installation#spotify-installed-from-flatpak

**Comment by Gwynsav** [comment]
Was trying to fix the other issue where the theme displays as a fully blank window and forgot to reassign the admin privileges to the files, whoops. Anyway both the the topic problem and the blank window are solved now, thanks.
