### ISSUE TITLE
When I click a drop-down button, it shows NOTHING.

### ISSUE THREAD

**Issue by McBlaza** [spicetify/spicetify-cli#1646]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.84.716.gc5f8b819
- Spicetify version: 2.9.8
```

### 📝 Description

All the drop-down button I click shows literally nothing except for the original Spotify drop-down buttons.

### 📸 Screenshots

![Screenshot 2022-05-04 203902](https://user-images.githubusercontent.com/104913326/166702611-b03b5fa8-ff67-4bff-8f68-d9f5ecca9b27.png)

**Comment by seniorkiller** [comment]
same here  but never got it worked anyway

**Comment by ririxidev** [comment]
marketplace issue.

**Comment by CharlieS1103** [comment]
@ririxidev I mean technically it is a spicetify issue as the menu hook probably needs to be reworked but who cares

**Comment by ririxidev** [comment]
Then issue should be about hook not marketplace Dropdown not working xD
