### ISSUE TITLE
[lyric-plus] Almost no animation

### ISSUE THREAD

**Issue by DontForgorMe** [spicetify/spicetify-cli#1648]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.84.716.gc5f8b819
- Spicetify version: v2.9.8

Win10 home 21H1 x64
Windows Feature Experience Pack 120.2212.4170.0
```

### 📝 Description

Less or no animation. 
The same installation process has been installed on other devices, but only my device is experiencing this.
It was an occasional phenomenon in previous cases, but it always happens to me.

### 📸 Screenshots

https://user-images.githubusercontent.com/104972912/166885646-bef10dd4-a556-4d66-bc06-d0a5129a1568.mp4

https://user-images.githubusercontent.com/104972912/166885856-44dc3b33-4f05-48b3-8029-d2aa316e489d.mp4

**Comment by catb0x** [comment]
hey! this might be an issue with block the spot.

**Comment by fevereaux** [comment]
> hey! this might be an issue with block the spot.

do u know how to remove block the spot? bcs i just reset my pc and it didnt work, still has no animation on the lyric:(

**Comment by DontForgorMe** [comment]
I finally solved this problem. But it wasn't the issue of Spicety.
This can be solved by turning on one function.

Control Panel -> System and Security -> System : Advanced system setting -> Advanced -> Performance : Settings -> Visual Effects -> Custom: -> Turn on : Animate controls and elements inside windows
