### ISSUE TITLE
Blank screen on Linux

### ISSUE THREAD

**Issue by erdemozdemir98** [spicetify/spicetify-cli#1649]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.84
- Spicetify version: 2.9.8
```

### 📝 Description

Spotify loads up with a black screen after `sudo -E spicetify apply` command.
I've tried using spotify, spotify-edge and spotify-snapstore from AUR.
I've tried removing the `Backup` folder, reinstalling Spotify and running `sudo -E spicetify backup apply` but I ended up with a black screen.
I know there are other closed issues about that but none of the provided problems has worked for me.
I also tried using different themes but results were not different.

**Comment by ririxidev** [comment]
Related to #1570
