### ISSUE TITLE
Add a guide in readme.md to block Spotify updates

### ISSUE THREAD

**Issue by Tetrax-10** [spicetify/spicetify-cli#1653]
### 📝 Provide a description of the new feature

`C:\Users\username\AppData\Local\Spotify` in this location if we create a folder `Update` and change the permission to deny for everyone Spotify can't update automatically. So this won't ruin spicetify as Spotify updates cause black screens.

If we want to update just change the permission to allow for everyone and restart Spotify. [Tutorial](https://youtu.be/84TT-deLQtU)

**Comment by CharlieS1103** [comment]
Meh, to be entirely honest this seems more like an issue for spicetify docs rather than the cli readme. + if we do it for one OS we need to do it for all the other ones as well.
