### ISSUE TITLE
All the custom apps have exceptionally large icons

### ISSUE THREAD

**Issue by rycerzes** [spicetify/spicetify-cli#1657]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.84.716.gc5f8b819
- Spicetify version: 2.9.8
```

### 📝 Description

The icons in Marketplace and Reddit are exceptionally large.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/59965507/167549095-53ef87ec-77c8-4528-859a-35392793abfe.png)
![image](https://user-images.githubusercontent.com/59965507/167549473-89bf820f-a25d-43ed-bdc6-4a6bd3d9a449.png)

**Comment by ririxidev** [comment]
Marketplace has it fixed. Update. Reddit the same.
