### ISSUE TITLE
Missing extensions, themes

### ISSUE THREAD

**Issue by LuckyTarget** [spicetify/spicetify-cli#1659]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows 1.1.84.716.gc5f8b819
- Spicetify version: 2.9.8
```

### 📝 Description

Even if I manually add the extension to the folder, I can only see two. I also recall seeing additional extensions, themes, and such around a month ago, but I'm pretty sure I remember the block advertisements extension. I'm not sure why I don't see them, and I'm also not sure whether the extensions were deleted from the source code for any reason. Please respond and let me know when you can.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/39243722/167823983-537aa38a-7b2c-404a-9db4-f8741054196c.png)

**Comment by ririxidev** [comment]
Not related to cli. Go to marketplace repo
