### ISSUE TITLE
All thmes broken with latest spotify version

### ISSUE THREAD

**Issue by rodolfol95** [spicetify/spicetify-cli#1662]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.84.716
- Spicetify version: 2.9.8
```

### 📝 Description

I don't understand why Spotify it's always on a race to block this so it's like a competition between Spicetify and Spotify what does spotify loses from people using themes come on!

### 📸 Screenshots

All themes are broken

**Comment by ririxidev** [comment]
Known, not related to cli.

**Comment by rodolfol95** [comment]
What’s it’s the problem them all them that I’m using seems to be Broken 😅
