### ISSUE TITLE
spicetify plugins not working

### ISSUE THREAD

**Issue by 0gameoverr** [spicetify/spicetify-cli#1663]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.84.716.gc5f8b819
- Spicetify version: 2.9.8
```

### 📝 Description

So basically, today my spicetify stopped working and I had a blank screen which I already fixed, but none of my plugins are working. I installed the marketplace plugin, for some reason it works and it shows only 1 available plugin to install, and when I throw my plugins into the Extensions folder they just don't work. This never happened to me before, and I've been using spicetify for about 6 months I think.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/105459360/168160512-110135f8-8bb1-4336-871d-a59eaa4cf144.png)
![image](https://user-images.githubusercontent.com/105459360/168160550-a18ccddf-60be-4d00-bef0-853f579dcb51.png)

**Comment by ririxidev** [comment]
Not related to cli.

**Comment by 0gameoverr** [comment]
Where should I post this then

**Comment by ririxidev** [comment]
Sorry for late response, dropped plugins to Extensions need to be added to `config-xpui.ini` to work. They don't appear on marketplace since marketplace only shows plugins installed by itself. Bug with not every plugin/extension not showing in marketplace is known and *hopefully* fixed soon. Sorry for convenience.
