### ISSUE TITLE
Webnowplaying does not display artist

### ISSUE THREAD

**Issue by ColeGoodnight** [spicetify/spicetify-cli#1667]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows 1.1.85.895.g2a71e1b8
- Spicetify version: 2.9.8
```

### 📝 Description

I am currently using the Rainmeter skin Monstercat Visualizer (https://github.com/MarcoPixel/monstercat-visualizer) in conjunction with the webnowplaying extension. Through Spicetify the artist is not displayed. When using the webnowplaying extension for Firefox with Youtube Music, this functionality is present. Interestingly when using the Firefox extension with browser based Spotify, the artist display is broken once again. 

### 📸 Screenshots

With Spicetify (same outcome for Spotify website)
![image](https://user-images.githubusercontent.com/38731391/168207046-c0500edf-5281-4023-9ea0-a5748a8ce3b1.png)

With Youtube Music via Firefox extension
![image](https://user-images.githubusercontent.com/38731391/168207474-9bd374e5-480b-454f-a22d-3694bd7306f1.png)

**Comment by IAmJulianAcosta** [comment]
Have you checked another of Rainmeter or another skin? I installed everything on a new machine and it worked fine with another skin:

![image](https://user-images.githubusercontent.com/1844640/168476887-b5d50d0a-64ec-48d6-bf0d-afa52ce12ac5.png)

**Comment by teddybloat** [comment]
downgrading to spotify-1-1-84-716 worked for me
