### ISSUE TITLE
Market place broken

### ISSUE THREAD

**Issue by Basic6969** [spicetify/spicetify-cli#1669]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:1.1.84.716
- Spicetify version:2.9.8
```

### 📝 Description

![image](https://user-images.githubusercontent.com/98833613/168272658-1d599ce6-0ad6-4e49-9dd9-240899177613.png)
Only two extensions in the extensions tab.
![image](https://user-images.githubusercontent.com/98833613/168272754-52becbe6-1412-43f5-a530-91e41c33862e.png)
Only these themes others are missing.

**Comment by ririxidev** [comment]
Not related to cli.

**Comment by Basic6969** [comment]
> Not related to cli.

why?

**Comment by ririxidev** [comment]
but isn't related to cli. It's known issue and repo for marketplace is here; https://github.com/spicetify/spicetify-marketplace
