### ISSUE TITLE
not able to install spicetify

### ISSUE THREAD

**Issue by SoulHunter287** [spicetify/spicetify-cli#1691]
### 🔍 Have you checked Spicetify.app page for your issue?

- [ ] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [ ] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
using the latest version of spotify
```

### 📝 Description

pleas help me to fix this issue

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/81796062/169526531-6951634f-85a4-4742-878d-3664ab445441.png)

**Comment by xerta555** [comment]
Not compatible with last Spotify version yet.
