### ISSUE TITLE
Spicetify Update Not Working

### ISSUE THREAD

**Issue by SoCoolMuchGitHub** [spicetify/spicetify-cli#1708]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.85
- Spicetify version: 2.9.9
```

### 📝 Description

I updated Spicetify to the latest version, and now this is all I get. (Refer to picture)

### 📸 Screenshots

![image_2022-05-23_134726052](https://user-images.githubusercontent.com/59752651/169877713-8b50cb3d-a690-4063-9646-0a31f89ee75b.png)

**Comment by SoCoolMuchGitHub** [comment]
I also get errors when applying
![Screenshot 2022-05-23 135040](https://user-images.githubusercontent.com/59752651/169878224-d23a8179-e5b4-418d-b763-f84cacc4ab3f.png)
.

**Comment by afonsojramos** [comment]
Yes, this is just a temporary fix while we work on #1660.
