### ISSUE TITLE
Does anyone know which theme is that (from installation guide)

### ISSUE THREAD

**Issue by skeletclique** [spicetify/spicetify-cli#1709]
### 📝 Provide a description of the new feature

I have searched everywhere does anyone know where i can get this?
![1](https://user-images.githubusercontent.com/71558339/170026268-d4d54068-dd73-4ea3-91fc-1b9a98e5b559.jpg)

**Comment by afonsojramos** [comment]
Closing as this is not an issue.

Where did you find it exactly?  This is probably just an old version of Spotify.

**Comment by skeletclique** [comment]
i found this at the bottom of this link:
https://spicetify.app/docs/advanced-usage/extensions
