### ISSUE TITLE
Drop down menu not showing and Everything is too big

### ISSUE THREAD

**Issue by Cachiey** [spicetify/spicetify-cli#1711]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.85
- Spicetify version:2.9.9
```

### 📝 Description

Drop down menu's are blank and I cant change themes with out commands neither can I change search filters when using the reddit custom_app the drop down menu is also blank
The tabs that show me what I'm looking at are too large the same was happening to the marketplace about a month ago but that was patched

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/104319398/170298542-dc312161-c14e-4d20-84e5-e14b07d3b662.png)
![image](https://user-images.githubusercontent.com/104319398/170298587-cf80d6be-6c6e-4bd8-a745-7b282da4be99.png)
![image](https://user-images.githubusercontent.com/104319398/170298635-aaa63f5c-b99d-42af-8d57-f77a9b68351f.png)
![image](https://user-images.githubusercontent.com/104319398/170298860-43906970-4acc-42e4-a911-5c46d098efc0.png)

**Comment by theRealPadster** [comment]
@Cachiey It looks like you should be able to update [Spicetify Taste Analyzer](https://github.com/Shinyhero36/Spicetify-Taste-Analyzer) to fix the grid sizing issue. I believe [this](https://github.com/Shinyhero36/Spicetify-Taste-Analyzer/commit/6142ca629403c7ed53597bb957c7af2a0887332a) would be the fix.
