### ISSUE TITLE
[Sidebar Config] Options not showing on hover of Create Playlist, Liked Songs and Episodes

### ISSUE THREAD

**Issue by fluteds** [spicetify/spicetify-cli#1716]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.85.895.g2a71e1b8
- Spicetify version: 2.9.9
- OS Name: Microsoft Windows 11 Home
- OS Version: 10.0.22000 N/A Build 22000
```

### 📝 Description

I recently reinstalled Spicetify after having it removed. When I go to edit my sidebar using sidebar config like I had before reinstalling, the options do not show on hover on the following tabs.

- Create Playlist
- Liked Songs
- Your Episodes

I have followed all the instructions like reinstalling and checking for updates. I've also attached a gif of what I'm seeing. While it's not a major bug, it's just slightly annoying to edit!

### 📸 Screenshots

![Spotify_48vjbbYJOF](https://user-images.githubusercontent.com/34608301/170607453-c185bdc6-0327-45da-81a5-c67950287f67.gif)

**Comment by Tetrax-10** [comment]
My [Extension](https://github.com/Tetrax-10/Spicetify-Extensions/tree/master/Hide-Sidebar-Items) Does That.

Sidebar Config won't hide `liked songs`, `create playlist`, `your podcast` from Spotify version `1.1.84`, So this extension is used to hide them.

![Screenshot](https://raw.githubusercontent.com/Tetrax-10/Spicetify-Extensions/master/Hide-Sidebar-Items/screenshot.png)

**Comment by nekato** [comment]
For me that extension doesn't work. It doesn't show up in the menu. Other extensions from the marketplace work normally.

**Comment by afonsojramos** [comment]
@Tetrax-10 please do make a PR to add back that functionality if you have the time! Thanks!
