### ISSUE TITLE
[BUG] Marketplace

### ISSUE THREAD

**Issue by barbiehunter** [spicetify/spicetify-cli#1725]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.86.857.g3751ee08
- Spicetify version: 2.10.1
```

### 📝 Description

To big Pictures of the "Marketplace", Not sure if its a issue of a Theme i have installed.

### 📸 Screenshots

![L5MFRA](https://user-images.githubusercontent.com/38357837/170823692-3725e2dc-c672-4d03-b3bb-0b598102f0dc.png)

**Comment by theRealPadster** [comment]
Update your marketplace. We fixed this ages ago.
