### ISSUE TITLE
Full App Display not updating Volume when using hotkeys

### ISSUE THREAD

**Issue by L3-N0X** [spicetify/spicetify-cli#1738]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify für Windows 1.1.86.857.g3751ee08
- Spicetify version: 2.10.1
```

### 📝 Description

I have the Keybinds for turning the volume up and down set vor special buttons on my Mouse and when I click them, the volume of Spotify changes, but in Full App Display the Volume Bar on the left doesn´t notice this change and stays in the position. 

So it´s not a really annoying Bug, but would be nice when the Bar there also updates!

**Comment by huhridge** [comment]
That's my bad, thought there wasn't a way to change spotify volume without clicking, so it doesn't update, i'll add it in the next version
