### ISSUE TITLE
It doesn´t show up after restart.

### ISSUE THREAD

**Issue by Adistelija** [spicetify/spicetify-cli#1743]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1-186.857.0
- Spicetify version:2.10.1
```

### 📝 Description

I don´t know is it only me or is it just like it, but when i restart my pc or just spotify it starts without spicetify so i need to install it again. Any recommends?

**Comment by theRealPadster** [comment]
Are you using the windows store version? Or did Spotify update when you rebooted?

**Comment by Adistelija** [comment]
Thanks my guy. The problem was that i have downloaded spotify from
microsoft store and now it works perfectly.

su 5. kesäk. 2022 klo 3.10 Isaac ***@***.***) kirjoitti:

**Comment by ophx** [comment]
im having this issue too. but, im not using microsoft one. im using the normal one..
