### ISSUE TITLE
Command not found after install

### ISSUE THREAD

**Issue by mrhappyma** [spicetify/spicetify-cli#1750]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:
Spotify for macOS (Intel)
1.1.86.857.g3751ee08
- Spicetify version:
12.10.1
```

### 📝 Description

Just running the commands on [the install page](https://spicetify.app/docs/getting-started) and I am instructed to run `spicetify --help`, however I get this error:
```console
zsh: command not found: spicetify
```

**Comment by theRealPadster** [comment]
> what directory do I need to add?

Wherever you installed spicetify. I think the script puts it in `$HOME/.spicetify`

**Comment by Arnau478** [comment]
I think what's missing is to reload the RC file. For example, after installing, I ran `source ~/.bashrc` and everything worked fine. (using bash)

Also, the bug is still present, at least on the latest release. I suppose it will be fixed in the next version, but until then, here you have a working solution!

**Comment by mrhappyma** [comment]
i tried restarting the terminal app 🤷

**Comment by Watanabethegreat** [comment]
> I think what's missing is to reload the RC file. For example, after installing, I ran `source ~/.bashrc` and everything worked fine. (using bash)
> 
> Also, the bug is still present, at least on the latest release. I suppose it will be fixed in the next version, but until then, here you have a working solution!
 




i have an isssue can you help me please 
Judes-MacBook-Air:~ playboiiculture$ curl -fsSL https://raw.githubusercontent.com/spicetify/cli/main/install.sh | sh
FETCHING Version 2.36.11
DOWNLOADING https://github.com/spicetify/cli/releases/download/v2.36.11/spicetify-2.36.11-darwin-amd64.tar.gz
######################################################################## 100.0%
EXTRACTING /Users/playboiiculture/.spicetify/spicetify.tar.gz
SETTING EXECUTABLE PERMISSIONS TO /Users/playboiiculture/.spicetify/spicetify
REMOVING /Users/playboiiculture/.spicetify/spicetify.tar.gz
spicetify path already set in /Users/playboiiculture/.zshrc, continuing...

spicetify v2.36.11 was installed successfully to /Users/playboiiculture/.spicetify
Run 'spicetify --help' to get started
Do you want to install spicetify Marketplace? (Y/n)
Y
Starting the spicetify Marketplace installation script..
FETCHING Version 1.0.2
DOWNLOADING https://github.com/spicetify/marketplace/releases/download/v1.0.2/marketplace.zip
######################################################################## 100.0%
EXTRACTING
COPYING
INSTALLING
sh: line 52: spicetify: command not found

**Comment by Watanabethegreat** [comment]
> ### 🔍 Have you checked Spicetify.app page for your issue?
> * [x]  I have checked the FAQ
> 
> ### 🔍 Is there already an issue for your problem?
> * [x]  I have checked older issues, open and closed
> 
> ### ℹ Environment / Computer Info
> ```
> - Spotify version:
> Spotify for macOS (Intel)
> 1.1.86.857.g3751ee08
> - Spicetify version:
> 12.10.1
> ```
> 
> ### 📝 Description
> Just running the commands on [the install page](https://spicetify.app/docs/getting-started) and I am instructed to run `spicetify --help`, however I get this error:
> 
> ```
> zsh: command not found: spicetify
> ```
> 
> ### 📸 Screenshots
> _No response_

Judes-MacBook-Air:~ playboiiculture$ curl -fsSL https://raw.githubusercontent.com/spicetify/cli/main/install.sh | sh
FETCHING Version 2.36.11
DOWNLOADING https://github.com/spicetify/cli/releases/download/v2.36.11/spicetify-2.36.11-darwin-amd64.tar.gz
######################################################################## 100.0%
EXTRACTING /Users/playboiiculture/.spicetify/spicetify.tar.gz
SETTING EXECUTABLE PERMISSIONS TO /Users/playboiiculture/.spicetify/spicetify
REMOVING /Users/playboiiculture/.spicetify/spicetify.tar.gz
spicetify path already set in /Users/playboiiculture/.zshrc, continuing...

spicetify v2.36.11 was installed successfully to /Users/playboiiculture/.spicetify
Run 'spicetify --help' to get started
Do you want to install spicetify Marketplace? (Y/n)
Y
Starting the spicetify Marketplace installation script..
FETCHING Version 1.0.2
DOWNLOADING https://github.com/spicetify/marketplace/releases/download/v1.0.2/marketplace.zip
######################################################################## 100.0%
EXTRACTING
COPYING
INSTALLING
sh: line 52: spicetify: command not found
