### ISSUE TITLE
error Cannot detect Spotify "prefs" file location - even though it exists and is defined

### ISSUE THREAD

**Issue by Khosraw** [spicetify/spicetify-cli#1758]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.84.716.gc5f8b819
- Spicetify version: 2.10.1
```

### 📝 Description

Firstly, I installed Spicetify from the AUR alongside Spotify. After applying any updates, I run `sudo spicetify restore backup apply`. I get the following error:

`error Cannot detect Spotify "prefs" file location. Please manually set "prefs_path" in config-xpui.ini`

It doesn't make much sense, because I have a `prefs` file at `/home/khosraw/.config/spotify/prefs`. In fact, it is clearly set in my config: 

`prefs_path              = /home/khosraw/.config/spotify/prefs`

`sudo find | grep "spotify/prefs$"` returns `./.config/spotify/prefs` so I'm not going wrong with the path mentioned. Yet `sudo spicetify apply` will not work because it believes the `prefs` file doesn't exist. I looked at other issues on here and they seem to be instances where the file doesn't exist. But this is quite unique...

**Comment by theRealPadster** [comment]
Don't run spicetify as root. When you run it with sudo, it will look for a config file for the root user, which has none. You need to change the permissions on the Spotify folder and run spicetify without sudo

**Comment by rizkhal** [comment]
I have tha same problem, when i try to apply **without** sudo, its return

```bash
spicetify v2.10.1
Copying raw assets:
fatal unlinkat /usr/share/spotify/Apps/xpui.spa: permission denied
```

My `spotify_path` at `/usr/share/spotify`

Thanks 🍻
