### ISSUE TITLE
Ability To Use Shuffle+ On Liked Songs If Possible

### ISSUE THREAD

**Issue by karimawii** [spicetify/spicetify-cli#1760]
### 📝 Provide a description of the new feature

Ability To Use Shuffle+ On Liked Songs If Possible

**Comment by kyrie25** [comment]
Not sure if this is a lacking feature at all, since you can select all tracks and then use Shuffle+ as normal.
![image](https://user-images.githubusercontent.com/77577746/174530622-daf94f68-27da-407c-ace2-7505540a9e2a.png)

**Comment by karimawii** [comment]
Didn't know that, thanks
