### ISSUE TITLE
[Lyrics Plus] Add global setting for Delay

### ISSUE THREAD

**Issue by LaMarCab76** [spicetify/spicetify-cli#1765]
### 📝 Provide a description of the new feature

Just a delay option that applys to all songs (The same that is already implemeted on the lyrics screen)

**Comment by CharlieS1103** [comment]
@LaMarCab76 What does this mean?

**Comment by LaMarCab76** [comment]
When you are lyrics tap, there's is a button with two circles, in that menu that button opens, there is a delay option. But that delay just applies only to the lyrics that are playing now. 
It would be usefull if that option was available on the setting options under the profile, so it can be applyed to all the lyrics that are played.

**Comment by kyrie25** [comment]
> When you are lyrics tap, there's is a button with two circles, in that menu that button opens, there is a delay option. But that delay just applies only to the lyrics that are playing now. It would be usefull if that option was available on the setting options under the profile, so it can be applyed to all the lyrics that are played.

In conclusion, you wish for the delay settings to be global and applied for all (future) songs instead of just the current one?

**Comment by LaMarCab76** [comment]
Yep
