### ISSUE TITLE
find | grep "spotify/prefs$" returns nothing

### ISSUE THREAD

**Issue by fily-gif** [spicetify/spicetify-cli#1780]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.84.716gc
- Spicetify version: 2.9.9

- OS: Ubuntu 22.04 LTS
```

### 📝 Description

when i try to do " find | grep "spotify/prefs$" " it just return nothing, i tried to do sudo find | grep "spotify/prefs$" , but still empty result

### 📸 Screenshots

![screenshot](https://user-images.githubusercontent.com/73085550/175797223-f069bea2-5758-467f-a213-98d98e5c81d4.png)

**Comment by kyrie25** [comment]
This is not a Spicetify problem, closing issue.
