### ISSUE TITLE
Giant Album Covers

### ISSUE THREAD

**Issue by falsisdev** [spicetify/spicetify-cli#1799]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.88.612.gcc529952
- Spicetify version: 2.10.2
```

### 📝 Description

There is no problem when I enter the application. However, when I click on a playlist, the cover of the currently playing song becomes gigantic. I tried it in every theme, I don't think there is a problem with the theme.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/63756985/176992790-9020f62d-8057-4464-870d-4b9efe45ddee.png)

**Comment by kyrie25** [comment]
Not a CLI issue.
Check if you have any extension/theme installed that could be causing this.
