### ISSUE TITLE
Install script doesn't properly add to $PATH with fish

### ISSUE THREAD

**Issue by KiritoLeFakePK** [spicetify/spicetify-cli#1808]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for macOS (Intel) 1.1.88.612.gcc529952
- Spicetify version: 2.10.2
```

### 📝 Description

If you install spicetify with fish, it pastes its `$PATH` directly into the `~/.config/fish/config.fish` file.
The problem is that if you have already entered lines in this file, it pastes its `$PATH` directly to another command which prevents fish to detect spicetify.

### 📸 Screenshots

![Capture d’écran 2022-07-04 à 15 56 51](https://user-images.githubusercontent.com/17341929/177169515-4fcc055d-eaaf-4e5c-b791-e9d6aba9774d.png)

**Comment by theRealPadster** [comment]
Did a little test, just to make sure, and `echo` with `>>` appears to add a new line. 
<img width="225" alt="image" src="https://user-images.githubusercontent.com/1565883/177189481-3ec8b83e-79e0-4f01-94f5-7eb639a87ec2.png">

Maybe your config file didn't end with a `\n` or something before?

**Comment by KiritoLeFakePK** [comment]
I have redone the test by deleting the spicetify `$PATH` and reinstalling the package with the script and everything seems to work...
I still don't know why it didn't work before because I tested it three times.
Sorry again for wasting your time and have a nice day
