### ISSUE TITLE
Path error

### ISSUE THREAD

**Issue by ParaliyzedEvo** [spicetify/spicetify-cli#1810]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows
1.1.88.612.gcc529952
- Spicetify version: 2.10.2
```

### 📝 Description

So I tried installing Spicetify and it just said "error C:\Users\paral\AppData\Local\Packages\SpotifyAB.SpotifyMusic_zpdnekdrzrea0\LocalState\Spotify\prefs does not exist or is not a valid path. Please manually set "prefs_path" in config-xpui.ini to correct path of "prefs" file." So I just created the path manually and now it says "BOM: read C:\Users\paral\AppData\Local\Packages\SpotifyAB.SpotifyMusic_zpdnekdrzrea0\LocalState\Spotify\prefs: The handle is invalid." So I dont know what to do now and I just wanna really use your app because its cool and all. I also tried reinstalling spotify and it said the same thing. I also installed spotify from the website if that helps. Hope you can help me. (Yes I'm running windows 11)

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/107338855/177249086-929e1b80-061b-4d2d-9dfb-d579447f0cf0.png)
![image](https://user-images.githubusercontent.com/107338855/177249140-e485cf2b-d8c5-4451-b0fb-9749bd0f8087.png)

**Comment by kyrie25** [comment]
FAQ.
https://spicetify.app/docs/faq#cannot-find-pref_file

**Comment by kyrie25** [comment]
Please actually do read the FAQ before ticking on the box and making a new issue as to not clutter the repository thanks.
