### ISSUE TITLE
spicetify.exe' failed to run error

### ISSUE THREAD

**Issue by Someone-Somwhere** [spicetify/spicetify-cli#1814]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.88.612.gcc529952
- Spicetify version:  Don't Know
```

### 📝 Description

I ran the code from the [getting stated page](https://spicetify.app/docs/getting-started#windows) but when it runs in PowerShell it says "iex : Program 'spicetify.exe' failed to run: The specified executable is not a valid application for this OS
platform.At line:12 char:14
+ $spicePath = spicetify -c | Split-Path
+              ~~~~~~~~~~~~.
At line:2 char:106
+ ... .com/spicetify/spicetify-marketplace/main/resources/install.ps1 | iex
+                                                                       ~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Invoke-Expression], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed,Microsoft.PowerShell.Commands.InvokeExpressionCommand"
I have updated Windows and I am running PowerShell in Admin mode. How do I fix it? 

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/71657811/178149501-ecba75a1-9e04-460f-9ea7-93afcd99f3c0.png)

**Comment by kyrie25** [comment]
1. You shouldn't be installing Spicetify as an administrator. Use an user account.

2. Are you using a 32-bit system by any chance?

**Comment by Someone-Somwhere** [comment]
> 1. You shouldn't be installing Spicetify as an administrator. Use an user account.
> 2. Are you using a 32-bit system by any chance?

I am using a user account but with administrator privileges and I am using a 32 Bit version of Windows

**Comment by kyrie25** [comment]
Spicetify only supports 64-bit versions of Operating Systems, closing issue.

**Comment by Someone-Somwhere** [comment]
> Spicetify only supports 64-bit versions of Operating Systems, closing issue.

Thanks
