### ISSUE TITLE
Error on fresh install

### ISSUE THREAD

**Issue by BigMilko** [spicetify/spicetify-cli#1821]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows 1.1.89.862.g94554d24
- Spicetify version: v2.10.2-latest

- OS Name Microsoft Windows 10 Home
- Version 10.0.19044 Build 19044
- Processor Intel(R) Core(TM) i9-10900K CPU @ 5.00GHz, 3696 Mhz, 10 Core(s), 20 Logical Processor(s)
- Installed Physical Memory (RAM) 32.0 GB
- Video Card NVIDIA GeForce RTX 3080 Ti
```

### 📝 Description

I've been working with Spicetify for I think four maybe almost five years now without much an issue; but A while back Spotify updated and I just never got around to updating Spicetify. So today I went to do a fresh install of both and ended up with this "error cannot find symbol for Custom app React Element 
panic: runtime error: index out of range [0] with length 0"

Along with much more I'm too lazy to type and will leave a screenshot of
.ps, I apologize for what my PowerShell looks like in advance
<img width="1907" alt="Spicetify,Error" src="https://user-images.githubusercontent.com/59469496/179073606-88f50069-938c-4a4a-8edd-c8b05cf814bc.PNG">

**Comment by kyrie25** [comment]
You claimed your Spicetify is latest/2.10.2?
![image](https://user-images.githubusercontent.com/77577746/179125221-d33135d7-dfa3-4c86-ba28-b6e85c5da9ab.png)

**Comment by kyrie25** [comment]
Outdated Spicetify and incompatible version of Spotify/Spicetify, closing issue.
https://spicetify.app/docs/advanced-usage/uninstallation
