### ISSUE TITLE
Double Search Bars

### ISSUE THREAD

**Issue by CryoRenegade** [spicetify/spicetify-cli#1824]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
OS: Windows v10.0.22000
Spotify: v1.1.89.862
Spicetify: v2.10.2
Dribbblish: v4.2.2-8da36b8
```

### 📝 Description

In title, we have two search bars showing up

### 📸 Screenshots

https://i.imgur.com/VI9TmnL.png

**Comment by CharlieS1103** [comment]
This is an issue with an extension or theme that you have installed, not spicetify cli.
