### ISSUE TITLE
[Popup Lyrics] Window turns red on hover

### ISSUE THREAD

**Issue by LaeDev** [spicetify/spicetify-cli#1827]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: For Windows Spotify 1.1.89.862.g94554d24
- Spicetify version: 2.10.2
```

### 📝 Description

popupLyrics screen goes red if i hover the cursor

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/78576284/180052725-28e7648e-54e5-4656-a088-cffd4e1367f2.png)

**Comment by kyrie25** [comment]
This is pretty much default behavior I think. You are requesting for it to be removed?

**Comment by kyrie25** [comment]
As much as it does hurt my eyes when I hover over Popup Lyrics, this behavior is managed by the Spotify client and not the extension AFAIK, so I'm afraid we can't remove it.

**Comment by abdansyakuuro** [comment]
19wwnefjfirnalalsh

**Comment by kyrie25** [comment]
> This was fixed half a year ago in [electron](https://github.com/electron/electron/issues/34406), but only recently in [cef](https://github.com/chromiumembedded/cef/issues/3482) Waiting for the update from spotify devs, i guess!

Guess that solves the issue, we'll wait for a future release then!
