### ISSUE TITLE
No display

### ISSUE THREAD

**Issue by arlooonie** [spicetify/spicetify-cli#1836]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.90.859
- Spicetify version: 2.10.1
```

### 📝 Description

there is literally no displayed elements whatsoever, just a blank slate.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/100902107/180599459-a58d1466-7242-4144-b98f-4a2e840a49cd.png)

**Comment by Ben-Break** [comment]
Duplicate of #1828,
run `spicetify upgrade` to update to version 2.11.1 to fix.

**Comment by arlooonie** [comment]
thanks!!! it's fixed now
