### ISSUE TITLE
[FullApp Display] Like button

### ISSUE THREAD

**Issue by makeworld-the-better-one** [spicetify/spicetify-cli#1838]
### 📝 Provide a description of the new feature

It would be nice to have the option to display the like (heart) button for songs when in Full App Display. That way I can easily like songs that catch my ear without having to exit the display and find the button.

Thanks! I'm enjoying spicetify and this extension :)

**Comment by kyrie25** [comment]
Just for more context to whoever wants to work on this, where would you want to place this button?
Supposedly the Like button would go to the right of the seekbar on normal view but then lies the problem for Vertical mode where everything this perfectly centered:

![image](https://user-images.githubusercontent.com/77577746/180959853-334c3e11-4e67-4917-b8c0-29d0ccee51ab.png)

**Comment by makeworld-the-better-one** [comment]
Here's two options.

Beside the song title:

![image](https://user-images.githubusercontent.com/25111343/181036816-bed842d5-cfeb-4b07-8030-31b7a2b145f1.png)

The title and heart could be centred together, to keep everything centred. But I don't think it looks too bad not centred as well!

Or it could go beside the title and artist together:

![image](https://user-images.githubusercontent.com/25111343/181037058-e85eed65-3848-48f8-a2bb-317eefa50086.png)

Once again this could be centred, with the title and artist on the left and the heart on the right.

**Comment by fallsimply** [comment]
If you're running the latest version of Full App Display, the like button in shown when you enable `Show Extra Controls`

**Comment by makeworld-the-better-one** [comment]
I see. I'm stuck on spicetify 2.9.9 because I'm on Linux. Would be nice to get a spicetify update that still supports the older Linux Spotify, but I was told it's not possible.

Will close the issue now, thanks for explaining.

**Comment by makeworld-the-better-one** [comment]
> If you're running the latest version of Full App Display, the like button in shown when you enable `Enable Extra Controls`

@fallsimply seems like this is false actually, or it relies on a spicetify version later than 2.9.9. I am running the latest version of `fullAppDisplay.js`.

Proof:

```
~
➤ sha256sum ~/.spicetify/Extensions/fullAppDisplay.js 
d2c31d22983eccebd9b4d2935ed647338fa4bbcb4080a0b422e40d18598c267a  /home/makeworld/.spicetify/Extensions/fullAppDisplay.js

~
➤ curl -sSL https://github.com/spicetify/spicetify-cli/raw/master/Extensions/fullAppDisplay.js | sha256sum
d2c31d22983eccebd9b4d2935ed647338fa4bbcb4080a0b422e40d18598c267a  -

~
➤ spicetify --version
2.9.9
```

I have no option available to me called "Enable Extra Controls". In fact if you look at the latest source code, that option doesn't even exist:

https://github.com/spicetify/spicetify-cli/blob/396d701adc915a853e0a94e3fa4a34293d9d3933/Extensions/fullAppDisplay.js#L754-L764

Not sure why you wrote your comment then, maybe you're using some fork of the extension or something?

**Comment by fallsimply** [comment]
Spicetify Marketplace was using a modified version. Here's the link https://github.com/huhridge/huh-spicetify-extensions#full-app-display-modified

**Comment by makeworld-the-better-one** [comment]
Oh ok, thanks for explaining. I will leave this issue open because I'd still like to have a like button for the built-in Full App Display extension.
