### ISSUE TITLE
spicetify command not found

### ISSUE THREAD

**Issue by xXDeathAbyssXx** [spicetify/spicetify-cli#1841]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify version 1.1.84.716.gc5f8b819, Copyright (c) 2022, Spotify Ltd
- Spicetify version: v2.11.1
```

### 📝 Description

The command is not found, I already tried restarting the pc and the terminal, I use void linux btw.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/97713025/181653529-d219aaa2-eef5-4a49-aeac-573de5124657.png)

![image](https://user-images.githubusercontent.com/97713025/181653599-9d49c82f-8233-4e72-9cfa-792cc512705a.png)

![image](https://user-images.githubusercontent.com/97713025/181653721-b61d8462-ae46-490d-8028-9e7c076dcc77.png)

**Comment by kyrie25** [comment]
Not a Spicetify bug.
Restart your terminal session or `cd` to the `.spicetify` folder and run the executable using the `./` prefix.

**Comment by xXDeathAbyssXx** [comment]
where is the prefix? i just found this in the `profile`
![image](https://user-images.githubusercontent.com/97713025/181662597-f28e0eed-688e-4d93-b9f7-0b0b8f22953c.png)

**Comment by kyrie25** [comment]
> where is the prefix? i just found this in the `profile` file ![image](https://user-images.githubusercontent.com/97713025/181662597-f28e0eed-688e-4d93-b9f7-0b0b8f22953c.png)

https://stackoverflow.com/questions/29805173/why-cant-git-bash-run-my-executable

**Comment by kyrie25** [comment]
Again, this is not our side of the issue because it is expected behavior that Bash gets `PATH` from `.bashrc`, you have to figure out by yourself because that's a **Bash** issue on **your** side.

The first screenshot showed that Spicetify has executed normally, and you don't need the `.exe` file type because that's a specific binary executable file type for Windows. If you don't want to fix the issue with your Bash path then you have to `cd` to `.spicetify` folder and use the `./` prefix at all times like the screenshot.

**Comment by kyrie25** [comment]
If you still require support then join our Discord server and the Helpers can assist you there. You won't get much from here because it's not a bug nor a place for one-on-one support.

**Comment by xXDeathAbyssXx** [comment]
> The first screenshot showed that Spicetify has executed normally, and you don't need the .exe file type because that's a specific binary executable file type for Windows 

Lmao i forgot it, but I'm doing another thing r8, sorry.

> If you still require support then join our Discord server and the Helpers can assist you there. You won't get much from here because it's not a Spicetify bug nor a place for one-on-one support.

It's ok, i will fix it, ty for all.
