### ISSUE TITLE
Keep repeat one song after changing songs

### ISSUE THREAD

**Issue by fancccyyy** [spicetify/spicetify-cli#1844]
### 📝 Provide a description of the new feature

Is it possible to keep the repeat one song function applied after changing songs?
As far as I know, Spotify itself "intentionally" deleted the feature, so I have to manually click the repeat button. It's just extremely inconvenient.

**Comment by kyrie25** [comment]
This is not a bug nor an enhancement of any sort, so it will not be dealt with via an issue. If you wish for an extension to be made, make a discussion or add it as a extension suggestion in our Discord server.
