### ISSUE TITLE
[Lyrics Plus] Click on a lyrics Line to seek song to that part

### ISSUE THREAD

**Issue by Tetrax-10** [spicetify/spicetify-cli#1846]
### 📝 Provide a description of the new feature

When we click a line on the lyric plus page it should seek to that part of the song. Like Spotify lyrics

**Comment by kyrie25** [comment]
Currently Lyrics Plus synced tab only renders 4 lines at a time so I don't really see the point in this.
This would require a huge rewrite in Lyrics Plus tab for all lyrics to be rendered at once and still be able to keep the lyrics scroll-to animation, for anyone who has interest in taking on this issue.
