### ISSUE TITLE
Blank Screen on MacOS 12.4 (Monterey M1)

### ISSUE THREAD

**Issue by AffinityGH** [spicetify/spicetify-cli#1852]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for macOS (Apple Silicon) 1.1.90.859.gf1bb1e36
- Spicetify version: Latest (2.11.1)
```

### 📝 Description

Install Spicetify CLI and Marketplace successfully. Run `spicetify backup apply` and blank screen ensues. Running `spicetify restore` fixes the issue. Reinstalled Spotify and Spicetify, no luck. Right clicking on Window leads to no response.

### 📸 Screenshots

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/45124929/182497560-aaf95aa5-5c60-408c-a020-7dc9eb7fc5ba.png">

<img width="661" alt="image" src="https://user-images.githubusercontent.com/45124929/182497867-b82a341b-2d39-499f-a36a-9da6dc6d1f01.png">

**Comment by kyrie25** [comment]
Common error. Closing issue.
Head to our Discord server for the troubleshooting guides linked and for support.
