### ISSUE TITLE
Requesting to mute all audio ads and banner ads

### ISSUE THREAD

**Issue by gihanadnivak** [spicetify/spicetify-cli#1853]
### 📝 Provide a description of the new feature

I want to mute spotify automatically when ad is playing .

**Comment by kyrie25** [comment]
Not a bug nor enhancement request for the CLI.  Closing issue.

**Comment by kyrie25** [comment]
There are already extensions and other projects that does the trick. We won't be implementing this into the CLI.

**Comment by gihanadnivak** [comment]
> There are already extensions and other projects that does the trick. We won't be implementing this into the CLI.

what is the extension ?

**Comment by kyrie25** [comment]
That you will have to look around yourself. I am not obliged to provide it in any way.
