### ISSUE TITLE
spicetify is making the main screen small

### ISSUE THREAD

**Issue by Skinny957** [spicetify/spicetify-cli#1854]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: latest 
- Spicetify version:2.11.1
```

### 📝 Description

it shows it in the screen shot

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/107206243/182669638-a6c17642-365d-45c8-974e-8a28ff5090bc.png)

**Comment by ririxichan** [comment]
theme issue. Closing.

**Comment by Skinny957** [comment]
how do i fix it?
