### ISSUE TITLE
player bar filling the whole main screen

### ISSUE THREAD

**Issue by chtulhu37** [spicetify/spicetify-cli#1855]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows
1.1.91.824.g07f1e963

info Current version: 2.11.1
```

### 📝 Description

i saw another threat abt this, but it was closed before someone could help

don't bully me for listening to deftones lol

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/110576447/182741061-fd46d591-101e-4977-a50b-c0a900901bd3.png)

**Comment by kyrie25** [comment]
Theme issue.
