### ISSUE TITLE
Spotify does not automatically open with Spiceitfy applied

### ISSUE THREAD

**Issue by AkiriMusic** [spicetify/spicetify-cli#1856]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows
1.1.90.859.gf1bb1e36
- Spicetify version:2.11.1
```

### 📝 Description

Every time I open Spotify, Spicetify is not enabled and I need to run "spicetify apply" in powershell to enable it.

**Comment by kyrie25** [comment]
Common bug. Head to our Discord server for the guide posted.
