### ISSUE TITLE
just a blank image even tho i have updated to the latest version

### ISSUE THREAD

**Issue by Novattz** [spicetify/spicetify-cli#1857]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: latest (dont know how to check but i redownloaded from the site today
- Spicetify version: 2.11.1
```

### 📝 Description

I had issues with prefs and spotify locations before i found a fix that uses the command line to update the config file. After i actually got it to work i just got a blank screen and the colors changed depending on what theme i was using. It has been a long time since i used spicetify and it might be that i loaded an old backup but im very unsure.

### 📸 Screenshots

![NVIDIA_Share_fcnH0hHNwA](https://user-images.githubusercontent.com/47538996/183298865-c8bbc464-8aa3-4b5c-9370-d76f3b9c75f9.png)

**Comment by kyrie25** [comment]
Common bug. Run `spicetify restore backup apply` again or head to the Discord server for support.

**Comment by Simon1511** [comment]
> Run `spicetify restore backup apply` again, remove whatever outdated theme/extension that you may have, or head to the Discord server for support. This is most likely user error and not a CLI bug.

I'm facing this exact problem on a fresh install of spicetify on Windows. No themes or extensions added. I'm using the one from the Spotify website, not the MS Store version.

However on Linux the installation worked fine.
