### ISSUE TITLE
Lyrics and Reddit apps show "Something went wrong"

### ISSUE THREAD

**Issue by Senya247** [spicetify/spicetify-cli#1858]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.84.716.gc5f8b819
- Spicetify version: 2.11.1
- Ubuntu 22.04 on Wayland
- Gnome 42.2
```

### 📝 Description

The Lyrics and Reddit pages show "Something went wrong"

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/65822218/183339256-267bfb41-5a44-463c-a3cf-ad9540592843.png)
![image](https://user-images.githubusercontent.com/65822218/183339299-3f2f079f-3666-4258-b2b5-4516efa0aa00.png)

**Comment by kyrie25** [comment]
Incompatible Spotify version. Update to latest or downgrade Spicetify.
![image](https://user-images.githubusercontent.com/77577746/183352855-6f2db011-1fc3-46ab-97b5-17ec1607e3e9.png)
