### ISSUE TITLE
Keyboard shortcut doesn't work

### ISSUE THREAD

**Issue by MDivne** [spicetify/spicetify-cli#1864]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.91.824.g07f1e963
- Spicetify version: v2.11.1
OS : Windows 10
```

### 📝 Description

Hello ! 
I'm a freshly user of Spicetify, all work well. Except my media shortcut on my keyboard. I can use it when I'm on the spotify window it work but soon I reduces the window, key doesnt work. Media Key only work for my browser, seens like my browser take over spotify even if I dont listen to anything on browser.
I try to unstall / install spicetify, restart PC. 

Thanks !

**Comment by kyrie25** [comment]
Not a CLI bug. Closing issue.
This is most likely due to how your OS handles and prioritizes media sessions.
