### ISSUE TITLE
Save Sync/Unsync Lyrics with timestamp

### ISSUE THREAD

**Issue by Tetrax-10** [spicetify/spicetify-cli#1868]
### 📝 Provide a description of the new feature

A save button to download lyrics with time stamp

**Comment by kyrie25** [comment]
Not possible. Spotify client does not have file write access/permissions.

**Comment by Tetrax-10** [comment]
> Not possible. Spotify client does not have file write permissions.

But What about drag and drop?
If you drag and drop a song to notepad it will drop the songs link
the same way we can drop the lyrics with time stamp to notepad

**Comment by kyrie25** [comment]
The component used for songs is hard-locked behind specific Spotify components that contains more data and functionality than just the song URL for web play (eg. dragging to playlists, `navBar` components and right click menus)
