### ISSUE TITLE
[Shuffle+] Fail to put track on queue

### ISSUE THREAD

**Issue by karimawii** [spicetify/spicetify-cli#1871]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows 1.1.91.824.g07f1e963
- Spicetify version: 2.11.1
```

### 📝 Description

Shuffle+ doesn't shuffle songs and shows an error

### 📸 Screenshots

![Spotify_EMMMebWQLL](https://user-images.githubusercontent.com/69881381/184632012-a101a923-3c5f-45c9-a903-82a924914a9d.gif)

**Comment by kyrie25** [comment]
Can't reproduce, try restoring and applying again.
