### ISSUE TITLE
[Lyrics-plus] Tab not loading

### ISSUE THREAD

**Issue by waterfox22** [spicetify/spicetify-cli#1878]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.84.716-2
- Spicetify version: 2.11.1
- Arch Linux
```

### 📝 Description

idk it's just not working
it's not conflict with Genius
after reading the FAQ did not find a solution, the key from musicxmatch is not clear where to insert, because I can not open the lyrics-plus settings until the tab is loaded.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/111059338/185726884-4ae1917e-0de8-4fc9-8941-7f1baa851fea.png)

**Comment by kyrie25** [comment]
Unsupported Spotify version. Closing issue.
![image](https://user-images.githubusercontent.com/77577746/185727242-017aaa57-221c-4d0d-b436-5997c24fb10f.png)
