### ISSUE TITLE
error initializing "fullscreen.js" extension Spicetify method not available

### ISSUE THREAD

**Issue by Someone-Somwhere** [spicetify/spicetify-cli#1881]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows 1.1.92.647.ga4397eb7
- Spicetify version:spicetify v2.11.1
```

### 📝 Description

My playlist icons, the music controls and the made-for-you page are blank. I also can't access the marketplace

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/71657811/185909382-4c26d47d-c9c4-4edb-970c-17897ff05513.png)

**Comment by kyrie25** [comment]
Resolved via #1875. Wait for the next release.
