### ISSUE TITLE
Spicetify refuses to install

### ISSUE THREAD

**Issue by HDAndreasEST** [spicetify/spicetify-cli#1883]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Newest
- Spicetify version: 2.12.0
```

### 📝 Description

I trying to install spicetify with powershell but its keeps pumping out errors.

### 📸 Screenshots

![Screenshot_1](https://user-images.githubusercontent.com/45965758/186151949-fa0a218b-fcd0-4289-9111-9c1189b74dc1.png)

**Comment by ririxiiscute** [comment]
Uninstall microsoft store version and install one from spotify version, then change prefs_path to spotify installation location

**Comment by kyrie25** [comment]
Common error. Head to the Discord server for fixes.
