### ISSUE TITLE
Problems with injecting Spicetify

### ISSUE THREAD

**Issue by Zzeyy** [spicetify/spicetify-cli#1888]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.92.647
- Spicetify version: The newest the Powershell script installs
```

### 📝 Description

Hello, I want to first say that the installation guide is very confusing for me.
I'm having a problem with injecting Spicetify to Spotify after restarting or turning on the computer.

I don't really want to run the Powershell script every day, is there any other option available?
I've found only one solution that I can't even apply, because I'd need to locate the Spicetify (exe?) file
in a directory that doesn't even exist on my computer. (More about it [here](https://spectrum.chat/spicetify/general/is-there-a-way-to-automatically-inject-spicetify-when-spotify-launches~27a695f3-7f1b-4b82-a447-9f516143ac2e))

So I'd really appreciate some instruction on how to do it properly, thanks.

Also if this perhaps is not the right GitHub page then I'm really sorry, but it's just all confusing for me.

**Comment by kyrie25** [comment]
Common bug, listed on the Discord server's FAQ.
Edit your Spotify's shortcut and set the `Target` field to `spicetify auto`
![image](https://user-images.githubusercontent.com/77577746/186419564-003230df-e611-41d7-9d05-67ea39812b79.png)

**Comment by Zzeyy** [comment]
The target from the screenshot DOES NOT GENERATE FOR ME WHEN USING THE POWERSHELL SCRIPT.
If I try using that then I'm told that destination does not exist.

**Comment by Zzeyy** [comment]
> Common bug, listed on the Discord server's FAQ.
> Edit your Spotify's shortcut and set the Target field to `spicetify auto`

Only `spicetify auto` or something in front of it?

**Comment by Zzeyy** [comment]
Thanks @kyrie25 for telling me about the Discord FAQ.
I think the staff team / administrators don't much care about the website as much as the Discord server.
They really should update the info on their website as well. I wasn't even aware they have a server.
