### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Sodz1aX** [spicetify/spicetify-cli#1890]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: idk
- Spicetify version: idk
```

### 📝 Description

open C: \ Program Files \ WindowsApps \ SpotifyAB.SpotifyMusic_1.190.859.0_x86__zpdnekdrzrea0 \ Apps: The specified file could not be found.
How to fix this?

**Comment by Poopooracoocoo** [comment]
... no version info?!

You may want to try uninstalling your current installation of Spotify which is from the Microsoft Store and then download the exe from Spotify's website, and then install Spicetify again

**Comment by kyrie25** [comment]
Please **do read FAQ** before ticking the box saying you have read FAQ.

**Comment by Sodz1aX** [comment]
bruh, but there is nothing in the FAQ about this error

**Comment by kyrie25** [comment]
Plus this is not a place for support, head to the Discord server where all guides and FAQs are listed.
