### ISSUE TITLE
[Lyrics Plus] Display different lyrics

### ISSUE THREAD

**Issue by OR-7264** [spicetify/spicetify-cli#1894]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.92
- Spicetify version: 2.12.0
```

### 📝 Description

In the Japanese version of sportify, English artist names may be displayed in Japanese.
For this reason, the API will return lyrics for songs with Japanese artist names.
It will then display the lyrics of a different song.

For example, the artist name for "OneRepublic" is "ワンリパブリック" in Japanese.

A translation API may be needed to cure this problem.
SimplyTranslate API : https://codeberg.org/SimpleWeb/SimplyTranslate-Web/src/branch/master/api.md

### 📸 Screenshots

![1](https://user-images.githubusercontent.com/105866841/186934128-f2255fe6-cd0b-4dc1-a698-dbd76414f1e4.gif)
"エド・シーラン" → "Ed Sheeran"
"カラム・スコット" → "Calum Scott"
"アリアナ・グランデ" → "Ariana Grande"
![2](https://user-images.githubusercontent.com/105866841/186934566-692ab702-8878-4322-b2e3-15752a1e924e.gif)
Wild Life Lyrics [here](https://genius.com/Onerepublic-wild-life-lyrics)

**Comment by kyrie25** [comment]
Using a translation service/API to translate artist names may not be ideal, but then again Spotify does have artists with non-Romanized names and simply Romanize the characters isn't ideal either.
Can't really think of a way to decide when to/not to convert artist names and how to differentiate which is the correct lyrics tbh :/

**Comment by kyrie25** [comment]
You can, however, try to switch lyrics providers according to your needs since this issue is because of how different third-party providers handle queries and returns the respective lyrics.

**Comment by OR-7264** [comment]
So, is it possible to anglicize the romanized name again?

I set the Spotify language setting to English and the romanized name remained..
![12](https://user-images.githubusercontent.com/105866841/186955235-21d0b83a-3fd0-4040-b503-f8172ccfb69b.gif)
.

**Comment by kyrie25** [comment]
> So, is it possible to anglicize the romanized name again?

I'm afraid not, this is something even a human struggles, so I highly doubt an automated service is up to the task, let alone an artist's name

> I set the Spotify language setting to English and the romanized name remained...

I'm guessing this is the matter of account region, which is something out of out control I'm afraid.

**Comment by OR-7264** [comment]
I understand. Thanks for the reply.
