### ISSUE TITLE
Album Cover blocks every button and everything and cannot access anything in spotify due to it

### ISSUE THREAD

**Issue by timowbasss** [spicetify/spicetify-cli#1897]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 
- Spicetify version:
```

### 📝 Description

Everytime I play a song, the Album cover blocks everything in spicetify

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/112242052/187020977-67a49800-c412-407c-a6b9-bcbdedc9c11e.png)

**Comment by kyrie25** [comment]
Theme issue.
