### ISSUE TITLE
MarketPlaces error

### ISSUE THREAD

**Issue by wayne-1211** [spicetify/spicetify-cli#1901]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 
- Spicetify version: v2.11.1
```

### 📝 Description

reload many time but it still not working

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/65344622/187108455-f47114d4-84ca-4f62-8484-323d34fcfd18.png)

**Comment by kyrie25** [comment]
Upgrade Spicetify.
