### ISSUE TITLE
config

### ISSUE THREAD

**Issue by GeistFan** [spicetify/spicetify-cli#1902]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.92.647
- Spicetify version: 2.12.0
```

### 📝 Description

Hi there,
I somehow f*cked my spicetify so hard so it doesnt work right anymore.
So I desided to reinstall my Spicetify and while that I upgraded from Windows Store version to normal version. But soon after that my spicetify give me the error "Cannot find Path" but after I searched after how to completly delete Spicetify for an fresh reinstall. On every forum it said "Delete .spicetify & spicetify-cli folder" but I dont have those but somehow my spicetify has still an config file but I can't find. Please help.

### 📸 Screenshots

![grafik](https://user-images.githubusercontent.com/48773535/187140000-560930e3-a53a-42e5-904f-8dfd08d9fa79.png)

**Comment by kyrie25** [comment]
FAQ.

**Comment by GeistFan** [comment]
In the FAQ it says the config is in the spicetífy folder im appdata. But their is also no config!!!!
![grafik](https://user-images.githubusercontent.com/48773535/187511409-cabe3344-eac7-4c27-ac53-6621b17070ea.png)

**Comment by GeistFan** [comment]
@kyrie25
