### ISSUE TITLE
Compatibility patch needed for new version

### ISSUE THREAD

**Issue by xerta555** [spicetify/spicetify-cli#1904]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.93.896.g3ae3b4f3
- Spicetify version: 2.12.0
```

### 📝 Description

Hi everyone

Spicetify need a fix to work with the last Spotify version.
After `spicetify backup apply` command, black screen on Spotify side.

**Comment by kyrie25** [comment]
For those who are concerned about this, we are aware of the issue and is looking into it.
However, due to the complex nature of this update, we are unable to guarantee a timely patch and advise you to downgrade your Spotify client for now.

**Comment by xerta555** [comment]
> For those who are concerned about this, we are aware of the issue and is looking into it. However, due to the complex nature of this update, we are unable to guarantee a timely patch and advise you to downgrade your Spotify client for now.

I obviously downgraded my Spotify, take the time to patch for compatibility.
