### ISSUE TITLE
`topBar` button disappears on clicking Player Lyrics button

### ISSUE THREAD

**Issue by Lseoksee** [spicetify/spicetify-cli#1912]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [x] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: win10 x64 1.1.93.896
- Spicetify version: v2.13.0
```

### 📝 Description

The Popup Lyrics button disappears when you click the Official Lyrics button.

### 📸 Screenshots

![Desktop Screenshot 2022 09 03 - 12 41 37 40](https://user-images.githubusercontent.com/91320047/188254509-1eb3f5ff-0bc7-4c0a-b880-d8fbf4470cfa.png)
Click the Official Lyrics button
![Desktop Screenshot 2022 09 03 - 12 41 37 40(2)](https://user-images.githubusercontent.com/91320047/188254562-6037112e-4645-4a45-a21e-592d7d823cda.png)
Popup Lyrics button disappears

**Comment by kyrie25** [comment]
Not a bug, Spotify hides `topBar` element on Lyrics page regardless

**Comment by Lseoksee** [comment]
> 버그가 아니라 Spotify는 `topBar`관계없이 가사 페이지에서 요소를 숨깁니다.

The second picture is not a lyric screen. I saw the lyrics screen and came back to the main page.


https://user-images.githubusercontent.com/91320047/188255291-1018373d-ab8f-4b31-96b6-0caf51089f9c.mp4

If you look at the video, you can see that the top popupLyrics icon disappears.

**Comment by Lseoksee** [comment]
> Not a bug, Spotify hides `topBar` element on Lyrics page by design.

The second picture is not a lyric screen. I saw the lyrics screen and came back to the main page.


https://user-images.githubusercontent.com/91320047/188255407-a25cf40d-f27f-41a6-a884-4d71e007c7f8.mp4

If you look at the video, you can see that the top popupLyrics icon disappears.

**Comment by kyrie25** [comment]
Could have been a little bit more descriptive on the issue but fair enough. This issue is not exclusive to Popup Lyrics however.
