### ISSUE TITLE
Local Files not available

### ISSUE THREAD

**Issue by TrveKvlt-666** [spicetify/spicetify-cli#1914]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify für Windows
1.1.93.896.g3ae3b4f3
- Spicetify version: 2.8.4
Windows 10 Pro 21H1
```

### 📝 Description

Hey there,

I've got some music that is not available on spotify, but that has been added as local files to my spotify-account.
These files are no longer available when spicetify is running. When i try to open the local files in my library, the "something went wrong" error-message is shown after aprox 20 secons of loading-screen (three dots).
I've tried to create a playlist with my local files, while spicetify isn't running but once spicetify is running again, even trying to open that playlists leads to the same swr-error-message without those 20 seconds of loading screen.

**Comment by kyrie25** [comment]
Outdated & incompatible Spotify/Spicetify version.

**Comment by TrveKvlt-666** [comment]
Have updated Spicetify to 2.13.0. Still the same Error

**Comment by kyrie25** [comment]
This is most likely not a Spicetify bug regardless since Spicetify doesn't handle library & local files API. Try reinstalling your Spotify build or head to the [Discord server](https://discord.gg/UVMuYNUK) and out Helpers will assist you.

**Comment by TrveKvlt-666** [comment]
Have reinstalled Spotify about an hour ago. Thanks for your help, I will head to the Discord-Server tomorrow :)

**Comment by kyrie25** [comment]
> Have updated Spicetify to 2.13.0. Still the same Error

Just to be sure, have you ran `spicetify restore backup apply` afterwards.

**Comment by TrveKvlt-666** [comment]
> > Have updated Spicetify to 2.13.0. Still the same Error
> 
> Just to be sure, have you ran `spicetify restore backup apply` afterwards?

Yes. Still the same error

**Comment by kyrie25** [comment]
Then do head to the Discord server when you have the time and we will assist you there.

**Comment by Goleminho** [comment]
> > > Have updated Spicetify to 2.13.0. Still the same Error
> > 
> > 
> > Just to be sure, have you ran `spicetify restore backup apply` afterwards?
> 
> Yes. Still the same error

Hello, have you solved the problem? I installed Spicetify yesterday and have the same issue with Spotify (flatpak version).

**Comment by TrveKvlt-666** [comment]
> > > > Have updated Spicetify to 2.13.0. Still the same Error
> > > 
> > > 
> > > Just to be sure, have you ran `spicetify restore backup apply` afterwards?
> > 
> > 
> > Yes. Still the same error
> 
> Hello, have you solved the problem? I installed Spicetify yesterday and have the same issue with Spotify (flatpak version).

Nope. Unfortunately not.

**Comment by Goleminho** [comment]
> > > > > Have updated Spicetify to 2.13.0. Still the same Error
> > > > 
> > > > 
> > > > Just to be sure, have you ran `spicetify restore backup apply` afterwards?
> > > 
> > > 
> > > Yes. Still the same error
> > 
> > 
> > Hello, have you solved the problem? I installed Spicetify yesterday and have the same issue with Spotify (flatpak version).
> 
> Nope. Unfortunately not.

Pity, I hope they'll solve it soon.
