### ISSUE TITLE
Marketplace not loading

### ISSUE THREAD

**Issue by SoCoolMuchGitHub** [spicetify/spicetify-cli#1915]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.93.896.g3ae3b4f3
- Spicetify version: 2.13.0
- Operating System: Windows
```

### 📝 Description

Every time I go into the Marketplace, nothing loads. It's just a blank page.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/59752651/188318968-37bc9cf4-f3b4-49c3-8fac-3fc983096e5b.png)

**Comment by kyrie25** [comment]
Not a CLI issue.
Update your Marketplace.
