### ISSUE TITLE
[Lyrics Plus] Compact Lyrics but scrollable

### ISSUE THREAD

**Issue by Tetrax-10** [spicetify/spicetify-cli#1916]
### 📝 Provide a description of the new feature

In compact mode we can't scroll lyrics which some times makes us switch between compact on/off. where as in Spotify lyrics we can scroll but its not customizable.

### ➕ Additional Information

https://user-images.githubusercontent.com/75513645/188332761-6dcfe4f4-972f-4e45-b045-e2c3be119bbd.mp4

Like this demo video but on Lyrics Plus it would be awesome

**Comment by kyrie25** [comment]
This undermines the whole point of Compact mode which literally makes the view "Compact"
Plus this is Synced mode with Compact mode off with extra stylings of which you can make your own CSS snippets for, but we won't make this a default feature for it would change the default behavior for everyone.

**Comment by kyrie25** [comment]
Do feel free do add this as a community snippet via Marketplace though.

**Comment by Tetrax-10** [comment]
> Do feel free do add this as a community snippet via Marketplace though.

Why snippet the I will directly change the compact mode off itself, current compact mode off is not looking that good. And not all users know there is something like snippets and marketplace. so I will make a PR once ready.

**Comment by kyrie25** [comment]
> Why snippet the I will directly change the compact mode off itself, current compact mode off is not looking that good.

Like I said, we won't be accepting any PR that changes the default behavior for everyone. If you do not like the current style, feel free to make a fork of the extension and publish it to your liking.
