### ISSUE TITLE
Doesn't generate config file

### ISSUE THREAD

**Issue by PolGZ** [spicetify/spicetify-cli#1917]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Debian stable
- Spotify version: Last flatpak
- Spicetify version: 2.13.0 (installed via thew recommended hell (pre-built binary)
```

### 📝 Description

Doesn't generate a config file `config-xpui.ini` even though it says:

```
error Could not detect "prefs" file location.
success Default config-xpui.ini generated.
error Cannot detect Spotify "prefs" file location. Please manually set "prefs_path" in config-xpui.ini
``` 

I know I would have to make changes to the config so it finds the flatpak, but I can't find an example of the config file to start from.

Also, when run:

```
$ spicetify config-dir 
error Cannot detect Spotify "prefs" file location. Please manually set "prefs_path" in config-xpui.ini
``` 
But there is not such file nor do I see an example config file to copy and edit from.

### 📸 Screenshots

[No config-xpui-ini](https://i.postimg.cc/t4vtPhb6/Screenshot-from-2022-09-05-18-41-23.png)

**Comment by iamririxi** [comment]
Spicetify v2.13.0 doesn't support Spotify 1.1.84, and tho - for flatpak installation please refer to our website: https://spicetify.app/docs/advanced-usage/installation

**Comment by PolGZ** [comment]
> for flatpak installation please refer to our website: https://spicetify.app/docs/advanced-usage/installation

I know I would have to change the `spotify_path`, but the problem is that I don't get a config file to start from. Would just adding that line + `[Setting]` work?? I don't know if there are any "default values" in that supposed generated config that I should be aware off...

**Comment by iamririxi** [comment]
Did you set right permissions for directories listed on documentation site?

**Comment by PolGZ** [comment]
> Did you set right permissions for directories listed on documentation site?

Yes, I did:
[history](https://i.postimg.cc/90FNCyjQ/Screenshot-from-2022-09-05-19-14-18.png)
[ls result](https://i.postimg.cc/7hdbwMT3/Screenshot-from-2022-09-05-19-12-45.png)

**Comment by kyrie25** [comment]
> ```
> [Setting]
> spotify_path    = /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify
> prefs_path      = ~/.var/app/com.spotify.Client/config/spotify/prefs
> ```
Path must be absolute, try:
```
prefs_path      = /var/app/com.spotify.Client/config/spotify/prefs
```

**Comment by PolGZ** [comment]
> Path must be absolute, try:
> 
> ```
> prefs_path      = /var/app/com.spotify.Client/config/spotify/prefs
> ```

Thanks for your reply, @kyrie25, but `~/.var/app/com.spotify.Client/config/spotify/prefs` it is an absolute path. In fact, it is the same they would reflect as an example in their [installation section](https://spicetify.app/docs/advanced-usage/installation) of the advanced usage guide (3rd step of spotify as a flatpak in linux).
