### ISSUE TITLE
Spicetify http requests fail with dial tcp: i/o timeout

### ISSUE THREAD

**Issue by elliotnash** [spicetify/spicetify-cli#1918]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for macOS (Apple Silicon) 1.1.93.896.g3ae3b4f3
- Spicetify version: 2.13.0

MacOS 13.0 Ventura beta 6
```

### 📝 Description

All http requests made from spicetify fail with with dial tcp: i/o timeout. 
For example, spicetify upgrade log 
```
spicetify upgrade
Fetch latest release info:
error Cannot fetch latest release info
error Get "https://api.github.com/repos/spicetify/spicetify-cli/releases/latest": dial tcp: i/o timeout
```
However, internet is working in all other apps, and running curl to that URL provides the proper output 
```
curl https://api.github.com/repos/spicetify/spicetify-cli/releases/latest
{
  "url": "https://api.github.com/repos/spicetify/spicetify-cli/releases/76042960",
  ...
}
```

**Comment by afonsojramos** [comment]
I truly cannot see how this might be related to spicetify itself.

This is most likely a DNS problem caused by slow resolution. Can you try a different DNS to test that theory?

**Comment by elliotnash** [comment]
I tried with both 1.1.1.1 and 8.8.8.8, and I get a very similar error (although with manually set DNS it seems to be more verbose) 
```
Fetch latest release info:
error Cannot fetch latest release info
error Get "https://api.github.com/repos/spicetify/spicetify-cli/releases/latest": dial tcp: lookup api.github.com on 8.8.8.8:53: read udp 192.168.0.100:62319->8.8.8.8:53: i/o timeout
```
Also, I should note that the result of `curl https://api.github.com/repos/spicetify/spicetify-cli/releases/latest` is nearly instant

**Comment by evtn** [comment]
I also see this, only with spicetify and on different networks. My version is v2.37.1
