### ISSUE TITLE
[Spotify Listen Together] Doesn't work

### ISSUE THREAD

**Issue by 42Willow** [spicetify/spicetify-cli#1919]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 
- Spicetify version:
```

### 📝 Description

The "spotify listen together" extension is deprecated and no longer works, check the GitHub page... the request host button is broken.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/70784752/188821870-c34f617d-e610-427c-8853-0124b662a824.png)

**Comment by kyrie25** [comment]
Not a CLI issue.
