### ISSUE TITLE
Cannot install Spicetify

### ISSUE THREAD

**Issue by SakethKanchi** [spicetify/spicetify-cli#1922]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows 1.1.93.896.g3ae3b4f3
- Spicetify version: 2.13.0
```

### 📝 Description

Installing Spicetify using this command: 
`iwr -useb https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.ps1 | iex` 

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/70198692/189109196-adb9ebc6-394d-4d56-a7b1-d419f40a5e76.png)

Running `spicetify` on terminal gives:
![image](https://user-images.githubusercontent.com/70198692/189109280-7d9c108a-a69b-4603-acca-d9fe239435c5.png)

Using the `cmd` as admin:
![image](https://user-images.githubusercontent.com/70198692/189109503-96ff20b8-d6a0-46bf-9ac6-3e95d1f904cc.png)

**Comment by kyrie25** [comment]
This might have occurred if you installed Spicetify with admin privileges, which you shouldn't.
Head to the Discord server linked on the Spicetify org Readme and our Helpers will assist you there.
