### ISSUE TITLE
Ability to play trimmed versions of songs/sections of songs

### ISSUE THREAD

**Issue by vancromy** [spicetify/spicetify-cli#1926]
### 📝 Provide a description of the new feature

Many songs have cold opens/endings which we many not necessarily want to listen to. Having an extension where we could specify timestamps to start songs at (where these would be saved to some local database for example) such that each time the song shows up, only the clipped/trimmed down version of it would be played automatically. 

This is quite a heavily requested feature on spotify's own forums which they have said they would not look at: https://community.spotify.com/t5/Live-Ideas/Music-Custom-Start-amp-Ending-Times-for-a-Track/idi-p/40013

It would also be a really nice extension for people wanting to play just a section of a song (if they did not like other parts of the song). :) 

### ➕ Additional Information

Proprosed solution:

Perhaps a new button on the 'Now Playing' bar (the one with the play, skip buttons) which would enable "trim mode". A user could then trim the song to the parts they want to listen, click save and from then on each time that song is to be played, it only plays the trimmed version (i.e. starts/ends the song at the saved timestamps). 

I have no experience with Spotify's API so I don't know whether specifying a start/end timestamp is possible.

**Comment by kyrie25** [comment]
We deal with **CLI-related** bugs and feature requests via Issues, thus this will be closed promptly. If you wish to make an extension suggestion, please do so as a Discussions or via the Discord server.
