### ISSUE TITLE
Open Spotify shows an error when apply

### ISSUE THREAD

**Issue by Aya-Yang** [spicetify/spicetify-cli#1928]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:1.1.93.896.g3ae3b4f3
- Spicetify version: 2.13.1
```

### 📝 Description

When execute spicetify apply command,  open Spotify app shows an error

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/12084255/190550225-8be39827-f9a7-44f8-bb0f-1246ae865cdd.png)

**Comment by kyrie25** [comment]
Use "spicetify restore backup apply".
If that doesn't work, head to the Discord server for support. This is most likely a common issue.
