### ISSUE TITLE
Glitched screen? Does anyone know how to fix :/

### ISSUE THREAD

**Issue by jeenerzz** [spicetify/spicetify-cli#1930]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for macOS (Apple Silicon)
1.1.94.870.gf994cb0b
- Spicetify version: v2.13.1
```

### 📝 Description

Config Flow ocean theme and color scheme
Open Spotify

I also tried restoring backup (before I applied a theme), to no avail

### 📸 Screenshots

<img width="1440" alt="Screen Shot 2022-09-15 at 11 24 31 PM" src="https://user-images.githubusercontent.com/113662619/190605222-4dce82bc-1389-4019-a788-696cb9c42f92.png">

**Comment by kyrie25** [comment]
Issues are **not** meant for support. Not a CLI issue.
