### ISSUE TITLE
Add TrashBin icon to the top left corner like bookmarks and full screen

### ISSUE THREAD

**Issue by foco76** [spicetify/spicetify-cli#1932]
### 📝 Provide a description of the new feature

As for now we can only go to the artists profile or song and manually click remove from trashbin one by one I thought it will be best to have a place(Trashbin in left corner)  to remove artists or songs from trashbin in bulk(multiple selection), Can you make that happen?
Thank you!Good Luck!

**Comment by kyrie25** [comment]
Not possible, the only way we can verify elements type is via Spotify, right-click menu. Having such selection on multiple types of pages is extremely difficult or impossible.
You can already bulk select songs and remove them.
