### ISSUE TITLE
NoPremium Without Adblock(New Snippet)

### ISSUE THREAD

**Issue by foco76** [spicetify/spicetify-cli#1933]
### 📝 Provide a description of the new feature

Currently SpotifyNoPremium by Daksh777 is used as theme but when using it you can't apply other themes since it's not particularly a theme I made this using Daksh777's SpotifyNoPremium theme but **without** Adblock Support But it can easily fix by installing Adblock extention!

Snippet Name -NoPremium Without Adblock

Snippet Description -Forked From SpotifyNoPremium by Daksh777 for remove update Spotify Links and other premium related stuffs from Spotify WITHOUT adblock support and as snippet for ones who need to use other themes!
 
Snippet Image -
![NWA](https://user-images.githubusercontent.com/109255482/190730921-b9a27582-b18d-40e4-8ff2-6346ce1761b0.jpg)

(Credit For Daksh777) 

Snippet CSS-
[https://raw.githubusercontent.com/Daksh777/SpotifyNoPremium/main/user.css](url)
(Credit For Daksh777)

**Comment by iamririxi** [comment]
Use discussions also not related to cli

**Comment by foco76** [comment]
Oh! Sorry I'm new to github I fixed it!
