### ISSUE TITLE
Lyrics plus  - Add more servers

### ISSUE THREAD

**Issue by foco76** [spicetify/spicetify-cli#1935]
### 📝 Provide a description of the new feature

Can you add more servers to Lyrics plus ,popup lyrics or official spotify lyrics other than musixmach , netease
[if possible add download button in Lyrics plus for downloading lyrics (some servers like rentanadviser.com supports it!)]
*such as-
    rentanadviser.com (synchronized)
    megalobiz.com (synchronized)
    lyricsify.com (synchronized)
    rclyricsband.com (synchronized)
    songmeanings.com
    songlyrics.com
    versuri.ro
    AZLyrics.com

you can use [https://github.com/SimonIT/spotifylyrics](url) for help it already have there features!
Thank you!

**Comment by kyrie25** [comment]
> [if possible add download button in Lyrics plus for downloading lyrics (some servers like rentanadviser.com supports it!)]

Not possible, Spotify client does not support downloading files. However, you can right-click lyrics on Synced & Unsynced tabs to copy them (with timestamps if Synced)

**Comment by iamririxi** [comment]
It's feature request, please use discussions
