### ISSUE TITLE
Synced Playback Across Devices Not Working 

### ISSUE THREAD

**Issue by karimawii** [spicetify/spicetify-cli#1938]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows 1.1.94.870.gf994cb0b
- Spicetify version: 2.13.1
```

### 📝 Description

I don't know what's causing it Spotify or Spicetify, but the app just doesn't sync with the web player/mobile app at all, and vice versa, app doesn't show if I'm playing smth on another device. Tried restarting Spotify multiple times, didn't try restoring because I don't wanna lose my settings T_T

**Comment by kyrie25** [comment]
Spotify bug.
https://community.spotify.com/t5/Desktop-Windows/Spotify-Connect-not-working/td-p/5429730
