### ISSUE TITLE
Play button scaled improperly on Mac

### ISSUE THREAD

**Issue by NewAgeDerpDerp** [spicetify/spicetify-cli#1945]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Intel 1.1.94.870.gf994cb0b
- Spicetify version: 2.13.1

MacBook Pro (2017, 13", Two Thunderbolt 3 ports)
Intel Core i5-7360U @ 2.3GHz
8GB 2133MHz LPDDR3 
Intel Iris Plus Graphics 640, 1.5GB shared with system RAM
macOS Ventura 13.0 Public Beta 7
```

### 📝 Description

To reproduce the error:
Boot up Spotify with a theme applied that does not have any major changes to the UI [most of the ones built off the default theme will trigger this, themes like Bloom will **not**]

What happens:
The play/pause button scales incorrectly and appears to render over itself four times

Expected results:
The play/pause button will render normally.

### 📸 Screenshots

<img width="677" alt="image" src="https://user-images.githubusercontent.com/38193901/191392933-7b3d3cb5-f924-458a-91aa-e3a51cc0cb2c.png">
<img width="644" alt="image" src="https://user-images.githubusercontent.com/38193901/191392959-cfabc60b-d829-4cb9-b574-d0716430404e.png">

**Comment by kyrie25** [comment]
Not a CLI bug.
Remove `bloom.js` from your extension list and re-apply.
