### ISSUE TITLE
Uninstalled Spicetify But Some Elements Left Even After Reinstalling Spotify

### ISSUE THREAD

**Issue by jaytrinitron** [spicetify/spicetify-cli#1948]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows
1.1.94.870.gf994cb0b
- Spicetify version: 2.13.1
```

### 📝 Description

I think I screwed up with spicetify's restore method somehow when I was messing about in the theme files of https://github.com/Comfy-Themes/Spicetify. When I tried to uninstall (after uninstalling the Comfy themes), spicetify restore didn't work but I thought it would be fine to just delete the spicetify directories and restart. But my spotify still looked different than normal, so I tried reinstalling Spotify but to no avail. How do I remove all the modifications?

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/62568097/191693837-62c47716-d032-47c5-ab45-ffec7815997c.png)

**Comment by jaytrinitron** [comment]
It has come to my attention that this is actually a Spotify change (my bad). However, it does appear to break some of the functionality of spicetify. Is there a way to revert it or does spicetify need to be updated to a newer version?

**Comment by kyrie25** [comment]
We are already working on support for the new layout, stay tuned :)

**Comment by kyrie25** [comment]
Just to be clear, regarding themes issues, it will be entirely up to the theme developers to adapt with this new change/layout.
As for what I've seen so far, only a few extensions that relies on Spotify's top bar is currently not visible (Full App Display, Popup Lyrics). If you found more missing features and wish to help patch for the new UI feel free to drop by the Discord server and inform us of those changes.

**Comment by jaytrinitron** [comment]
Sure. I'm pretty sure the rest are theme issues, but if I find any that seem like they might not be I'll let you guys know on discord.
