### ISSUE TITLE
Hide lyrics button in bottom bar if Lyrics Plus is enabled

### ISSUE THREAD

**Issue by francescoaracu** [spicetify/spicetify-cli#1949]
### 📝 Provide a description of the new feature

The lyrics button in the bottom bar opens the Spotify lyrics fragment. It is good if you don't use Lyrics Plus, but I think that with LP enabled this button is a double.

**Comment by kyrie25** [comment]
Users shouldn't have to remove/re-add Lyrics Plus if they feel like switching nor should applying a custom app must remove a non-conflicting Spotify feature.
