### ISSUE TITLE
"error Theme "marketplace" not found" but marketplace is in Themes

### ISSUE THREAD

**Issue by RedmineTV** [spicetify/spicetify-cli#1953]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.94.872
- Spicetify version: v2.13.1
```

### 📝 Description

Spicetify cant find the standard "marketplace" theme and gives the error "error Theme "marketplace" not found"
i tried to manual install the Marketplace Theme and the Theme is in the folder but spicetify cant recognize it.

### 📸 Screenshots

![Screenshot 2022-09-23 202839](https://user-images.githubusercontent.com/44092568/192033521-cc097ae8-2eb9-482f-8c38-3f02200b2a96.png)

**Comment by iamririxi** [comment]
Not related to CLI.
