### ISSUE TITLE
Please add MacOS 'manual "$PATH" install' steps to the install instructions

### ISSUE THREAD

**Issue by WheezyE** [spicetify/spicetify-cli#1954]
### 📝 Provide a description of the new feature

I was installing spicetify on a MacOS Monterey laptop with the following commands:
```bash
curl -fsSL https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.sh | sh
curl -fsSL https://raw.githubusercontent.com/spicetify/spicetify-marketplace/main/resources/install.sh | sh
```
But I couldn't understand at first why the terminal was saying `zsh: command not found: spicetify` and why the installation wasn't completing.

I thought the `spicetify` script might not be in the system's $PATH, so started googling how to add that on a Mac, but I also ran the first command on its own a few more times just to learn what I could and then finally saw the 'manual $PATH install' instructions listed adjacent to all the rest of the installation output from the first script:
```bash
...
REMOVING /Users/REDACTED/.spicetify/spicetify.tar.gz
Manually add the directory to your $PATH through your shell profile
export SPICETIFY_INSTALL="/Users/REDACTED/.spicetify"
export PATH="$PATH:/Users/REDACTED/.spicetify"
```

### ➕ Additional Information

I'm fairly savvy with bash, but I think if I was a new user I might have given up. I was thinking ... for new users, would it be possible to add a blurb in the main install instructions for MacOS to make sure users type each command in one at a time and read any instructions that come out? Or a blurb about possibly adding path manually? Or even just highlight the text color of the manual $PATH install in the terminal so users can see it more easily?

Thank you for this awesome script.  I'm a Linux/Win dark theme guy, but my fiancé loves the soft pink "flow" theme on her MacBook.

**Comment by kyrie25** [comment]
The command output is printed out when either the `profile` or `rc` file is not available/accessible. Either way there is no universal guides for both Linux/MacOS, all shells and it's not related to the CLI. Users are free to google or ask their questions inside the Discord support server.

**Comment by kyrie25** [comment]
If you are able to highlight the text in terminal output however, feel free to make a PR :)

**Comment by CharlieS1103** [comment]
I think this is a pretty good suggestion tbh, @kyrie25 
All you need to do is  run(for zshrc) 
`touch ~/.zshrc; open ~/.zshrc`
and then paste
`alias spicetify="$PATH:$HOME/.spicetify/spicetify"`
And for bash  it'd be:
``touch ~/.bash_profile; open ~/.bash_profile``
And paste in 
``export PATH="$PATH:$HOME/.spicetify"``

**Comment by kyrie25** [comment]
You forgot Fish lol
