### ISSUE TITLE
Since Spicetify is removed every time Spotify changes anything, is there a way to automatically apply Spicetify on Startup

### ISSUE THREAD

**Issue by WatchfulSeal** [spicetify/spicetify-cli#1956]
### 📝 Provide a description of the new feature

I've tried with PowerShell, but couldn't get it to work consistently, since I didn't really know what command to use, but I'm sure that it would be possible (On Windows that is)

**Comment by kyrie25** [comment]
Problem listed in Discord server's FAQ.
