### ISSUE TITLE
New UI changes to the UI before update 1.1.94 when enabling any experimental feature

### ISSUE THREAD

**Issue by Plueres** [spicetify/spicetify-cli#1961]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows 1.1.94.872.g7a9200fe
- Spicetify version: 2.13.1
```

### 📝 Description

When the new UI is visible like this 
![Screenshot 2022-09-28 115433](https://user-images.githubusercontent.com/71077562/192750450-c4f7c65b-4855-45d7-ba6c-2c6c6ed8ecc6.png)
and you enable an experimental feature, the UI goes back to this one
![Screenshot 2022-09-28 115954](https://user-images.githubusercontent.com/71077562/192751828-cd04e7fa-1071-42b7-a6ac-f9d9d6a76d5b.png)

Note: I have plugins installed but they don't interfere with this and don't cause the issue as I've uninstalled all my plugins to see if the plugins were the problem

Also, I'm not sure if this is a spicetify issue or a spotify issue but when this UI was in experimental phase I was able to use both experimental features and the new UI

**Comment by kyrie25** [comment]
Clear all experimental features using the button at the bottom of the list.

**Comment by kyrie25** [comment]
A PR is made recently helps enable feature that uses enum type (such as this new layout) and will be shipped with the next release of CLI

**Comment by Plueres** [comment]
> On Spotify version 1.1.94, they changed how the feature is implemented internally. As such, the cached "new layout" feature does not reflect correctly how it is implemented anymore. Thus, you can't enable it via Experimental Features on 1.1.94. The new layout isn't shipped with versions, it is linked to each account as a testing feature.

Thanks for all the info!
