### ISSUE TITLE
Shuffle Enabled, cannot be Disabled

### ISSUE THREAD

**Issue by S0Iomon** [spicetify/spicetify-cli#1962]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 2.13.1
- Spicetify version: 1.1.94
```

### 📝 Description

as the title says, installing spicetify 2.13.1 and using it on spotify 1.1.94, I cannot disable shuffle. I tried removing spicetify and shuffle is disabled. I think that there is a bug in spicetify.

**Comment by kyrie25** [comment]
Spicetify does not alter functions by default.
Remove all applied extensions in config and Marketplace.

**Comment by S0Iomon** [comment]
bruh, the fix is to go to experimental feature and reset every preference

**Comment by eclipsek20** [comment]
> bruh, the fix is to go to experimental feature and reset every preference

Had the same issue, the fix was nowhere to be found everywhere but after searching issues here it fixed itself, the thing is to disable "Enable pick and shuffle".
