### ISSUE TITLE
Liked Songs don't work / Themes don't install

### ISSUE THREAD

**Issue by K3NOXOFFICIAL** [spicetify/spicetify-cli#1975]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.95.893
- Spicetify version: v2.14.0
- Windows 11
```

### 📝 Description

After the recent spicetify update, I wasn't able to open my liked songs anymore, any other playlist works.
Tried to uninstall spotify, Spicetify, reinstall Spotify, Spicetify, Cleared the Local and roaming app data, tried different Spotify versions but nothing works.
Also, if I try to install a theme, it keeps either saying "Error: No marketplace theme installed" or "Error: Please create an Issue".

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/46091052/194447645-fbe6c9b7-eb66-422c-acab-5de92cbd7384.png)

**Comment by kyrie25** [comment]
Not reproducible.
Clean uninstall all Spotify & Spicetify files and reinstall, **do not** install Spicetify as an administrator.
If that doesn't work then send config for diagnostics.
