### ISSUE TITLE
mac os 13 not support

### ISSUE THREAD

**Issue by 1017189542** [spicetify/spicetify-cli#1977]
### 📝 Provide a description of the new feature

<img width="740" alt="WechatIMG999" src="https://user-images.githubusercontent.com/25679115/194718389-a280e764-8f7b-4f7f-ab0c-083eedaad382.png">

**Comment by iamririxi** [comment]
That's not the spicetify problem, when installing from homebrew, you need to have xcode installed for git and stuff. You should install beta of xcode from link that is provided in this screenshot. Nothing to do from our end.
