### ISSUE TITLE
can't find offline.bnk in user installed flatpak & no colors applying

### ISSUE THREAD

**Issue by wael444** [spicetify/spicetify-cli#1979]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.84.716.gc5f8b819
- Spicetify version:2.14.0
```

### 📝 Description

can't find offline.bnk: 
```
prefs_path   = /home/wael/.var/app/com.spotify.Client/config/spotify/prefs
spotify_path = /home/wael/.local/share/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify
```
https://github.com/spicetify/spicetify-cli/blob/4b1fda2198fc61eb0b9a5fe30f3585dd47a02c16/src/cmd/devtools.go#L36
since `spotify_path` isnt in the 'flatpak installations' (`/usr/var/lib/flatpak`, which cannot be used) this does not work.

as for the no colors, i do not understand either; i am using marketplace and marketplace's CSS colors are being used.
```ini
current_theme           = spotify
color_scheme            = gruvbox
```
```ini
[gruvbox]
text               = #ebdbb2
subtext            = #a89984
main               = #1d2021
sidebar            = #1d2021 
player             = #1d2021
card               = #1d2021
shadow             = #1d2021
selected-row       = #1d2021
button             = #928374
button-active      = #928374
button-disabled    = #282828
tab-active         = #1d2021
notification       = #1d2021
notification-error = #282828
misc               = #1d2021
```

**Comment by kyrie25** [comment]
Unsupported Spotify version. Downgrade to Spicetify `v2.9.9` for compatibility with Spotify `v1.1.84`

**Comment by kyrie25** [comment]
Also color scheme hexs aren't supposed to have `#` at the start of the value. Use other themes or `SpicetifyDefault` as reference.
Default Marketplace theme is named `marketplace`.

**Comment by wael444** [comment]
> Also color scheme hexs aren't supposed to have # at the start of the value.

yeah that should explain it. thanks for pointing that out.

> Unsupported Spotify version. Downgrade to Spicetify v2.9.9 for compatibility with Spotify v1.1.84

why was this closed then? i was just experimenting with system installed flatpak to check. plus spicetify DOES attach and css and extensions work.

**Comment by kyrie25** [comment]
> why was this closed then? i was just experimenting with system installed flatpak to check. plus spicetify DOES attach and css and extensions work.

Linux's Spotify version is almost a year behind every other platforms. Even if it does manage to work, we won't and will not guarantee anything to work, not provide support or fix any problems that occurs.
Latest Spicetify releases are meant for latest Spotify versions.

**Comment by wael444** [comment]
> Latest Spicetify releases are meant for latest Spotify versions.

thanks, i sort of forgot this myself.

just to make sure, wouldn't it conflict with existing themes or extensions that are meant to be used with the newer versions that (maybe) have different CSS mappings?

**Comment by kyrie25** [comment]
> just to make sure, wouldn't it conflict with existing themes or extensions that are meant to be used with the newer versions that (maybe) have different CSS mappings?

CSS mappings are added every new version, not replaced. There won't be any concerns about unmatched class names.
**However**, lots of (maintained) theme have adapted their theme to patch bugs that appears in newer versions of Spotify (most noticeably Spotify released a new UI in their latest versions), so those themes might no longer work for older versions

**Comment by wael444** [comment]
yep. theme works now, will re-open as different issue since offline.bnk still errors.
