### ISSUE TITLE
Error parsing Markdown when attempting to load extension details

### ISSUE THREAD

**Issue by TacoRat** [spicetify/spicetify-cli#1981]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.95.893.g6cf4d40c
- Spicetify version: 2.14.0
```

### 📝 Description

Error with displaying marketplace extensions, etc. Tried reinstalling both spicetify, spotify, clearing all associated files. 

https://user-images.githubusercontent.com/56605422/195445255-3adba95a-7619-4001-9ae3-09d1202b3428.mp4

**Comment by theRealPadster** [comment]
The 403 means the github api for that is not accessible. Are you using a vpn or something?

**Comment by TacoRat** [comment]
Nope, no vpn nor proxy enabled. Straight connected to my network.

**Comment by TacoRat** [comment]
> The 403 means the github api for that is not accessible. Are you using a vpn or something?

Nope, no vpn nor proxy enabled. Straight connected to my network.

**Comment by kyrie25** [comment]
Not a CLI issue.
