### ISSUE TITLE
progress bar displacement

### ISSUE THREAD

**Issue by arlooonie** [spicetify/spicetify-cli#1988]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.96.785
- Spicetify version: 2.14.0
```

### 📝 Description

When I start my spotify, progress bar seems fine but when I check out playlists, albums, etc., progress bar is displaced

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/100902107/197111514-31c72ab9-c0eb-4151-afea-3d58efc4905a.png)

**Comment by kyrie25** [comment]
Not a CLI issue.
