### ISSUE TITLE
massive issues with Spicetify themes and extensions. unsure if Spotify updated.

### ISSUE THREAD

**Issue by Novattz** [spicetify/spicetify-cli#1995]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows 1.1.97.962.g24733a46
- Spicetify version: 2.14.0
```

### 📝 Description

i opened the normal exe i always use for Spotify and it said "installing Spotify please wait" for like 2 seconds then launched Spotify. Spicetify obviously broke and i then applied Spicetify again. After that hella issues started popping up like marketplace not working anymore and extensions not loading. It might be a Spotify update but i highly doubt so considering i didn't even get notified it was getting updated.

### 📸 Screenshots

![Spotify_9H9zx21zea](https://user-images.githubusercontent.com/47538996/198352375-4d4a1a8b-c08f-42dc-8194-52526f899262.png)
![Spotify_UVmt4jlVnC](https://user-images.githubusercontent.com/47538996/198352532-f7dea0c1-5820-4916-b135-3ea8e7825ada.png)

![Spotify_lFKhpb0Huy](https://user-images.githubusercontent.com/47538996/198352544-8b841a33-28e0-420d-91ab-b5cf046824d8.png)

**Comment by ririxidev** [comment]
Update to https://github.com/spicetify/spicetify-cli/releases/tag/v2.14.1 by running `spicetify upgrade`
