### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by LewiFF** [spicetify/spicetify-cli#1996]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 8.7.78.373
- Spicetify version: v2.14.1
```

### 📝 Description

error Cannot detect Spotify location. Please manually set "spotify_path" in config-xpui.ini if you can help me i always get this error

### 📸 Screenshots

![Screen Shot 2022-10-29 at 4 02 46 PM](https://user-images.githubusercontent.com/108858704/198846478-9bbe4e00-3b1f-4611-a53c-63a5704fd950.png)

**Comment by ririxidev** [comment]
You don't have `root` permissions aka `sudo` and such it couldn't find it. You need these permissions to use spicetify.
