### ISSUE TITLE
spicetify config extensions queueAll.js and newRelease.js and djMode.js not found

### ISSUE THREAD

**Issue by alijr2018** [spicetify/spicetify-cli#1997]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify  pour Windows
1.1.97.962.g24733a46
- Spicetify version:2.14.1
Transferring extensions:
error Extension "djMode.js" not found.
error Extension "newRelease.js" not found.
error Extension "queueAll.js" not found.
```

### 📝 Description

error extension

### 📸 Screenshots

![Capture d’écran 2022-10-30 014451](https://user-images.githubusercontent.com/106558621/198856539-451c5816-ec11-4c6e-a764-c8e869291404.jpg)

**Comment by ririxidev** [comment]
Remove them from config or by `config extensions djMode.js-` and so on...

**Comment by alijr2018** [comment]
thanks
