### ISSUE TITLE
Dunno how to explain it

### ISSUE THREAD

**Issue by asianegod** [spicetify/spicetify-cli#1998]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows 1.1.97.962.g24733a46
- Spicetify version: idfk
```

### 📝 Description

The spotify folder is there its a valid path in file explorer  but spicetify cant find it somehow and this happens to every cmds

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/117000219/198866929-9fca7159-9b74-4c35-9e12-db6e3753a38e.png)

**Comment by kyrie25** [comment]
FAQ.
