### ISSUE TITLE
Kali Linux - Not working after installation

### ISSUE THREAD

**Issue by httpshotmaker** [spicetify/spicetify-cli#2001]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: latest on 01.11.22
- Spicetify version: 2.14.1
```

### 📝 Description

After installing the market and spicetify, when starting Spotify, the client starts without changes, there were no installation errors

### 📸 Screenshots

![Screenshot_2022-11-01_22_07_50](https://user-images.githubusercontent.com/80145620/199317821-df880fa8-d605-486f-b977-3f57666e005c.png)

**Comment by ririxidev** [comment]
Did you run `spicetify backup apply`? And spotify comes from what source (flatpak etc.)?

**Comment by theRealPadster** [comment]
Spicetify 2.9.9 is the latest working one for Linux, since Spotify on Linux hasn't been updated past 1.1.84.

**Comment by kyrie25** [comment]
It seems like the default `config-xpui` was generated when you ran `spicetify restart`, which means you haven't ran `spicetify backup apply`.

I'll close this for the time being, make sure to try both suggestions above before reporting issues again.

**Comment by httpshotmaker** [comment]
> Did you run `spicetify backup apply`? And spotify comes from what source (flatpak etc.)?

Yes, I already tryed. From curl from installation page
