### ISSUE TITLE
If I uninstall spicetify will i still have a chance to have my account deleted?

### ISSUE THREAD

**Issue by loving-u** [spicetify/spicetify-cli#2002]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 8.6
- Spicetify version: None, Uninstalled..
```

### 📝 Description

Will I still have a chance to get my account terminated if I uninstall spicetify?

**Comment by theRealPadster** [comment]
1. That is not an actual Spotify version
2. You won't get your account deleted
