### ISSUE TITLE
(._.) Isn't displayed correctly

### ISSUE THREAD

**Issue by EchoLWS999** [spicetify/spicetify-cli#2003]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.97.962.g24733a46
- Spicetify version: 2.14.1
```

### 📝 Description

I use Full App Display on an old phone of mine that I don't use anymore, and everything works fine until the face for no lyrics pops up. I would like an option to disable the face when there aren't any lyrics, it doesn't display right as my screen is too small.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/107898744/199379124-21ec786f-4ff0-4219-86b8-1bd62438fda5.png)

**Comment by TrialExpired** [comment]
You could try Full App Display Modified from @huhridge here (also available in Marketplace): https://github.com/huhridge/huh-spicetify-extensions

It's a bit buggy for me but it automatically closes the lyrics section and centers the album info when lyrics aren't available.

**Comment by ohitstom** [comment]
@kyrie25 would this not want closing now?
