### ISSUE TITLE
Private session is un togglable / broken

### ISSUE THREAD

**Issue by Exynos-nibba** [spicetify/spicetify-cli#2005]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.97.962.g24733a46
- Spicetify version: 2.14.1
```

### 📝 Description

**Steps to reproduce the bug:** _Clean install Spotify, install Spicetify with marketplace._
**What Happens:** _Private session becomes not togglable, the private session button in the drop down menu does nothing and the settings switch does nothing either_
**Expected behaviour:** _Private session works as normal and can be triggered with the button in the drop down menu or the switch in the settings_

P.S :- No extensions or plugins were installed.

**Comment by kyrie25** [comment]
Not a CLI bug.
