### ISSUE TITLE
Why is my spotify looking like this?

### ISSUE THREAD

**Issue by The-Unknown-Programming-Student** [spicetify/spicetify-cli#2011]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.98
- Spicetify version: 2.14.1
```

### 📝 Description

I removed my previous theme and applied a new one and my spotify started to look like this
Pls tell me any fix to this bug

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/116381063/201321670-71bcbff9-def9-422a-84e8-8dc1bb2e08fe.png)

**Comment by kyrie25** [comment]
Not a CLI issue.

**Comment by theRealPadster** [comment]
Also, remove the dribbblish extension, that's what causes the messed up playlists

**Comment by The-Unknown-Programming-Student** [comment]
> Also, remove the dribbblish extension, that's what causes the messed up playlists

Yeah , It works. But i had to to restore and then apply the current theme again to make it work.
Can you suggest or edit the playlist bar to show only names and not the playlist pic. That would be a nice touch.

**Comment by theRealPadster** [comment]
Isn't that how it works by default? I know I installed an extension to add playlist icons

**Comment by The-Unknown-Programming-Student** [comment]
> Isn't that how it works by default? I know I installed an extension to add playlist icons

 I know It is working by default. I am trying to give a suggestion to add an option to change a few settings like these. You can take some ideas from Nord Spotify theme available in the marketplace

**Comment by theRealPadster** [comment]
Marketplace isn't really meant for adding its own customization and extension stuff, mostly just enabling easy access to install other extensions. Nord Spotify has a lot of JS and settings that aren't in the scope of what we're trying to do with marketplace
