### ISSUE TITLE
Disable devtools

### ISSUE THREAD

**Issue by jacksongoode** [spicetify/spicetify-cli#2012]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Latest
- Spicetify version: Latest
```

### 📝 Description

There used to be a `disable-devtools` command? There needs to be docs on this since there is an `enable-devtools` command.

**Comment by theRealPadster** [comment]
Considering it just resets itself now you can probably just restart it and they'll be gone.

**Comment by ririxidev** [comment]
There is no `disable-devtools` because the method we use, is modifying offline.bnk which most likely will "reset" when you will re-open spotify and such there is no need for that command.

**Comment by Jeffery-Song** [comment]
Sometimes when cmd+Q and relaunch spotify, the devtools is still enabled. This causes certain operation unreachable (e.g. auxclick on lyrics-plus to copy lrc. When devtools enabled, right click shows context menu.)

**Comment by kyrie25** [comment]
> Sometimes when cmd+Q and relaunch spotify, the devtools is still enabled. This causes certain operation unreachable (e.g. auxclick on lyrics-plus to copy lrc. When devtools enabled, right click shows context menu.)

#2176
