### ISSUE TITLE
Spicetify 2.14.1 not working on Spotify 1.1.84.716-2

### ISSUE THREAD

**Issue by diogogmatos** [spicetify/spicetify-cli#2015]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.84.716-2
- Spicetify version: 2.14.1
```

### 📝 Description

Spicetify seems to be breaking my Spotify installation after applying any theme. This happens on Spotify version 1.1.84.716-2. The UI seems to go back to an old version, with the old icons and without the lyrics icon. Clicking the profile icon gives an error (see screenshot) and clicking "Hide Announcements" doesn't do anything.

Is this a problem on my end? I'm using the Catppuccin-Mocha-Lavender theme (which I've used before without any problems) and now since updating my Linux system I just can't get it to work properly.

Thank you so much.

### 📸 Screenshots

**Home page:**

![image](https://user-images.githubusercontent.com/80540164/202231312-880436af-ec6f-4111-94f2-50983f638f06.png)

**After clicking profile:**

![image](https://user-images.githubusercontent.com/80540164/202231478-bbafc765-957b-492b-b535-c336fae8a63a.png)

**Search:**

Some icons/images don't load.

![image](https://user-images.githubusercontent.com/80540164/202232009-539d4a9f-179a-438c-acf2-e7bcbdab8266.png)

**Comment by theRealPadster** [comment]
The latest Spotify version available for Linux is quite outdated, so you will need to use Spicetify 2.9.9. The latest Spicetify isn't fully compatible with it anymore.

**Comment by diogogmatos** [comment]
@theRealPadster Did that and the problem persists. Installed Spicetify version 2.9.9. and reapplied the theme. All the problems indicated above still persist. Spicetify now gives the following error messages:

```
Applying additional modifications:
error cannot find symbol for Custom app React symbols
error cannot find symbol for Custom app React Element
error Spotify version mismatch with Spicetify
Spicetify currently only supports until Spotify v1.1.84
```

**Comment by theRealPadster** [comment]
Try reinstalling spotify, or running `spicetify restore`? It might be in a broken state and needs to be reset.

**Comment by kyrie25** [comment]
Restore Spicetify before downgrading Spotify. If you have forgot to do so you have to reinstall Spotify.
