### ISSUE TITLE
Playlist sidebar blank space and irregular scrolling bug

### ISSUE THREAD

**Issue by Goodly58** [spicetify/spicetify-cli#2019]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows
1.1.98.691.gf759311c
Spicetify v2.14.2
```

### 📝 Description

I created a new issue since the previous one by a person facing an identical problem was marked closed due to inactivity by the GitHub-actions bot. As mentioned by @channer72 in [their issue](https://github.com/spicetify/spicetify-cli/issues/1544), "about halfway through my playlist list on the sidebar, the bottom of the bar gets filled with blank space as you scroll down. The scroll animation also becomes janky as it skips back and forth when scrolling."

![image](https://user-images.githubusercontent.com/63460148/203395314-d3ef4309-72c1-4726-b8f7-8073ce2efd80.png)

I only have these extensions:
![image](https://user-images.githubusercontent.com/63460148/203395341-c1f79ce1-4746-46e0-9cfa-9b7e77ad077b.png)
as well as Shuffle+ and GoToSong. However, these extensions should not affect the sidebar.

As a byproduct, when I click on a playlist, it takes me down, which doesn't happen in vanilla Spotify. This can be seen in the following video:
https://user-images.githubusercontent.com/63460148/203399416-13edd348-1724-4c62-aca0-0892a014098e.mp4

When I scroll, a similar problem happens:

https://user-images.githubusercontent.com/63460148/203399391-587a3c28-8a20-40bf-8b09-e0f13beab535.mp4

It doesn't matter which theme I use, the problem remains, including the default Spicetify theme.
Removing Spicetify fixes this problem.

**Comment by kyrie25** [comment]
Not a CLI isue
Remove `bloom.js` from your config and re-apply.

**Comment by Goodly58** [comment]
@kyrie25 
Removed all extensions, removed theme, and reset all experimental features. Problem still exists.
![image](https://user-images.githubusercontent.com/63460148/203543668-cd3e4f40-c758-470e-acc2-12f035a5317b.png)
![image](https://user-images.githubusercontent.com/63460148/203543819-a69c2f7b-99b4-47de-9143-cbe35ed348be.png)

**Comment by kyrie25** [comment]
Reinstalled Spotify?

**Comment by Goodly58** [comment]
Reinstalled spotify from spotify.com/download. Same results when I apply spicetify.

**Comment by kyrie25** [comment]
That would be the case since that tamper with sidebar height values.
![image](https://user-images.githubusercontent.com/77577746/203552773-80231450-083c-466b-b9c8-2c96eba1ff04.png)

**Comment by Goodly58** [comment]
@kyrie25 Is there any way I can remove it?

**Comment by kyrie25** [comment]
Run `spicetify config-dir`, open `config-xpui` and delete those 2 lines below the Patch section, run `spicetify apply` again afterwards.

**Comment by Goodly58** [comment]
That did the trick, thank you so much!
