### ISSUE TITLE
theme not applying to Spotify 

### ISSUE THREAD

**Issue by bunniiismiless** [spicetify/spicetify-cli#2020]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for macOS (Apple Silicon)
1.1.98.691.
- Spicetify v2.14.2

- MacOS - 13.0.1 (22A400)
```

### 📝 Description

Im having some trouble applying a theme to Spotify. i'm editing the text then saving it and when i apply in brew it says that the text is blank. I typed in the golden theme and nothing. 

### 📸 Screenshots

<img width="1440" alt="Screenshot 2022-11-22 at 9 42 03 PM" src="https://user-images.githubusercontent.com/118867997/203459965-bb4b489a-fea1-4e4c-a4a9-130a92ac139b.png">
<img width="1440" alt="Screenshot 2022-11-22 at 9 43 11 PM" src="https://user-images.githubusercontent.com/118867997/203460049-54e71cd3-68e5-40c8-b13f-3088ace0af37.png">
<img width="1440" alt="Screenshot 2022-11-22 at 9 42 18 PM" src="https://user-images.githubusercontent.com/118867997/203460063-e2cd53c9-9f2e-4642-96b6-19c2f26d2918.png">

**Comment by kyrie25** [comment]
Not a CLI issue.

**Comment by bunniiismiless** [comment]
> Not a CLI issue. Incorrect usage of the CLI.

Im not understanding im sorry did i type something wrong?
