### ISSUE TITLE
Blank custom apps pages

### ISSUE THREAD

**Issue by DarkArtz0** [spicetify/spicetify-cli#2021]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:11.99.878
- Spicetify version:2.14.2
```

### 📝 Description

The marketplace was working fine, i resetted my computer then when i installed spicetify the marketplace was blank. I installed marketplace again still the same issue

### 📸 Screenshots

![Spotify_Free 68dbf5fb-0c45-4735-837a-fa3da6a2908d              floppabest 🚬](https://user-images.githubusercontent.com/95894740/203490766-b1becbcd-d905-4207-94db-c836650df5d4.png)

**Comment by kyrie25** [comment]
This issue is not exclusive to Marketplace but to all custom apps, and it seems to happen on Spotify `1.1.99` exclusively.
