### ISSUE TITLE
Rainmeter crashes on startup

### ISSUE THREAD

**Issue by stevehoek** [spicetify/spicetify-cli#2023]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 
1.1.98
- Spicetify version:
2.14.3
```

### 📝 Description

Starting with Spicetify 2.14.2, after doing 'restore backup apply' Rainmeter is crashing, and when I restart it it crashes again until I reboot.
I've turned on logging in Rainmeter and it is not showing anything.

**Comment by kyrie25** [comment]
Spicetify is a Spotify client modifier, Rainmeter crashing has nothing to do with the CLI.
