### ISSUE TITLE
I can't install spicetify....HELP PLS

### ISSUE THREAD

**Issue by danielpro-rpi** [spicetify/spicetify-cli#2026]
### 🔍 Have you checked Spicetify.app page for your issue?

- [x] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Latest
- Spicetify version: Latest
```

### 📝 Description

I wanted to install Spicetify on my Linux PC, but

1. I couldn't install the Marketplace
2. I couldn't do spicetify apply.

If I did spicetify apply, it would give me this "error Cannot detect Spotify location. Please manually set "spotify_path" in config-xpui.ini" and theres no config-xpui.ini. PLS HELP

**Comment by danielpro-rpi** [comment]
Btw the part with no config-xpui.ini is done:)

**Comment by kyrie25** [comment]
Read the FAQ. Issues are not meant for support.

**Comment by danielpro-rpi** [comment]
sorry i read the faq but theres nothing

**Comment by danielpro-rpi** [comment]
and i forgot to click the checkmark

**Comment by kyrie25** [comment]
https://spicetify.app/docs/advanced-usage/installation#note-for-linux-users
https://spicetify.app/docs/faq#where-is-the-config-file
Again, issues are meant for bugs & feature requests, we will **not** be providing support here.
