### ISSUE TITLE
Set Provider

### ISSUE THREAD

**Issue by Flyingbacen** [spicetify/spicetify-cli#2028]
### 📝 Provide a description of the new feature

for lyrics-plus
add an option to look for lyrics from a song from a specific provider. It tends to like defaulting to netease, and, it's very inaccurate to the songs I listen to, and it makes it essentially unusable.

**Comment by kyrie25** [comment]
Open Lyrics Plus config and move the providers listing prioritizing from top to bottom. Or just untick NetEase.
![image](https://user-images.githubusercontent.com/77577746/204076828-8919274d-643e-4ad4-91d0-69519251aa27.png)
