### ISSUE TITLE
timeline isn't displayed correctly

### ISSUE THREAD

**Issue by Mikaks** [spicetify/spicetify-cli#2030]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: newest
- Spicetify version: newest
- Theme: Bloom
```

### 📝 Description

![image](https://user-images.githubusercontent.com/75081159/204093633-52b478fa-68b3-4b5f-8596-4e8b5464c73f.png)
timeline isn't displayed correctly

**Comment by kyrie25** [comment]
Not a CLI issue.
