### ISSUE TITLE
Lyrics-Plus with Romaji Conversion 

### ISSUE THREAD

**Issue by ItsPinkLasagna** [spicetify/spicetify-cli#2031]
### 📝 Provide a description of the new feature

Is there a way for the Romaji Conversion to work in Lyrics Plus?
I tried looking for a way to do it but my brain is tired of researching a way to do it

### ➕ Additional Information

The Conversion works in the normal Spotify API Lyrics, but when its on Lyrics Plus, It doesn't seem to work/

**Comment by kyrie25** [comment]
Extension developers will have to deal with this themselves, not a CLI issue.
