### ISSUE TITLE
Spicetify not working!!

### ISSUE THREAD

**Issue by brickyosu** [spicetify/spicetify-cli#2032]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [x] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows
1.1.99.878.g1e4ccc6e
- Spicetify version:v2.14.3
```

### 📝 Description

spotify still looks bland, and spicetify is not working and when i do commands it says that its the microsoft store version but i uninstalled the ms store edition and used the installer but it still says that im using ms store so can you help? also i dont know how to make a shortcut running "spicetify auto"

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/85379324/204705303-4e669362-92f7-4681-ac34-ae538ca7d9c5.png)

**Comment by brickyosu** [comment]
ive checked some of the older issues relating to ms store and spicetify not working (SOME of them)

**Comment by kyrie25** [comment]
Run `spicetify config-dir`, remove `config-xpui` and run `spicetify backup apply` again

**Comment by kyrie25** [comment]
Spotify appearances **will not** change even after Spicetify is applied, you will need to install extensions and themes by yourself.

**Comment by kyrie25** [comment]
Issues are not meant for support, refer to the website and/or the Discord server for help.

**Comment by Poopooracoocoo** [comment]
Btw @kyrie25 you should make a pinned and locked issue that says that! Might reduce the issues a bit. Thanks for your amazing work as always :)
