### ISSUE TITLE
Can't seek songs (automatically skips to the next)

### ISSUE THREAD

**Issue by philia1** [spicetify/spicetify-cli#2033]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.99.878.g1e4ccc6e
- Spicetify version: 2.14.3
```

### 📝 Description

The song that is currently playing gets skipped when I try to move the progress bar forward or backward. I have tried reinstalling both Spotify and Spicetify but it doesn't seem to work.

**Comment by kyrie25** [comment]
Spotify issue.
https://community.spotify.com/t5/Ongoing-Issues/Song-Podcast-skipping-when-clicking-sliding-the-progress-bar-in/idi-p/5461014
