### ISSUE TITLE
Extracting issue while backing up

### ISSUE THREAD

**Issue by ZohebMOPO** [spicetify/spicetify-cli#2036]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.84.716.gc5f8b819
- Spicetify version: 2.9.9
- Computer: PopOS on KDE Plasma
```

### 📝 Description

I installed the spicetify version which is compatible with my spotify version. But there seems to a problem of extracting.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/72716462/204986086-f0385fb8-c996-4b19-9d51-59f6e297edb6.png)

**Comment by kyrie25** [comment]
Outdated & unsupported Spotify and Spicetify version.
