### ISSUE TITLE
Please add a download button for playlists

### ISSUE THREAD

**Issue by monkeyop-0** [spicetify/spicetify-cli#2037]
### 📝 Provide a description of the new feature

The download button for playlist currently does not work.Pls add a feature which enables me to download playlists

**Comment by theRealPadster** [comment]
What do you mean it doesn't work? The built-in Spotify one probably just downloads the songs to your computer's Spotify cache so you can listen through Spotify in offline mode. It won't download files or anything.

**Comment by kyrie25** [comment]
Not a CLI issue. The CLI provides tools for modification, not modifying itself.
