### ISSUE TITLE
spotify not responding

### ISSUE THREAD

**Issue by glingus** [spicetify/spicetify-cli#2039]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: latest
- Spicetify version:latest
```

### 📝 Description

after a few days using spicetify spotify doesn't run anymore. i tried reinstalling it but it says "unable to insall spotify because the installating files are already used by another process.
i think the process is spicetify

sorry for bad english and thank you in adivice

**Comment by kyrie25** [comment]
Not a CLI issue. Spicetify does not run in the background.
