### ISSUE TITLE
Windows 10 Blue Screens

### ISSUE THREAD

**Issue by zerealone** [spicetify/spicetify-cli#2041]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Latest
- Spicetify version: Latest
```

### 📝 Description

When I tried to turn on my windows 10 pc a day after installing spicetify, many blue screens started appearing, with weird error codes. I used the pc for over a month, and needed to format it. From now I am afraid to download spicetify to the pc again if those blue screens will apear again. I have an error code I wrote down from the bluscreens, which was : "PAGE_FAULT_IN_NON_PAGED_AREA" .
I am just saying that the pc was brand new, and I downloaded only games and visual studio before installing spotify + spicetify.

### 📸 Screenshots

I did not captures the blue screens.

**Comment by ririxidev** [comment]
Not spicetify related, recommended to check `eventvwr` for more information what app causes that

**Comment by zerealone** [comment]
I checked it and it said something that starts with spicetify. It's not something related to the memory because the rams are fine.

**Comment by kyrie25** [comment]
Spicetify does not run in the background, nor run anywhere outside the terminal. It certainly could not have run then.
