### ISSUE TITLE
[UBUNTU] Romaji Extensions

### ISSUE THREAD

**Issue by AwanArdy** [spicetify/spicetify-cli#2046]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 
- Spicetify version:2.14.3
```

### 📝 Description

i have installed romaji extension but the lyrics is not change to romaji

### 📸 Screenshots

![Screenshot from 2022-12-07 18-19-30](https://user-images.githubusercontent.com/94277917/206155162-00def2e2-9248-47b7-bb2e-e935ee95b77d.png)

**Comment by kyrie25** [comment]
Not a CLI issue.
