### ISSUE TITLE
"Spiced Up" but still normal Spotify

### ISSUE THREAD

**Issue by SpRe3** [spicetify/spicetify-cli#2047]
### 🔍 Is there already an issue for your problem?

- [x] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.84.716.gc5f8b819
- Spicetify version:1.2.1
- Fedora 37 (Spotify Flatpak)
```

### 📝 Description

I do all the steps and the last "Spiced Up" notification comes. When I open Spotify it's still normal spotify

**Comment by theRealPadster** [comment]
Spicetify 1.2.1 is suuuuper old. Use 2.9.9 if you're using Spotify 1.1.84. If you update Spotify to 1.1.99, you can use the latest Spicetify (2.14.3).
