### ISSUE TITLE
"Spiced Up" but still Spotify (Spicetify 2.9.9) Fedora 37

### ISSUE THREAD

**Issue by SpRe3** [spicetify/spicetify-cli#2048]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.84
- Spicetify version: 2.9.9
```

### 📝 Description

I opened Issue but you said you are using an old version. I reinstalled with the new version but it didn't change. Even though I'm still getting the "Spiced Up" notification, Spotify is still normal Spotify

- Sorry for my bad English

**Comment by theRealPadster** [comment]
You ran `spicetify restore` and then `spicetify backup apply`?

**Comment by SpRe3** [comment]
> You ran `spicetify restore` and then `spicetify backup apply`?

Yep, still normal Spotify

**Comment by SpRe3** [comment]
> Spicetify does not change Spotify layout by default, you will have to install themes manually.

"Marketplace" button does not appear

**Comment by SpRe3** [comment]
> > > Spicetify does not change Spotify layout by default, you will have to install themes manually.
> > 
> > 
> > "Marketplace" button does not appear
> 
> Marketplace is also not part of Spicetify CLI.

Owh, oki thanks for help.

**Comment by theRealPadster** [comment]
If you'd like Marketplace, you'll need to install it. 
https://github.com/spicetify/spicetify-marketplace/wiki/Installation
