### ISSUE TITLE
I've got no idea what's going on.

### ISSUE THREAD

**Issue by Captain-Noob47** [spicetify/spicetify-cli#2049]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows 1.2.0.1165.gabf054ab
- Spicetify version: ...that's the problem.
```

### 📝 Description

I tried installing spicetify through powershell (copied the code under "Powershell pre-built binary), it keeps on giving an error which i absolutely can't figure out how to fix

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/105149569/206720752-8e90767e-2ecc-466c-8da4-bbae701dfbc3.png)

**Comment by kyrie25** [comment]
Connection/Network issue with GitHub, not a CLI issue.
Use a VPN or public DNS for the install script.
