### ISSUE TITLE
[keybaordShortcut.js] Global like shortcut?

### ISSUE THREAD

**Issue by karimawii** [spicetify/spicetify-cli#2050]
### 📝 Provide a description of the new feature

I really really need smth like that, I've always wanted to like songs without alt-tabbing, and do it from anywhere on the device, I tried using a third(or in that case fourth lmao)-party codes from GitHub that use python Spotify's API or written AHK to automate the clicks but those are just so unreliable, so please if it's possible to add, please add it, I need it so much, it'll help me focus on whatever I'm doing without getting distracted by all the alt-tabbing than just simply using a key combination and get a toast notification or a feedback of some sort.

**Comment by kyrie25** [comment]
Simply not possible as a Spicetify extension.
