### ISSUE TITLE
No playback icons on Taskbar window hover

### ISSUE THREAD

**Issue by ThunderE75** [spicetify/spicetify-cli#2051]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.0.1165.gabf054ab
- Spicetify version: v2.14.3
```

### 📝 Description

I can't see the playback icons on the window preview when i hover over a icon in the taskbar.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/74486623/206898555-275f0575-95fe-411f-8eca-48cd9e99c1ee.png)

**Comment by kyrie25** [comment]
Not a CLI issue.

**Comment by ThunderE75** [comment]
Sorry, but can you point me where i should report this issue? I thought this was the main repo for Spicetify so it would have been  the appropriate place.

**Comment by kyrie25** [comment]
> Sorry, but can you point me where i should report this issue? I thought this was the main repo for Spicetify so it would have been the appropriate place.

https://community.spotify.com/
This has to do with the Spotify client and the window manager.
