### ISSUE TITLE
[Shuffle+] Auto shuffle playlist option missing.

### ISSUE THREAD

**Issue by Archiekel** [spicetify/spicetify-cli#2052]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.0.1165.gabf054ab
- Spicetify version: 2.14.3
```

### 📝 Description

 In the spicetify  [github](https://user-images.githubusercontent.com/26436809/118361211-a4a2fc00-b5cd-11eb-9bf0-83c1b9b9d2c9.png) shows that Auto Shuffle was an drop down option on the menu, now all it has is this. 
![image](https://user-images.githubusercontent.com/54745717/207391593-e71b7d0a-da64-4190-ab85-ed3d6d27da77.png)

**Comment by kyrie25** [comment]
Shuffle+ was rewritten, and that feature was removed (for reasons I can't actually remember)
Docs will be updated soon.

**Comment by kyrie25** [comment]
#1921
