### ISSUE TITLE
Rename Item IO Error

### ISSUE THREAD

**Issue by KnightKing2179** [spicetify/spicetify-cli#2053]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:
- Spicetify version:
```

### 📝 Description

See the screenshot

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/92685947/207668401-682a98d7-b5b1-440b-a4fd-3490692a428c.png)

**Comment by theRealPadster** [comment]
It's because you've got a space in your username

**Comment by kyrie25** [comment]
Do not install Spicetify with administrator privileges.

**Comment by KnightKing2179** [comment]
> 

did that nothing happened

**Comment by KnightKing2179** [comment]
> It's maybe because you've got a space in your username

thats how it is
