### ISSUE TITLE
Playback Speed

### ISSUE THREAD

**Issue by thiagoeldp** [spicetify/spicetify-cli#2054]
### 📝 Provide a description of the new feature

It'd be cool to make an extension like this one: https://chrome.google.com/webstore/detail/spotify-playback-speed/bgehnoihoklmofgehcefiaicdcdgppck/related
It's only on  Spotify web, I don't know if it's posible besucase I don't know how to Code.
I know there's a feature on the desktop app that you can control the playback speed but it's only for podcast.

**Comment by kyrie25** [comment]
Not an issue. Give your extension suggestions as a Discussion or on the Discord server.
