### ISSUE TITLE
Cannot fetch latest release info

### ISSUE THREAD

**Issue by unoriginals** [spicetify/spicetify-cli#2056]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify Windows 1.2.0.1165
Spicetify v2.14.3
```

### 📝 Description

I'm trying to run the spicetify upgrade command but I keep getting an error saying something about API rate limit and I'm not sure what it's about. I don't use Github much so I know im not making requests to the API myself. I have recently uninstalled programs from my PC and I'm unsure if that has something to do with that since one of the programs was Git, might be others.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/25624971/208213293-f9238ff7-1dda-4935-a4e3-a38edf878f15.png)

**Comment by kyrie25** [comment]
That message is fetched directly from GitHub's response message and not a built-in Spicetify one, therefore it's a connection issue on your side and we can't really do anything about it.
Try using a VPN or a different DNS.
