### ISSUE TITLE
spicetify watch -a doesn't reload correctly on macOS

### ISSUE THREAD

**Issue by thewildtree** [spicetify/spicetify-cli#2059]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.0.1165.gabf054ab
- Spicetify version: v2.15.0
- macOS version: 13.1
```

### 📝 Description

On Windows, running `spicetify watch -a` and then `npm run build`ing was very handy and worked flawlessly.

Unfortunately, on macOS it just doesn't work most of the time. Spicetify will correctly notice that the custom app is updated (`success Spotify reloaded` is printed), but nothing happens to Spotify itself at all. Re-rerunning spicetify, rebuilding the app, force killing Spotify etc. does absolutely nothing once it breaks.

Worth noting is that this isn't consistent - after an OS restart it did work correctly for a while, but then just gave up at a random point in time.

I'm happy to help investigating this, but got no idea on how to start.

**Comment by jeroentvb** [comment]
I think this goes for all watch related flags. Noticed `spicetify watch -e` doesn't reload spotify either.
```
- MacOs 11.6.7
- Spicetify 2.15.0
- Spotify 1.2.0.1165
```
