### ISSUE TITLE
Lyrics Plus is Censoring lyrics.

### ISSUE THREAD

**Issue by Jeetylime** [spicetify/spicetify-cli#2062]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.84
- Spicetify version: v2 13.0
```

### 📝 Description

I installed Lyrics plus and when I go to lyrics on the right it censors curse words. How can I disable this?

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/92277537/209248559-2cabed44-adc9-45aa-891e-0ff05b8a1f0e.png)

**Comment by kyrie25** [comment]
This is directly from their API, we don't have control over this.
