### ISSUE TITLE
Unable to connect the remote server

### ISSUE THREAD

**Issue by KennyBerry** [spicetify/spicetify-cli#2065]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows
1.2.0.1165.gabf054ab
- Spicetify version:
```

### 📝 Description

iwr : Unable to connect to the remote server
At line:1 char:1
+ iwr -useb https://raw.githubusercontent.com/spicetify/spicetify-cli/m ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
    
    
    The solution in #418 doesnt work isnt working as well

**Comment by ririxidev** [comment]
Not related to spicetify. Issue is on your end (e.g. SSL certificates or old Powershell and so on...)

**Comment by oyeabhijit** [comment]
An average windows enjoyer doesn't know how to solve the issue on "our end". Please don't close an issue without providing a follow up solution.

I got this error:
![image](https://user-images.githubusercontent.com/67273840/211844621-0327834d-3c13-4c43-9d77-d159b4758893.png)

I checked my Powershell version, which gave me this:
![image](https://user-images.githubusercontent.com/67273840/211842978-3d7f7081-1c81-400c-b8d7-549ecc4eaa1b.png)

So, I updated my poweshell to latest version(as you said it could be for old Powershell):
![image](https://user-images.githubusercontent.com/67273840/211843079-2403dee4-3223-4894-88b2-e5678e9078c9.png)

And, after running the installation command for Spicetify, I got this:
![image](https://user-images.githubusercontent.com/67273840/211843259-8eb76013-5725-49b8-ac1d-bda3733f4797.png)

**Comment by kyrie25** [comment]
https://github.com/spicetify/spicetify-cli/issues/2072#issuecomment-1373722751

**Comment by ririxidev** [comment]
This issue is most likely an issue related to TLS/SSL. You can try forcing TLS 1.2 to see if that helps. NET Framework v4.5 uses TLS 1.0 by default which isn't supported by github anymore. NET Framework v4.7 uses TLS 1.2 by default so if you installed Powershell 7 you shouldn't have these issues.

```powershell
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
iwr -useb https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.ps1 | iex
```
