### ISSUE TITLE
Spicetify unable to work with newest version of Spotify?

### ISSUE THREAD

**Issue by ThisIsSesco** [spicetify/spicetify-cli#2070]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: v1.2.0
- Spicetify version: v2.12.0
```

### 📝 Description

Hello. I just recently downloaded Spicetify for my Windows PC, and after applying my changes I get a message from my Powershell that says "error: Spotify version mismatch with Spicetify. Spicetify currently only supports until Spotify v1.1.90"

Will there be an update coming soon to make sure there won't be a version mismatch? It would be appreciated.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/56412118/209507540-31d06be5-4671-4164-87b1-cedfd912aea8.png)

**Comment by kyrie25** [comment]
Latest Spicetify version is `2.15.0`
Latest Spotify version is `1.2.1`
