### ISSUE TITLE
Auto update Spicetify

### ISSUE THREAD

**Issue by FNDme** [spicetify/spicetify-cli#2071]
### 📝 Provide a description of the new feature

It would be awesome if **spicetify** would update automatically when you start windows / start spotify / there was an update.

### ➕ Additional Information

I've been a few months making use of a script that runs the update commands and have kept that script in the windows startup folder, but it would be great if this was implemented natively in the application itself.

```bash
#!\usr\bin\sh
spicetify upgrade
if [ $? -eq 0 ]; then
    spicetify restore backup apply --yes
    if [ $? -eq 0 ]; then
        echo "Spicetify has been successfully upgraded and restored"
    else
        echo "Spicetify has been successfully upgraded but failed to restore"
        return 1
    fi
else
    echo "Spicetify has failed to upgrade"
    return 1
fi
exit 0
```

**Comment by xerta555** [comment]
If this feature is added into Spicetify, it would be nice to to be able to enabling/disabling auto-updates, so typically adding 2 commands (exemple: spicetify config enable-spicetify-auto-update=1).
Bcz if the user run a specific version of Spicetify for any reason, the command will be usefull as a toggler.

Windows case:
Also about your script, you have install WSL to be able to run your shell script on your Windows host, so it will need to be adaptated in Windows syntax (Batch or Powershell).
And adding a little optional command to the script in the Spicetify installer to create the shortcut in `shell:startup` or in `shell:common startup`, i recommend the first one bcz it's the startup folder of the user session.

**Comment by ohitstom** [comment]
I'm sure many users wouldn't appreciate it needing to be run at startup or as a background task, and being an application that doesn't need administrative privileges this could be a restricting feature for some users.

though the option would indeed be pretty sweet, but I don't see a problem with users just setting up an nssm service or something

**Comment by rxri** [comment]
Please use `spicetify <cmds> --check-update` to update spicetify before launching any of provided commands, more explanation about why we did it this way is on #2227
