### ISSUE TITLE
Unable to install spicetify

### ISSUE THREAD

**Issue by theunsolvedguy** [spicetify/spicetify-cli#2072]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.0
- Spicetify version: v2.15
```

### 📝 Description

I was trying to install it through power shell but it kept showing this error

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/102846069/209686691-11db6ffd-c089-41ef-b6c8-7176a3a282ea.png)

**Comment by ririxidev** [comment]
Issue on GitHub end. Try again later

**Comment by theunsolvedguy** [comment]
Pardon me? So like should I try downloading it again later?

**Comment by R2-iDiot2** [comment]
still cannot download
same error still

image 1: on powershell 7
image 2: on regular powershell (i believe 5.1)
![image](https://user-images.githubusercontent.com/96367432/210741398-90f8499f-5a58-4d54-99e2-2350c8c23ca8.png)
![image](https://user-images.githubusercontent.com/96367432/210741450-c1a86a8f-48ea-411d-b154-bd335b2dd528.png)

**Comment by theunsolvedguy** [comment]
Try turning on a VPN and then try the same thing again.
