### ISSUE TITLE
Spicetify installed but no marketplace

### ISSUE THREAD

**Issue by KnightKing2179** [spicetify/spicetify-cli#2074]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 
- Spicetify version:2.15.0
```

### 📝 Description

![image](https://user-images.githubusercontent.com/92685947/209782679-c1a04924-d840-4fff-9d5b-946533c93a15.png)

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/92685947/209782830-9e52f843-a06b-4af1-8cfe-dfed2598b597.png)

**Comment by kyrie25** [comment]
Marketplace is not included in the CLI.

**Comment by KnightKing2179** [comment]
> 

how to fix that

**Comment by theRealPadster** [comment]
> how to fix that

Install it. 
https://github.com/spicetify/spicetify-marketplace
