### ISSUE TITLE
[Bug Report] Spicetify doesn't work on latest Spotify version

### ISSUE THREAD

**Issue by MatadorProBr** [spicetify/spicetify-cli#2079]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.2.582.gfae9c59b
- Spicetify version: 2.15.0
```

### 📝 Description

Seems that if you start Spotify with Spicetify in the 1.2.2.582.gfae9c59b (probably latest, I don't know) version, it starts normally but if you try to add some extension, it just breaks the app complety saying "Something went wrong".

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/71022656/210192170-a959c23f-d4be-4f62-9ee6-e50521883559.png)
> Translating gives to "Something went wrong"

**Comment by kyrie25** [comment]
Resolved via #2078, wait for a release.
