### ISSUE TITLE
Hide spicetify features in user.css

### ISSUE THREAD

**Issue by sun95n** [spicetify/spicetify-cli#2083]
### 📝 Provide a description of the new feature

Hi. I was wondering if there is a way to hide new features implemented by Spicetify (Your Episodes, Experimental Features and Sidebar config) in `user.css`

![001](https://user-images.githubusercontent.com/120290802/210682169-c3fb343e-dac1-49a0-b8ea-f33207a608f0.png) ![002](https://user-images.githubusercontent.com/120290802/210682188-7439079a-e0a3-4a3a-8335-107f7bfb1d31.png)

For `Your Episodes` I tried `Sidebar config > Hide` but noticed that it reappears if you clear the Spotify cache (`linux dir=$HOME/.cache/spotify`).

![003](https://user-images.githubusercontent.com/120290802/210682199-a0a5e8a4-426f-4b94-8676-7c3e1061f1bf.png)

**Comment by kyrie25** [comment]
Also please use Discussion for questions, this is not an issue.
