### ISSUE TITLE
Installment

### ISSUE THREAD

**Issue by eserkesar** [spicetify/spicetify-cli#2087]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Window 10 - 1.2.0.1165.gabf054ab
- Spicetify version: latest
```

### 📝 Description

Invoke-Expression : Exception calling "SetEnvironmentVariable" with "3" argument(s): "Requested registry access is not
allowed."
At line:9 char:117
+ ... ent.com/khanhas/spicetify-cli/master/install.ps1" | Invoke-Expression
+                                                         ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-Expression], MethodInvocationException
    + FullyQualifiedErrorId : SecurityException,Microsoft.PowerShell.Commands.InvokeExpressionCommand

iex : Exception calling "SetEnvironmentVariable" with "3" argument(s): "Requested registry access is not allowed."
At line:1 char:90
+ ... ithubusercontent.com/spicetify/spicetify-cli/master/install.ps1 | iex
+                                                                       ~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-Expression], MethodInvocationException
    + FullyQualifiedErrorId : SecurityException,Microsoft.PowerShell.Commands.InvokeExpressionCommand

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/62413671/211039766-df191cf5-eb3e-438d-9bc3-07d53fe6618a.png)

**Comment by kyrie25** [comment]
Limited user privileges, nothing to do with the installer itself.
If possible, install as an administrator
