### ISSUE TITLE
Spicetify wont install

### ISSUE THREAD

**Issue by PotatoBOBBY** [spicetify/spicetify-cli#2088]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 
- Spicetify version:v2.16.0
```

### 📝 Description

my spicetify wont install and says the following when i try installing it 

New-Object : Exception calling ".ctor" with "3" argument(s): "Central Directory corrupt."
At
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Archive\Microsoft.PowerShell.Archive.psm1:934
char:23
+ ... ipArchive = New-Object -TypeName System.IO.Compression.ZipArchive -Ar ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand
    
    
    
    
    
    does anyone mind helping i tried deleting the files in the file location said above but it won't let me delete them because of trustedinstaller

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/91748589/211166619-01daddf3-bd11-4f24-adde-34430e00ff26.png)

**Comment by kyrie25** [comment]
Install normally, don't use the cURL script

**Comment by PotatoBOBBY** [comment]
> Install normally, don't use the cURL script

i tried that and it still wont work
