### ISSUE TITLE
spicetify installing error

### ISSUE THREAD

**Issue by vignesh-1109** [spicetify/spicetify-cli#2089]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: v1.2.0.1165
- Spicetify version:v2.16.0
```

### 📝 Description

my spicetify is showing error when i am pasting the command on powershell

### 📸 Screenshots

![Capture](https://user-images.githubusercontent.com/122180402/211170513-ea0c2ea4-0b2b-4dba-b01e-e300fc13703e.PNG)

**Comment by kyrie25** [comment]
Duplicate of #2072
