### ISSUE TITLE
Default tab when clicking on "Your Library"

### ISSUE THREAD

**Issue by nekato** [spicetify/spicetify-cli#2090]
### 📝 Provide a description of the new feature

I want default tab to be Albums. Already had that modification in config-xpui, but forgot to backup. I know that I had to add something under [Patch], but I can't remember and find what was it.

**Comment by kyrie25** [comment]
Not a CLI issue.

**Comment by nekato** [comment]
Where can I find help for this?

**Comment by kyrie25** [comment]
> Where can I find help for this?

Use Discussions
