### ISSUE TITLE
Spicetify On Steam Deck.

### ISSUE THREAD

**Issue by creightonmcc** [spicetify/spicetify-cli#2095]
### 📝 Provide a description of the new feature

Does Spicetify work on the Steam Deck?

**Comment by kyrie25** [comment]
If it can run Spotify, the terminal and if you have root privileges (to `chmod` Spotify files), it can run Spicetify.

Please use Discussion for questions.

**Comment by Jackmeplay** [comment]
how do i install spicetify on steamdeck? when i try to download spicetify on the linus terminal it says i have to type my steamdecks password even though i turned it off. even if i try to type in the password it wont work
