### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by RazerFlick** [spicetify/spicetify-cli#2098]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.2.582.gfae9c59b
- Spicetify version: v2.16.0
```

### 📝 Description

Unable to install spicetify from powershell
Error while Unzipping and installing....
```
iex : Program 'spicetify.exe' failed to run: Access is deniedAt line:38 char:1
+ spicetify config custom_apps spicetify-marketplace-
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
At line:2 char:106
+ ... .com/spicetify/spicetify-marketplace/main/resources/install.ps1 | iex
+                                                                       ~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Invoke-Expression], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed,Microsoft.PowerShell.Commands.InvokeExpressionCommand
```

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/93324953/212305991-a4a353d7-6052-4c47-858f-812cbecce26e.png)

**Comment by kyrie25** [comment]
Not a CLI error.
Do not run as admin.

**Comment by RazerFlick** [comment]
> Not a CLI error. Do not run or install Spicetify as admin. Another possible problem is that for whatever reason Windows Defender might be blocking it, try whitelisting it as well.

how do i whitelist it

**Comment by RazerFlick** [comment]
![image_2023-01-13_170134526](https://user-images.githubusercontent.com/93324953/212310711-9efba1ff-c131-413c-a2b4-a63d36b4a0c4.png)

**Comment by kyrie25** [comment]
https://answers.microsoft.com/en-us/windows/forum/all/allowing-a-threat-in-windows-defender/20e415b2-6fbe-42dc-9e59-e10a8de81c4f

**Comment by RazerFlick** [comment]
still the error even after whitelisting spicetify.exe 
![image_2023-01-13_171605096](https://user-images.githubusercontent.com/93324953/212313210-0ee63432-7996-4e17-80f0-b17b7d4dcf7e.png)

**Comment by kyrie25** [comment]
Confirm that you have whitelisted it by taking a screenshot of allowed threats and current detected ones.

**Comment by RazerFlick** [comment]
nevermind it wasnt the windows firewall....it was blocked by windows security and now its working tysm
