### ISSUE TITLE
Spicetify auto skip song

### ISSUE THREAD

**Issue by Podkin21** [spicetify/spicetify-cli#2101]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Probably the last one
- Spicetify version: 2.16.0
```

### 📝 Description

Spicetify auto skip song when a song finish or when skipping one song (I tried with and whithout spicetify, and there is no bug without)

**Comment by kyrie25** [comment]
Duplicate of #2033
