### ISSUE TITLE
Styling of Bottom Padding of Background Color of Lyrics Plus

### ISSUE THREAD

**Issue by 4A9EBB44** [spicetify/spicetify-cli#2103]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.0.1165.gabf054ab (Apple Silicon)
- Spicetify version: v2.16.0
 - Custom apps: new-releases, lyrics-plus
```

### 📝 Description

Seems someone touched the bottom padding(just guessing, havnot look up the code) of the background color of Lyrics Plus.

### 📸 Screenshots

<img width="1916" alt="image" src="https://user-images.githubusercontent.com/33310255/212496267-4757b6c3-d405-4e2d-a910-dc9e6202d8ce.png">

**Comment by ohitstom** [comment]
Line 579 in `spicetify-routes-lyrics-plus.css`

`.lyrics-config-button-container`
```
margin: -40px 0 0;
>>
margin: -5vh 0 0;
```
