### ISSUE TITLE
Lyrics not being shown in FullScreen

### ISSUE THREAD

**Issue by vandan404** [spicetify/spicetify-cli#2110]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.99.878.g1e4ccc6e
- Spicetify version: 2.16.0
```

### 📝 Description

fullscreen plugin doesnt show lyrics when switched to fullscreen

### 📸 Screenshots

![213510924-a862a1f8-25ab-4879-996b-b47097d72078](https://user-images.githubusercontent.com/71869160/213511271-20b538ed-0f16-4c4f-93ba-ec36949eaaaf.png)

**Comment by vandan404** [comment]
what might be the issue?

**Comment by kyrie25** [comment]
> what might be the issue?

I'm assuming you haven't applied Lyrics Plus. If you have then I have no clue, might want to forward this to the extension developer themselves as we don't maintain this.
