### ISSUE TITLE
"Something went wrong" error after latest Spotify Update

### ISSUE THREAD

**Issue by TeknoSenpai** [spicetify/spicetify-cli#2111]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.3.1115.gd61a8f5c
- Spicetify version: v2.14.3
- OS: Windows 10 Pro for Workstations
- Theme: Blossom / Color Scheme: Dark
```

### 📝 Description

Applying with command `spicetify backup apply` completely breaks Spotify.
This happened, too, with Spotify version `1.2.2.582.gfae9c59b`

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/74503731/213513213-b56d3343-1910-45c1-a112-39d0d379abec.png)

**Comment by theRealPadster** [comment]
Might I suggest updating your spicetify?

**Comment by TeknoSenpai** [comment]
> Might I suggest updating your spicetify?

Will do

**Comment by TeknoSenpai** [comment]
Updating fixed the issue.
Sorry for the inconvenience, thanks @theRealPadster
