### ISSUE TITLE
Can't open liked song

### ISSUE THREAD

**Issue by syunohito** [spicetify/spicetify-cli#2116]
### 🔍 Have you checked Spicetify.app page for your issue?

- [x] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1-1-88-612
- Spicetify version: 2.16.0
```

### 📝 Description

When I try to open my liked songs, I get an error message. spotify cannot be updated because if I update spotify, various plugins will not work, sorry!

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/72976164/213867605-5e9662a7-1181-486c-8ca5-0063152ffc15.png)

**Comment by kyrie25** [comment]
Unsupported Spotify version.
