### ISSUE TITLE
Theme "marketplace" not found

### ISSUE THREAD

**Issue by andrermat** [spicetify/spicetify-cli#2117]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:1.2.3.1115.gd61a8f5c 
- Spicetify version: spicetify v1.2.1
```

### 📝 Description

After running both powershell commands in getting started, I run spicetify apply and it says "error Theme "marketplace" not found" and when I open spotify there is no marketplace

### 📸 Screenshots

![WhatsApp Image 2023-01-23 at 01 02 33](https://user-images.githubusercontent.com/72992532/213950575-802164db-36cc-465b-bf18-72a35313d3d2.jpeg)
![WhatsApp Image 2023-01-23 at 01 04 18](https://user-images.githubusercontent.com/72992532/213950668-5660b6bb-60c7-483d-add4-aa1e059af354.jpeg)
![WhatsApp Image 2023-01-23 at 01 06 14](https://user-images.githubusercontent.com/72992532/213950783-4ac8b3ef-9273-4ebd-92e3-f731ae343e22.jpeg)

**Comment by kyrie25** [comment]
Not a CLI issue.

**Comment by andrermat** [comment]
Then what's the issue?
