### ISSUE TITLE
right click on mic "popuplyrics"

### ISSUE THREAD

**Issue by chinwiabdellkabir** [spicetify/spicetify-cli#2123]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Ubuntu 20.04
- Spotify version: 1.1.84.716.gc5f8b819
- Spicetify version: 2.16.0
```

### 📝 Description

right click not working as if the extension not applied

**Comment by kyrie25** [comment]
Unsupported Spotify version.

If the extension *is* applied, the top bar will have the icon. If it isn't then it wouldn't, there's no where in between.
