### ISSUE TITLE
spotify  auto updates

### ISSUE THREAD

**Issue by amralfy1** [spicetify/spicetify-cli#2124]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.80.699.gc3dac750
- Spicetify version:
```

### 📝 Description

spotify updates remove spicetify extension and i cant disable auto update

**Comment by kyrie25** [comment]
Not a CLI issue.
