### ISSUE TITLE
error on linux ubuntu 22.4.1

### ISSUE THREAD

**Issue by JoseMVZ** [spicetify/spicetify-cli#2126]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: last version
- Spicetify version: last version
- System: Linux Ubuntu 22.04.1 LTS
```

### 📝 Description

I tried to install spicetify in all ways from the repository or from the terminal but in any of the 2 it gives me this error :( 

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/107633066/215232345-7ad9dda6-b131-47d0-af71-d8b4450e1197.png)

**Comment by AlessandroPerazzetta** [comment]
Seems that install script fail downloadin latest release number.

In https://github.com/spicetify/spicetify-cli/blob/master/install.sh at line 33 try to change from:

tag=$(curl -LsH 'Accept: application/json' $releases_uri/latest)

to:

tag=$(curl -I $releases_uri/latest | awk -F '/' '/^location/ {print  substr($NF, 1, length($NF)-1)})


Also on marketplace install script.

Probably need a pull request if confirmed

**Comment by CreepTron365** [comment]
It's also happening on MacOS, i've made a pull request on #2127 that solves the issue.

**Comment by rxri** [comment]
Issue on GitHub end. Script has nothing to do with it

**Comment by rxri** [comment]
Script has been tested and works just fine. Most likely it is an issue on GitHub end
