### ISSUE TITLE
Spicetify not working

### ISSUE THREAD

**Issue by SacredDorito1** [spicetify/spicetify-cli#2131]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.3.1115.gd61a8f5c
- Spicetify version: 2.16.0
```

### 📝 Description

Everytime I try to start up Spicetify, it doesn't work. I have tried reinstalling it, I've tried -spicetify restart, -spicetify auto. I have tried everything I can think of. Please help, these ads are killing me.

**Comment by kyrie25** [comment]
Spicetify does not block ads by default. If you see Marketplace on the sidebar, you can install the community-made Adblocker extension there.

**Comment by SacredDorito1** [comment]
> Spicetify does not block ads, or change any behavior by default. If you see Marketplace on the sidebar, you can install the community-made Adblocker extension there.

my spicetify doesn't work

**Comment by fowlis** [comment]
> my spicetify doesn't work

Are you sure its just not doing what you're expecting it to do by default when you install it?
