### ISSUE TITLE
Breaks Spotify upon `spicetify apply`

### ISSUE THREAD

**Issue by Korozin** [spicetify/spicetify-cli#2132]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.84.716.gc5f8b819
- Spicetify version: 2.16.0
- Operating system: Lubuntu / LXDE Ubuntu
```

### 📝 Description

Downloaded the official .deb from Spotify's website and guide on the spicetify website using

```cmd
curl -sS https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg | sudo apt-key add -
echo "deb http://repository.spotify.com stable non-free" | sudo tee /etc/apt/sources.list.d/spotify.list
sudo apt-get update && sudo apt-get install spotify-client
```

Works fine on it's own which is to be expected. Fast forward a bit and I installed `spicetify-cli` and the `spicetify-marketplace` via the commands below.

```cmd
curl -fsSL https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.sh | sh
curl -fsSL https://raw.githubusercontent.com/spicetify/spicetify-marketplace/main/resources/install.sh | sh
```

Set up both the `spotify_path` and `prefs_path` correctly using `/usr/share/spotify/` and `/home/placeholder/.config/spotify/prefs`. Backed up Spotify just in case, and proceeded to use `spicetify apply` to "Spice up Spotify". But upon loading the Spotify Launcher now it returns with a completely empty window. Thought it may be due to the theme, so I both tried disabling the Theme, then tried using a new one both with `colors.ini` and `user.css` to see if that solved anything- which It did not. I also tried doing it via flatpak, with no change since it produced the same results.

I was browsing a lot of the closed issues to see if there were any definitive fixes for this, but as far as I saw it was pretty inconclusive. If I'm wrong and just missed the solution then feel free to direct me there and close the issue. Otherwise, any idea what I can do? Or should I just move on and use as stock.

#### Picture Example

![2023-01-30_16-21](https://user-images.githubusercontent.com/90534409/215597875-96c9b437-012d-434e-8724-3545d349eb04.png)

**Comment by Korozin** [comment]
Ah, I was thinking it was something with the Spotify version. I hadn't looked to closely at the version requirements but assumed it would work to some extent using the most recent version in the repos, but I guess not.

When it comes to installing other versions of spicetify, is there a place where you can actively pull from to get them? Because, albeit it's my own fault, I really didn't look too into depth at other versions.

As for the OS, I'm using Lubuntu which is an LXDE / LXQT Version of Ubuntu, so I'm pretty sure `spotify-edge` won't be available. Thank you for your time.

**Comment by theRealPadster** [comment]
No problem. Spotify doesn't really maintain the Linux version very well, since it's technically not officially supported in the same way, and it's chronically far behind the Windows and macOS ones. 

From the [download page](https://www.spotify.com/ca-en/download/linux/)
> Here you can find different ways of installing Spotify for Linux. Spotify for Linux is a labor of love from our engineers that wanted to listen to Spotify on their Linux development machines. They work on it in their spare time and it is currently not a platform that we actively support. The experience may differ from our other Spotify Desktop clients, such as Windows and Mac. You can tell us what you think and ask other users for help at the

They seem to publish releases to the Snap store before anything else, but Snap packages are essentially immutable, so you can't use spicetify with the Snap version. The `spotify-edge` aur package just downloads and repackages the snap into an arch package. I'm sure it's possible to write a script to generate a .dev package from it, but as far as I know, nobody has made one. 

You can download an older spicetify binary from the [past releases](https://github.com/spicetify/spicetify-cli/releases). Just manually run the `spicetify` binary from the zip, or replace the one that the installer made.

**Comment by Korozin** [comment]
Many thanks! You can go ahead and close the issue for now as that will more than likely resolve the issue. If I encounter anything else I'll comment, but otherwise it seems resolved.

**Comment by Korozin** [comment]
Just to clarify, since the version I'm using is - `1.1.84.716.gc5f8b819` / `1.1.84`, and after searching the release pages spicetify version `2.9.8` should work as it says it supports `1.1.84`? Just wanting to be extra sure since after restoring the Spotify backup and then deleting the `2.16.0` version and trying with  `2.9.8` it still has the same issue.

Should I try other versions or is there something I've done wrong / am unaware of.

**Comment by Korozin** [comment]
Alright, I finally got it to work. The cause is kind of embarrassing, and it was because I made `spicetify` a global command and forgot to remove it's contents from  `/usr/bin` as well when I replaced versions.

`2.9.9` works perfectly, so issue resolved.
