### ISSUE TITLE
Show liked songs in Recommended

### ISSUE THREAD

**Issue by DEVolkan** [spicetify/spicetify-cli#2133]
### 📝 Provide a description of the new feature

The "Recommended" section at the end of a playlist is supposed to suggest new songs based on your existing playlist. Unfortunately, the songs that show up as "new" are often the same songs and you have to click on refresh multiple times to find truly new songs. To determine if a song is new or not, you have to click on it and see if you have liked it before. The only way to keep track of which songs you have listened to is by downloading them, which adds a download symbol under the song name.

### ➕ Additional Information

![liked in recomanded](https://user-images.githubusercontent.com/12856032/216460688-253bd5c4-abf3-4ced-aa77-99cc232d95d8.PNG)

**Comment by kyrie25** [comment]
Extension requests should go to Discussion.
