### ISSUE TITLE
Sorting for liked songs in playlist

### ISSUE THREAD

**Issue by DEVolkan** [spicetify/spicetify-cli#2134]
### 📝 Provide a description of the new feature

Please add an option for sorting liked songs in a playlist. One can sort for title, album, duration and date added, but not for which songs are liked.  

### ➕ Additional Information

![Sort liked songs](https://user-images.githubusercontent.com/12856032/216461994-c3cc388e-3809-4453-a81b-0e2ef4e0a347.png)

**Comment by kyrie25** [comment]
Extension requests should go to Discussion.

**Comment by DEVolkan** [comment]
> Extension requests should go to Discussion.

Which discussion you're talking about? Did you set up GitHub discussion, because I don't see it? Or do you mean discord?

**Comment by kyrie25** [comment]
> > Extension requests should go to Discussion.
> 
> 
> 
> Which discussion you're talking about? Did you set up GitHub discussion, because I don't see it? Or do you mean discord?

Discord yeah. Either way the CLI isn't meant for this.
