### ISSUE TITLE
Spotify pages do not load after applying Spicetify

### ISSUE THREAD

**Issue by petercel** [spicetify/spicetify-cli#2135]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows
1.2.3.1115.gd61a8f5c
- Spicetify version: 2.15.0
```

### 📝 Description

I recently re-applied Spicetify using the instructions given in the FAQ, and now nothing on Spotify (with Spicetify installed/applied) will load. I am unsure what caused this issue in the first place, but I know this is specifically a Spicetify issue as after trying my backup (so no Spicetify) it loads fine. How can I get it to load like normal?

**Comment by kyrie25** [comment]
Upgrade Spicetify.
