### ISSUE TITLE
Spicetify marketplace command getting picked up as a virus

### ISSUE THREAD

**Issue by Vergepoland** [spicetify/spicetify-cli#2137]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: whatever the latest one is
- Spicetify version: 2.16.1
- Windows: 11 22H2
```

### 📝 Description

for some apparent reason, if i try putting in the command `iwr -useb https://raw.githubusercontent.com/spicetify/spicetify-marketplace/main/resources/install.ps1 | iex` Norton will just pick it up as a virus and delete it but i have installed it fine in the past. 

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/100927153/216683328-9c259247-0bb2-41fe-a215-f307d5428684.png)
![image](https://user-images.githubusercontent.com/100927153/216683945-ec14f90e-047c-4147-8d6b-054435a6837d.png)

**Comment by theRealPadster** [comment]
Nothing we can do about that. You'll have to disable it or add an exception or something.

**Comment by rxri** [comment]
False positive. Not related to cli
