### ISSUE TITLE
Error: no such host

### ISSUE THREAD

**Issue by Nerxxy** [spicetify/spicetify-cli#2138]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.4.912.g949d5fd0
- Spicetify version:
```

### 📝 Description

when trying to upgrade spicetify i get this error as seen in the picture

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/37718547/216777784-a550330e-9c91-4b43-a604-d052eb585f51.png)

**Comment by theRealPadster** [comment]
Looks like your internet isn't able to resolve github api for some reason. It's either having issues or blocked or something. Maybe try a vpn or alternative dns, like 8.8.8.8

**Comment by Nerxxy** [comment]
I have resolved the issue, my DNS was set to something that i didnt put. has been fixed now :)
