### ISSUE TITLE
Spicetify 2.9.9 not working with Spotify 1.1.84.716.gc5f8b819

### ISSUE THREAD

**Issue by rafiazman** [spicetify/spicetify-cli#2139]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.84.716.gc5f8b819
- Spicetify version: 2.9.9
```

### 📝 Description

Hello, I have installed Spotify via Flatpak and seem to have issues getting spicetify to work with it. I have downloaded the .tar.gz for v2.9.9 and extracted it to `~/.spicetify` and ran the spicetify-marketplace installation script. Then I executed `spicetify backup apply`:

```sh
deck@steamdeck ~)$ spicetify backup apply
spicetify v2.9.9
info There is available backup.
info Clear current backup:
success Backup is cleared.
Backing up app files:
OK
Extracting:
OK
Preprocessing:
info Fetching remote CSS map for newer compatible tag version: v2.9.9
OK
OK
success Everything is ready, you can start applying now!
Copying raw assets:
OK
Overwriting themed assets:
OK
Transferring user.css:
OK
Applying additional modifications:
OK
Transferring custom apps:
OK
success Spotify is spiced up!

```

Trying to access the Marketplace inside Spotify however shows the Something went wrong error message with the Reload Page button. Is 2.9.9 broken with 1.1.84.716?

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/7603038/216959456-064ebc70-9381-49aa-9382-9de4ac56b218.png)

**Comment by kyrie25** [comment]
Issues are not support pages.

Spotify versions lower than listed on release pages are no longer supported, so as other components of Spicetify, such as Marketplace.

**Comment by theRealPadster** [comment]
Are you able to update to Spotify 1.1.99? [AUR](https://aur.archlinux.org/packages/spotify-edge) package here, not sure about other distros.

**Comment by rafiazman** [comment]
> Are you able to update to Spotify 1.1.99? [AUR](https://aur.archlinux.org/packages/spotify-edge) package here, not sure about other distros.

I'm using SteamOS so I'm not able to do this without breaking the immutability of the OS (which I would rather keep). I appreciate the assistance though.
