### ISSUE TITLE
Show Release Date below album cover

### ISSUE THREAD

**Issue by baszero** [spicetify/spicetify-cli#2140]
### 📝 Provide a description of the new feature

On the bottom left where the cover is shown, Track title and artists, I'd like to see the release date. 
It's annoying always to navigate to the album view in order to see it.
Can somebody make a little addon? :)

**Comment by kyrie25** [comment]
Make a suggestion on the Discord server.

Issues are meant for bug or CLI requests only.

**Comment by baszero** [comment]
I don't find the server nor an invite page. Where?
