### ISSUE TITLE
Lyrics Button Missing

### ISSUE THREAD

**Issue by chikobara** [spicetify/spicetify-cli#2141]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.84.716.gc5f8b819
- Spicetify version: 2.16.1
```

### 📝 Description

After I installed Spicetify I noticed that lyrics button is missing.
I searched the closed and opened issues i found that maybe it will be on top bar 
but there is nothing as shown in this screenshot.

### 📸 Screenshots

![Screenshot from 2023-02-017 14-47-52](https://user-images.githubusercontent.com/29534140/217237706-93faa1a1-12a6-4a27-9f7a-74863936748f.png)

**Comment by kyrie25** [comment]
Not a CLI issue.
Song may not have lyrics or theme issue, CLI does not disable any stock features by default.

**Comment by chikobara** [comment]
no, I tried other songs, still lyrics button not appearing . :

**Comment by chikobara** [comment]
> Not a CLI issue & unsupported Spotify version. Song may not have lyrics or theme issue, CLI does not disable any stock features by default.


no, I tried other songs, still lyrics button not appearing . :
