### ISSUE TITLE
Spotify 1.2.4.912 breaks with experimental features enabled

### ISSUE THREAD

**Issue by ImCheesecake** [spicetify/spicetify-cli#2143]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.4.912.g949d5fd0
- Spicetify version: v2.16.1
```

### 📝 Description

It looks like the latest Spotify update comes with some UI breaking changes if you have the **new home** experimental feature enabled

### 📸 Screenshots

With new home: 
![image](https://user-images.githubusercontent.com/43030367/217510635-59d3266e-7e19-4d53-bfc3-28cfd5ab95fe.png)
![image](https://user-images.githubusercontent.com/43030367/217510700-6e0885cc-b1d1-424f-a63d-d92d500750fa.png)

Without new home:
![image](https://user-images.githubusercontent.com/43030367/217511238-81bec1f8-1bcd-4506-91a1-fdbe85d22c77.png)
![image](https://user-images.githubusercontent.com/43030367/217511271-af9db6d1-cb5e-4497-8e2a-baeb798dc389.png)

**Comment by kyrie25** [comment]
Experimental Features are exposed internal Spotify features.
We simply provide the "on/off" switch for those and such we won't be fixing their mistakes lol.
