### ISSUE TITLE
bookmark.js extension and New Releases app stopped working

### ISSUE THREAD

**Issue by 840r4uwjefi98g0iekopf** [spicetify/spicetify-cli#2144]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.4.912.g949d5fd0
- Spicetify version: v2.16.0

MacOS Ventura 13.1
```

### 📝 Description

I don't know if this happened after I updated Spotify or after I updated Spicetify, but I noticed that the bookmark.js extension icon at the top of the app disappeared. The other extensions are still there and working.
I reinstalled Spotify, Spicetify, and the bookmark.js extension but nothing changed.
I didn't make any other changes that I know of to Spotify or Spicetify.
Edit: I should also add. The New Releases app is also not working, although the app appears on the sidebar. When I open the app, the screen shows "Something went wrong"
I also use the Spicetify Marketplace app and the extensions I download through there still work.

**Comment by kyrie25** [comment]
Outdated Spicetify version.
Upgrade Spicetify and run `spicetify restore backup apply`.

**Comment by 840r4uwjefi98g0iekopf** [comment]
I'm dumb, I thought that was the latest version for some reason and reinstalled it. Thanks!
