### ISSUE TITLE
BadRequestError status code 400

### ISSUE THREAD

**Issue by pxeno** [spicetify/spicetify-cli#2148]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.4.912.g949d5fd0
- Spicetify version:v2.16.1
```

### 📝 Description

Problem when trying to use shuffle+ through any channel (playlist, album, artist page)

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/125214257/218332955-3f1ac4e6-5b64-444c-beb0-8a30ea266f8e.png)
![image](https://user-images.githubusercontent.com/125214257/218332972-10e79f06-a05f-4c95-b8ed-d2e3cb70dcd7.png)

**Comment by kyrie25** [comment]
Run `spicetify restore backup apply` to actually apply patches from the latest version.
