### ISSUE TITLE
Enhance button goes missing after applying spicetify, doesn't come back even after uninstalling spicetify.

### ISSUE THREAD

**Issue by LordKaos39** [spicetify/spicetify-cli#2155]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.4.912 Desktop version
- Spicetify version: 2.16.1
```

### 📝 Description

After installing spicetify and running spicetify apply, the enhance button goes missing. Even after uninstalling spicetify the button doesn't reappear. Only a clean reinstall helps.

**Comment by kyrie25** [comment]
Enhance feature can be enabled/disabled via Experimental Features.
