### ISSUE TITLE
Custom App - New Releases - Something went wrong

### ISSUE THREAD

**Issue by guttitto** [spicetify/spicetify-cli#2156]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.4.912.g949d5fd0 (Windows 11)
- Spicetify version: Spicetify v2.16.1
```

### 📝 Description

After I click on New Releases, it says it is fetching the artists, but after some seconds it says something went wrong.

**Comment by kyrie25** [comment]
`spicetify restore backup apply`

**Comment by RWCoding58** [comment]
I've also been experiencing this for more than a week (I've also mentioned it in the Discord server, but I'm still waiting for a reply). I can confirm that the problem still occurs when removing all the themes, extensions and custom apps besides New Releases.

**Comment by kyrie25** [comment]
To confirm this is actually an issue, provide screenshots of the console errors:
1. Run `spicetify enable-devtools`
2. Open New Releases
3. Press `Ctrl + Shift + I` or right-click on the client until you see a menu that lists `Show DevTools`
4. Go to the `Console` tab and take screenshots of all errors in the console

**Comment by RWCoding58** [comment]
> 

Here's what I've gotten
<img width="1680" alt="Screenshot 2023-02-17 at 17 54 10" src="https://user-images.githubusercontent.com/87898490/219612024-04dfc128-4cf1-4d0b-be4f-f3fe655bb7af.png">

**Comment by kyrie25** [comment]
Yeah, this is what I meant when I said this issue has been resolved via `2.16.1` (#2129):
![image](https://user-images.githubusercontent.com/77577746/219615975-2d4d090b-d6c5-4e7f-811e-f22560018d2f.png)

A clean reinstall would resolve the issue:
1. Run `spicetify restore`
2. Remove everything under `%appdata%/spicetify` and `%localappdata%/spicetify`
3. Run the install scripts from the website.

**Comment by RWCoding58** [comment]
It seems like editing Card.js to reflect the changes and running `spicetify restore backup apply` is enough to fix the issue; no need for a clean install. Strange how my file was still using the old version even though I'm using version 2.16.1, but anyways it works now. I'm going to mention this in the Discord forum now. Thanks!

**Comment by kyrie25** [comment]
> It seems like editing Card.js to reflect the changes and running `spicetify restore backup apply` is enough to fix the issue; no need for a clean install.

The person who made this issue also had issues with the old version of Reddit and seems to be using a custom version of it also, so it's better to be safe than sorry.

**Comment by guttitto** [comment]
> 2. Remove everything under `%appdata%/spicetify` and `%localappdata%/spicetify`

Thanks, the problem was that I had only removed the files from AppData/Local and not from AppData/Roaming.
