### ISSUE TITLE
Custom App - Reddit - Loading indefinitely

### ISSUE THREAD

**Issue by guttitto** [spicetify/spicetify-cli#2157]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.4.912.g949d5fd0 (Windows 11)
- Spicetify version: Spicetify v2.16.1
```

### 📝 Description

I tried with all default subreddits, they are simply loading indefinitely, no release shows up.

**Comment by kyrie25** [comment]
#2156

**Comment by guttitto** [comment]
@kyrie25 I already tried that, didn't work.

**Comment by guttitto** [comment]
Ok sorry, I wasn't in the latest version of Spotify. But now I updated and I continue with the same issues for both custom apps
![image](https://user-images.githubusercontent.com/25709670/219414736-230a18a5-8798-42b8-9e34-6e92c91c05bf.png)

**Comment by kyrie25** [comment]
1. Remove the "latest" custom app files you have downloaded
2. Reinstall Spicetify using the guide on the website.

**Comment by guttitto** [comment]
I just did that, I also reinstalled Spotify itself, the same issues continue. Weird that both issues were closed before any discussion...
Are your Reddit and New Releases custom apps working fine?

**Comment by kyrie25** [comment]
> Are your Reddit and New Releases custom apps working fine?

Yes, same as anyone else. `2.16.1` was specifically made to fix that bug.
