### ISSUE TITLE
Lyrics Plus problem

### ISSUE THREAD

**Issue by todayisyokult** [spicetify/spicetify-cli#2158]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify Windows 版 1.2.4.912.g949d5fd0
- Spicetify version:v2.16.1
```

### 📝 Description

When I load local lyrics in Lyrics Plus, close the software and open it again, the local lyrics loaded by the software are not displayed

**Comment by kyrie25** [comment]
Made by design, not a bug.

Local lyrics will be stored within a session and only used then, since it is much easier for the user to load local lyrics than switch from local to remote.

**Comment by todayisyokult** [comment]
ok, so every time i restart the software, i can only manually load the local lyrics again to correct the wrong lyrics?

**Comment by kyrie25** [comment]
Pretty much.

**Comment by todayisyokult** [comment]
It's a pity that the local upload function is really useful, but this is equivalent to losing the role it needs to play。
Thank you for your reply, looking forward to more features coming online
