### ISSUE TITLE
i tried to install spicetify in my windows laptop (not the microsoft version) i am sure it is a web version but it show the error in the powershell 

### ISSUE THREAD

**Issue by OGVedu** [spicetify/spicetify-cli#2164]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 
- Spicetify version:
```

### 📝 Description

Error keeps coming up i am not sure why! please help

### 📸 Screenshots

![Untitled](https://user-images.githubusercontent.com/98245375/219962567-2f03bc6d-1f11-4fb0-8fef-6a53a5bf00bc.png)

**Comment by rxri** [comment]
Don't use powershell as administrator, also it could be an issue on GitHub end. You could also try using winget - `winget install Spicetify.Spicetify` if you have it installed
