### ISSUE TITLE
Lyrics can't do Karaoke mode and this logo appears (._.)

### ISSUE THREAD

**Issue by pinglingalvin** [spicetify/spicetify-cli#2167]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.5.1006.g22820f93
- Spicetify version:2.16.1
```

### 📝 Description

PI just installing update for spotify and spicetify latest version, and i want to use karaoke mode from the lyrics plus and still i can't using the karaoke mode for music and it work for few music only.  and only (._.) this logo just showed*

### 📸 Screenshots

![Screenshot (374)](https://user-images.githubusercontent.com/120280602/220045792-6effe834-2ad2-48ed-8700-79097a01475b.png)

**Comment by kyrie25** [comment]
Karaoke mode depends on if whether the provider has the Karaoke/Advanced Lyrics version or not.

This is not a bug and some songs still indeed have Karaoke lyrics.

**Comment by pinglingalvin** [comment]
> Karaoke mode depends on if whether the provider has the Karaoke/Advanced Lyrics version or not.
> 
> This is not a bug and some songs still indeed have Karaoke lyrics

i just look in this tutorial video, for the song in this video played is same song i played on the screenshot, so it's kinda weird 
https://www.youtube.com/watch?v=sjh80AanWFs

**Comment by pinglingalvin** [comment]
> > Karaoke mode depends on if whether the provider has the Karaoke/Advanced Lyrics version or not.
> > This is not a bug and some songs still indeed have Karaoke lyrics
> 
> i just look in this tutorial video, for the song in this video played is same song i played on the screenshot, so it's kinda weird https://www.youtube.com/watch?v=sjh80AanWFs

in this video has karaoke mode and it worked, and i played same song and it didn't work for karaoke

**Comment by kyrie25** [comment]
Karaoke lyrics are mainly based on Netease, and is purely community-maintained.
It could have been removed or moved elsewhere, or Spotify internally has several versions of the song in different URIs, etc.
Nonetheless, the mode has been proven to work on multiple songs and unless the Lyrics Plus tab crashed entirely, the Karaoke version was not found.
