### ISSUE TITLE
Spicetify.PopupModal.display() reads variable "content" rather than the one passed

### ISSUE THREAD

**Issue by LucyUwI** [spicetify/spicetify-cli#2169]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.5.1006
- Spicetify version: 2.16.1
```

### 📝 Description

Calling the function 
`Spicetify.PopupModal.display()`
Reads from the global variable `content` rather than the variable passed through the function. 

### 📸 Screenshots

https://user-images.githubusercontent.com/73023435/221041682-4510ebea-3e4d-420a-863c-8cab6bca4961.MOV

https://user-images.githubusercontent.com/73023435/221041692-885ac765-2324-4b3e-8685-b8155c6aea13.MOV

**Comment by kyrie25** [comment]
This is how JavaScript works, not a bug.

![image](https://user-images.githubusercontent.com/77577746/221071810-a13fd358-321f-499b-9f11-3c664669b028.jpeg)
