### ISSUE TITLE
Lyrics overlapped when length is too long

### ISSUE THREAD

**Issue by comcomson** [spicetify/spicetify-cli#2172]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows 1.2.5.1006.g22820f93
- Spicetify version: Spicetify v2.16.1
```

### 📝 Description

When lyric is at the same sentence is too long and jumps to next line, both line will overlap.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/51400316/221404088-b279014c-5012-40a7-9a9c-7eace5d7d908.png)

**Comment by kyrie25** [comment]
Unable to replicate, theme issue.
![image](https://user-images.githubusercontent.com/77577746/221412191-32968136-e26f-4bad-ae6d-f419a82c960a.png)

**Comment by comcomson** [comment]
Solved issue by adding custom css to change the font-size to 0.05em, also added line-height.
