### ISSUE TITLE
Spicetify.URI.from is not a function

### ISSUE THREAD

**Issue by jeroentvb** [spicetify/spicetify-cli#2177]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.5.1006
- Spicetify version:2.16.2
```

### 📝 Description

The latest Spotify update broke the `Spicetify.URI.from` method, which broke some functionality in [power-bar](https://github.com/jeroentvb/spicetify-power-bar/issues/35). Though, I can switch to using `Spicetify.URI.fromString`, so this is not a high priority issue.

If the method doesn't exist anymore it should be removed from the globals.d.ts. If not it just needs to be re-added to the `Spicetify.URI` global

### 📸 Screenshots

![Scherm­afbeelding 2023-02-28 om 17 55 17](https://user-images.githubusercontent.com/36192730/221923772-cefffeb6-4421-49df-962f-6cf3d8db5dac.png)

**Comment by kyrie25** [comment]
Yeah it has been on my TODO list to update the type declarations since #2129, but got my hands a bit full atm.
It has been noted tho, dw.
