### ISSUE TITLE
i don't see the marketplace

### ISSUE THREAD

**Issue by uwu-Nick-uwu** [spicetify/spicetify-cli#2179]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 2.16.2
- Spicetify version:latest ( i can't find the version info but i reinstalled the newest version
```

### 📝 Description

i tried reinstalling , apply backup, restore,etc .. both spicetify and spotify but still can't find the problem 

in the second image i see that there's spicetify and 3 category but i don't know if it's working , it's been a few minutes so i don't know if ad will pop up .

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/122073287/222040391-62d79e48-d475-4413-9105-e50ef6a702b0.png)
![image](https://user-images.githubusercontent.com/122073287/222040427-39264f2b-5964-482e-9a85-c65a9d09ef8b.png)

**Comment by uwu-Nick-uwu** [comment]
there's still ad poping up

**Comment by kyrie25** [comment]
1. Spicetify doesn't block ads by default
2. Marketplace is installed separately, run **both** the install scripts on the website guide.
