### ISSUE TITLE
All custom apps are missing

### ISSUE THREAD

**Issue by iBlazeX** [spicetify/spicetify-cli#2181]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.6.863
- Spicetify version: v2.16.2
```

### 📝 Description

The Spotify version is supported but the icons are missing in the new UI and i don't know how to switch to the old ones

And without marketplace im unable to install snippets and extensions

### 📸 Screenshots

Custom apps 
![image](https://user-images.githubusercontent.com/85124169/222649129-ac9ef66d-d64f-4ec7-bad0-2f2349d77307.png)

The UI
![image](https://user-images.githubusercontent.com/85124169/222649171-fcf4c12a-1801-4667-943f-a83f5661dcad.png)

**Comment by kyrie25** [comment]
Experimental Features are not supported.
Disable Library X to use custom apps.

**Comment by iBlazeX** [comment]
Thank You.. i didn't know it was causing that

**Comment by iBlazeX** [comment]
i just realized that Library X is enabled by default.. if it isn't supported why is it enabled by default?

**Comment by kyrie25** [comment]
Experimental Features are just internal Spotify features of which is not-production ready and/or available for A/B testing. We do not enable **any** of them by default.

If the feature stays on **after** you have reset Experimental Features then it is possible Spotify has included you for their A/B rollout.

**Comment by iBlazeX** [comment]
> Experimental Features are just internal Spotify features of which is not-production ready and/or available for A/B testing. We do not enable **any** of them by default, Spotify does.
> 
> If the feature stays on **after** you have reset Experimental Features then it is possible Spotify has included you for their A/B rollout.

oh okay i see thanks, yes it stays on after reset and its the same without spicetify
