### ISSUE TITLE
Spotify Romanizes Lyrics but LyricsPlus Won't, Even when the providers are same....

### ISSUE THREAD

**Issue by JymxB28** [spicetify/spicetify-cli#2186]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.6.863.ge7902f05
- Spicetify version: v2.16.2

Windows 10 21H2 (OS Build19044.2604)
```

### 📝 Description

When playing any Hindi/Urdu/Punjabi Songs, I see, Spotify Romanizes the lyrics (Which shows below, Provided by Musixmatch), But on the same song, LyricsPlus shows me the lyrics in the original language. 

Sometimes, it alternates, A song where Spotify Romanizes and LyricsPlus won't, Sometimes I see LyricsPlus Romanizing the lyrics but not Spotify... and in some songs, it works fine in both... 

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/63513189/222982485-d4b4b587-df17-4fcd-881d-bf6e3b359bd4.png)
![image](https://user-images.githubusercontent.com/63513189/222982489-3f772355-a10d-4759-889d-b5ed27ea4792.png)

**Comment by kyrie25** [comment]
That's a feature of Spotify, Lyrics Plus gets raw lyrics from external sources and display them.
