### ISSUE TITLE
Unable to install, Missing terminator: ".

### ISSUE THREAD

**Issue by jjjjn2** [spicetify/spicetify-cli#2189]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.6.863.ge7902f05
- Spicetify version: N/A
```

### 📝 Description

When i try to run `iwr -useb https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.ps1 | iex`
I get this error (sent as a screenshot)
What do i do?

### 📸 Screenshots

![Screenshot 2023-03-06 131233](https://user-images.githubusercontent.com/65252351/223195330-524b4f94-0ac6-40b8-8a9a-f0a3db2d75d0.png)

**Comment by kyrie25** [comment]
Not a CLI issue.
Upgrade Powershell and try again.

**Comment by jjjjn2** [comment]
Got it thank you

**Comment by GauravByadwal** [comment]
I faced the same problem, When I updated my Powershell (version 5.1 to 7.3), its showing different error.
![Screenshot (10)](https://user-images.githubusercontent.com/94883243/223344319-c96f0c67-aac6-4f9d-96f9-261448ee2034.png)
 (screenshot attacted)

**Comment by kyrie25** [comment]
> I faced the same problem, When I updated my Powershell (version 5.1 to 7.3), its showing different error.  (screenshot attacted)
> 
> 
> 
> 
> 
> 
> 
> ![Screenshot (10)](https://user-images.githubusercontent.com/94883243/223344319-c96f0c67-aac6-4f9d-96f9-261448ee2034.png)
> 
> 

Use a VPN and try again.
