### ISSUE TITLE
Unable to play Playlist Radio

### ISSUE THREAD

**Issue by skeven** [spicetify/spicetify-cli#2192]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.6.863ge7902f05
- Spicetify version: 2.16.2
- Extensions/apps: hidePodcasts.js, marketplace
Windows 10 64-bit
```

### 📝 Description

1. Take any playlist
2. Choose menu point "Playlist radio"
3. Playlist Radio appears, click play button

✔️ Expected result
Playlist radio starts

❌ Actual result
If music is already playing it will stop the currently playing music.
If music is not playing, nothing happens

Older issues:
https://github.com/spicetify/spicetify-cli/issues/1448

Also not able to select any of the songs from the Playlist Radio playlist. Able to start the playlist radio from another device, but will stop playing after about 10 songs when it exhausts the initial queue.

Attempted uninstalling/reinstalling Spotify and Spicetify. Feature worked in Spotify correctly prior to applying Spicetify.

**Comment by kyrie25** [comment]
Can't replicate. Try clean reinstalling Spotify/Spicetify and run without extensions.
![image](https://user-images.githubusercontent.com/77577746/224444690-4755e3a6-5c6b-438e-90f4-35f38afb5f78.png)

**Comment by skeven** [comment]
Clearing the %appdata% and %localappdata% folders was the steps I missed before.
Working correctly now.

Thank you.
