### ISSUE TITLE
Option to stop Discord from stopping your music

### ISSUE THREAD

**Issue by Schlumpikatze** [spicetify/spicetify-cli#2193]
### 📝 Provide a description of the new feature

Would be pretty awesome if there was an option to prevent Discord from stopping your audio when talking or streaming your screen because it is annoying. If it isn't possible then it is how it is.

### ➕ Additional Information

Spicetify is pretty great but i have always missed a feature to stop ↓this↓ 
![mceclip0](https://user-images.githubusercontent.com/86611749/224394646-7bdb6b2f-905f-455b-a37f-4a420d7293d3.png)

**Comment by kyrie25** [comment]
Not a CLI issue. Make a suggestion on the Discord server.
