### ISSUE TITLE
Singles and EPs > See discography won't play the songs. (FAQ solution already tested)

### ISSUE THREAD

**Issue by Some1sm** [spicetify/spicetify-cli#2196]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.6.863.ge7902f05
- Spicetify version: v2.16.2
```

### 📝 Description

Deleting %LOCALAPPDATA%\Spotify contents doesn't fix it.

If you go to an artist profile, go into any category with "See discography" and try playing any of the songs inside, you won't be able to. 

1.  Go to artist profile
2.  Scroll to any category with See Discography button(Ex: Albums, Singles and EPs)
 ![image](https://user-images.githubusercontent.com/27234082/224803635-2bbda56f-219d-4901-be32-5ee83bf3d192.png)
4.  Click See Discography
5.  Try playing any song.
6.  Nothing plays, doesn't even show on the bar below.

Video example: https://youtu.be/mlalQu5eu7A

I can't see any error show up on console when clicking play.

**Comment by kyrie25** [comment]
Not a CLI issue.
Try [clean reinstalling both Spotify/Spicetify](https://github.com/spicetify/spicetify-cli/issues/2192#issuecomment-1464623642)

**Comment by Some1sm** [comment]
The video is on a clean Spotify/spicetify installation. 0 modifications. Problem starts whenever I install spicetify on a new installation of Spotify.

And as I said, I'm applying the %appdata% fix every time. 

This error shows up when clicking the play button the first time in the playlist. 
![image](https://user-images.githubusercontent.com/27234082/224926042-7c0d36d8-df1b-4af4-a611-5caba97a9ae8.png)

**Comment by kyrie25** [comment]
> And as I said, I'm applying the %appdata% fix every time. 

The fix means that you remove all Spicetify directories alongside Spotify, not just Spotify. That also includes the Spicetify executable in `%localappdata%`

> This error shows up when clicking the play button the first time in the playlist. 
> 
> ![image](https://user-images.githubusercontent.com/27234082/224926042-7c0d36d8-df1b-4af4-a611-5caba97a9ae8.png)
> 

This shows up as a internal Spotify API error as it doesn't trace back to any Spicetify stack nor is it modified in any part of the Spicetify CLI source code.
