### ISSUE TITLE
cant download

### ISSUE THREAD

**Issue by markimoofan** [spicetify/spicetify-cli#2197]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:﻿1.2.6.863.ge7902f05 
- Spicetify version: can't download
it says -> Invoke-WebRequest : 404: Not Found
```

### 📝 Description

I tried to download it with a guide but didn't even make it past the second step  https://amitgujar15.medium.com/change-spotify-themes-on-desktop-e8a34f339f83

### 📸 Screenshots

![problem](https://user-images.githubusercontent.com/17669325/225013629-a80b6c46-307d-49ae-a986-3a15adc9c165.png)

**Comment by kyrie25** [comment]
Follow the guide on [our website](https://spicetify.app) to correctly install Spicetify.
