### ISSUE TITLE
Experimental features not working at all 

### ISSUE THREAD

**Issue by ibimcoll** [spicetify/spicetify-cli#2201]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify for Windows: 1.1.90.859.gf1bb1e36
- Spicetify version: 2.16.2
- Theme: Bloom / darkmono
- Extensions: playOnYouTube.js, seekSong.js, spotifyBackup.js, spotifyGenres.js, trashBin.js, volumePercentage.js, webnowplaying.js, fullScreenWrapper.js, bloom.js
- Custom apps: lyrics-plus, marketplace
```

### 📝 Description

If I click on "experimental features" it simply shows nothing 

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/124598867/225961432-b82525f3-11da-4c98-89d8-cbefe1777e0f.png)

**Comment by kyrie25** [comment]
Does not work for Spotify under `1.1.92`
