### ISSUE TITLE
enable devtools not working and market place not showing.

### ISSUE THREAD

**Issue by itzshiva38** [spicetify/spicetify-cli#2202]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: latest
- Spicetify version: latest
```

### 📝 Description

1. I tried a command spicetify backup apply enable-devtool 
2. error: it says enable-devtool was not found as a command
3. when i opened spotify there was not market place.

### 📸 Screenshots

![Screenshot 2023-03-18 100813](https://user-images.githubusercontent.com/128204303/226085103-9378b70c-5c1f-4dbb-8bcb-78507a251860.png)
![image](https://user-images.githubusercontent.com/128204303/226085114-ec1a0cc9-b34d-42bf-a4cf-18f461f55269.png)

**Comment by kyrie25** [comment]
1. `enable-devtools`
2. Marketplace is not bundled with Spicetify
