### ISSUE TITLE
Some bugs only present while Spicetify is active

### ISSUE THREAD

**Issue by fowlis** [spicetify/spicetify-cli#2208]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows 1.2.7.1277.g2b3ce637
- Spicetify version: 2.16.2
```

### 📝 Description

• Window will sometimes "reload" without stopping music, causing taskbar icon to flash until the app is focused
• Seekbar will sometimes visually freeze on the current song - these screenshots [1](https://files.catbox.moe/107l37.png) and [2](https://files.catbox.moe/nyzcmv.png) were taken at the same time

didn't really want to make this two seperate issues for two minor bugs
my [`spicetify config`](https://files.catbox.moe/jhk1wy.png)

**Comment by kyrie25** [comment]
Not a CLI issue.
Remove all extensions or clean reinstall both Spotify and Spicetify.
