### ISSUE TITLE
wont open 

### ISSUE THREAD

**Issue by Delta8407** [spicetify/spicetify-cli#2209]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 
- Spicetify version:
```

### 📝 Description

so i got it and it wont open it open then it closes and i have uninstalled and reinstailled.

**Comment by theRealPadster** [comment]
Please fill in the minimum info outlined in the bug report firm, and provide any sort of details that may be useful for troubleshooting.
