### ISSUE TITLE
background image not centered in smaller viewports

### ISSUE THREAD

**Issue by Etsi0** [spicetify/spicetify-cli#2211]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.7.1277.g2b3ce637
- Spicetify version: v2.16.2
```

### 📝 Description

The background image is not centred properly on small viewports, which causes the two lines to be misaligned. As shown in the screenshot below.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/43541844/226836377-25caa0ba-5bf2-4e21-9073-17a868fe2244.png)

**Comment by kyrie25** [comment]
https://github.com/spicetify/spicetify-cli/issues/2210#issuecomment-1479659601
