### ISSUE TITLE
"Something went wrong. Try reloading the page."

### ISSUE THREAD

**Issue by theEpicjosh** [spicetify/spicetify-cli#2215]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows
1.2.7.1277.g2b3ce637
Spicetify v2.15.0
Theme: marketplace
Extensions: webnowplaying.js, hidePodcasts.js
Custom apps: marketplace
```

### 📝 Description

I used the PowerShell command `spicetify backup restore` and `spicetify apply` and I got an error message saying "Something went wrong. Try reloading the page.". I click on "RELOAD PAGE", but it keeps showing the same message. I try to go on other tabs, but it says the same thing, even when I open the Marketplace.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/25969231/227724855-47a5b367-5cf4-40a9-9acd-1f0f2da109ea.png)
![image](https://user-images.githubusercontent.com/25969231/227724878-bb125073-17eb-4953-bc87-3d2504b6dbad.png)
This last one is while opening the Marketplace.

**Comment by kyrie25** [comment]
Outdated Spicetify version. Run `spicetify upgrade` then `spicetify restore backup apply`
