### ISSUE TITLE
Spicetify Gets Stuck During Download in Powershell

### ISSUE THREAD

**Issue by AstroWildcat** [spicetify/spicetify-cli#2216]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.8.907
- Spicetify version: Unable to Install
```

### 📝 Description

1. Go to the installation page.
2. Copy the commands in the Powershell (pre-built binary) section.
3. Go to Windows Powershell.
4. Paste the commands.
5. Get stuck during the installation process.

Every time I keep doing this, it gets stuck on various byte numbers instead of downloading the whole application.

### 📸 Screenshots

<img width="843" alt="Screenshot 2023-03-25 113004" src="https://user-images.githubusercontent.com/101528411/227727793-e218de24-0521-40a8-954a-1338558c2468.png">

**Comment by rxri** [comment]
github related issue
