### ISSUE TITLE
Lyrics Plus - Lyrics provider which does not exist in settings

### ISSUE THREAD

**Issue by AHRI2nd** [spicetify/spicetify-cli#2230]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.8.923.g4f94bf0d
- Spicetify version: v2.16.0
```

### 📝 Description

In the Lyrics Plus, the sync lyrics are displayed through a プチリリ provider that does not exist in the settings.
Even if I specify the order in which lyrics are fetched, it's not visible in the settings and always shows at first, causing the wrong lyrics to be fetched or the sync to fall behind.
This problem occurs with any song that can bring up sync lyrics on プチリリ.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/86597677/228911730-0e149d0b-d374-4611-b876-e7a6d35797c0.png)
![image](https://user-images.githubusercontent.com/86597677/228911781-922964c1-8485-4991-91a4-786c6f0bed6b.png)

**Comment by rxri** [comment]
Lyrics Plus and Spotify doesn't have implemented PetitLyrics support so I don't think it's something that we can change. It could be that netease provides lyrics from them, but I'm not really sure
