### ISSUE TITLE
Mini player - Experimental

### ISSUE THREAD

**Issue by Azemblage** [spicetify/spicetify-cli#2231]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 
- Spicetify version:
```

### 📝 Description

On the experimental menu under the account, I select to enable mini player - but when i click the new icon nothing happens.

### 📸 Screenshots

<img width="435" alt="Screenshot 2023-03-30 at 23 59 18" src="https://user-images.githubusercontent.com/47430066/228983098-5b338a85-8510-4f49-883a-9554ffe1f75c.png">

**Comment by kyrie25** [comment]
Experimental Feature are Spotify internal features, we have no influence on what it can do and will bare no responsibility on what it does/does not do.
