### ISSUE TITLE
Spicetify overlapping

### ISSUE THREAD

**Issue by JustAnotherMG** [spicetify/spicetify-cli#2233]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: latest
- Spicetify version: latest
```

### 📝 Description

I recently ran into a problem, after i updated spotify and reinstalled spicetify. I tried fixing it by reinstalling Spotify from the .exe application. But now I have a problem where the play button and the sidebar playlist text/icons are getting messed up. I feel like this is because Spicetify is rendering 2 bits from the Modern Theme, for some reason. I did install Spicetify (spicetify, not the spicetify modern theme) after I reinstalled the Spotify app. I'd like some help, if possible. Thank you.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/91489755/229069089-300761c5-6262-49bc-b17f-f04bfc2d37ea.png)
![image](https://user-images.githubusercontent.com/91489755/229069124-80051560-71ab-411f-b37a-1653b42e5978.png)
![image](https://user-images.githubusercontent.com/91489755/229069149-f85854ea-f282-41e7-8629-8603c8aa5a4b.png)

**Comment by kyrie25** [comment]
Not a CLI issue.
