### ISSUE TITLE
"Something went wrong" error when opening any tab like home or liked songs

### ISSUE THREAD

**Issue by TheStupidOneHere** [spicetify/spicetify-cli#2234]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.8.923g4f94bfOd
- Spicetify version: v2.17.0
```

### 📝 Description

Happened to me once before, and was fixed by reinstalling spotify and spicetify
Issue came up again when I installed a new theme, **will not go away even if I upgrade spicetify**
Shows the error whenever I open any tab

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/71955577/229070351-d98b56bd-76df-4463-8cd5-2198424b2f0a.png)

**Comment by kyrie25** [comment]
`spicetify restore backup apply`

**Comment by TheStupidOneHere** [comment]
I'm really sorry but I tried both of those twice, one thing I noticed was that it worked fine without marketplace. Could it be an issue with marketplace?

**Comment by kyrie25** [comment]
> I'm really sorry but I tried both of those twice, one thing I noticed was that it worked fine without marketplace. Could it be an issue with marketplace?

Follow the steps in the message and post the screenshot here.

**Comment by TheStupidOneHere** [comment]
Settings
spotify_path                  C:\Users\Dell\AppData\Roaming\Spotify
color_scheme
check_spicetify_upgrade       0
prefs_path                    C:\Users\Dell\AppData\Roaming\Spotify\prefs
current_theme                 marketplace
inject_css                    1
replace_colors                1
overwrite_assets              0
spotify_launch_flags

Preprocesses
expose_apis                   1
disable_upgrade_check         1
disable_sentry                1
disable_ui_logging            1
remove_rtl_rule               1

AdditionalFeatures
sidebar_config                1
home_config                   1
experimental_features         1
extensions
custom_apps                   marketplace

Backup
version                       1.2.8.923.g4f94bf0d
with                          2.17.0

when running the command
![image](https://user-images.githubusercontent.com/71955577/229094110-6cbd23b0-bf20-4537-ab84-7488943b846a.png)

**Comment by kyrie25** [comment]
> Follow the steps in the message

![image](https://user-images.githubusercontent.com/77577746/229096161-68fede85-9fe1-4ace-bb83-e8c3d03face4.jpeg)

**Comment by TheStupidOneHere** [comment]
Oh. Really sorry for not noticing that, here's the screenshot
![image](https://user-images.githubusercontent.com/71955577/229098163-9e3c3966-eae3-46e0-b443-1f0e705559c9.png)

**Comment by kyrie25** [comment]
Seems like internal issues since the relevant errors doesn't trace back to anything Spicetify-related, so I can't actually confirm this as a CLI issue nor investigate the problem, sadly.

**Comment by TheStupidOneHere** [comment]
Well, thanks for the great amount of help anyways, I will try to tinker around myself and see if I can get anything working. Again, thanks for all the help
