### ISSUE TITLE
Spicetify Not Working at all!

### ISSUE THREAD

**Issue by DefaultUser9148** [spicetify/spicetify-cli#2237]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows 11 | 1.2.8.923.g4f94bf0d

- Spicetify version: v2.16.2
```

### 📝 Description

Install Spicetify using Powershell
Run Spicetify Apply in Powershell
Spotify Is Terminated
Spicetify Gives no errors and says everything is set up 

```
Overwriting raw assets:
OK
Transferring user.css:
OK
Applying additional modifications:
OK
success Spotify is spiced up!
```
Spotify Starts up
Nothing has changed. No Marketplace button, Nothing!
I did it again and again. Nothing!

### 📸 Screenshots

![2023-03-31 17_31_38-](https://user-images.githubusercontent.com/99608227/229150787-d3806729-4cbd-4639-841e-dfadd0085011.png)

**Comment by DefaultUser9148** [comment]
I should mention im on Windows 11 Home Insider Canary Channel. May be useful.

**Comment by theRealPadster** [comment]
Your list of steps did not include installing the Marketplace custom app. Did you do that?

**Comment by DefaultUser9148** [comment]
1. I installed spotify like 10 minutes ago from spotify.com/us/download/windows/ so its not outdated.
2. I installed Marketplace and its not showing up at all.

**Comment by 123yuyu123** [comment]
i have the same issues
