### ISSUE TITLE
[meta] Users should not make support requests in this repo in the issue template

### ISSUE THREAD

**Issue by DragoCubed** [spicetify/spicetify-cli#2238]
### 📝 Provide a description of the new feature

I see many users post support requests here. I hope they can be reduced by adding that support requests do not belong in GitHub issues. The issue template picker is a great place for that information. 

### ➕ Additional Information

Linking to the FAQ from the Spicetify Docs in the issue template may also help

**Comment by abdansyakuuro** [comment]
28wbsudbsu

**Comment by REALtony4twenty** [comment]
as someone who uses github all the time to find things to use on my pc for my workflow, I have still yet to find out how to post anything to any github without it being labeled as an "issue" I would love to learn how to change the tag to a "feature request" or "concern" etc. Yet when I try to google the question on how to do it, I get lost in useless information and never find the answer.

**Comment by rxfrxctxd** [comment]
Could maybe the [Discussions](https://docs.github.com/en/discussions) feature play here well?

**Comment by ohitstom** [comment]
> Could maybe the [Discussions](https://docs.github.com/en/discussions) feature play here well?

Could, could not. 

At the end of the day everything that would be discussed in discussions is covered on our discord and reddit numerous times and also in our docs, any actual bugs/issues would be kept open on our issue pages and properly tracked by the dev team. 

So i dont see this *really* helping tbh.

**Comment by Flair001** [comment]
@kyrie25 why did you close it? I need help. #1 the installation still doesn't work?

**Comment by Flair001** [comment]
@kyrie25 worst fucking helper - i haven't wished someone this in a long time buddy. you fucking wasted my time

**Comment by kyrie25** [comment]
> @kyrie25 worst fucking helper - i haven't wished someone this in a long time buddy. you fucking wasted my time

**Read** the content of the message I wrote in your issue before going around, thanks.

If you fail to comply we will restrict your access to the repository.

**Comment by rxri** [comment]
I think a link to our discord server is enough when trying to create new issue. For some time I noticed less help requests here. In the end adding this link was a good idea
![image](https://github.com/spicetify/spicetify-cli/assets/9348108/ab96190e-79f9-480a-943f-352789953f51)

**Comment by DragoCubed** [comment]
Thanks for adding this!

**Comment by DragoCubed** [comment]
Fixed by https://github.com/spicetify/.github/pull/7
