### ISSUE TITLE
Antivirus Block the installation Process

### ISSUE THREAD

**Issue by Aleoneboo** [spicetify/spicetify-cli#2239]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Last
- Spicetify version:Last
```

### 📝 Description

I keep getting an error because my Nothon Antivirus Keeps disabling a process. How can i stop the antivirus from deleting the file without turning off the antivirus complitely?

### 📸 Screenshots

![Screenshot 2023-03-31 204445](https://user-images.githubusercontent.com/66528478/229204277-27f57b81-e94f-4bac-b5e0-31c96662c723.png)

**Comment by rxri** [comment]
Not related to cli and disable defender temporarily
