### ISSUE TITLE
[lyrics plus] dual panel mode of genius no longer works.

### ISSUE THREAD

**Issue by Lseoksee** [spicetify/spicetify-cli#2243]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [x] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.8.923
- Spicetify version: 2.17
```

### 📝 Description

If you turn on the dual panel mode, you will no longer see two.

### 📸 Screenshots

![Desktop Screenshot 2023 04 03 - 15 03 30 45](https://user-images.githubusercontent.com/91320047/229425309-91fab2f6-5b0e-4478-ad4d-fa07c0cda097.png)

![Desktop Screenshot 2023 04 03 - 15 03 21 51](https://user-images.githubusercontent.com/91320047/229425278-299d0669-a2bb-4e94-91f6-7d4c427151b2.png)

**Comment by kyrie25** [comment]
This was deliberately disabled in #1444 as a temporary fix for the issue, but it seems like it was never patched correctly.
