### ISSUE TITLE
Traditional Chinese Lyrics in CustomApps / lyrics-plus / Provider Netease 

### ISSUE THREAD

**Issue by 01qwasa10** [spicetify/spicetify-cli#2245]
### 📝 Provide a description of the new feature

HI there! As a Taiwanese user, I found that Netease translates all lyrics which originally in Traditional Chinese into Simplified Chinese. Is there an option to switch between the both?

### ➕ Additional Information

![image](https://user-images.githubusercontent.com/61235151/229897503-4e7a003d-53f4-4f51-b596-d330cd29a3e1.png)

**Comment by kyrie25** [comment]
> Is there an option to switch between the both?

Netease lyrics are taken as-is, we only display what they provided to us.

So no, there aren't any options to switch.
