### ISSUE TITLE
Spotify doesn't refresh when targeted files changed in -watch mode

### ISSUE THREAD

**Issue by Tetrax-10** [spicetify/spicetify-cli#2246]
### 🔍 Have you checked Spicetify.app page for your issue?

- [x] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.8
- Spicetify version: 2.17.0

Spotify for Windows
1.2.8.923.g4f94bf0d
Spicetify vDev (latest: spicetify/spicetify-cli@395daabd31d064ac7d2f0521fb4e6b6fa076ac5d)
```

### 📝 Description

I tried to watch Extensions and Themes on Spotify, but when I save a file in terminal it says spotify reloaded but actually it didn't. I noticed this only happens only on `Spotify 1.2.8`.

I used these commands

```
spicetify enable-devtools
spicetify -s -e watch
```

### 📸 Screenshots

https://user-images.githubusercontent.com/75513645/229908029-13bbac00-cc52-4979-ad72-bda7e4aa5f2d.mp4

**Comment by kyrie25** [comment]
Spotify `1.2.8` has a buggy DevTools (font not working correctly on early builds of `1.2.8`, Sources tab completely broken, DevTools would sometimes freeze/unable to execute commands after a period of inactivity, etc.) thus this can't be conclusively be confirmed as a CLI issue as the communication between Spotify DevTools via socket may be broken as well.

If on the next versions of Spotify all the aforementioned bugs are resolves yet `watch` still doesn't work then remind me to reopen the issue
