### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by RobbsBro** [spicetify/spicetify-cli#2249]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 
- Spicetify version:
```

### 📝 Description

Why i enter the command 
curl -fsSL https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.sh | sh

Always get the path redirected to .bashrc

### 📸 Screenshots

![Screenshot from 2023-04-06 20-39-57](https://user-images.githubusercontent.com/108186107/230418053-37cb341e-ece0-4349-b6f9-c420a569262a.png)

**Comment by rxri** [comment]
your .bashrc seems broken. you should fix it first (lines 81, 74) and then run installer
