### ISSUE TITLE
watch reloading broken

### ISSUE THREAD

**Issue by ohitstom** [spicetify/spicetify-cli#2258]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: latest
- Spicetify version: 1.2.7 forward
```

### 📝 Description

Whilst the last few updates of spotify have given buggy devtool windows, i doubt this issue has anything to do with that. Since remote debugging (which watch relies on) works perfectly fine except in the cli this is what happens whilst i was investigating:
![image](https://user-images.githubusercontent.com/22730962/231287803-9bbba133-2d7d-4d76-8afb-85ae89f01899.png)

however note that using chrome://inspect you can still access and reload spotify perfectly fine.

**Comment by kyrie25** [comment]
Duplicate of #2246
