### ISSUE TITLE
Stuck on migrating

### ISSUE THREAD

**Issue by eziophagus** [spicetify/spicetify-cli#2259]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows 1.2.8.923.g4f94bf0d
- Spicetify version:2.17.1
```

### 📝 Description

After installing through Choco; I ran spicetify apply. it is stuck on "Migrating spiceitfy config folder."

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/93644342/231432026-55f79f41-eb0a-48f2-903d-87c571956859.png)

**Comment by kyrie25** [comment]
**Do not** run Spicetify in an elevated environment.
Remove all content in `%appdata%/spicetify` (if there is any) and run `spicetify backup apply`.

**Comment by eziophagus** [comment]
The theme folder in Roaming/Spicetify isn't getting deleted

**Comment by kyrie25** [comment]
> The theme folder in Roaming/Spicetify isn't getting deleted

Yeah this is why you should not have run Spicetify as an admin.
You'll have to look up how to force delete a folder.

**Comment by eziophagus** [comment]
I tried force deleting through CMD in Safe Mode. still doesn't work. Any other methods?
