### ISSUE TITLE
Spicetify no longer working since last update

### ISSUE THREAD

**Issue by xAvatar6969** [spicetify/spicetify-cli#2262]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.9.743.g85d9593d
- Spicetify version: 1.16.1
```

### 📝 Description

I updated Spotify as usual and restored Spicetify, but now every time I try to enter the marketplace it says "Something went wrong" and the ads aren't blocked, but the theme I set up before is working. I alredy tried to restore the original Spotify and then re-spice it, but it didn't work.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/64364834/232207757-c21e6429-3c98-482a-92db-0c7b8b01bc5d.png)

**Comment by kyrie25** [comment]
Outdated Spotify and Spicetify version.
Latest Spotify version is `1.2.9`.
Latest Spicetify version is `2.17.2`.
