### ISSUE TITLE
Trojan:Script/Wacatac.b!ml

### ISSUE THREAD

**Issue by RobbieSpeedyNL** [spicetify/spicetify-cli#2266]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: doesn't matter
- Spicetify version: 2.17.2
```

### 📝 Description

when i install it says this
so i'm not gonna install it
just putting this here incase u guys don't know there's malware in there
(windows defender)

**Comment by theRealPadster** [comment]
False positive. The source code is on this repo. You can check for yourself, there is no malware.
