### ISSUE TITLE
Extensions, Themes, etc. not working with Lyrics-Plus

### ISSUE THREAD

**Issue by eclipse828** [spicetify/spicetify-cli#2268]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.9
- Spicetify version: 2.17.2
```

### 📝 Description

When I use Lyrics-Plus, no other widgets, extensions, etc. work. The only exception is when you redownload the thing, but after you restart Spotify, the issue comes up again. It's like Lyrics-Plus won't work with anything else.

**Comment by kyrie25** [comment]
Lyrics Plus is a custom app, it only works within its sandbox.
Remove each extension to see the issue.
