### ISSUE TITLE
No run spicetify in spotify update

### ISSUE THREAD

**Issue by DawaDokuna** [spicetify/spicetify-cli#2269]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.743.g85d9593d
- Spicetify version:v2.17.2
- Windows: 11
```

### 📝 Description

After a few seconds, all spotify services are stopped including the tabs.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/61769120/232376828-07b86a54-6938-4fc8-b3b4-76a28a55a345.png)

**Comment by kyrie25** [comment]
Outdated Spotify version.
