### ISSUE TITLE
Unable to use spicetify. bugs out when opening marketplace

### ISSUE THREAD

**Issue by DABOSS2016YT** [spicetify/spicetify-cli#2270]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 
Spotify for Windows
1.2.9.743.g85d9593d
Spicetify v2.16.2
Theme: Sleek / UltraBlack
Extensions: adblock.js, fullScreenWrapper.js, sortByPlayCount.js, spotdj.js, fullAppDisplayMod.js
Custom apps: marketplace

- Spicetify version: spicetify v2.17.2

PC DETAILS :
Processor	AMD Ryzen 5 5600X 6-Core Processor                4.20 GHz
Installed RAM	32.0 GB
System type	64-bit operating system, x64-based processor
Edition	Windows 11 Pro
Version	22H2
OS build	22621.1555
Experience	Windows Feature Experience Pack 1000.22640.1000.0
```

### 📝 Description

when opeing spotify and interacting with marketplace, spotify stops working, interacting with playlists and anything else returns : 
![image](https://user-images.githubusercontent.com/43446532/232493819-de55d748-82bc-45a4-b511-102c94053322.png)

All existing plugins and themes that i was originally using don't seem to work, I've tried reinstalling and runing spicetify update and spicetify apply but neither provide any change

**Comment by kyrie25** [comment]
Outdated Spicetify version
Run `spicetify upgrade` then `spicetify restore backup apply`
