### ISSUE TITLE
Spicetify commands just hang

### ISSUE THREAD

**Issue by Spedwards** [spicetify/spicetify-cli#2277]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- OS: Windows 10
- Spotify version: 1.2.9.743.g85d9593d
- Spicetify version: v2.17.2
```

### 📝 Description

I've been trying to install Spicetify for a while now but none of the commands do anything. They just hang. I've tried entering `spicetify backup apply` and `spicetify apply` but both just do nothing. I've tried with Spotify open and I've tried with Spotify closed. Nothing seems to help.

I've tried running the installation script directly from the site again a few times and sometimes the `spicetify` command doesn't even work.

I've gone through the issues and tried to find any instances of someone having the same problem but there's over 500 issues just for the search "spicetify apply". If this happens to be a duplicate, please link the original.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/3257096/233147386-c2bff219-d9c0-4467-9e71-0a780cdb16b8.png)

Shows exactly what Spicetify is doing: nothing.

**Comment by rxri** [comment]
Remove spicetify directories from `%appdata%\spicetify` and `%localappdata%\spicetify` paths and re-run install script

**Comment by Spedwards** [comment]
> Remove spicetify directories from `%appdata%\spicetify` and `%localappdata%\spicetify` paths and re-run install script

I've deleted the directories within those two locations and re-ran the installation script however it still hangs.
![image](https://user-images.githubusercontent.com/3257096/233152640-4e695e54-5ee9-4a20-851d-a90621859496.png)

Should I delete those directories completely?

**Comment by kyrie25** [comment]
This happens when Spicetify recursively tries to find Spotify path and fails.
Remove Spotify and install from their website, afterwards remove all directory as said above. If it doesn't work, [manually set both paths in your config](https://spicetify.app/docs/faq#cannot-find-pref_file)

**Comment by Spedwards** [comment]
> This happens when Spicetify recursively tries to find Spotify path and fails. Remove Spotify and install from their website, afterwards remove all directory as said above. If it doesn't work, [manually set both paths in your config](https://spicetify.app/docs/faq#cannot-find-pref_file)

It'd be nice if an actual descriptive error was thrown if the path is not found. Recursively looking for something that isn't there and hoping it appears is stupid. If the file is not found, throw an error so people know how to resolve it.

Also, I am using an install from the official Spotify website. I'm not re-installing, so I'll just have to hope that changing the config alone will work.

**Comment by kyrie25** [comment]
> It'd be nice if an actual descriptive error was thrown if the path is not found. Recursively looking for something that isn't there and hoping it appears is stupid. If the file is not found, throw an error so people know how to resolve it.

AppX version of Spotify has multiple install\cache locations, usually the AppX package manager doesn't flush cache after uninstallation so it returns a false path. We run checks there and dump it if it isn't valid.
Usually it would throw an error after the first check, this is the first case where it doesn't.
