### ISSUE TITLE
Spicetify marketplace doesnt work and when refreshing it loads back to home page and the marketplace still doesnt work

### ISSUE THREAD

**Issue by JayKayHere3987** [spicetify/spicetify-cli#2278]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.7.1277.g2b3ce637
- Spicetify version: 2.16.0
```

### 📝 Description

Upon loading spotify ( after reinstalling ) I ran  `spicetify backup ` and then `spicetify backup apply`
Spotify relaunched ( as expected and as it always happened )
Went to the marketplace to install a theme and some extensions 
The marketplace showed "Something Went Wrong" and prompted to refresh ( Can be found in screenshots below )
The marketplace did not work even after refreshing.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/91802166/233176096-bd64278f-2e31-48c9-85a4-df2a45a34b6d.png)

**Comment by theRealPadster** [comment]
Both your spotify and spicetify are outdated. Update them and reapply.

**Comment by JayKayHere3987** [comment]
> how to update them and reapply. I already did it but they still didn't work

I will guide you through!!!
First we need to fix Spicetify
1. Launch **Windows PowerShell **
2. Run `iwr -useb https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.ps1 | iex`
3. After it is finished, run `iwr -useb https://raw.githubusercontent.com/spicetify/spicetify-marketplace/main/resources/install.ps1 | iex`
Make sure before applying that you have downloaded latest version of spotify from [https://www.spotify.com/us/download/windows](url)
After you have downloaded and installed the latest official spotify version
run in the previous powershell window `spicetify backup apply` 


If you need anything else I will be here to guide you through!

**Comment by ilhamhamdani123** [comment]
> > how to update them and reapply. I already did it but they still didn't work
> 
> I will guide you through!!! First we need to fix Spicetify
> 
> 1. Launch **Windows** **PowerShell**
> 2. Run `iwr -useb https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.ps1 | iex`
> 3. After it is finished, run `iwr -useb https://raw.githubusercontent.com/spicetify/spicetify-marketplace/main/resources/install.ps1 | iex`
>    Make sure before applying that you have downloaded latest version of spotify from [https://www.spotify.com/us/download/windows](url)
>    After you have downloaded and installed the latest official spotify version
>    run in the previous powershell window `spicetify backup apply`
> 
> If you need anything else I will be here to guide you through!

thankyou so much
