### ISSUE TITLE
Pop Up Lyrics Transparent and Click-through Option

### ISSUE THREAD

**Issue by JARalph23Z** [spicetify/spicetify-cli#2280]
### 📝 Provide a description of the new feature

What the title says. I like using the feature while working on something or playing a game, as I like singing along to songs I don't know the lyrics to. But yeah, it's visually obstructing and I was wondering if it would be possible to just hide the background or make it transparent, so only the lyrics are seen.

Additionally, if it's at all possible, I want the popup to be possible to be clicked-through. So I can get to something behind the popup. Of course, it's also configurable, so I can choose to drag the popup first to my desired position before making it click-through.

I hope I was clear enough. Thank you very much for taking the time :D

### ➕ Additional Information

![image](https://user-images.githubusercontent.com/74003742/233326489-ef2d2685-3703-4418-8633-9da3a5b8e3bc.png)

I want the background to be transparent so I can see what goes on behind. And also to be able to equip my accessories without moving the popup around. :D

**Comment by kyrie25** [comment]
Not possible. You can achieve the same thing using third-party applications that injects alpha values on draw.

**Comment by sarthak9793** [comment]
Even though this is outside your scope, but can you please give some direction as to how I can achieve this?
