### ISSUE TITLE
App crashed

### ISSUE THREAD

**Issue by Nodix01** [spicetify/spicetify-cli#2292]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: last version
- Spicetify version:2.17.2
```

### 📝 Description

when i search a playlist or an artist and click it, the app crash

### 📸 Screenshots

![q](https://user-images.githubusercontent.com/103963448/234056011-bd4d39e0-278b-4ab3-9195-f816278eebc5.png)

**Comment by rxri** [comment]
provide your specific version - we don't know what is the latest for you

**Comment by Nodix01** [comment]
Spotify for Windows
1.2.9.743.g85d9593d
Spicetify v2.17.2

**Comment by kyrie25** [comment]
Provide config.

**Comment by Nodix01** [comment]
nvm, i reinstall it,but i see a new problem, i can't find "MARKETPLACE"
![image](https://user-images.githubusercontent.com/103963448/234132687-6809ef24-2599-44dc-b414-82735b395fc3.png)

**Comment by kyrie25** [comment]
Marketplace is installed separately, run the installer from https://spicetify.app/docs/getting-started.
If the issue persists after reinstalling Marketplace then remove all themes/extensions added from Marketplace and try each one by one.
