### ISSUE TITLE
Spicetify doesn't apply

### ISSUE THREAD

**Issue by Ambralin** [spicetify/spicetify-cli#2299]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 
- Spicetify version: 2.17.2
```

### 📝 Description

I startup spicetify and can't see marketplace, running spicetify auto, upgrade, update, backup apply. doesn't do anything

in the spicetify upgrade it says I have the newest version

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/71408404/235139538-12e5bc01-ff2b-4320-8dbc-62479779ea8e.png)

**Comment by kyrie25** [comment]
Run `spicetify restore backup apply` as stated in the command.
Marketplace is installed separately, run the installer on our website.

**Comment by Ambralin** [comment]
that doesn't fix my issue, I had marketplace and other extensions applied. But now the spotify is bare.

**Comment by kyrie25** [comment]
You can re-run the Marketplace install script regardless and your configuration will be preserved.

Issues are not meant for support, if you need assistance make a support ticket on our Discord server and our Helpers will reach out to you.

**Comment by Ambralin** [comment]
so it can just dissapear out of nowhere?

**Comment by kyrie25** [comment]
If you are using the Microsoft Store version and/or if your Spotify client just updated, you will need to re-apply Spicetify patches.

**Comment by Ambralin** [comment]
not using the store spotify, no updates running latest spicetify. reinstalling the marketplace kept the config and its all good. thank you, although a bug.
