### ISSUE TITLE
Not able to install Spicetify

### ISSUE THREAD

**Issue by AMRzip** [spicetify/spicetify-cli#2306]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Latest
- Spicetify version: tried to install latest
```

### 📝 Description

I have tried to install Spicetify using the command u guys told but have not ben successful so require your assistance

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/85310902/235363416-96cb6358-b742-431e-8416-7bf83ecc86a4.png)

this is the error message

**Comment by rxri** [comment]
Try this:
```powershell
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; iwr -useb https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.ps1 | iex
```

If this command doesn't work, please use VPN or another network.
Closing: Not related to CLI
