### ISSUE TITLE
lyrics plus white text color on white background

### ISSUE THREAD

**Issue by rootleg** [spicetify/spicetify-cli#2307]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.10.760
- Spicetify version: 2.17.2
```

### 📝 Description

Was listening to a song called buku by wolfacejoeyy ant wanted to see the lyrics but its nearly invisible to see the one currently on screen. The only lined displayed is the next line after the highlighted one.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/93836206/235374424-4ced3add-fbe7-4df3-9087-8e842f03e1c8.png)

**Comment by rxri** [comment]
I believe it will be fixed by #2304 or https://github.com/spicetify/spicetify-cli/commit/00bdd2d0427c5c169a5be16288ba8f8743c2fd48
