### ISSUE TITLE
experimental features

### ISSUE THREAD

**Issue by senolfndk** [spicetify/spicetify-cli#2308]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: v2.17.2
- Spicetify version: 1.2.10.760.g52970952
```

### 📝 Description

experimental features not working

### 📸 Screenshots

![Ekran görüntüsü 2023-05-01 052218](https://user-images.githubusercontent.com/52818836/235392504-046f8d1a-143f-4e1b-9c26-20cbbd9126f5.png)

**Comment by kyrie25** [comment]
Can't reproduce. 
Run `spicetify restore backup apply` or try [clean reinstalling both Spotify/Spicetify](https://github.com/spicetify/spicetify-cli/issues/2192#issuecomment-1464623642)

**Comment by senolfndk** [comment]
I tried the way you described and it still doesn't work 😒

**Comment by kyrie25** [comment]
1. Run `spicetify enable-devtools`
2. Press `Ctrl + Shift + I` or right-click anywhere on the Spotify window until a dropdown menu appears saying `Show DevTools`, if so choose that option.
3. Open the `Console` tab and type in each of these strings (`Spicetify.RemoteConfigResolver`, `Spicetify.Platform.RemoteConfiguration`, `Spicetify.Platform.RemoteConfigOverrides`, `Spicetify.Platform.RemoteConfigResolver`) and press Enter.
4. Take a screenshot of each output and send it here.

If this is indeed a Spicetify issue based on the errors posted then we'll reopen and investigate it.
