### ISSUE TITLE
Pull Synced/Karaoke from musixmatch

### ISSUE THREAD

**Issue by LarveyOfficial** [spicetify/spicetify-cli#2311]
### 📝 Provide a description of the new feature

Right now Karaoke is only pulled from netease which has a very limited library of karaoke synced lyrics. It would be nice to have it as well using musixmatch's database.

**Comment by kyrie25** [comment]
![image](https://user-images.githubusercontent.com/77577746/235565145-343b1308-8413-44a3-bade-8886080b1719.png)
Has always been a feature. Modify your provider states on your profile dropdown menu > Lyrics Plus config.

**Comment by LarveyOfficial** [comment]
Yes i noticed it says "Provided synced lyrics"

But I am wondering about word-by-word synced lyrics, AKA Karaoke. 

Also It seems there already is a musixmatch API key in my config. But going to change it, it states that the free tier does not provide synced lyrics
![image](https://user-images.githubusercontent.com/39219859/235566613-4205f494-f929-4c40-b088-d093233ae235.png)
And the "plus" tier doesn't have a price, it's only a contact page.

**Comment by LarveyOfficial** [comment]
Nvm I realized how to get a key, Will come back after I get a new key

**Comment by kyrie25** [comment]
> Yes i noticed it says "Provided synced lyrics"
> 
> But I am wondering about word-by-word synced lyrics, AKA Karaoke.

Already implemented in #2248. Available in latest version.
![image](https://user-images.githubusercontent.com/77577746/235567354-e0d392af-70e0-462a-b506-e4b7fd92672f.png)
