### ISSUE TITLE
spicetify wont install

### ISSUE THREAD

**Issue by milchsaufer** [spicetify/spicetify-cli#2312]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [x] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.10.760.g52970952
- Spicetify version: 2.17.2
- os: windows 11 22h2
```

### 📝 Description

everytime i try to install spicetify, it tells me it finished installing. everytime when i check though, it seems to have changed nothing at all. theres no "edit sidebar" or "marketplace". idk why this issue is there, i tried to search for some solutions but didnt find anything. thanks in advance!

ps: sorry if my english is broken, its not my first language

**Comment by rxri** [comment]
Please check our discord support server for more information about your problem. Marketplace also doesn't come with cli by default and you need to execute second command that is available in docs.
