### ISSUE TITLE
Blank screen after theme applied @ v2.17.2, works @ HEAD

### ISSUE THREAD

**Issue by rxfrxctxd** [spicetify/spicetify-cli#2313]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
❯ spotify --version
Spotify version 1.2.9.743.g85d9593d, Copyright (c) 2023, Spotify Ltd

❯ spicetify -v
2.17.2

- OS:openSUSE Tumbleweed 20230430
- Spotify from [home:marcus_gama](https://build.opensuse.org/project/show/home:marcus_gama)
- Spicetify from [home:Dead_Mozay](https://build.opensuse.org/package/show/home:Dead_Mozay/spicetify-cli)
```

### 📝 Description

Just like on issue #1570, Spotify seems to give me a blank screen after being started with a spicetify theme applied.

Using all the solutions provided in issue 1577, the issue still persists.
Cloning the repository and compiling locally from master/HEAD, and applying using the Dev executable makes it work.

I have done `spicetify restore backup apply` as the program has shown me after running the git master executable, and after using the release one again.
This also happened before ever compiling myself, just in case.

Has this been looked into? Is it a distribution issue? I should note that OBS `home` packages are not official SUSE maintained ones.

### 📸 Screenshots

# Spicetify v2.17.2 
![Spicetify v2.17.2](https://user-images.githubusercontent.com/104025732/235785112-c8a537d9-ce14-4d57-b898-c7d1fbbdeb20.png)

# Spicetify HEAD
![Screenshot from 2023-05-02 22-57-05](https://user-images.githubusercontent.com/104025732/235785455-f28e53bb-39ae-4630-b7e2-12a83bf0f190.png)

**Comment by kyrie25** [comment]
The blank screen issue on Linux is mainly caused by not granting enough permissions, running Spicetify with root permissions, etc. If you're using a third-party distribution of Spotify, it can also cause unwanted behaviors.

Since the issue no longer persists on the `master` build, it is no longer relevant to keep this open.
