### ISSUE TITLE
spotify shows black on linux

### ISSUE THREAD

**Issue by TotallyThatSandwich** [spicetify/spicetify-cli#2315]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.84.716.gc5f8b819
- Spicetify version: 2.17.2
```

### 📝 Description

spotify shows black ones applied, if i restore it is fine but apon applying again it goes back to black, i have read every other issue i could and tried every solution i found

config:

```
[Preprocesses]
disable_sentry        = 1
disable_ui_logging    = 1
remove_rtl_rule       = 1
expose_apis           = 1
disable_upgrade_check = 1

[AdditionalOptions]
experimental_features = 0
extensions            = 
custom_apps           = 
sidebar_config        = 0
home_config           = 0

[Patch]

[Setting]
1spotify_path            = /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify/
current_theme           = Sleek
inject_css              = 1
replace_colors          = 1
check_spicetify_upgrade = 0
prefs_path              = /home/hamish/.var/app/com.spotify.Client/config/spotify/prefs
color_scheme            = Elementary
inject_theme_js         = 1
overwrite_assets        = 1
spotify_launch_flags    = 

; DO NOT CHANGE!
[Backup]
version = 1.1.84.716.gc5f8b819
with    = 2.17.2
```

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/100185552/235895672-c4fd0fea-76a7-4484-ba7a-6a3ecb27c34d.png)

**Comment by rxri** [comment]
1.1.84 isn’t supported by v2.17.2. Please update your spotify
