### ISSUE TITLE
Add support for those who have this?

### ISSUE THREAD

**Issue by Dnjey** [spicetify/spicetify-cli#2324]
### 📝 Provide a description of the new feature

Spicetify don't work with the new redesign of Spotify... 
Can you add support for those like me who have the same problem

Here's a picture of what i'm talking about:

![Screenshot 2023-05-04 195108](https://user-images.githubusercontent.com/132625574/236353411-ba6e8d97-9ff0-4321-b52a-68dd14f02b00.png)

Despite having installed Spicetify, the themes and plugins are not visible.

**Comment by rxri** [comment]
Spicetify does work with new UI. After installing theme, extension or custom app, you need to apply spicetify to reflect these changes in your Spotify client by “spicetify apply”
