### ISSUE TITLE
theme apply error

### ISSUE THREAD

**Issue by sleeplessKomodo** [spicetify/spicetify-cli#2325]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.8.923-1.fc37
- Spicetify version: 2.18.0
- OS: Linux
- Distribution: Fedora 37 (Nobara)
```

### 📝 Description

invoke the spicetify-cli command on linux, like so:

```Markdown
$ spicetify-cli apply

spicetify vDev
open /usr/bin/spotify/Apps: not a directory
```

or

```Markdown
$ spicetify-cli update

spicetify vDev
open /usr/bin/spotify/Apps: not a directory

```

why is is looking for an "Apps" directory? For me, /usr/bin/spotify is an executable script, made by the official linux build of spotify. Is this a windows or mac directory that spicetify is configured to look for?

**Comment by kyrie25** [comment]
https://spicetify.app/docs/advanced-usage/installation#spotify-installed-from-snap

Also change your `config-xpui` to point to such directory.
