### ISSUE TITLE
[Lyrics Plus]当切换歌曲时，歌词并未随之正确切换，而是停留在第一次播放的歌曲上

### ISSUE THREAD

**Issue by WilliamWangshao** [spicetify/spicetify-cli#2331]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:Spotify macOS (Intel) 版 1.2.10.760.g52970952
- Spicetify version:Spicetify v2.18.0
```

### 📝 Description

当切换歌曲时，歌词并未随之正确切换，而是停留在第一次播放的歌曲上。
重启app才正常，然后会继续复现。

如下图，歌曲为纯中文歌曲，歌词仍停留在上一首英文歌曲上

### 📸 Screenshots

![截屏2023-05-07 20 01 37](https://user-images.githubusercontent.com/33147340/236676142-76bdfac2-dd99-4066-9b0a-e3ab41b4ec4c.png)

**Comment by rxri** [comment]
Please open an issue in English
