### ISSUE TITLE
Error with user.css on fedora 38

### ISSUE THREAD

**Issue by MarkKoval** [spicetify/spicetify-cli#2332]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.9.743.g85d9593d
- Spicetify version: 1.2.1
```

### 📝 Description

I`m using FlatPak version Spotify, but I can`t install spicetify, terminal give me this error: fatal open /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify/Apps/zlink/css/user.css: no such file or directory

how can I fix it? (previously I used fedora 38 and it works stable)

### 📸 Screenshots

![Screenshot from 2023-05-07 20-09-06](https://user-images.githubusercontent.com/45714591/236692163-8e2e3e2b-8a3c-4c83-87a3-40450200b856.png)

**Comment by theRealPadster** [comment]
Your spicetify version is super old. I'd try updating that to the latest first.

**Comment by rxri** [comment]
Sorry, we do not provide support for legacy version of spicetify

**Comment by MarkKoval** [comment]
update the manual, people are having problems because of it

**Comment by theRealPadster** [comment]
Update what in the manual? Making sure you have the latest version of whatever software you're using is generally one of the first things you do when you're troubleshooting problems.
