### ISSUE TITLE
Spiceify required sudo access to change theme 

### ISSUE THREAD

**Issue by Besufikad17** [spicetify/spicetify-cli#2333]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.84
- Spicetify version: 2.17
```

### 📝 Description

I followed the instructions in each theme github page on how to install and set themes but when i try to run spicetify apply i am getting permission denied error. fyi i installed spotify in flatpak (OS, fedora 37)

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/64811433/236743005-51af9a41-e6cd-45dd-b8e9-10f6d829378f.png)

**Comment by kyrie25** [comment]
https://spicetify.app/docs/advanced-usage/installation#spotify-installed-from-flatpak
