### ISSUE TITLE
Can't find the element for the song times

### ISSUE THREAD

**Issue by End3rdragon1234** [spicetify/spicetify-cli#2339]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.10.760.g52970952
- Spicetify version: v2.17.2
```

### 📝 Description

Not really a bug but, I can't find the element to change the color of the song times in theme dev tools. Can someone tell me where it is?

**Comment by kyrie25** [comment]
- Theme Dev Tools is a Marketplace feature, not related to the CLI.
- Discussion and questions should be forwarded to the Discord server.

Not an issue.
