### ISSUE TITLE
the most recent update (spicetify / spotify desktop) makes the "what's new" panel on right side completely unusable

### ISSUE THREAD

**Issue by davai124asf** [spicetify/spicetify-cli#2346]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.11.916.geb595a67 - MacOS (Apple Silicon) 
- Spicetify version: v2.18.1
```

### 📝 Description

When you click on the alarm button to see the "WHAT'S NEW" panel (basically new releases) on the right side on the Spotify Desktop, the feature seems to be trying to grab the data from somewhere but is unable to update it. So it's completely unusable as nothing happens when you click on the alarm button besides the message that populates after a few seconds which reads as follows: "SOMETHING WENT WRONG. THERE HAS BEEN AN ERROR WHILE FETCHING UPDATES."

I've tried everything, including: deleting Spotify & Spicetify; rebooting computer; updating Spotify & Spicetify; turning hardware acceleration off / then on; flushing DNS; playing around with the experimental feature settings; toggling the "What's New" panel off and then back on; etc. Nothing works, however, before this most recent update - this feature was working just fine and showed the same new songs / new albums that you see on your phone when looking at new releases. Not sure what happened between that time and this latest update. 

### 📸 Screenshots

<img width="1389" alt="Screenshot 2023-05-12 at 7 22 43 PM" src="https://github.com/spicetify/spicetify-cli/assets/133454045/6e5f07a2-8e1f-4344-9948-2d7af88910eb">
<img width="1374" alt="Screenshot 2023-05-12 at 7 23 57 PM" src="https://github.com/spicetify/spicetify-cli/assets/133454045/3ef61391-52c7-4994-bc04-11a10d521481">

**Comment by rxri** [comment]
We do not tamper with `What's new` functionality, so your issue most likely doesn't come because of spicetify. This is still new and I believe it's still behind Experimental Features so, it can be buggy or broken like in your case.
If you need help with that, please check out our discord server
