### ISSUE TITLE
Cover art image class names don't get replaced with values from the css map.

### ISSUE THREAD

**Issue by SunsetTechuila** [spicetify/spicetify-cli#2354]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.11.916.geb595a67
- Spicetify version: v2.18.1
- Windows 10 22h2
```

### 📝 Description

Class names H0HbpIM3UrcupWIAjLWu, FqmFsMhuF4D0s35Z62Js, W0TACB7OY0iXtKVOtEhY, zmOtW0vqqn1qpZrtQ_w9 don't get replaced with [values](https://github.com/spicetify/spicetify-cli/blob/b30f214dbde551c83a04ee22d720dece3609ad38/css-map.json#L2336) from the css map.

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/115353812/93f23b4f-38f1-4f93-a16f-c2f5a1b7fbe4)

**Comment by rxri** [comment]
has been fixed in https://github.com/spicetify/spicetify-cli/commit/b30f214dbde551c83a04ee22d720dece3609ad38

**Comment by SunsetTechuila** [comment]
so I should just wait?

**Comment by SunsetTechuila** [comment]
Deleting css-map.json and re-applying worked, thanks. It would be nice if Spicetify would update the css map automatically when needed. At least when using spicetify apply/upgrade (without new app version) commands

**Comment by kyrie25** [comment]
> Deleting css-map.json and re-applying worked, thanks. It would be nice if Spicetify would update the css map automatically when needed. At least when using spicetify apply/upgrade (without new app version too) commands 

Deleting your local CSS map is not needed. As long as you have an active Internet connection, running `spicetify restore backup apply` will automatically get the latest mappings.
