### ISSUE TITLE
Broken UI

### ISSUE THREAD

**Issue by Mardart** [spicetify/spicetify-cli#2357]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: newes
- Spicetify version: 2.17.0
```

### 📝 Description

Ui broken bug 

### 📸 Screenshots

![2023-05-17_15h28_13](https://github.com/spicetify/spicetify-cli/assets/133882468/54e76cbd-9ad9-467e-9118-1500439dab04)

**Comment by kyrie25** [comment]
Theme issue, not related to the CLI.
