### ISSUE TITLE
unable to play songs directly from an artist's discography 

### ISSUE THREAD

**Issue by fawnyeo** [spicetify/spicetify-cli#2365]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.11.916.geb595a67
- Spicetify version:2.17.2
```

### 📝 Description

i am able to play the songs from the artist's popular songs, but when clicked into their discography, i am unable to play songs from both album and singles/eps.

### 📸 Screenshots

https://github.com/spicetify/spicetify-cli/assets/102406279/8a6779c6-cafb-455a-b5bf-4c6bc0c7904a

**Comment by rxri** [comment]
It's not spicetify related issue. We do not change anything regarding playback. Try reinstalling Spotify
