### ISSUE TITLE
Documentation Issues (with resolutions) - PopOs Flatpak

### ISSUE THREAD

**Issue by error-try-again** [spicetify/spicetify-cli#2366]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Software
- Spotify version: 1.2.11.916.geb595a67 - 15 May 2023
- Spicetify version: 2.18.1
- PopOs! version: 22.04
- KDE version: 5.24.7
- Qt version: 5.15.3
- Kernel version: 6.2.6-67060206-generic x64
- X11
```

### 📝 Description

Using ZSH to install, I initially experienced the following error when running `curl -fsSL https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.sh | sh` 
```
6:49:28 void@null ~ curl -fsSL https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.sh | sh
FETCHING Version 2.18.1
CREATING /home/void/.spicetify
DOWNLOADING https://github.com/spicetify/spicetify-cli/releases/download/v2.18.1/spicetify-2.18.1-linux-amd64.tar.gz
######################################################################## 100.0%
EXTRACTING /home/void/.spicetify/spicetify.tar.gz
SETTING EXECUTABLE PERMISSIONS TO /home/void/.spicetify/spicetify
REMOVING /home/void/.spicetify/spicetify.tar.gz
sh: 81: [: .zshrc: unexpected operator
spicetify path already set in /home/void/.zshrc, continuing...

spicetify v2.18.1 was installed successfully to /home/void/.spicetify
Run 'spicetify --help' to get started
```

Which was resolved by running 
```
6:49:34 void@null ~ curl -fsSL https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.sh | zsh
FETCHING Version 2.18.1
CREATING /home/void/.spicetify
DOWNLOADING https://github.com/spicetify/spicetify-cli/releases/download/v2.18.1/spicetify-2.18.1-linux-amd64.tar.gz
######################################################################## 100.0%
EXTRACTING /home/void/.spicetify/spicetify.tar.gz
SETTING EXECUTABLE PERMISSIONS TO /home/void/.spicetify/spicetify
REMOVING /home/void/.spicetify/spicetify.tar.gz
spicetify path already set in /home/void/.zshrc, continuing...

spicetify v2.18.1 was installed successfully to /home/void/.spicetify
Run 'spicetify --help' to get started
```

I had a look at the [install docs for flatpaks](https://spicetify.app/docs/advanced-usage/installation) 
But the instructions didn't line up for me.. The binary wasn't in `/var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify/` and the `flatpak --installations` command didn't perform as expected:

```
6:55:24 void@null flatpak flatpak --installations
/var/lib/flatpak
6:55:32 void@null flatpak ls /var/lib/flatpak
overrides  repo
```
After about 15 minutes of searching I found where flatpak had installed spotify 
```
~/.local/share/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify
```

Also the documentation for installing the prefs_path was wrong..
`spicetify config prefs_path ~/.var/app/com.spotify.Client/config/spotify/prefs`
It should be: 
`spicetify -c prefs_path ~/.var/app/com.spotify.Client/config/spotify/prefs`

so to resolve it in `/home/void/.config/spicetify/config-xpui.ini` I had to use the following configuration

```
[Setting]
prefs_path              = /home/void/.var/app/com.spotify.Client/config/spotify/prefs
spotify_path            = /home/void/.local/share/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify
color_scheme            =
```

`void@null:~
 $ spicetify backup apply enable-devtools
`

Then I could finally install comfy theme
`curl -fsSL https://raw.githubusercontent.com/NYRI4/Comfy-spicetify/main/install.sh | zsh`

Let me know if you need any additional documentation

**Comment by rxri** [comment]
Actually, documentation states that you need to find this directory by yourself because it's dependent on your distro. About changing config, `spicetify config` should work just fine.

If you want to report an issue in documentation, please open it in https://github.com/spicetify/spicetify-docs repo
