### ISSUE TITLE
[New Releases] Cannot read properties of undefined (reading 'DragHandler')

### ISSUE THREAD

**Issue by guttitto** [spicetify/spicetify-cli#2371]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.11.916.geb595a67 (Windows)
- Spicetify version: 2.18.1
```

### 📝 Description

Something went wrong appears while trying to load the New Releases custom app.

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/25709670/23c890fc-18dc-4d44-9ed2-05eada9fa789)

**Comment by kyrie25** [comment]
`master` build custom apps must be used with `master` build CLI
