### ISSUE TITLE
[New Releases]: Display new releases as a list of albums (i.e. like `Artist -> Discography -> Show All`)

### ISSUE THREAD

**Issue by sandersantema** [spicetify/spicetify-cli#2373]
### 📝 Provide a description of the new feature

On an artists page you can go to their discography click on `Show All` and get a list of all their albums such that you can play the whole discography consecutively i.e. it is added to `Up Next`.

The advantage of this is that you can go trough all new releases and get an overview of them without having to click on all albums separately.

### ➕ Additional Information

Here's the `Artist -> Discography -> Show All` view:
![image](https://github.com/spicetify/spicetify-cli/assets/21057514/f262c271-b2b9-4940-86ac-9efb4c43725d)

And here's the new releases view:
![image](https://github.com/spicetify/spicetify-cli/assets/21057514/cb40b115-fad7-402a-8b43-9b7a5e562f65)

**Comment by ohitstom** [comment]
i think you are misunderstanding the function of the new releases page.

**Comment by karimawii** [comment]
I kinda prefer the current layout ngl

**Comment by sandersantema** [comment]
I'd assume that if this feature were to be added it would be a preference, meaning you can keep using the current layout.

But the feature request is not really about the layout itself but the functionality it provides. Using the current layout you have to click on each album separately if you want to listen trough them, while you can click once on a song using `Artist -> Discography -> Show All` and listen through all albums. It furthermore allows you to see the songs in an album without again having to click.

Those clicks add up if you're going through a lot of releases :)

**Comment by Aimarekin** [comment]
Alternatively, you could make an extension that queues up an artist's entire discography.

**Comment by ohitstom** [comment]
> I'd assume that if this feature were to be added it would be a preference, meaning you can keep using the current layout.
> 
> But the feature request is not really about the layout itself but the functionality it provides. Using the current layout you have to click on each album separately if you want to listen trough them, while you can click once on a song using `Artist -> Discography -> Show All` and listen through all albums. It furthermore allows you to see the songs in an album without again having to click.
> 
> Those clicks add up if you're going through a lot of releases :)

the whole point of new releases is to play new releases, not everything that is a new release is a full album and often it's 1 song in an album by an artist you follow, and having the discography layout wouldn't make sense.

**Comment by ohitstom** [comment]
![image](https://github.com/spicetify/spicetify-cli/assets/22730962/2e9616bb-740f-4e3c-a20d-11c2e2db3b9b)
![image](https://github.com/spicetify/spicetify-cli/assets/22730962/03250ec8-5c58-418f-83f8-c064b9d2aeb6)
It looks like spotify is moving towards doing exactly this, currently it uses the same system we do but given the layout they will likely add tracklists like discography soon...

**Comment by rxri** [comment]
Spotify removed the endpoints we used for it in `1.2.25` which means that we're deprecating `New Releases`. Due to this, this issue will be closed. Please use `What's New` page which provides the same data.
