### ISSUE TITLE
Allow sorting of `Artist -> Discography -> Show All` by release date ascending

### ISSUE THREAD

**Issue by sandersantema** [spicetify/spicetify-cli#2374]
### 📝 Provide a description of the new feature

Currently the releases shown in `Artist -> Discography -> Show All` are sorted by descending release date. I'd like to be able to to sort them by release date ascending as well, i.e. the oldest releases are shown first.

### ➕ Additional Information

For example this dead simple mock up where the user can choose what to sort by using the `Sort` dropdown indicated by the red arrow.
![image](https://github.com/spicetify/spicetify-cli/assets/21057514/169d0523-9513-4bea-82ac-1288bee2817d)

**Comment by kyrie25** [comment]
Make an extension suggestion on Discord.
Not related to CLI.
