### ISSUE TITLE
Sound suddently lowers while changing between songs.

### ISSUE THREAD

**Issue by Joaozinhodopineu2** [spicetify/spicetify-cli#2376]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.12.902.g1924b088
- Spicetify version: v2.18.1
```

### 📝 Description

At the end of each song right at the turning point the sound suddently lowers and then fixes itself, this only happens to some songs (some are really noticeable and other seem to not have this problem).

This bug only happend when I applied the marketplace, I've tried un-installing my spotify and even updated it to the latest version but this bug persists.

This is a audio bug so I have no screenshots.

**Comment by rxri** [comment]
We do not interact with audio so unfortunately, it's not cli issue
