### ISSUE TITLE
D

### ISSUE THREAD

**Issue by Skinny957** [spicetify/spicetify-cli#2377]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows
1.2.12.902.g1924b088
Spicetify v2.16.0
```

### 📝 Description

When opening the DJ feature on the normal desktop app it plays immediately when opening it on spicetify it thinks its a playlist and I can play it 

The expected out come is for it to start to play but when I click it comes up with the second screenshot
also when there should be the DJ skip button too if you are able to add it

### 📸 Screenshots

![Screenshot 2023-05-26 153731](https://github.com/spicetify/spicetify-cli/assets/107206243/dcb7b4f1-fe5f-4950-9cb1-f24fbded0435)
![image](https://github.com/spicetify/spicetify-cli/assets/107206243/ae651c3a-5d5c-499c-b3fb-cbf665a62ab6)
![image](https://github.com/spicetify/spicetify-cli/assets/107206243/52d61941-10e1-480a-9a26-e68b7e2e1993)
(image 3 is expected outcome)

**Comment by rxri** [comment]
DJ is an experimental feature made by Spotify. This has nothing to do with spicetify and we do not provide support for these features.
