### ISSUE TITLE
Weird UI on latest spotify

### ISSUE THREAD

**Issue by NaufalF22** [spicetify/spicetify-cli#2379]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows 1.2.12.902.g1924b088
- Spicetify version: 2.8.1
```

### 📝 Description

Something about UI on latest spotify is change so my spotify with dribbblish theme have very fucked up UI

### 📸 Screenshots

![gambar](https://github.com/spicetify/spicetify-cli/assets/63091744/dd96b7b6-0f3d-4b66-a0e9-db642423196c)

**Comment by kyrie25** [comment]
Theme issue. Not related to CLI.
