### ISSUE TITLE
Spicetify.URI: isArtist, isTrack & isAlbum always returning false

### ISSUE THREAD

**Issue by Davoleo** [spicetify/spicetify-cli#2380]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.12.902.g1924b088
- Spicetify version: v2.18.1
```

### 📝 Description

Found out when debugging URI.isArtist for specific uris like this one:
```js
Spicetify.URI.isArtist("spotify:artist:7p2S6p9yYGhJTtbTQFnsYZ"); //returns false in the console
```
Same thing for this example track:
```js
Spicetify.URI.isTrack("spotify:track:3fCO1n6l7yekcNRDRkoJJ4");
```
Also tested on album URIs:
```js
Spicetify.URI.isAlbum("spotify:album:6wJxfvqu3PHr5bAYKpSvoI")
```

I haven't tested all the other calls but knowing these basic ones don't work I'm guessing the other ones will probably be broken as well

Extra note: I've also tried parsing the URI into an object before calling the method like this:
```js
Spicetify.URI.isArtist(Spicetify.URI.fromString("spotify:artist:7p2S6p9yYGhJTtbTQFnsYZ")); //returns false in the console
```
As a workaround for this issue you can still access the `.type` member in a parsed URI object

**Comment by kyrie25** [comment]
Resolved via #2370, wait for next release
