### ISSUE TITLE
Lyrics Plus page crashes on open

### ISSUE THREAD

**Issue by yuqingc** [spicetify/spicetify-cli#2381]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 2.18.1
- Spicetify version: 2.18.1
- OS: MacOS 13.3.1 (a) (M1)
```

### 📝 Description

There is a JS error when I open the page of Lyrics Plus.

```
TypeError: Cannot read properties of null (reading 'clientWidth')
    at TopBarContent (spicetify-routes-lyrics-plus.js:2556:58)
    at na (vendor~xpui.js:29:4848483)
    at js (vendor~xpui.js:29:4900608)
    at Ol (vendor~xpui.js:29:4887886)
    at Tl (vendor~xpui.js:29:4887814)
    at Al (vendor~xpui.js:29:4887677)
    at ml (vendor~xpui.js:29:4884664)
    at vendor~xpui.js:29:4834402
    at t.unstable_runWithPriority (vendor~xpui.js:29:5106616)
    at Ji (vendor~xpui.js:29:4834179)
a
```

### 📸 Screenshots

<img width="1272" alt="image" src="https://github.com/spicetify/spicetify-cli/assets/29723652/db379889-a29b-4a9d-bfc1-5049abdd5c3b">

**Comment by rxri** [comment]
Spotify version “2.18.1” doesn’t exist. Also, it’s a bug on your end. Try reinstalling Spotify (delete it first with AppCleaner)

**Comment by yuqingc** [comment]
Sorry, I made a mistake about the version. 2.18.1 is spicetify version. Spotify version is 1.2.12.902.g1924b088
<img width="486" alt="image" src="https://github.com/spicetify/spicetify-cli/assets/29723652/22ff5fc1-e920-4302-8322-be89b9185f8b">

**Comment by kyrie25** [comment]
Caused because you're using an outdated CSS mapping version.
Run `spicetify restore backup apply` or reinstall the client like ririxi said.

**Comment by yuqingc** [comment]
> Caused because you're using an outdated CSS mapping version. Run `spicetify restore backup apply` or reinstall the client like ririxi said. You may have to allow Spicetify in your firewall to fetch the latest mappings.

Thanks bro. Yes, it seems to be the CSS problem because the cli prompts "Cannot fetch remote CSS map  Using local CSS map instead...".  when I run `spicetify restore backup apply. There might be an error of my network. I'm trying to fix my network. Thanks!

**Comment by yuqingc** [comment]
> Caused because you're using an outdated CSS mapping version. Run `spicetify restore backup apply` or reinstall the client like ririxi said. You may have to allow Spicetify in your firewall to fetch the latest mappings.

Thanks bro. Yes, it seems to be the CSS problem because the cli prompts "Cannot fetch remote CSS map  Using local CSS map instead...".  when I run `spicetify restore backup apply. There might be an error of my network. I'm trying to fix my network. Thanks!
