### ISSUE TITLE
Let the `test` function return a boolean or throw an error.

### ISSUE THREAD

**Issue by Qwerty-133** [spicetify/spicetify-cli#2382]
### 📝 Provide a description of the new feature

The [`Spicetify.test`](https://github.com/spicetify/spicetify-cli/blob/3e8954f4c08036a722c99ad9292d26b47b103fc4/jsHelper/spicetifyWrapper.js#L83C1-L260) function currently just logs errors if any methods are unavailable, if it additionally returns `true` if everything's fine then it can be used in extensions.

**Comment by kyrie25** [comment]
An extension doesn't need for every method to be available, nor does it need to use all of it.
It is meant for CLI devs to easily catch on which component has broken on latest versions.
Cross-reference other extensions on how to wait for a method to finish initializing.
