### ISSUE TITLE
Spotify live reload does not work

### ISSUE THREAD

**Issue by Teenarp2003** [spicetify/spicetify-cli#2384]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.11.916
- Spicetify version: 2.16.1
```

### 📝 Description

i have a custom colors.ini with pywal that inputs colors from xrdb . the theming works fine. 
Hoever spicetify does not live reload colors.. 
Ctrl + Shift + R does nothing.. 
```spicetify watch -l``` restarts spotify once but does not detect subsequent color changes. 
```spicetify watch -s```  also same response. 
I referred to issue number #1091 and none of the listed fixes work for me.

**Comment by kyrie25** [comment]
Outdated Spicetify version.
Run `spicetify upgrade` then `spicetify restore backup apply`

**Comment by Teenarp2003** [comment]
upgraded spicetify but still no change

**Comment by kyrie25** [comment]
For further context, `watch` can only detect filesystem changes, as for all other watch methods.
If you're trying to modify the color using an external source (e.g. system variables) it won't be able to detect changes.

**Comment by Teenarp2003** [comment]
okay thanks for your help!
