### ISSUE TITLE
Spicetify broken after update

### ISSUE THREAD

**Issue by Mavoy** [spicetify/spicetify-cli#2388]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:  1.2.12.902.g1924b088
- Spicetify version: 2.19.0
- Windows 10
```

### 📝 Description

Maybe stupid question but... saw the icon informing me about new Spicetify version, so, kinda mindlessly, I've put these two commands in powershell as suggested

spicetify upgrade
spicetify restore backup apply

It did upgrade to 2.19.0, but unfortunately it's freezing now on a blank window with three dots at the top and I can't use it. I can do "restore" and go back to normal Spotify, but Spicetify is broken.

Is my backup ruined? Do I have to restart the app now? Do I have to do something else? I'd rather have you guys take it over from here.

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/21195105/a063e383-28e0-41a7-8f2b-0cbb32b03827)

**Comment by kyrie25** [comment]
User issue not a bug.
Reinstall Spotify if needed then run `spicetify backup apply`
