### ISSUE TITLE
Does Not Block any Ad

### ISSUE THREAD

**Issue by ItssJxstnDe** [spicetify/spicetify-cli#2392]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Newest
- Spicetify version: Newest
```

### 📝 Description

It does not Block any Ad

**Comment by kyrie25** [comment]
Spicetify is ***not*** an adblocker.
