### ISSUE TITLE
Hover Panel Issue

### ISSUE THREAD

**Issue by Endy48** [spicetify/spicetify-cli#2398]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Latest Version
- Spicetify version: Latest Version
```

### 📝 Description

What to do when I install 'hover panels' on Spicetify and I can view options like 'marketplace' even though I tried hovering it and it didn't show ?

### 📸 Screenshots

I cannot send videos and some photos here for no reason😔

**Comment by Endy48** [comment]
![IMG_20230605_214337](https://github.com/spicetify/spicetify-cli/assets/135624171/c2a57b32-4542-4358-935d-dcb1d0654f65)
Cannot hover onto panel eventho I djd

**Comment by rxri** [comment]
Not cli related
