### ISSUE TITLE
Themes and extentions suddenly isn't responding. 

### ISSUE THREAD

**Issue by MarioIbrahem1** [spicetify/spicetify-cli#2399]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.12.902.g1924b088
- Spicetify version:v2.20.0
```

### 📝 Description

I had installed my fav extentions and themes, but yesterday when I tried to activate them using the command 'spicetify apply', after the program reloaded and started again, nothing was working. The ads were showing up as usual and the full screen mode wasn't working either.
Therefore, please solve the problem quickly as I really need the program. I have been using spicetify for a long time, about more than a year, and this is the first time it has behaved like this.

**Comment by kyrie25** [comment]
Run `spicetify restore backup apply` or clean reinstall Spotify & Spicetify.
