### ISSUE TITLE
Bookmark issue 

### ISSUE THREAD

**Issue by thegoldknight** [spicetify/spicetify-cli#2404]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.13.661.ga588f749
- Spicetify version: 2.20.0
```

### 📝 Description

On clicking certain bookmarked songs in the bookmark tab, it takes you to the place where you were when the song was bookmarked (eg the playlist you were looking at when you bookmarked it) instead of the album oft the song itself.

**Comment by kyrie25** [comment]
Not a bug. Bookmark stores to context of the song.
