### ISSUE TITLE
After Lyrics Plus Is Gone

### ISSUE THREAD

**Issue by pinglingalvin** [spicetify/spicetify-cli#2410]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.13.661.ga588f749
- Spicetify version:2.17.2
```

### 📝 Description

After Update spotify and spicetify the lyrics plus is gone and can't be used any tips?

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/120280602/db795ce5-e520-4091-84bb-41ee66e38d05)

**Comment by kyrie25** [comment]
Outdated Spicetify version. Latest Spicetify version is `2.20.0`
Run `spicetify upgrade` then `spicetify restore backup apply`.

**Comment by kyrie25** [comment]
You installed Spicetify via Chocolatey then update using it.
Run `choco upgrade spicetify` then `spicetify restore backup apply`.

Github Issues are **not** support tickets, if you need help you can make a support ticket on our Discord server.

**Comment by pinglingalvin** [comment]
i just reinstall the 

> choco upgrade spicetify-cli

![image](https://github.com/spicetify/spicetify-cli/assets/120280602/14a8bdd5-d8b2-4b1d-a971-b92b4ffce781)
same problem, access denied
