### ISSUE TITLE
Spicetify not working

### ISSUE THREAD

**Issue by Mythi3** [spicetify/spicetify-cli#2411]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.13.661.ga588f749 (not microsoft store version)
- Spicetify version: 2.20.0
- Cpu ryzen 7 2700x
- mem 32gb
- gpu 2070ti
```

### 📝 Description

When I try to load anything it shows that (look below). I tried to turn everything off (all the configs to 0) and that does not help too. I tried disabling all the extensions which didn't help. When I do spicetify restore backup the default spotify theme loads but I cannot get onto my liked songs. (see below also). I wouldn't mind using the default theme if everything loaded. I just need to be able to use the extensions as they are helpful.

### 📸 Screenshots

Not loading at all: ![image](https://github.com/spicetify/spicetify-cli/assets/118481823/96ab77e2-3462-47e6-b926-288dd80d88a0)
Liked songs not loading: ![image](https://github.com/spicetify/spicetify-cli/assets/118481823/f0f84398-48d5-4119-8dbf-b17ac6926d6c)

**Comment by rxri** [comment]
Uninstall spotify, remove anything related to spotify from `%appdata%` and `%localappdata%`, install it again and re-apply

**Comment by Mythi3** [comment]
same thing happened again, when I try to apply this is the log:

C:\Users\user>spicetify apply
spicetify v2.20.0
Copying raw assets:
OK
Transferring user.css:
OK
Applying additional modifications:
warning Sidebar X item not found, ignoring
OK
Transferring extensions:
OK
Transferring custom apps:
OK
success Spotify is spiced up!

> Uninstall spotify, remove anything related to spotify from `%appdata%` and `%localappdata%`, install it again and re-apply

**Comment by Mythi3** [comment]
fixed^^
