### ISSUE TITLE
Spicetify doesn't working

### ISSUE THREAD

**Issue by kantdye** [spicetify/spicetify-cli#2415]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.13.661.ga588f749
- Spicetify version: 2.20.0
- GPU: Radeon RX 580 
- CPU: AMD Ryzen 5 3600X 
- Memory: 16 gb
```

### 📝 Description

I just used Spotify as usual I use it, and at a random moment the "Something went wrong" error poped up. I tried to completely remove Spotify and Spicetify, and at some point the "The Spotify application is not responding" issue started to pop up to, but Spotify app running without issues. If I run "spicetify restore", Spotify working and no issues doesn't pop up.

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/128914534/ff29576c-a5c8-4956-bd33-4645b54239c8)
![image](https://github.com/spicetify/spicetify-cli/assets/128914534/8f5582dc-3991-4a5f-822f-2032ba809318)

**Comment by rxri** [comment]
Uninstall spotify - and remove any remaining stuff from `%localappdata%`, `%appdata%`, install again and use this command to apply: `spicetify backup apply`.
Closing as it's not an spicetify issue
