### ISSUE TITLE
[fullAppDisplay] The lyrics plus lyrics display is weird

### ISSUE THREAD

**Issue by Lseoksee** [spicetify/spicetify-cli#2416]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.13
- Spicetify version: 2.20.1
```

### 📝 Description

- Enable the lyrics plus view in fullAppDisplay.

### 📸 Screenshots

![Desktop Screenshot 2023 06 18 - 11 09 25 57](https://github.com/spicetify/spicetify-cli/assets/91320047/1597707b-f985-4a06-a626-5fce4af7aade)

**Comment by kyrie25** [comment]
Theme issue.

**Comment by Lseoksee** [comment]
> Theme issue.

This is the Default  theme

**Comment by WenchenWang** [comment]
same question
