### ISSUE TITLE
New releases tab pure blank

### ISSUE THREAD

**Issue by Horrid-12** [spicetify/spicetify-cli#2422]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.13.661.ga588f749
- Spicetify version: 2.20.1
```

### 📝 Description

New releases tab is blank

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/96373496/90581702-921e-47f3-bc7c-68eabe19d2b5)

**Comment by th3an7** [comment]
Hey
I know there is already fix pending but what about using this API?
```
https://api-partner.spotify.com/pathfinder/v1/query?operationName=queryWhatsNewFeed&variables=%7B%22offset%22%3A0%2C%22limit%22%3A50%2C%22onlyUnPlayedItems%22%3Afalse%2C%22includedContentTypes%22%3A%5B%5D%7D&extensions=%7B%22persistedQuery%22%3A%7B%22version%22%3A1%2C%22sha256Hash%22%3A%220dde13545a843b8a337ac2b0af03a1605a9427d67e268b4abc0d3375b56c1dc9%22%7D%7D
```

This is the API that Spotify itself uses to display new "What's New" section (available via experiments)
The response looks more less like this:
![image](https://github.com/spicetify/spicetify-cli/assets/13398380/42af401f-cb5d-4ccf-bde6-ffe27e66acd9)


Then you could filter those by release date and display them as it was before - I guess that's the only way as you cannot queue only for specific timeframe (unless some variable exists??)

**Comment by kyrie25** [comment]
> Hey I know there is already fix pending but what about using this API?
> 
> ```
> https://api-partner.spotify.com/pathfinder/v1/query?operationName=queryWhatsNewFeed&variables=%7B%22offset%22%3A0%2C%22limit%22%3A50%2C%22onlyUnPlayedItems%22%3Afalse%2C%22includedContentTypes%22%3A%5B%5D%7D&extensions=%7B%22persistedQuery%22%3A%7B%22version%22%3A1%2C%22sha256Hash%22%3A%220dde13545a843b8a337ac2b0af03a1605a9427d67e268b4abc0d3375b56c1dc9%22%7D%7D
> ```

It can only query **at max** 150 releases for **every** artist you have followed and pagination parameters does nothing. 
This would deprecate the `Time range` feature on New Releases configuration.
It also doesn't query `Compilation` and `Appears on` releases which would also deprecate those features.

![image](https://github.com/spicetify/spicetify-cli/assets/77577746/81b65dd2-f865-41f6-a4e5-45613bb1d57c)
![image](https://github.com/spicetify/spicetify-cli/assets/77577746/8054bfe2-ee08-4328-a8a2-bcd8d0e467b0)

**Comment by Idyllwilde** [comment]
It's still blank for me after updating to the latest version.

**Comment by kyrie25** [comment]
> It's still blank for me after updating to the latest version.

Run `spicetify upgrade` then `spicetify restore backup apply`
