### ISSUE TITLE
New Library Sidebar not changing with theme

### ISSUE THREAD

**Issue by Yasssiiin** [spicetify/spicetify-cli#2424]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows (32 bit)
1.2.14.1149.ga3ae422d
- Spicetify version: 2.20.1
Theme: DefaultDynamic / base
Extensions: default-dynamic.js, Vibrant.min.js, volumePercentageWrapper.js, imageOpener.js, spotifyGenres.js
Custom apps: marketplace
```

### 📝 Description

New Library in the new spoitfy update that shows your library similar to the one on Spotify Mobile Comes up always as dark or light and doesn't react with the theme i have ( default dynamic ) i tired updating the theme with no avail can someone help me find a fix? 
 

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/79786546/ec250718-83b4-45c1-875a-3dfd44d7cebd)

**Comment by rxri** [comment]
Not spicetify related issue
