### ISSUE TITLE
broken theme : how do i remove everything and reinstall

### ISSUE THREAD

**Issue by KiraiEEE** [spicetify/spicetify-cli#2428]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows 1.2.13.661.ga588f749

Spicetify v2.20.1
```

### 📝 Description

everything was okay, but once i installed another theme from marketplace it became like that

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/54278089/5d49f4f9-133c-401b-9cf4-e5945e18445e)

**Comment by rxri** [comment]
Not cli issue. For help please use our discord server

**Comment by KiraiEEE** [comment]
anyways i reinstalled spotify and everything using "everything search" and reinstalled them all and its perfectly fine now xD
