### ISSUE TITLE
Enabled experimental feature and unable to open experimental features

### ISSUE THREAD

**Issue by thegoldknight** [spicetify/spicetify-cli#2429]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for macOS (Apple Silicon)
1.2.13.661.ga588f749
Spicetify v2.20.1
```

### 📝 Description

I selected one of the home experimental features, and now I am unable to click my profile to turn the experimental feature off.
Is there a way to reset experimental features without clicking my profile? 
 
What the experimental feature looks like:
<img width="1439" alt="image" src="https://github.com/spicetify/spicetify-cli/assets/135397968/13c845df-a256-482e-b1a7-ce149e20d1d3">

**Comment by kyrie25** [comment]
Click on the Search bar and press <kbd>Tab</kbd> until it highlights the dropdown, then press <kbd>Enter</kbd> to open the dropdown.

Issues are **not** support tickets, please refrain from doing so in the future.
