### ISSUE TITLE
the adblock extention dont work

### ISSUE THREAD

**Issue by kzervas1** [spicetify/spicetify-cli#2431]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:latest i think
- Spicetify version:lastest(i updated it 5 minutes ago)
```

### 📝 Description

I have this extension installed(screenshot) and it is supposed to block ads but it is not working

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/75249595/8b76592a-82ef-48c4-8bda-59a11f2828e7)

**Comment by kyrie25** [comment]
Not a CLI issue.
