### ISSUE TITLE
Spicetify.exe Got Deleted via spicetify apply

### ISSUE THREAD

**Issue by Reno279** [spicetify/spicetify-cli#2434]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.5.1006
- Spicetify version:v2.20.1
```

### 📝 Description

When I type spicetify apply, it doesn't work and suddenly "spicetify.exe" is gone for some reason

### 📸 Screenshots

<img width="1216" alt="Screenshot 2023-06-24 215222" src="https://github.com/spicetify/spicetify-cli/assets/125335464/a6d8b553-b968-4be6-94e6-99db4e3a0fc5">
<img width="1189" alt="Screenshot 2023-06-24 215259" src="https://github.com/spicetify/spicetify-cli/assets/125335464/c3cc1b1b-6ac0-44a2-90c2-b61326a3b6dd">

**Comment by kyrie25** [comment]
Not a CLI issue.
Whitelist Spicetify from your antivirus.

**Comment by Reno279** [comment]
ok
