### ISSUE TITLE
[Lyrics Plus] Genius page crashes

### ISSUE THREAD

**Issue by Lseoksee** [spicetify/spicetify-cli#2435]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.14
- Spicetify version: 2.20.2
```

## This issue has occurred since #2343 was applied.
* Click Genius in lyrics plus
* Select the latest song without some lyrics and open lyrics plus

### 📸 Screenshots

* Click Genius

https://github.com/spicetify/spicetify-cli/assets/91320047/31e15b66-71bd-4971-bced-7dd51910f95f

* Select the latest song without some lyrics and open lyrics plus

https://github.com/spicetify/spicetify-cli/assets/91320047/a91cd5c7-a536-42fc-9374-677d7378d4f9

**Comment by kyrie25** [comment]
Can you screenshot the DevTools console log in both situations?

**Comment by kyrie25** [comment]
Then the PR should fix both
