### ISSUE TITLE
Feature Request - Allow app transparency on Mac

### ISSUE THREAD

**Issue by Explosion-Scratch** [spicetify/spicetify-cli#2439]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.14.1149.ga3ae422d
- Spicetify version: spicetify v2.20.2
```

### 📝 Description

You can't make the window transparent on Mac. This would be a good CLI flag/config setting. Then themes could look a lot more macOS-neutral

**Comment by kyrie25** [comment]
Not possible. We have no control over the executable itself.

**Comment by Explosion-Scratch** [comment]
> Not possible. We have no control over the executable itself.

Oh ok, darn
