### ISSUE TITLE
Cannot detect spotify location, open: not a directory

### ISSUE THREAD

**Issue by burgersarefat** [spicetify/spicetify-cli#2441]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for macOS (Intel) 1.2.14.1149.ga3ae422d
- Spicetify version: 2.20.2
```

### 📝 Description

Every time I try to run `spicetify backup apply`, the error is `error Cannot detect Spotify location. Please manually set "spotify_path" in config-xpui.ini`. I've set the spotify path to `/Users/bryan/Applications/Spotify.app/Contents/MacOS/Spotify`, and it gives me a new error: 
`open /Users/bryan/Applications/Spotify.app/Contents/MacOS/Spotify/Apps: not a directory`
I've tried reinstalling spotify, deleting .spicetify and .config/spicetify, but nothing works. I can do `spicetify restart`. My account is also a standard account. I've successfully installed the same version of spotify and spicetify on another Intel mac where my account is administrator, so I'm not sure if that affects the installation.

### 📸 Screenshots

a

**Comment by kyrie25** [comment]
https://spicetify.app/docs/advanced-usage/installation/#linux-and-macos

**Comment by kyrie25** [comment]
Issues are not support tickets.

If you need help please make a support ticket on our Discord server.
