### ISSUE TITLE
A theme that changes the color of the interface depending on the color of the song

### ISSUE THREAD

**Issue by KapibaraUa** [spicetify/spicetify-cli#2445]
### 📝 Provide a description of the new feature

Tell me, was there once a theme that changed the color of the interface to match the color of the song, is it still there? if not please do

**Comment by rxri** [comment]
Not cli related, please use our discord server for that kind of feature requests

**Comment by theRealPadster** [comment]
@KapibaraUa Marketplace has that feature in the settings, or some other themes have their own, like Nord.
