### ISSUE TITLE
Broken UI upon Spotify V1.2.14

### ISSUE THREAD

**Issue by Caramel-Heaven** [spicetify/spicetify-cli#2449]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.14.1149.ga3ae422d
- Spicetify version: 2.20.3
```

### 📝 Description

Upon Spotify updating to 1.2.14, the UI side of things went bonkers and it's kinda annoying.
Sorry if this issue had been raised already.

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/138136781/626adb1a-719b-44ee-a33a-8205b1020598)

**Comment by kyrie25** [comment]
Theme issue.
