### ISSUE TITLE
Unable to install spotify via its repository in order to allow spicetify to have access

### ISSUE THREAD

**Issue by Nebzla** [spicetify/spicetify-cli#2450]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Latest
- Spicetify version: 2.20.3
```

### 📝 Description

I am running Ubuntu 22.04 and through following the documentation i am told to uninstall the snap version that i currently have to install it through the repository instead, however in doing so, i get an error saying that there is no longer a release file available to download, even spotifys official website has the same instructions that do not function. I'm aware that this is not directly related, however i have to uninstall the snap version in order to get spicetify to function on linux and i dont see anyone over at spotify being able to help. Thanks

**Comment by kyrie25** [comment]
Not a CLI issue.

**Comment by Nebzla** [comment]
Mind pointing me to where i can get help then instead of just closing the issue? I don't know where else to ask and that response isn't very helpful
