### ISSUE TITLE
Blank spotify

### ISSUE THREAD

**Issue by CoolJosh0221** [spicetify/spicetify-cli#2451]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 2.16.0
- Spicetify version: 1.2.14.1149.ga3ae422d
MacOS Monterey 12.6 (Apple Silicon)
```

### 📝 Description

I've reinstalled spicetify and Spotify because of the theme issue. Now, when I run `spicetify restore backup apply`, the Spotify's screen is blank.

I've checked #1939, nothing works for me.

### 📸 Screenshots

<img width="1728" alt="Screen Shot 2023-07-01 at 10 40 15 AM" src="https://github.com/spicetify/spicetify-cli/assets/88709160/860dad65-995f-4457-b6a2-cdb6702cc519">
This is just a blank screen, maybe it's not worth looking at it.

**Comment by kyrie25** [comment]
Outdated Spicetify version. Latest Spicetify version is `2.20.3`
Run `spicetify upgrade` and `spicetify restore backup apply`.
