### ISSUE TITLE
Stream Youtube video in Spotify

### ISSUE THREAD

**Issue by thenameskayla** [spicetify/spicetify-cli#2452]
### 📝 Provide a description of the new feature

A plugin where you can drop a YouTube link into Spotify and it will stream just the audio through the Spotify app, awesome for long YouTube videos I would love to have integrated into Spotify itself.

### ➕ Additional Information

Have some form of textbox to copy and paste YouTube links? (potentially toggle-able through a little YouTube logo?)
Just drag and drop a YouTube link into the client window?

**Comment by kyrie25** [comment]
Make a suggestion on the Discord server. Feature Request issues are for the CLI only.
