### ISSUE TITLE
"Enable Your Library X view of the left sidebar" not there in Experimental settings

### ISSUE THREAD

**Issue by Cryptic1526** [spicetify/spicetify-cli#2453]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (32 bit)
1.2.14.1149.ga3ae422d
Spicetify v2.20.3
Theme: SpotifyNoPremium / Base
Extensions: adblock.js
Custom apps: marketplace
```

### 📝 Description

I used the experiment because the new UI looks like absolute garbage, and the only way I got it to go away was to turn that experiment on. Now it's not in the list. Is there any way to get it back?

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/119151348/cad146ee-921b-43ad-bc28-2348eb2eec32)

![image](https://github.com/spicetify/spicetify-cli/assets/119151348/daa19687-50a1-44ac-b01f-e0d56651c5d7)

**Comment by kyrie25** [comment]
Not a CLI issue.

Option has been removed on Spotify `1.2.14`

**Comment by Resxt** [comment]
@Cryptic1526 you have to downgrade Spotify to the latest 1.2.13 version (or earlier) and block updates. The option will be there for you to untick, like I did.
There's a guide on how to downgrade and block updates on Spicetify's Discord server, in the #faq channel

**Comment by Cryptic1526** [comment]
Thanks, I'll check out the FAQ
