### ISSUE TITLE
Spicetify isn't working after spotify update at all

### ISSUE THREAD

**Issue by JoeSayed2007** [spicetify/spicetify-cli#2454]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.14.1149 for Windows
- Spicetify version: 2.20.3
```

### 📝 Description

first spotify was updated a month ago and spicetify didn't work that time i searched for a solution but they said that spotify has changed and spicetify team has to rerwrite the whole asset so I uninstalled spicetify that day, but today I downloaded it again after the update for both spotify and spicetify and it says that it supports the latest version (1.2.14 on Windows) but it didn't work at all the marketplace was successfully added but when I download a theme or an extension it doesn't work at all

**Comment by rxri** [comment]
Not cli issue. Please join our discord server for general help because your issue is related to marketplace
