### ISSUE TITLE
None of the theme's nor the extentions are working, the only mostly working thing is snippets

### ISSUE THREAD

**Issue by omaksahbety** [spicetify/spicetify-cli#2456]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.14.1149.ga3ee422d
- Spicetify version:2.20.3
```

### 📝 Description

all the themes and extentions don't work, ive tried reinstalling spotify, downgrading it, reinstalling spicetify, none of themworked properly, instead im given an error saying 
"Error: Class name list not found; please create an issue"

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/138420282/d8cbaa83-aa38-4f6c-922b-a8e173aabfe9)

**Comment by kyrie25** [comment]
Not a CLI issue.
