### ISSUE TITLE
Spicetify jumps to 100%+ cpu when music plays

### ISSUE THREAD

**Issue by thegoldknight** [spicetify/spicetify-cli#2457]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for macOS (Apple Silicon)
1.2.14.1149.ga3ae422d
Spicetify v2.20.3

MacBook Pro 13 in, M1, 2020
8 GB ram
```

### 📝 Description

Spicetify (Spotify renderer) jumps to over 100% in cpu when music plays; I've tried enabling hardware acceleration which drops it to 40% but still pretty high. Spotify by itself without spicetify doesn't have this problem (only takes up 1–4%). 

### 📸 Screenshots

<img width="274" alt="image" src="https://github.com/spicetify/spicetify-cli/assets/135397968/c5948564-3ee1-4650-9f73-3087a762c1a0">

**Comment by kyrie25** [comment]
Not a CLI issue. Remove whichever theme/extension you have running.

**Comment by thegoldknight** [comment]
Is there a way to uninstall a theme when it was installed manually?

**Comment by kyrie25** [comment]
```
spicetify config current_theme theme_name-
spicetify apply
```
