### ISSUE TITLE
Not working on macOS (Apple Silicon) + Spotify not loading blacked screen

### ISSUE THREAD

**Issue by Flair001** [spicetify/spicetify-cli#2458]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for macOS (Apple Silicon)
1.2.14.1149.ga3ae422d
- Spicetify version:
curl -fsSL https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.sh | sh
and
curl -fsSL https://raw.githubusercontent.com/spicetify/spicetify-marketplace/main/resources/install.sh | sh
```

### 📝 Description

When I correctly followed the instructions of how to download Spicetify marketplace on Spotify, it suddenly could not load and the screen was just black and I couldn't click on any tabs or buttons on the menu-line on mac in the Spotify Application. I did run spicetify apply backup, etc. as admin on my terminal and everything was executed succesfully, but not after the app closed because I ran the command, then it just suddenly stopped and I couldn't load the home screen on Spotify (it some sort of freezed).

I don't know what I did wrong or maybe I am missing something, but I got the newest kinda mac/linux design in Spotify, and all the videos about how you install this are on the older version of Spotify. Maybe that's the problem?

Anyone knows? Please help me! :)

**Comment by kyrie25** [comment]
- Issues are **not** support tickets (#2238).
Make a support ticket in our Discord server for general help.

- Do **not** run Spicetify as admin.
https://spicetify.app/docs/advanced-usage/installation#linux-and-macos
