### ISSUE TITLE
Is there a way to restore the look of old Spotify?

### ISSUE THREAD

**Issue by kanishknishar** [spicetify/spicetify-cli#2459]
### 📝 Provide a description of the new feature

I am not a fan of the new Spotify UI or the insistence of the right side-bar opening every time a new song is played. Is there a way to restore Spotify to how it used to look?

**Comment by rxri** [comment]
Unfortunately no. You would need to downgrade to <=1.2.13

**Comment by kanishknishar** [comment]
That sucks big time. Thanks. I was looking at the feature list. What does “new search” do? It did not give back Spotify results as they were before they broke the search.
