### ISSUE TITLE
Is it possible to fix the new releases app for old Spotify version ?

### ISSUE THREAD

**Issue by FiftyFour7250** [spicetify/spicetify-cli#2460]
Hey guys, I've been using the old version of Spotify (about two years) because I have a lot of my own extensions that don't work on the new version, and I don't like the new design. So everything was fine. But a couple of weeks ago, the new releases app stopped working. And installing the new version of it in my old Spotify didn't solve the problem either. Is there any way to fix this? I still want to stay on the old version, and maybe the problem there is a couple lines of code? 

I attach a screenshot of the console while trying to open new releases, and the my version of new releases app.

![image](https://github.com/spicetify/spicetify-cli/assets/78786088/63f450da-8eb9-4e5d-895d-95d43d426806)
[new-releases.zip](https://github.com/spicetify/spicetify-cli/files/11952310/new-releases.zip)

**Comment by kyrie25** [comment]
Our focus is always the latest version of Spotify as it should be.

Currently Spotify has moved all their endpoints to one that is exclusively available on latest versions and also at the mean time deprecated old ones so it is not possible for us to do so.

**Comment by kyrie25** [comment]
Please keep in mind that this heavily affected other libre-Spotify and modification projects also.
