### ISSUE TITLE
[Lyrics Plus] Conversion (JP) enabled on genius page freezes spotify

### ISSUE THREAD

**Issue by ohitstom** [spicetify/spicetify-cli#2462]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
1.2.15.828.g79f41970
v2.20.3

Theme: Comfy / catppuccin-dark
Extensions: popupLyrics.js, shuffle+.js, oneko.js, immersiveView.js, scannables.js, fullAppDisplayMod.js, imageToClipboard.js
Custom apps: lyrics-plus, marketplace, new-releases, reddit
```

### 📝 Description

![image](https://github.com/spicetify/spicetify-cli/assets/22730962/02b31cd5-80d7-4da6-8103-3581720f22b7)

Enable these conversion settings, then go to genius, spotify and dev tools completely brick and you have to close and open spotify again. If its a japanese song it will brick for around 10 seconds, but if you then go to any other language it will brick indefinitely.

**Comment by rxri** [comment]
Fixed by #2443
