### ISSUE TITLE
[Lyrics Plus] Use both the original lyrics and Chinese lyrics from Netease at the same time

### ISSUE THREAD

**Issue by moonlightbladeol** [spicetify/spicetify-cli#2463]
### 📝 Provide a description of the new feature

![螢幕擷取畫面 2023-07-08 212418](https://github.com/spicetify/spicetify-cli/assets/90969133/9c8f4e21-f44e-4c5a-b41b-ddde3d56f617)
Currently, when displaying the original lyrics and Chinese lyrics from Netease, The original lyrics are all translated back into Chinese through machine translation. This often results in significant errors compared to the original text. 
To avoid these errors, I would like to simultaneously display the original lyrics and Chinese lyrics from Netease. I have made some modifications to the code, but due to my limited knowledge of JavaScript, I can only display the original and Chinese lyrics on the same line. 

![螢幕擷取畫面 2023-07-08 212646](https://github.com/spicetify/spicetify-cli/assets/90969133/3038be87-0844-4ba9-9aa4-867ee3f513c1)

Therefore, I would like to request assistance in adding this functionality. Thank you.

**Comment by kyrie25** [comment]
We don’t provide help on request.

You can visit the Discord server linked on our Organization Readme and ask other developers in general.
