### ISSUE TITLE
Test-Path : Cannot bind argument to parameter 'Path' because it is null.

### ISSUE THREAD

**Issue by Itsbillihere** [spicetify/spicetify-cli#2469]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bit)
1.2.15.828.g79f41970
- Spicetify version: 2.20.3
```

### 📝 Description

while installing , it gives me error while installing ''iwr -useb https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.ps1 | iex''

it shows this error on powershell
Test-Path : Cannot bind argument to parameter 'Path' because it is null.

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/91925465/7b1a0ac8-8bd3-408b-8c10-9f35f766e405)

**Comment by kyrie25** [comment]
Do not install Spicetify as administrator.

**Comment by Itsbillihere** [comment]
> Do not install Spicetify as administrator.

i am not , i did not open power shell as administrator

**Comment by kyrie25** [comment]
> > Do not install Spicetify as administrator.
> 
> 
> 
> i am not , i did not open power shell as administrator 

![image](https://github.com/spicetify/spicetify-cli/assets/77577746/beb2053e-d98c-4adc-969e-eb3138ea68ad)

**Comment by Itsbillihere** [comment]
> > > Do not install Spicetify as administrator.
> > 
> > 
> > i am not , i did not open power shell as administrator
> 
> ![image](https://user-images.githubusercontent.com/77577746/253248094-beb2053e-d98c-4adc-969e-eb3138ea68ad.png)

how do i run it without administrator?

**Comment by kewin100** [comment]
I have the same problem and get get powershell to run without administrator

**Comment by NocetiFederico** [comment]
hello, could you solve it? I have the same problem

**Comment by Itsbillihere** [comment]
> hello, could you solve it? I have the same problem

nope , i didnot find a way to run powershell without administrator

**Comment by FlashSkyNews** [comment]
Rightclick on the windows icon and select Powershell :)

https://github.com/spicetify/spicetify-cli/assets/24974529/81f6717c-a81d-422e-ba68-9b3a12b3dd53

**Comment by Itsbillihere** [comment]
> Rightclick on the windows icon and select Powershell :)
> 
>  fE2sRQNl4c.mp4

thanks , but i am using windows 10 , but still theres an option to open command prompt with and without administrator , but it still open cmd with admin rights doesnot matter which one i choose

**Comment by wuhurmuhu** [comment]
Hello, a bit late here but search uac in search bar, it's probably at never notify, change it to always notfiy
