### ISSUE TITLE
i cant get it to update, plz help

### ISSUE THREAD

**Issue by marshenmanhunter** [spicetify/spicetify-cli#2473]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.15.828.g79f41970
- Spicetify version: v2.20.0
```

### 📝 Description

every time I go into the command prompt to go and update it says that I'm up to date. i would download it from GitHub itself but im both not experienced enough and also too lazy to figure it out by myself.

**Comment by kyrie25** [comment]
Run `spicetify upgrade` or rerun the installer from our website.

If you still have questions make a support ticket on our Discord server, issues are not for support.
