### ISSUE TITLE
Gibberish over artist/podcast name

### ISSUE THREAD

**Issue by rpgdev** [spicetify/spicetify-cli#2474]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.11.916.geb595a67
- Spicetify version: 2.20.3
```

### 📝 Description

I just installed spicetify and I'm seeing this weird text overlay over the artist/podcast name. It makes it hard to understand and looks like gibberish. On podcasts sometimes it blinks in and out, looks like it's the title of the podcast being overlayed over the artist/podcast name section. Is that some "dev-tool" option I may have enabled? I doubt it because it appeared right after I applied spicetify. It happens with every theme I tried but right now I'm running the https://github.com/Daksh777/SpotifyNoPremium theme and cited scripts. Any ideas of what might be causing this?

### 📸 Screenshots

![2023-07-16_11-37](https://github.com/spicetify/spicetify-cli/assets/20094474/73fcac1d-51dd-4d7e-bcf4-bdd0ce983970)

**Comment by rxri** [comment]
Not cli related. If you need help with theme/extension, please visit our discord server
