### ISSUE TITLE
Spicetify Marketplace Makes UI Unusable

### ISSUE THREAD

**Issue by fernandoasikin** [spicetify/spicetify-cli#2479]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.11.916.geb595a67
- Spicetify version: 2.21.0
```

### 📝 Description

UI of the app seems unusable after installing spicetify marketplace or installing some theme from the spicetify marketplace, already tried to remove all the folder and installed spicetify and even spotify again but still not usable. Current temporary solution i used is avoid using spicetify marketplace. Anyone know how to solve this kinda weird problem? Thank you

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/59933093/58fbb7cf-88d1-4ae6-92d5-2f877e934598)
![image](https://github.com/spicetify/spicetify-cli/assets/59933093/7bc4ab04-83b7-452e-a11a-50ef649cce26)

**Comment by rxri** [comment]
Not cli issue, but it's theme issue so you need to use different one. To reset marketplace settings please open DevTools (spicetify enable-devtools), go to Application tab, and in Storage, Clear site data
