### ISSUE TITLE
Can not get the lyrics from neatease

### ISSUE THREAD

**Issue by WilliamWangshao** [spicetify/spicetify-cli#2481]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.16.947.gcfbaa410 for intel
- Spicetify version:v2.21.0
```

### 📝 Description

I can not get the lyrics from netease
It just display the lyrics from musixmatch

### 📸 Screenshots

![SCR-20230719-lbpj](https://github.com/spicetify/spicetify-cli/assets/33147340/877738e4-33ce-4d08-a033-c111a57dbd29)

**Comment by kyrie25** [comment]
Server-side issue.

**Comment by Lseoksee** [comment]
@kyrie25 
 I think the way natease api works has changed Directly requesting a get request to that address results in a `code -462` error. If you guess the error, it seems that some authentication method has been added to the api.

`request`
https://music.xianqiao.wang/neteaseapiv2/search?limit=10&type=1&keywords=2002%20Anne-Marie

`response`
~~~ json
{"code":-462,"data":{"actionCode":null,"verifyType":40,"verifyId":1007602,"verifyUrl":"https://st.music.163.com/encrypt-pages","blockText":"验证成功后，可进行下一步操作哦~","verifyToken":"00.40.cfec65500f3c1a2f1c70868355be4dd7.3823463379","btnText":"","orpheusUrl":"","frontRuleIds":null,"params":{"event_id":"00392226168979120160","sign":"00a8da042f8b254e900f8e8bf49ad3d8"},"url":"https://st.music.163.com/encrypt-pages?params=%7B%22sign%22%3A%2200a8da042f8b254e900f8e8bf49ad3d8%22%2C%22event_id%22%3A%2200392226168979120160%22%7D&verifyType=40&verifyId=1007602&verifyToken=00.40.cfec65500f3c1a2f1c70868355be4dd7.3823463379","urlAutoOpen":0,"orpheusUrlParamAppend":null},"message":"请完成验证操作"}
~~~

**Comment by WilliamWangshao** [comment]
> @kyrie25 I think the way natease api works has changed Directly requesting a get request to that address results in a `code -462` error. If you guess the error, it seems that some authentication method has been added to the api.
> 
> `request` https://music.xianqiao.wang/neteaseapiv2/search?limit=10&type=1&keywords=2002%20Anne-Marie
> 
> `response`
> 
> ```json
> {"code":-462,"data":{"actionCode":null,"verifyType":40,"verifyId":1007602,"verifyUrl":"https://st.music.163.com/encrypt-pages","blockText":"验证成功后，可进行下一步操作哦~","verifyToken":"00.40.cfec65500f3c1a2f1c70868355be4dd7.3823463379","btnText":"","orpheusUrl":"","frontRuleIds":null,"params":{"event_id":"00392226168979120160","sign":"00a8da042f8b254e900f8e8bf49ad3d8"},"url":"https://st.music.163.com/encrypt-pages?params=%7B%22sign%22%3A%2200a8da042f8b254e900f8e8bf49ad3d8%22%2C%22event_id%22%3A%2200392226168979120160%22%7D&verifyType=40&verifyId=1007602&verifyToken=00.40.cfec65500f3c1a2f1c70868355be4dd7.3823463379","urlAutoOpen":0,"orpheusUrlParamAppend":null},"message":"请完成验证操作"}
> ```

thank you，that's what i mean
