### ISSUE TITLE
Spicetify not applying even after reinstalltion 

### ISSUE THREAD

**Issue by Someone-Somwhere** [spicetify/spicetify-cli#2482]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bit) 1.2.16.947.gcfbaa410
- Spicetify version: Spicetify v2.21.0
```

### 📝 Description

Spicetify options don't appear when Spicetify is applied even after reinstalling (both Spotify and Spicetify)don't

**Comment by kyrie25** [comment]
Install Marketplace.

Issues are not support tickets. If you need help, make a support ticket in our Discord server.
