### ISSUE TITLE
Installing Spotify using Windows Store requires 'spicetify apply' every time

### ISSUE THREAD

**Issue by MrMiquy** [spicetify/spicetify-cli#2483]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Windows (x64) 1.2.16.947.gcfbaa410
- Spicetify version: 2.21.0
```

### 📝 Description

If you have Spotify installed using the Windows Store, you need to write 'spicetify apply' in PowerShell every time you close Spotify, because spicetify stops working. 
So download Spotify using the official site.

You can close this issue. 
This is just a note for users who have encountered the problem I had.

**Comment by rxri** [comment]
It's the feature of Microsoft Store. Not something we will or can fix. I'm sorry. You should use the one downloaded from spotify website. We also state in release notes that there can be issues
