### ISSUE TITLE
Installation FAQ is incorrect.

### ISSUE THREAD

**Issue by murtazarang** [spicetify/spicetify-cli#2486]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: "Not Snap"
- Spicetify version: v2.21.0
```

### 📝 Description

```
user@PC:~/Downloads$ curl -fsSL https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.sh | sh

FETCHING Version 2.21.0
DOWNLOADING https://github.com/spicetify/spicetify-cli/releases/download/v2.21.0/spicetify-2.21.0-linux-amd64.tar.gz

Warning: Failed to open the file /home/user/.spicetify/spicetify.tar.gz: 

Warning: Permission denied

curl: (23) Failure writing output to destination
```

Spicetify installation instructions do not work. 

I have added the necessary permission to /usr/share/spotify and /usr/share/spotify/App directories.

**Comment by rxri** [comment]
They are correct. You don't have permissions to `/home/user/.spicetify`. It's the issue in your configuration

**Comment by rxri** [comment]
curl was installed with snap? That's something new to me. Thanks for the information ❤️
