### ISSUE TITLE
Add support for Pop-up Lyrics to remember its position and size

### ISSUE THREAD

**Issue by jahirfiquitiva** [spicetify/spicetify-cli#2491]
### 📝 Provide a description of the new feature

Hi

When I open the lyrics pop-up for the first time after opening Spotify, it is positioned at the bottom right corner and with a specific size.

I would like it to remember its position and size regardless of it is the first time I open it or not.

Thanks in advance!

**Comment by jahirfiquitiva** [comment]
@rxri  couldn't it be possible for it to read the settings from a file so that the popup script repositions it?

**Comment by rxri** [comment]
No, not really. It's PiP window. We hook into it in `PopupModal` method, so we have no way of moving it around etc since it's all handled in chromium
