### ISSUE TITLE
blank screen

### ISSUE THREAD

**Issue by StavrosArceusX** [spicetify/spicetify-cli#2494]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [x] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: newest
- Spicetify version: 2.22.1
```

### 📝 Description

i try to install spicetify on kali linux but whenever i finish installing when i add the marketplace everything goes blank does maybe anyone know how to fix my issue?

### 📸 Screenshots

![spicetfy](https://github.com/spicetify/spicetify-cli/assets/94086433/7a338488-ef69-4620-83c1-24fdbbea5935)

**Comment by rxri** [comment]
it's not an cli issue and linux doesn't have "newest" version of spotify.
reinstall spotify and do `spicetify backup apply`

**Comment by StavrosArceusX** [comment]
> it's not a cli issue and linux doesn't have "newest" version of spotify. Reinstall spotify and do `spicetify backup apply`. For more help please visit our discord server

@rxri means i cant have marketplace or wha?

**Comment by rxri** [comment]
Do as I said and then you can install marketplace

**Comment by StavrosArceusX** [comment]
> Do as I said and then you can install marketplace

ill try this then

**Comment by StavrosArceusX** [comment]
> spicetify backup apply

thank you very much this worked
