### ISSUE TITLE
GET returns 404 infinite loop causing lag

### ISSUE THREAD

**Issue by Laqco** [spicetify/spicetify-cli#2497]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.16.947.gcfbaa410
- Spicetify version: v2.22.1

Pretty decent PC, normally not having lags with anything.
- AMD Ryzen 7 3700X
- AMD Radeon RX 5700 XT
- 32 GB RAM
```

### 📝 Description

I just installed spicetify to test it out and noticed some (mostly network) lag while using it.

The console got spammed with `GET https://raw.githubusercontent.com/*/*/main/manifest.json 404` errors, coming from file `extension.js:1` (an inner function of extension.js, Column 47567 [...]`fetch(o).then(e=>e.json()).catch(()=>C([o], "noManifests"))) && window.sessionStorage.setItem(e + "-" + t, JSON.stringify(n)),`.

Without reading much into the code, I think that these errors might be the proplem causing my lag.

--

Also, while a game anticheat was running on my pc, no extension/theme would work. I don't think that this is the cause, but I'll update, if I notice any coincidence between the lag and the anticheat.

**Comment by rxri** [comment]
Not cli related, also this shouldn’t cause any lag since it makes requests once and doesn’t repeat them to the same address
