### ISSUE TITLE
New spotify UI bug

### ISSUE THREAD

**Issue by philia1** [spicetify/spicetify-cli#2503]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (64 bit)
1.2.17.834.g26ee1129

Spicetify v2.22.1
```

### 📝 Description

Spotify updated recently so I re-applied Spicetify and I found that the UI has changed and I found some bugs along with it.

1. The panel on the left side seems to be bugged, as in the theme isn't working on the panel. (Screenshot 1)

**Screenshot 1**
![Screenshot 2023-08-06 124752](https://github.com/spicetify/spicetify-cli/assets/119487704/ed2fa446-e57b-4c53-bba5-ac84f69f5326)

2. The album art seems to clip through one of the buttons when expanded. (Screenshot 2)

**Screenshot 2**
![Screenshot 2023-08-06 124823](https://github.com/spicetify/spicetify-cli/assets/119487704/6cc73d18-b47a-4837-8a8a-b3a86c6f668f)

3. When collapsing the side panel while the album cover is expanded results in the album cover being collapsed mostly with the sidebar. (Screenshot 3)

**Screenshot 3**
![Screenshot 2023-08-06 124842](https://github.com/spicetify/spicetify-cli/assets/119487704/77dceaeb-d080-4621-82ba-04249507a524)

I don't know what is causing this issue. I have tried restoring, backing up and applying several times but this issue still remains. I have also tried the Reset option under extensions which uninstalls all extensions and themes and resets the preferences. 

(The Spotify album art background still remains so I'm guessing it's part of Spicetify).

Is the spotify UI supposed to be the updated latest version or is it supposed to go back to the old UI when applying spicetify?

### 📸 Screenshots

**More screenshots:** 

![Screenshot 2023-08-06 132431](https://github.com/spicetify/spicetify-cli/assets/119487704/5f869494-2080-4539-b96e-5d6d526e4938)
![Screenshot 2023-08-06 132459](https://github.com/spicetify/spicetify-cli/assets/119487704/4e810d6c-ea76-4dc4-aaef-3418eca10f7a)
![Screenshot 2023-08-06 132515](https://github.com/spicetify/spicetify-cli/assets/119487704/0977154a-cd90-47f1-b682-e4305eb7a648)

**Comment by kyrie25** [comment]
Not a CLI issue.

Right side bar is a production Spotify feature, all their development is worked around adapting to it. Toggling any Experimental features in mind (in this case right side bar is disabled) must be taken with caution and is expected to break.

**Comment by philia1** [comment]
Is there a way to get back the old User Interface?

**Comment by kyrie25** [comment]
Either enable Right sidebar or downgrade Spotify.

**Comment by philia1** [comment]
Can you elaborate on what you mean by the right sidebar? Because I can't find any option to enable what you mentioned. My problem is with the left sidebar which has a black background unlike the rest of the User Interface.

**Comment by kyrie25** [comment]
> Can you elaborate on what you mean by the right sidebar? Because I can't find any option to enable what you mentioned. 

![image](https://github.com/spicetify/spicetify-cli/assets/77577746/f48394d1-6f05-48d2-a181-f89f7d3e2c69)
This will disable expandable album covers.

> My problem is with the left sidebar which has a black background unlike the rest of the User Interface.

Theme issue.

**Comment by philia1** [comment]
I got it fixed after removing and reinstalling the theme. Thanks for the help!
