### ISSUE TITLE
Marketplace Extensions Not Installing

### ISSUE THREAD

**Issue by HGAdam** [spicetify/spicetify-cli#2505]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.17.834.g26ee1129
- Spicetify version: 2.22.1

Spotify for Windows (64 bit)
1.2.17.834.g26ee1129
Spicetify v2.22.1
```

### 📝 Description

Whenever I install an extension, they appear in the "Installed" tab of the Marketplace, but they aren't functional. I've even checked my %AppData%\spicetify\Extensions folder and I found nothing. I don't know if this is a Spicetify issue or if Spotify is trying to prevent the Spicetify Marketplace from working. I've even tried reinstalling both Spotify and Spicetify, but nothing seems to fix this issue.

**Comment by rxri** [comment]
Not cli issue. Please visit our discord server for general help
