### ISSUE TITLE
Lyrics in full screen mode extension

### ISSUE THREAD

**Issue by wuhurmuhu** [spicetify/spicetify-cli#2515]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: .
- Spicetify version:.
*Not sure which is which so I pasted config
Backup
version                       1.2.17.834.g26ee1129
with                          2.22.2
```

### 📝 Description

Lyrics do not show up in full screen mode automatically. I have to click on the lyrics button on the sidebar, go to synced or unsynced (unsynced if synced not available) then go to fullscreen mod and turn off then on the Lyrics button in it's configuration.
If I leave fullscreen mode the process above has to be repeated.
Note: This started about a week ago, tried uninstalling and reinstalling the lyrics plus extension but same issue.

### 📸 Screenshots

Lyrics at sidebar
![image](https://github.com/spicetify/spicetify-cli/assets/141845310/8dd37509-760d-473b-9a6f-fc07764d74e5)
Fullscreen mode (auto hide if no lyrics)
![image](https://github.com/spicetify/spicetify-cli/assets/141845310/791f2db9-ea20-445a-ac22-8ed6fdf76b2a)
After turning lyrics button off and on in configuration
![image](https://github.com/spicetify/spicetify-cli/assets/141845310/e38557fb-cedc-4ecd-b6d8-38787ef201fd)

**Comment by wuhurmuhu** [comment]
*Issue also reappears when skipping songs

**Comment by rxri** [comment]
Right click anywhere in full screen and enable Lyrics Plus Integration. Please use discord server for general help next time

**Comment by wuhurmuhu** [comment]
It is enabled...

**Comment by rxri** [comment]
This is not  FullAppDisplay extension that is built-in to repo. This is not something we can fix

**Comment by wuhurmuhu** [comment]
Issue got fixed, turns out karaoke was set as default instead of synced.
