### ISSUE TITLE
Spotify No Longer Works After Marketplace Install

### ISSUE THREAD

**Issue by Davidp07** [spicetify/spicetify-cli#2518]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.17.834.g26ee1129
- Spicetify version: 2.22.2
```

### 📝 Description

Whenever I install the marketplace spotify completely breaks and displays a something went wrong try reloading the page. And when I click on reload the page nothing happens. I looked through the other reports of this issue and none of the solutions provided worked. I tried reinstalling spotify and restoring a backup, but that didn't fix the issue.

### 📸 Screenshots

![Spotify_afFCUM7pac](https://github.com/spicetify/spicetify-cli/assets/10317182/5d491e84-7957-41ae-8b45-7dcbd33a9f8b)
![Spotify_Yy7UDqwsFu](https://github.com/spicetify/spicetify-cli/assets/10317182/512f07eb-e8fb-451e-b46c-e3a531963182)

**Comment by rxri** [comment]
Not cli related. For general help, please look on discord server
