### ISSUE TITLE
After installing Spicetify, app runs fine until you close spotify where trying to reopen spotify brings up the popup "The Spotify application is not responding"

### ISSUE THREAD

**Issue by Cooperfur** [spicetify/spicetify-cli#2519]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: unknown
- Spicetify version: v2.22.2
```

### 📝 Description

So, like I said, I installed spicetify and everything ran fine, the only problem I'm having is when the app is closed and I try to open it. 
when I go to open spotify it comes up with the prompt:
![image](https://github.com/spicetify/spicetify-cli/assets/142376863/9a56248c-5055-4197-bce9-80611ccd471f)
Even if I go into windows PowerShell and try restart spicetify, or use the "spicetify restore backup apply" command, the same prompt appears and I cannot get into Spotify. So far I have only found that uninstalling spicetify works to manage to open Spotify.

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/142376863/d0f141ef-c64c-4d2f-9fdc-65e08a64b1c8)

**Comment by rxri** [comment]
Not cli related

**Comment by Cooperfur** [comment]
> Not cli related

what?

**Comment by rxri** [comment]
This issue is not spicetify related in any means even when it happens after applying it. Recommended steps to troubleshoot this issue are to uninstall and install Spotify and then apply
