### ISSUE TITLE
Spicetify will support Spotube for GNU/linux user?

### ISSUE THREAD

**Issue by VXEAD** [spicetify/spicetify-cli#2521]
### 📝 Provide a description of the new feature

Im using Spicetify on my Windows, now i want to see Spicetify on my GNU/Linux
Spicetify will support Spotube for GNU/linux user?

**Comment by theRealPadster** [comment]
No, Spicetify works by modifying the xpui.js from the official Spotify app, and has no relation to Spotube. You can use the official Spotify app on Linux and use Spicetify with it though.
