### ISSUE TITLE
cant install

### ISSUE THREAD

**Issue by markimoofan** [spicetify/spicetify-cli#2523]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:latest
- Spicetify version:tried to install latest
```

### 📝 Description

I tried the solution from April 30th that didn't work either.  iwr -useb https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.ps1 | iex 'iwr' is not recognized as an internal or external command, operable program or batch file. 

### 📸 Screenshots

![cant install](https://github.com/spicetify/spicetify-cli/assets/17669325/1d02c056-61f1-4a8b-996f-f26f486436d0)

**Comment by rxri** [comment]
use powershell
