### ISSUE TITLE
[Full App Display] Enter FAD directly from full screen button

### ISSUE THREAD

**Issue by SkyeWong** [spicetify/spicetify-cli#2529]
### 📝 Provide a description of the new feature

<img width="297" alt="image" src="https://github.com/spicetify/spicetify-cli/assets/93854496/476d0bf2-bd39-4026-b9d4-44ed342e84d8">

It would be really cool if the "full screen" button in the playing bar could directly enter the full app display, instead of having to click the button at the top of the display.

**Comment by rxri** [comment]
It's not possible. The mentioned full screen button is from Premium features

**Comment by SkyeWong** [comment]
That's a shame, but I guess it's fine for now ;-;
