### ISSUE TITLE
AirPlay support on MacOS

### ISSUE THREAD

**Issue by zerol1ght** [spicetify/spicetify-cli#2530]
### 📝 Provide a description of the new feature

I have 2 HomePods and to play the music on them from my Mac I need to use the airplay option in Mac OS but it has a considerable delay.
Apple Music on the other side has an integrated button for airplay, which fixes the delay (other apps have it too and there is no delay on them).

I think this is the guide to add the button on apps.
https://developer.apple.com/documentation/avfoundation/streaming_and_airplay/supporting_airplay_in_your_app#

I don't know if this is a possible thing to do but I'd love to have this option on Spotify.

### The Dedicated Button on Apple Music
![image](https://github.com/spicetify/spicetify-cli/assets/77642830/a15e9b75-2f4a-472a-8e9f-9e0d621c96fa)

### Same thing on PoolSuiteFM
![image](https://github.com/spicetify/spicetify-cli/assets/77642830/48a36ec2-e091-482c-b123-ba7bbcc3dc8e)

**Comment by rxri** [comment]
Spotify plays the audio from the backend. We can't access it from the frontend and such this functionality isn't possible. We also don't take suggestions for new extensions in this repository anymore
