### ISSUE TITLE
music dont stops when paused!

### ISSUE THREAD

**Issue by prodbyeagle** [spicetify/spicetify-cli#2534]
### 🔍 Have you checked Spicetify.app page for your issue?

- [x] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: newest (31.08.23)
- Spicetify version: 2.23.0
```

### 📝 Description

when i paused my music, 1 seconds it plays again without prseeing any buttons

**Comment by rxri** [comment]
If you use beautiful lyrics extension, it might be the reason. Please wait for the update

**Comment by prodbyeagle** [comment]
yes it use it ok then i wait 
thanks
