### ISSUE TITLE
How to disable / bypass this annoying feature Spotify added 

### ISSUE THREAD

**Issue by unsrve** [spicetify/spicetify-cli#2535]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (64 bit)
1.2.19.941.gbf202593
Spicetify v2.23.0
```

### 📝 Description

I've been having this issue since 2 weeks ago and I don't know why. I never had this happing to me ever. 

- ok so I try to turn off shuffle and it comes up with this message.
![fdgfgfgf](https://github.com/spicetify/spicetify-cli/assets/38105459/e07ee75a-f7c9-4041-b4a3-2a57c28a284a)

if someone has any fix/bypass to this please help, its so annoying having to **manually** pick a song every time in my **liked songs.**

**Comment by rxri** [comment]
Since it’s in order to advertise Premium, we can’t do much
