### ISSUE TITLE
no fullscreen works

### ISSUE THREAD

**Issue by razerbank** [spicetify/spicetify-cli#2538]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.19.941.gbf202593
- Spicetify version: 2.20.3
- cpu intel i5 10400f
- gpu nvidia gtx 1650super
- ram 8gb 
- ssd 512gb
```

### 📝 Description

i try to open full screen (i have 2 different) one opens doesnt show lyrics and the other is just a blurred cube on my screen can anyone tell me is it because the spotify uppdate or should i restore backup of spicetify

### 📸 Screenshots

![Screenshot (39)](https://github.com/spicetify/spicetify-cli/assets/73061940/27452891-dec2-4877-85ab-351bdc2894eb)
![Screenshot (35)](https://github.com/spicetify/spicetify-cli/assets/73061940/b6dcad4e-573f-4e1c-8ec7-adefb6706a52)

**Comment by rxri** [comment]
Not related to cli. Please contact developer
