### ISSUE TITLE
Attempt to install spicetify results in error from Github

### ISSUE THREAD

**Issue by Vessel-Legends** [spicetify/spicetify-cli#2540]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.19.941.gbf202593
- Spicetify version: 2.23
```

### 📝 Description

Upon trying to install the latest version of spicetify, I get this in my powershell window (that IP address or whatever is not mine): 
![image](https://github.com/spicetify/spicetify-cli/assets/79474598/5220e69f-23e9-48b2-b4d6-7d49db187b29)

I am not sure if I have to wait for a while or something, but even after attempting to go to backup it still fails.

**Comment by rxri** [comment]
You need to wait for a few minutes before trying again
