### ISSUE TITLE
[Question] Have client-side window decorations drawn in Spotify

### ISSUE THREAD

**Issue by fr3nchalp4a** [spicetify/spicetify-cli#2542]
In GNOME, the close/minimize buttons and title are inside a generic titlebar. 
![image](https://github.com/spicetify/spicetify-cli/assets/68474172/525a157f-01ba-4581-8d8f-530ba670dba6)

I was wondering if, with some CSS/JS, it is possible to make it look like this, like Firefox's GTK default theme :
![image](https://github.com/spicetify/spicetify-cli/assets/68474172/9db8742e-4070-49d1-b8c9-271ad44fb728)

This would make integration in the rest of the system better. I know Spotify Windows is doing it.

**Comment by fr3nchalp4a** [comment]
Someone had the idea, and asked it on Spotify forums :
[https://community.spotify.com/t5/Desktop-Linux/client-side-decorations/td-p/4507136](https://community.spotify.com/t5/Desktop-Linux/client-side-decorations/td-p/4507136)

**Comment by rxri** [comment]
Not possible
