### ISSUE TITLE
WebNowPlaying Broken on Latest Spotify

### ISSUE THREAD

**Issue by Sol1vaN** [spicetify/spicetify-cli#2544]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.19.941.gbf202593
- Spicetify version: 2.23.0
```

### 📝 Description

Nothing appears to be working (no cover, media controls, or info).

In the past, there's an alternative solution:
https://github.com/spicetify/spicetify-cli/issues/1415

But now this solution don't work with the actual versions.
Anybody have the same problem now?

Anyway to fix this in 2023?

**Comment by rxri** [comment]
Resolved by https://github.com/spicetify/spicetify-cli/commit/40adf67a6771d2811f17dfd734b68d0b225c4910

**Comment by Sol1vaN** [comment]
and what need to do to apply this fix for me now? 😥
