### ISSUE TITLE
WebNowPlaying extension no longer works properly for Rainmeter

### ISSUE THREAD

**Issue by Potato22** [spicetify/spicetify-cli#2546]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (64 bit)
1.2.19.941.gbf202593
Spicetify v2.23.0
Theme:
Extensions: webnowplaying.js, shuffle+.js, fullAppDisplay.js, turntable.js
Custom apps: new-releases
```

### 📝 Description

[WebNowPlaying](https://github.com/tjhrulz/WebNowPlaying) standalone is archived on 4 March 2023 and is no longer properly working with the one that comes with Spicetify as an extension. It displays the typical `N/A` for title, artist, and missing artwork.

As seen on WebNowPlaying `README.md`:
> ## The WebNowPlaying Rainmeter plugin has been rewritten to take advantage of the new adapter library for easier implementation. The source code for the new version can be found [here](https://github.com/keifufu/WebNowPlaying-Redux-Rainmeter)
Upon installing the new [WNP rmskin](https://github.com/keifufu/WebNowPlaying-Redux-Rainmeter), it works perfectly again.

Spotify has been restored multiple times, same result.
**I've yet to been able to verify if it's tied to the specific rainmeter skin or Spicetify itself, so there needs some more witnesses.**
Please let me know if there's anything else I should know or missed.

**Comment by rxri** [comment]
Resolved by https://github.com/spicetify/spicetify-cli/commit/40adf67a6771d2811f17dfd734b68d0b225c4910

**Comment by Potato22** [comment]
understood, thanks for clarifying.
