### ISSUE TITLE
Installation error - iex : Exception calling "FlushInputBuffer" with "0" argument(s): "The method or operation is not implemented."

### ISSUE THREAD

**Issue by jbax1899** [spicetify/spicetify-cli#2549]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 
Spotify for Windows (64 bit)
1.2.19.941.gbf202593
- Spicetify version: 
n/a
```

### 📝 Description

Powershell output:
`PS C:\Users\Administrator> [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; iwr -useb https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.ps1 | iex
The script was ran as Administrator which isn't recommended
iex : Exception calling "FlushInputBuffer" with "0" argument(s): "The method or operation is not implemented."
At line:1 char:171
+ ... ithubusercontent.com/spicetify/spicetify-cli/master/install.ps1 | iex
+                                                                       ~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-Expression], MethodInvocationException
    + FullyQualifiedErrorId : NotImplementedException,Microsoft.PowerShell.Commands.InvokeExpressionCommand`

Couldn't find a way to run Powershell without admin rights, always got the "this isn't recommended" message, maybe related.

**Comment by rxri** [comment]
Use higher version of Powershell and script tells you to not run it as administrator

**Comment by SunsetTechuila** [comment]
> Use higher version of Powershell
Works for 5.1 or higher. If you already have 5.1+ then your Windows installation is broken
