### ISSUE TITLE
Custom app "lyrics—plus" not found

### ISSUE THREAD

**Issue by Aeropro4** [spicetify/spicetify-cli#2551]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.19.941
- Spicetify version: 2.23.0
```

### 📝 Description

Just pasted these commands  
spicetify config custom_apps lyrics-plus
spicetify apply
but in spicetify apply
it says Custom app "lyrics—plus" not found.

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/113044496/afd2191a-21ad-4473-bd27-191d6a0e371d)

**Comment by rxri** [comment]
Issues are not for general help. You do not have folder called `lyrics-plus` with needed files

**Comment by Aeropro4** [comment]
> Issues are not for general help. You do not have folder called `lyrics-plus` with needed files

K sry and thx
