### ISSUE TITLE
Lyrics button disappears

### ISSUE THREAD

**Issue by amiria703** [spicetify/spicetify-cli#2554]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.18.999
- Spicetify version: 2.23.0
- OS: Arch Linux
```

### 📝 Description

Lyrics button disappears but after removing everything it comes back.

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/54179379/6e40c1a1-bbab-434b-810d-ba29b7ac97b1)

**Comment by Rickyrvxlovet** [comment]
I have the same issue

**Comment by rxri** [comment]
This is a Beautiful Lyrics button I believe so unfortunately, it's not related to cli

**Comment by amiria703** [comment]
> This is a Beautiful Lyrics button I believe so unfortunately it's not related to cli

![image](https://github.com/spicetify/spicetify-cli/assets/54179379/7ceb5122-6d48-42c8-bbb4-d25668f72ccb)
Uninstalled Beautiful Lyrics, check out this screenshot:
I don't have lyrics button (mic button) anymore.

**Comment by dhupee** [comment]
pretty sure this is unrelated to the CLI, however i have a clue why

https://techcrunch.com/2023/09/05/spotify-lyrics-free-tier-premium-test/
