### ISSUE TITLE
„Spotify“ 1.2.20 seems to have broken „Spicetify“ 

### ISSUE THREAD

**Issue by dziugas1959** [spicetify/spicetify-cli#2555]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.201210.g2a8a8a57
- Spicetify version: 2.23.1
```

### 📝 Description

After patching „Spicetify“, „Spotify“ just shows a black screen.

### 📸 Screenshots

![paveikslas](https://github.com/spicetify/spicetify-cli/assets/53124670/3dc62ff9-6e97-450a-ad24-b02768aebd14)

**Comment by rxri** [comment]
As mentioned in release notes, spicetify supports up to `1.2.19`. `1.2.20` is not a supported version as of yet

**Comment by dhupee** [comment]
@rxri i wonder whether this is applied for all functionality or things like extensions and custom apps only?

**Comment by rxri** [comment]
The preprocess breaks spotify in the `vendor~xpui.js` which prevents from loading modules etc. I already made pull request fixing this

**Comment by dhupee** [comment]
oh good god

**Comment by dxcvvxd** [comment]
so is it fixed now? how do i download or install the fix?

**Comment by sansmoraxz** [comment]
I think the auto updates are not working. Had to manually reinstall to get the fix.

**Comment by rxri** [comment]
They do. However if you already had spicetify applied then you had to restore and then apply again

**Comment by ewof** [comment]
aur is either not updated or broken, i had to install from git to get it to work
