### ISSUE TITLE
Is it possible to import and use @spotify/web-api-ts-sdk in extension or apps?

### ISSUE THREAD

**Issue by jkohlin** [spicetify/spicetify-cli#2557]
### 📝 Provide a description of the new feature

In your examples you fetch from the SpotifyAPI via 
`Spicetify.CosmosAsync.get(`sp://core-playlist/v1/playlist/${uri}/metadata`)`

Spotify already have a library with build in methods to do all that like `sdk.currentUser.playlists.playlists()`. Would it be possible to use that in Spicetify? 

I believe [they use es-modules](https://github.com/spotify/spotify-web-api-ts-sdk/blob/main/src/index.ts) so then it should be fine to import right?

It's just that to construct the sdk/api object you need to pass an authorization strategy, and that's where this request comes in. Since I don't know where all that happens in Spicetify, it would be nice if this library was already build in. It's a really nice library.

**Comment by rxri** [comment]
The requests to `sp://` etc are internal and are not the same like Web API (in this case web-api-sdk library). CosmosAsync already adds authentication headers etc to its requests. We already expose GraphQL requests and more so you can get stuff easier. We do not have plans to implement it because it's not necessary

**Comment by jkohlin** [comment]
Aha, I see. Where can I read about the graphql requests?

**Comment by rxri** [comment]
They should be available under `Spicetify.GraphQL` and definitions under `Spicetify.GraphQL.Definitions` You can check documentation under this link; https://spicetify.app/docs/development/api-wrapper/methods/graphql

**Comment by jkohlin** [comment]
Gotcha. Missed that. Thank you for pointing this out 🙏
