### ISSUE TITLE
Spotify path error

### ISSUE THREAD

**Issue by The-Unknown-Programming-Student** [spicetify/spicetify-cli#2562]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 
- Spicetify version:
```

### 📝 Description

I am getting this type of error what to do?

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/116381063/95fc2347-0be5-49a4-b6aa-f3ac1364ab9f)

**Comment by The-Unknown-Programming-Student** [comment]
I have recently downloaded spotify. The version is 1.2.19.941

**Comment by rxri** [comment]
Issues are not for general help. Install spotify from their website and it will resolve your issue
