### ISSUE TITLE
Trouble Changing Native Audio in Spicetify

### ISSUE THREAD

**Issue by JohnDiniz** [spicetify/spicetify-cli#2564]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.20.1216.ge7a7b92f
- Spicetify version: 2.23.0
```

### 📝 Description

I am encountering an issue while attempting to modify the native audio behavior in Spicetify.

Typically, in web browsers, we can achieve this by intercepting the creation of HTML elements. I am using the following code snippet:

```javascript
document.createElement = function (tagName) {
  const element = baseCreateElement.apply(this, arguments);
  if (tagName === "video" || tagName === "audio") {
    spotifyPlayback= element;
  }
  return element;
};
```
I am interested in understanding the reasons behind this discrepancy and why the code functions differently when used in the context of Spicetify compared to its functionality as a Chrome extension. Any insights or suggestions for resolving this issue would be greatly appreciated.

**Comment by rxri** [comment]
That’s not possible. Spotify plays audio from backend (C++ code) and not web view itself

**Comment by fucksophie** [comment]
> That’s not possible. Spotify plays audio from backend (C++ code) and not webview itself

To get a raw audio stream then, the only way is to capture spotify's audio using a different language such as C++?
