### ISSUE TITLE
Turn spicetify into a generic CEF/Electron mod tool

### ISSUE THREAD

**Issue by fugkco** [spicetify/spicetify-cli#2568]
### 📝 Provide a description of the new feature

It would be nice to be able to use spicetify with other cef and possibly electron based apps.

Would be great to be able to add custom functionality to things like Slack (e.g. to disable the new horrendous UI).

I don't know what all is involved when it comes to having spicetify work with Spotify, so this may be way harder for other apps, but it would be great nonetheless.

**Comment by rxri** [comment]
Spicerify was never intended to be its own app and such we are not going to consider this
