### ISSUE TITLE
fatal zip: not a valid zip file

### ISSUE THREAD

**Issue by crummei** [spicetify/spicetify-cli#2569]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.20.1218 (according to Spotify.exe, i cant open the app)
- Spicetify version: v2.23.2
```

### 📝 Description

- open spotify
- spotify crashes
- open powershell
- spicetify upgrade
- spicetify backup apply
"fatal zip: not a valid zip file"
- spicetify clear backup apply
"fatal zip: not a valid zip file"

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/56043602/d553c26b-3840-445b-bfda-ff89a01b148a)

**Comment by rxri** [comment]
Not cli issue. You’re most likely ratelimited by github

**Comment by crummei** [comment]
> Not cli issue. You’re most likely ratelimited by github

literally just turned on my pc 20 minutes ago, havent used github since last spotify update, so i doubt that

**Comment by rxri** [comment]
Try later then. Nothing we can do about it, sorry
