### ISSUE TITLE
Spicetify for linux version unuseble

### ISSUE THREAD

**Issue by KRBUG-Lee** [spicetify/spicetify-cli#2570]
### 🔍 Have you checked Spicetify.app page for your issue?

- [x] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: unknown
- Spicetify version:1.2.17
- system: debian sid
```

### 📝 Description

When I install Spicetify and Spicetify marketplace, it says **_"note Full Spicetify functionality is not guaranteed above Spotify's v1.2.17"_** and does not work in spotify. After checking Spicetify's release notes, I found that Spicetify doesn't seem to support spotify for linux versions 1.2.8, 1.2.9, 1.2.11, 1.2.13, 1.2.20. So, I uninstalled my spotify as well as Spicetify, reinstalled the latest version of the official spotify for linux using apt, and reinstalled Spicetify, and I found that the problem is still there!

May I ask, **how can I confirm my versions and make sure they are among the versions supported by Spicetify? If unfortunately Spicetify doesn't support my version, how do I install the old version of spotify for linux?**

**I would appreciate it if you could reply as soon as possible! Thank you for contributing to the software ecosystem on the linux desktop!**

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/62648255/ca7cda5b-06aa-4130-9998-308d57f9f2fa)

**Comment by rxri** [comment]
It’s the last version that is supported fully. Spotify releases Linux builds every 2-3 major releases. Use the version that is listed in release and you will be good to go. As screenshot says you need to backup first then apply

**Comment by KRBUG-Lee** [comment]
> It’s the last version that is supported fully. Spotify releases Linux builds every 2-3 major releases. Use one of the versions that are listed in release notes and you will be good to go. As screenshot says you need to backup first then apply

so my spotify version is supported? i should backup it, then well done?

**Comment by KRBUG-Lee** [comment]
> It’s the last version that is supported fully. Spotify releases Linux builds every 2-3 major releases. Use one of the versions that are listed in release notes and you will be good to go. As screenshot says you need to backup first then apply
before i backup, the Spicetify still unuseble
![image](https://github.com/spicetify/spicetify-cli/assets/62648255/b00bf0a9-43ae-4cd1-b1ac-3dd8bc97a04e)
what should i do to slove it

**Comment by rxri** [comment]
Follow this guide https://spicetify.app/docs/advanced-usage/installation#note-for-linux-users
