### ISSUE TITLE
 Unable to connect to the remote server

### ISSUE THREAD

**Issue by prameesh-4664** [spicetify/spicetify-cli#2571]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.20
- Spicetify version:v2.23.2
```

### 📝 Description

 Unable to connect to the remote server

**Comment by rxri** [comment]
Not a cli issue. Please visit our discord server for general help
