### ISSUE TITLE
[Cover Art] SSL/TLS issue with webnowplaying.js

### ISSUE THREAD

**Issue by TeZwo** [spicetify/spicetify-cli#2572]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.20.1218.g02aff7a4 (Win10 64bit)
- Spicetify version: v2.23.2
- Extensions: webnowplaying.js
- Rainmeter version: 4.5.18.3727
```

### 📝 Description

I'm using https://github.com/avenom/Spotibar with Rainmeter and Spicetify-CLI.

Debug in Rainmeter:
```
Unable to get album art from: https://i.scdn.co/image/ab67616d0000b273aed1ea93e9a35577c176866d
System.Net.WebException: Can not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.GetResponse()
   at WebNowPlaying.Measure.GetImageFromUrl(String id, String url)
```
After change the line in 71 https://github.com/spicetify/spicetify-cli/blob/master/Extensions/webnowplaying.js from https to http it is works fine.
```
71: if (cover?.indexOf("localfile") === -1) this.spicetifyInfo.cover = "http://i.scdn.co/image/" + cover.substring(cover.lastIndexOf(":") + 1);
```
The guys from https://github.com/keifufu/WebNowPlaying-Redux-Rainmeter/issues/13 seems to have the same issue.

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/125074364/71380b8e-0e8c-4950-a490-6bd93ef2b0a9)

**Comment by rxri** [comment]
That looks more like an issue with rainmeter itself (most likely doesn't handle TLS correctly). There's nothing to fix on our end. Changing `https://` to `http://` doesn't change anything because it still redirects to HTTPS version

**Comment by TeZwo** [comment]
thanks for the quick response, i will look futher into it.

**Comment by rxri** [comment]
I believe in rainmeter settings you can turn on some TLS-related options, you should try that

**Comment by TeZwo** [comment]
nope unfortunately there are no ssl/tls related settings in Rainmeter. Had also checked the firewall. Yes it is redirected to https strangely enough by the change in the code, the skin works correctly now. If it's not a big deal I'll just leave it as is.

**Comment by keifufu** [comment]
@TeZwo Please post the full debug log in keifufu/WebNowPlaying-Redux-Rainmeter#13, also note that spicetify isn't needed for WebNowPlaying 2.0.0 and newer since we just get Spotify info from GSMTC as long as you're on win10 or 11.
