### ISSUE TITLE
Option to disable Spotify-connect or forget devices

### ISSUE THREAD

**Issue by plopin3472** [spicetify/spicetify-cli#2574]
### 📝 Provide a description of the new feature

An option that disables the ''Spotify-connect'' function. This way, it prevents you from joining (or getting connected) onto an unwanted session by a partner/friend/pet or whatever that is listening on the same net.

### ➕ Additional Information

Afaik this only falls onto the Windows version, as phones already have an option to forget the devices. Maybe there is for pc, that I am not aware of? If so, pls enlighten me.

**Comment by rxri** [comment]
Sounds like an idea for extension. We only keep legacy extensions and don't add new ones to this repository anymore

**Comment by plopin3472** [comment]
> Sounds like an idea for extension. We only keep legacy extensions and don't add new ones to this repository anymore

I have no idea how big brain programming works nor apis, but would an addon like that be possible on spotify?
