### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by LUISMAGAIVER341** [spicetify/spicetify-cli#2579]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [x] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.21
- Spicetify version: latest
```

### 📝 Description

Are spicetify team trying to do it work in 1.2.21?
i can't install it!

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/84512640/38207ff9-38e1-466c-ba7b-5ce1db73ac6f)
The screenshot on "Dribbblish"

**Comment by rxri** [comment]
Issues are not for general help. If you followed guide on our website, spicetify should work just fine

**Comment by LUISMAGAIVER341** [comment]
@rxri I fucking did what they said. But searching more, i discovered that my version is not supported
If u don't know how to ask, don't talk any shit 😉

**Comment by rxri** [comment]
I don't understand you? Spicetify v2.24.2 supports versions from `1.2.0` to `1.2.22` (latest). The version of Spotify you listed in description is supported. I'm a maintainer of it so I know what I'm saying btw

**Comment by LUISMAGAIVER341** [comment]
Right
