### ISSUE TITLE
Certain Experimental Features Not Working

### ISSUE THREAD

**Issue by ohitstom** [spicetify/spicetify-cli#2582]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (32 bit)
1.2.21.1104.g42cf0a50
Spicetify v2.24.2
xpui_2023-09-22_1695379677000_42cf0a5
cef_116.0.22+g480de66+chromium-116.0.5845.188
```

### 📝 Description

Toggling these features does not work and it displays a tickbox when it should be a dropdown box like other features. there doesnt seem to be any errors.

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/22730962/f5597af2-7131-4953-922c-31d1328964c3)
![image](https://github.com/spicetify/spicetify-cli/assets/22730962/ec163c21-5506-410e-bb0a-5c248da3cfb7)

**Comment by rxri** [comment]
Not spicetify related. As shown in first screenshot it uses true/false so this is how it’s parsed

**Comment by ohitstom** [comment]
> Not spicetify related. As shown in first screenshot it uses true/false so this is how it’s parsed

thats not true it doesnt use true and false it should be parsing the dropdown box like others.
![image](https://github.com/spicetify/spicetify-cli/assets/22730962/d0f13269-5234-4292-835d-e1c490ea6b35)
![image](https://github.com/spicetify/spicetify-cli/assets/22730962/37691f04-0048-48b0-b762-c4a16838b4b0)


this is problem with the logic parsing the remote vals and not local vals.

**Comment by rxri** [comment]
It does use true and false (Default and Remote values). I’m pretty sure Spotify just shows Enabled and Disabled values in Dropbox for convenience

**Comment by ohitstom** [comment]
> It does use true and false (Default and Remote values). I’m pretty sure Spotify just shows Enabled and Disabled values in Dropbox for convenience

that is true but again the logic could be changed to use the local value store and not the remote/default value store no?

**Comment by rxri** [comment]
Local values should be set as true/ when shown as Enabled/Disabled in this panel

**Comment by ohitstom** [comment]
> Local values should be set as true/ when shown as Enabled/Disabled in this panel
what a bout "restricted"

**Comment by rxri** [comment]
It might set it to „2” because Spotify sets some variables in this way; which means they could use 0/1/2 in this instance

**Comment by ohitstom** [comment]
> It might set it to „2” because Spotify sets some variables in this way; which means they could use 0/1/2 in this instance

so the issue is with spotify using true and false for remote naming and disabled and enabled for local? so the must have just forgot to update that when adding restricted lol

**Comment by rxri** [comment]
Try resetting your experimental feature cache and see if it was changed because they could’ve change it to different data type
