### ISSUE TITLE
Spicetify installation error in Linux Mint

### ISSUE THREAD

**Issue by winpower21** [spicetify/spicetify-cli#2584]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.13.661.ga588f749
- Spicetify version: v2.24.2 (2023-09-28)
- System: Linux Mint 21.2 Cinnamon
```

### 📝 Description

On installing spicetify using curl as given in the instructions for linux, when running: 
`curl -fsSL https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.sh | sh`  it says that spicetify was installed successfully, but on running the second command:
`curl -fsSL https://raw.githubusercontent.com/spicetify/spicetify-marketplace/main/resources/install.sh | sh` the following output is generated: sh: 52: spicetify: not found

Same when running `spicetify --help` command

### 📸 Screenshots

![Screenshot from 2023-10-02 13-31-18](https://github.com/spicetify/spicetify-cli/assets/95289325/7676c1c4-005d-4b37-a701-b2d9910bbb3a)

**Comment by rxri** [comment]
Your `.bashrc` is corrupted (line 98)
