### ISSUE TITLE
file contains virus - unable to launch spicetify since update

### ISSUE THREAD

**Issue by fawnyeo** [spicetify/spicetify-cli#2586]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bit)
1.2.21.1104.g42cf0a50
- Spicetify version:
```

### 📝 Description

yoo help i wanted to update spicetify so i did spicetify upgrade and it led to this mess. tried deleting and reinstalling but i wasnt even allowed to delete it 
tried downloading the zip file and it stated virus detected? not sure if its on my end or the source file but i did a malware run and everyt seems fine 

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/102406279/2b1040db-b35e-4828-b702-d247a77d21f6)
![image](https://github.com/spicetify/spicetify-cli/assets/102406279/151b563d-aeed-4b57-83b2-90dfa94da926)

**Comment by theRealPadster** [comment]
Turn off or make exception with your antivirus I guess?

**Comment by rxri** [comment]
False positive. Add spicetify.exe to exclusions
