### ISSUE TITLE
installer doesnt work

### ISSUE THREAD

**Issue by kittenvr** [spicetify/spicetify-cli#2587]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: latest 
- Spicetify version: not installed
```

### 📝 Description

if i run the commands they give errors

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/103120356/f86bca25-c9a5-4e23-845b-5cc811becbd8)
![image](https://github.com/spicetify/spicetify-cli/assets/103120356/2ec19368-6210-460a-a3cb-8bbd221ab03c)

**Comment by rxri** [comment]
Use powershell v5.3 or higher
