### ISSUE TITLE
[lyrics plus] add an option to disable the floating lenny face

### ISSUE THREAD

**Issue by dxcvvxd** [spicetify/spicetify-cli#2592]
### 📝 Provide a description of the new feature

title is self-explanatory, i wish it could be togglable to turn off or on the lenny(i dont remember the correct name) face when it failed to find lyrics because right now it causes issues with other extensions such as full app display:
![image](https://github.com/spicetify/spicetify-cli/assets/77129815/dfe9d98d-6573-445b-b1f5-cdba2de10516)
the face is floating around the screen even in this mode and always toggling lyrics plus integration on and off is such a hassle.

### ➕ Additional Information

.

**Comment by rxri** [comment]
That's up to the extension to disable this face. If this face is shown it means there was no lyrics found
