### ISSUE TITLE
Spotify is detected as a malware as soon as I close the app

### ISSUE THREAD

**Issue by SaGAMER95** [spicetify/spicetify-cli#2593]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.9.743.g85d9593d
- Spicetify version: 2.17.1
```

### 📝 Description

Whenever I closed spotify, it shows that a malware was detected. I have bitdefender antivirus. It used to delete spotify too but luckily it isn't deleting now after I added the exception. But it keeps showing a popup that a virus was detected whenever I close Spotify.

### 📸 Screenshots

<img width="652" alt="Screenshot 2023-10-08 151701" src="https://github.com/spicetify/spicetify-cli/assets/98413128/dffed801-4093-4417-9a9c-a931c92bf453">
<img width="317" alt="Screenshot 2023-10-08 152049" src="https://github.com/spicetify/spicetify-cli/assets/98413128/f4dff27b-eccc-462f-a151-dc6f290a04f7">

**Comment by rxri** [comment]
What you’ve shown on screenshot isn’t spicetify related
