### ISSUE TITLE
Spicetify.ContextMenu._addItems throwing error when using Spicetify.ReactComponent.Menu

### ISSUE THREAD

**Issue by ohitstom** [spicetify/spicetify-cli#2594]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (32 bit)
1.2.21.1104.g42cf0a50
Spicetify v2.24.2
xpui_2023-09-22_1695379677000_42cf0a5
cef_116.0.22+g480de66+chromium-116.0.5845.188
```

### 📝 Description

This may be dev error, however no matter what props i pass this error seems to still appear, and it leads me to section of code which is supposed to be for older version support except im not on an older version.

The docs are a bit confusing for this specific component and no one seems to use it widely so i didnt have a reference to base it off of so i really hope this isnt an issue with my code in itself.

my component:
```js
const menuWrapper = Spicetify.React.memo(props => {
[stopMenuItem, setstopMenuItem] = Spicetify.React.useState(false);

return Spicetify.React.createElement(
	Spicetify.ReactComponent.Menu,
	{ ...props },
	Object.entries(timeIntervals)
		.map(([key, value], index) => {
			return Spicetify.React.createElement(
				Spicetify.ReactComponent.MenuItem,
				{
					key: index,
					onClick: e => {
						clickTip.hide();
						startTimer(value);
						Spicetify.showNotification(`Selected: ${key}`);
					}
				},
				key
			);
		})
		.concat(
			stopMenuItem
				? [
						Spicetify.React.createElement(
							Spicetify.ReactComponent.MenuItem,
							{
								divider: "before",
								key: "Turn off timer",
								onClick: e => {
									clickTip.hide();
									stopTimer(0, false);
									Spicetify.showNotification(`Timer stopped`);
								}
							},
							"Turn off timer"
						)
						]
				: []
		)
);
});
```

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/22730962/adff02a1-2f15-421b-b799-394640779313)
![image](https://github.com/spicetify/spicetify-cli/assets/22730962/b1d8d1a4-3d8b-4993-849a-ee4ad5c50020)

**Comment by rxri** [comment]
I don't know what you did, but I can't reproduce it. This part of code belongs to `Spicetify.ContextMenu` which you do not use

**Comment by ohitstom** [comment]
> I don't know what you did, but I can't reproduce it. This part of code belongs to `Spicetify.ContextMenu` which you do not use

is it possible this is being influenced by other addons i have? this error only shows in console once the menu is rendered, anything you think i can do to diagnose this because  i dont understand why contextmenu is being called either

**Comment by SunsetTechuila** [comment]
try with spicetify 2.23.2

**Comment by ohitstom** [comment]
> try with spicetify 2.23.2

im not sure why downgrading would fix this but i'll give it a go if i get time

**Comment by rxri** [comment]
Also, what is throwing an error is not `Spicetify.Menu._addItems`. Your screenshot shows the function from `Spicetify.ContextMenu._addItems`

**Comment by ohitstom** [comment]
> Also, what is throwing an error is not `Spicetify.Menu._addItems`. Your screenshot shows the function from `Spicetify.ContextMenu._addItems`

I think ive figured out the issue, i was basing me structure off of the user dropdown menu

which is:
```html
<div id="context-menu">
 <div class="main-userWidget-dropDownMenu">
   <menuWrapper>
 </div>
</div>
```

However if i dont do this the styling is completely off and i cant find a single menu example which is JUST a menu and doesnt have this context-menu.

I guess this isnt a spicetify issue but not sure where to go from here so if you have any tips please let me know 😭

**Comment by ohitstom** [comment]
I cant ping riri cause blocked  but how do we feel about preventing this error?
![image](https://github.com/spicetify/spicetify-cli/assets/22730962/9facaa4b-8d08-4bb5-8814-7f4be9c5bbe4)
(top is normal context menu, bottom is context menu made without react)
![image](https://github.com/spicetify/spicetify-cli/assets/22730962/370b1d4f-2ef1-443f-b651-d9585cce95f8)

This error is present in any custom made context menus that dont require props or are just made without react.
