### ISSUE TITLE
spotify is bricking after latest update

### ISSUE THREAD

**Issue by liiyung** [spicetify/spicetify-cli#2603]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for macOS (Apple Silicon) 1.2.22.982.g794acc0a
- Spicetify version: 2.22.1
```

### 📝 Description

On these versions of Spotify and Spicetify, Spotify opens up as a completely blank window. It doesn't seem like this issue has been submitted yet (could just be macOS), so I'm submitting a bug report. Thanks! 

steps to reproduce : spotify updated automatically, I updated spicetify manually. After the usual `spicetify backup apply`, Spotify bricks. `spicetify restore` restores Spotify to default version with no issue.

**Comment by rxri** [comment]
From our testing Spicetify works fine with latest Spotify. Do a clean install of Spotify

**Comment by befabry** [comment]
https://github.com/spicetify/spicetify-cli/issues/546#issuecomment-1762888747

I commented there. I have the latest spotify version on Arch and the latest spicetify, but it don't work.

> Downloading deb file for "spotify-client_1.2.22.982.g794acc0a_amd64.deb" version="spotify-client" ("1:1.2.22.982.g794acc0a")

> Spicetify : 2.24.2

Doing a spicetify restore did not work, I still had the `error-dialog.generic.header` error and I had to manually clean everything in order for Spotify to even work

**Comment by rxri** [comment]
I'm pretty sure spicetify doesn't work with `spotify-launcher`. Try with different aur package like [`spotify-edge`](https://aur.archlinux.org/packages/spotify-edge) or [`spotify`](https://aur.archlinux.org/packages/spotify)

**Comment by befabry** [comment]
I was using `spotify` at first, it didn't work with `spicetify`. Tried to restore, didn't work. The player wouldn't work. 

I removed the package, [checked the doc](https://spicetify.app/docs/advanced-usage/installation#spotify-installed-via-spotify-launcher-package-arch-linux), found out it supports spotify-player. I installed it, it was working. Proceeded to clear my themes, then applied it. It didn't work. I couldn't clear it, I had to manually clean everything. Reboot, re-install. Now Spotify works but I can't spice it.

**Comment by rxri** [comment]
From our testing spicetify works just fine with `1.2.22` so I suggest joining our discord server for needed help because issues on this repository are not for it

**Comment by befabry** [comment]
I don't know, tried again, this time it worked.

Sorry for the annoyance. Keep up the good work !

**Comment by liiyung** [comment]
I've actually done a clean install of Spotify and it works now. Thanks! 

However, there is possibly another bug(?) I've spotted now, in that `@media (prefers-color-scheme: light)` does not register, only changes from `@media (prefers-color-scheme: dark)` applies. Is that something you're able to address?
