### ISSUE TITLE
double button amount

### ISSUE THREAD

**Issue by dxcvvxd** [spicetify/spicetify-cli#2605]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1:1.2.22.982-3
- Spicetify version: 2.24.2
```

### 📝 Description

i have this weird thing after installing a theme and now i dont know how to fix it.
i tried `rm -rf`ing the spotify cache folder but its useless
here are the buttons
![image](https://github.com/spicetify/spicetify-cli/assets/77129815/22d48acf-4fe7-48c5-902a-2ff6b3638142)

**Comment by rxri** [comment]
You can have duplicated entries in custom_apps, but it’s not cli issue
