### ISSUE TITLE
Options to hide "By Spotify" playlists from search

### ISSUE THREAD

**Issue by Nerxxy** [spicetify/spicetify-cli#2609]
### 📝 Provide a description of the new feature

(optional) Add an option in the settings that allows the user to hide playlists by spotify only in search.

Have a pill button next to the "all, audio books, playlists......" pills that allows a user to hide or show. This button would temporarily override the option in the settings 

### ➕ Additional Information

![image](https://github.com/spicetify/spicetify-marketplace/assets/37718547/c0d2ef2a-3bce-4775-b9d9-a5eda0710754)

![image](https://github.com/spicetify/spicetify-marketplace/assets/37718547/f5a010d0-373d-4d33-b845-c1c6a6ae0c98)

**Comment by rxri** [comment]
Sorry, CLI repo doesn’t take new extensions/custom apps ideas

**Comment by Nerxxy** [comment]
wasnt an extension/custom app idea, it was meant to be something that a new spicetify update gives out to everyone as standard

**Comment by rxri** [comment]
That idea goes under new extension idea, sorry

**Comment by Nerxxy** [comment]
can u let me know where to post it then?

**Comment by rxri** [comment]
You can request it on our discord server and some developer might do it

**Comment by Nerxxy** [comment]
in the  #extensions-customapps chat?
