### ISSUE TITLE
1.2.23 icons arent sized properly

### ISSUE THREAD

**Issue by ohitstom** [spicetify/spicetify-cli#2610]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.23.1114
- Spicetify version: 2.24.2
```

### 📝 Description

im not sure what is causing this? its definitely spicetify though since when its not applied its fine.
I've uninstalled all extensions and theme related stuff and it has not helped.
![image](https://github.com/spicetify/spicetify-cli/assets/22730962/ea7c2a03-9fbe-469e-a007-489e83226e4c)

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/22730962/59140919-1035-4550-9382-98fc13034040)
![image](https://github.com/spicetify/spicetify-cli/assets/22730962/0667fc1b-4c6b-4350-86ce-2dc06004ec28)

**Comment by ohitstom** [comment]
i think its the new usage of `Button-small-small-buttonTertiary-iconOnly-useBrowserDefaultFocusStyle`, it seems all these identifiers have changed? but i didnt think we messed with any of this in spicetify

**Comment by yellowberryHN** [comment]
I also have this issue, but I also noticed that my theme wasn't loading at all after the update, potentially related?

**Comment by ohitstom** [comment]
> I also have this issue, but I also noticed that my theme wasn't loading at all after the update, potentially related?

this is because marketplace won't load without our notifications apo being loaded, I've made a pr to fix this just waiting on merge and release

**Comment by vorlie** [comment]
Same happens here. 
![Zrzut ekranu 2023-10-26 o 19 55 11](https://github.com/spicetify/spicetify-cli/assets/99135647/303f9365-80a1-4947-8b12-4a464de0c919)

**Comment by rxri** [comment]
We're aware of this issue and saying `same happens for me` or something similar only creates a spam in this issue, so I decided to lock it. Please wait for spicetify update
