### ISSUE TITLE
Use spicetify over Spotify web app

### ISSUE THREAD

**Issue by DanRotaru-lislex** [spicetify/spicetify-cli#2611]
### 📝 Provide a description of the new feature

I am using Web Version of Spotify (https://open.spotify.com/).
Reason why I use it, because on my work I always have Chrome browser opened, and, instead of use 2 apps (Spotify and Chrome) I use only one. This has positive effect on RAM management, it is using much less ram memory than having 2 separately apps, with own chromium instances.
So, It is possible to run all spicetify scripts inside web app? Extensions like Tampermonkey don't work with current scripts, because these scripts use some spicetify APIs.

All Chrome website are using 1.8 GB with all tabs and extensions opened, and only Spotify client is using 1.6 GB of RAM 😞 
![image](https://github.com/spicetify/spicetify-cli/assets/109525275/c97bf325-69b8-48f4-ac74-c4cadb0e141a)

**Comment by rxri** [comment]
Spicetify is specifically designed to work with Desktop client because we patch stuff inside javascript files and more https://github.com/spicetify/spicetify-cli/blob/master/src/preprocess/preprocess.go, so answering your question - no it's not possible, sorry
