### ISSUE TITLE
Spicetify is not installing extensions

### ISSUE THREAD

**Issue by Sabisa324** [spicetify/spicetify-cli#2614]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.22.982.g794acc0a
- Spicetify version:v2.25.0
```

### 📝 Description

so today i turned on my pc but it blue screen saying something like "KERNEL DATA IPAGE ERROR" i dont think thats related to the problem but anyways, spotify and spicetify were working good but i updated spicetify and extensions were not installing, already tried reinstalling spotify and spicetify but it did not work

### 📸 Screenshots

![Captura de pantalla 2023-10-26 105745](https://github.com/spicetify/spicetify-cli/assets/148300542/632d3169-3e5b-4804-aaad-d062fee15ad5)

**Comment by rxri** [comment]
Marketplace doesn't save installed extensions, custom apps or themes on disk. They are saved in Spotify's "memory". Your blue screen isn't related to spicetify
