### ISSUE TITLE
issue when upgrading

### ISSUE THREAD

**Issue by ssamin69** [spicetify/spicetify-cli#2619]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 0.5.1-2
- Spicetify version:2.24.2
```

### 📝 Description

cannot upgrade it says rename permission denied when it has permissions also running it as root perms it cannot detect my spotify location even when its specified already in the config-xpui.ini

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/72408262/a78e655d-9a1b-4c28-bd07-da926e34873a)

**Comment by afonsojramos** [comment]
Please find support in our discord, thanks

**Comment by SunsetTechuila** [comment]
@afonsojramos https://github.com/spicetify/.github/pull/8
