### ISSUE TITLE
Snackbar is not prioritized in `showNotification`

### ISSUE THREAD

**Issue by ohitstom** [spicetify/spicetify-cli#2621]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (32 bit)
1.2.22.982.g794acc0a
Spicetify v2.25.1
xpui_2023-10-06_1696604276454_794acc0
cef_116.0.27+gd8c85ac+chromium-116.0.5845.190
```

### 📝 Description

#2613 caused this issue.

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/22730962/57d3db82-d21f-4e60-a268-7b74b3c41f96)
![image](https://github.com/spicetify/spicetify-cli/assets/22730962/d7df1b87-6215-432f-9ac0-774eaec6980d)
![image](https://github.com/spicetify/spicetify-cli/assets/22730962/5218dab3-b5e7-4328-810e-3df2feadbeff)

**Comment by ohitstom** [comment]
note:
it works as intended on 1.2.23 however since .22 has snackbars actively available we should shoot for .22 forwards using snacks

**Comment by rxri** [comment]
It happens because xpui is loaded with defer so it's loaded after the wrapper and rewrites this function

**Comment by ohitstom** [comment]
> It happens because xpui is loaded with defer so it's loaded after the wrapper and rewrites this function

i see, but why would we want this? was the previous implementation not enough? this isnt really backwards compatibility more just "if shownotification is there use it no matter what"

**Comment by rxri** [comment]
Can you test #2622 if that fixes this issue for you?

**Comment by ohitstom** [comment]
> Can you test #2622 if that fixes this issue for you?

in its current state it does not

**Comment by rxri** [comment]
![image](https://github.com/spicetify/spicetify-cli/assets/9348108/a2c734a8-70f5-48af-abd4-bdda06b33f9c)
Weird, works for me after applying this pull request every time I reload

**Comment by ohitstom** [comment]
i think the issue lies in the usage of a set ms, the results will vary depending on computing power no?

**Comment by rxri** [comment]
We can raise it to 500ms. I don't think someone will need notification api earlier

**Comment by ohitstom** [comment]
you are slightly on a different version to me if you want to try 982 first maybe

**Comment by rxri** [comment]
> > Can you test #2622 if that fixes this issue for you?
> 
> in the prs current state it does not

It appears to be the case on `1.2.22.982.g794acc0a`. Raising the timeout value to `150`ms fixes this in my case

**Comment by ohitstom** [comment]
can confirm 150ms fixes it for me too, though if possible maybe theres a more logical way of approaching this that doesnt rely on a set timeout?

**Comment by rxri** [comment]
Wrapper is loaded earlier than `vendor~xpui.js`. Snackbar related functions are loaded later than `showNotification` which creates this issue. I tried looking for different solution but couldn't find any. I'm going to raise the timeout value to `250ms` so vendor will have time to load needed functions

**Comment by ohitstom** [comment]
sounds good to me!

**Comment by Delusoire** [comment]
Why not check the Spotify version to decide which one should be loaded instead?
Another option would be to add a function call at the end of xpui that signals that everything is loaded.

**Comment by ohitstom** [comment]
> Why not check the Spotify version to decide which one should be loaded instead?
> Another option would be to add a function call at the end of xpui that signals that everything is loaded.

i could be wrong but technically Spotify already has internal signals for this we could hook into

**Comment by rxri** [comment]
I'm not stopping you from improving it so go ahead if you want
