### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by WenchenWang** [spicetify/spicetify-cli#2624]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.22.982.g794accOa
- Spicetify version:2.25.2
```

### 📝 Description

Black Screen on windows 2023.10.30

### 📸 Screenshots

![Snv0PAGg7X](https://github.com/spicetify/spicetify-cli/assets/54831037/74018542-4a7c-4875-a66b-d9568350ee21)

**Comment by rxri** [comment]
Reinstall Spotify and then apply

**Comment by stpnwf** [comment]
> Reinstall Spotify and then apply

I am on Fedora 38 and have this issue as well. I uninstalled Spotify and reinstalled it (via flatpak) and when I open it it shows up the black screen, even before running spicetify apply. Must I do something else?

**Comment by DMGPage** [comment]
I have Pop OS 22.04 LTS and today Spotify just stopped working. Yesterday it was working just fine, but today show only black screen and nothing else. I tried to reinstall it, but that does not help.

**Comment by stpnwf** [comment]
Ok, what finally worked for me (flatpak install) was to reinstall spotify AND delete the config files, in my case in `.var`.
That got rid of the black screen for me.

Then to get the spicetify theme back on, I ran the commands below:

```
sudo chmod a+wr /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify
sudo chmod a+wr -R /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify/Apps

spicetify apply
```
