### ISSUE TITLE
Spicetify won't apply: "Marketplace theme not found"

### ISSUE THREAD

**Issue by BigLadDylan** [spicetify/spicetify-cli#2629]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: /opt/spotify/spotify: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /opt/spotify/spotify)
Spotify version 1.2.22.982.g794acc0a, Copyright (c) 2023, Spotify Ltd
- Spicetify version: 2.25.3
```

### 📝 Description

![image](https://github.com/spicetify/spicetify-cli/assets/76881322/bb960344-0e65-4076-aef6-89297090e1a6)

Hello, recently, spicetify has stopped working for some reason, it used to throw the error "spotify path not found" but i reinstalled both spicetify and spotify and now when i attempt to apply spicetify, it says that the marketplace theme not found. Other github issues are inconclusive and responses are "not related to the CLI" how could i fix the issue

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/76881322/4e074b5a-bf9a-4217-bd79-9653aaad41ea)

**Comment by rxri** [comment]
Not cli related. Issues are not for general help
