### ISSUE TITLE
Use local CSS map when remote CSS map is malformed

### ISSUE THREAD

**Issue by FrzMtrsprt** [spicetify/spicetify-cli#2631]
### 📝 Provide a description of the new feature

Due to my own network issues, spicetify always receive broken data when fetching css map from `raw.​githubusercontent.​com`. As a result, Spotify is somehow patched using a wrong css map, rendering it unable to launch.
To address this issue, spicetify should fallback to local css map not only when it can't fetch remote css map, but also when the remote css map is malformed.

**Comment by SunsetTechuila** [comment]
Send your malformed css map

**Comment by rxri** [comment]
CSS map should have no effect on properly launching Spotify. CSS map is fetched remotely only on latest version. I will close this issue because this doesn't sound as good idea

**Comment by FrzMtrsprt** [comment]
> CSS map should have no effect on properly launching Spotify. CSS map is fetched remotely only on latest version. If spicetify can't parse css map it will throw an error. If you did not see it then it's not malformed

It does throw the error "css map malformed", but it continues patching, resulting spotify not launching

**Comment by rxri** [comment]
Regardless, if it would be malformed it should throw an error https://github.com/spicetify/spicetify-cli/blob/f0d3e9fa5382c3ec31774b78dd8d4261dc5e14d2/src/preprocess/preprocess.go#L47

**Comment by rxri** [comment]
And actually just noticed if remote css fails then it will load local css so your idea is already implemented

**Comment by FrzMtrsprt** [comment]
Well, it seems it doesn't. If it does it should log "using local css map" and Spotify shouldn't be showing up an error saying it can't render the page.
![image](https://github.com/spicetify/spicetify-cli/assets/15852717/93960679-a4b9-48f9-928b-c41de4567d0d)
![image](https://github.com/spicetify/spicetify-cli/assets/15852717/788a8645-838c-4bc9-83dd-cf427f736eab)

**Comment by rxri** [comment]
Made a pull request fixing this. This fix should be available in the next release

**Comment by FrzMtrsprt** [comment]
I see, thanks!
