### ISSUE TITLE
Spicetify breaks spotify.

### ISSUE THREAD

**Issue by GiorgosAthanasopoulos** [spicetify/spicetify-cli#2639]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bit) 1.2.23.1125.g920a7ada
- Spicetify version: 2.20.0
```

### 📝 Description

I deleted spotify then reinstalled from the latest installer on spotify website. Logged in, everything works fine.
I didnt have spicetify, so i got the powershell install link, run that, and after that run `spicetify backup apply`.
Upon opening spotify, the ui never loads in, instead i get an empty black screen.

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/90207655/85f4bc65-8881-454d-b092-a7b08a58e1e7)

**Comment by rxri** [comment]
https://github.com/spicetify/spicetify-cli/releases/tag/v2.20.0 states that maximum supported version of Spotify is `1.2.13`. You're on `1.2.23` which is supported in the latest one (https://github.com/spicetify/spicetify-cli/releases/tag/v2.26.0). Please execute `spicetify upgrade` to upgrade and follow the instructions of the program

**Comment by GiorgosAthanasopoulos** [comment]
Oh thank you that worked. I just grabbed spicetify from the official website a few hours ago, i thought the install link would download the latest release.

**Comment by rxri** [comment]
If you grabbed it few hours ago, then it would download the latest version. You probably copied the link from another website that had specified specific version to download and install. No worries though. Good that it works
