### ISSUE TITLE
libc.so.6: version `GLIBC_2.34' not found

### ISSUE THREAD

**Issue by Nathan-Moresco** [spicetify/spicetify-cli#2643]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version : 1.2.22.982.g794acc0a
- Spicetify version : 2.27
- Ubuntu : 20.04.6 LTS
```

### 📝 Description

I can't run any spicetify command after the update of this morning (9 Nov 23)
The first time i got that is when i tried to run ```spicetify backup apply```

I get this :

```bash
spicetify: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by spicetify)
spicetify: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by spicetify)
```

I wish for a simple to understand and execute anwser to solve the problem please.

**Comment by rxri** [comment]
Not spicetify related - https://stackoverflow.com/questions/71940179/error-lib-x86-64-linux-gnu-libc-so-6-version-glibc-2-34-not-found

**Comment by Nathan-Moresco** [comment]
So i can't launch any spicetify command because i updated and i will have no help for getting out of this ?

**Comment by rxri** [comment]
That's due to your distro that you use not having installed necessary libs, in this case glibc. Install the version containing the `2.34` and this issue will be resolved. This issue is not necessarily related to spicetify
