### ISSUE TITLE
not working?

### ISSUE THREAD

**Issue by valtiara** [spicetify/spicetify-cli#2651]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bit) 1.2.24.756.g7a7fc7f0
- Spicetify version: v2.27.0
```

### 📝 Description

I've updated my spicetify to the latest version, but why does my spotify go back to the original again? I've reinstalled Spotify and Spicetify but it's the same as this

I also tried searching in closed case, but didn't find my problem

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/133134628/b03c30e1-5530-42bf-9b51-ca2c34c7432b)

**Comment by rxri** [comment]
Probably you’re using Microsoft store version. Uninstall and install Spotify from their official website

**Comment by valtiara** [comment]
mine is from official website , any another suggestion ?

**Comment by rxri** [comment]
Then this wouldn't be the case. After upgrading you're supposed to write `spicetify restore backup apply` and it apply spicetify, if not, show me the screenshot from terminal after executing this command
