### ISSUE TITLE
Spicetify Upgrade Redundant Info Message

### ISSUE THREAD

**Issue by ohitstom** [spicetify/spicetify-cli#2655]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spicetify: 2.27.1
```

### 📝 Description

![image](https://github.com/spicetify/spicetify-cli/assets/22730962/b0895454-3c53-480f-9264-a48d6d5a16ab)

**Comment by ohitstom** [comment]
im guessing the functionality changed to auto run spicetify restore etc but why then show the info message still? furthermore why show subsequent logs at all unless errors?

**Comment by rxri** [comment]
I forgot to remove it

**Comment by ohitstom** [comment]
> I forgot to remove it

any way we can trim the other logs? it seems weird to have so much logging for what should be done behind the scenes as part of the upgrade
