### ISSUE TITLE
Blink when click list choose in settings

### ISSUE THREAD

**Issue by hmanhng** [spicetify/spicetify-cli#2658]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.22.982.g794acc0a (nixpkgs)
- Spicetify version: https://github.com/MichaelPachec0/spicetify-nix
```

### 📝 Description

When I click on list settings like change `language`,... just blink and exit, nothing happens

### 📸 Screenshots

https://github.com/MichaelPachec0/spicetify-nix/assets/64454245/a82684c3-e8c6-4a0a-8dcf-7368ba37398c

**Comment by rxri** [comment]
Not cli related. Could be theme issue or backup issue. Try reinstalling Spotify from scratch
