### ISSUE TITLE
Change the "Guide" from when a new version is available to the new "spicetify refresh"

### ISSUE THREAD

**Issue by Tim-Odermatt** [spicetify/spicetify-cli#2659]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: (unrelated) probably the newest 
- Spicetify version: 1.27.0
```

### 📝 Description

Change the inapp guide for how to update to the newer Spicetify version, from "spicetify update" to the new "spicetify refresh".

### 📸 Screenshots

![grafik](https://github.com/spicetify/spicetify-cli/assets/91256797/8dcf40b9-042b-4250-909b-7bf5b82917ca)

**Comment by Tim-Odermatt** [comment]
never mind i am monkee brain

**Comment by rxri** [comment]
I think you misunderstood the release notes. `spicetify refresh` is for developers, however `spicetify update` does the same what `spicetify upgrade` since v2.27.0
