### ISSUE TITLE
Unable to upgrade to latest version or apply spicetify on linux

### ISSUE THREAD

**Issue by skypetroller** [spicetify/spicetify-cli#2660]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.22.982.g794acc0a flatpack
- Spicetify version v2.27.1
```

### 📝 Description

I tried upgrading to the latest version and kept getting this error message. After a while i tried to clean install spotify and spicetify and it would not apply any new changes.

### 📸 Screenshots

![Screenshot from 2023-11-14 20-19-02](https://github.com/spicetify/spicetify-cli/assets/40546792/61252798-4562-49b2-9294-a6b3495bca9a)

**Comment by rxri** [comment]
https://stackoverflow.com/questions/71940179/error-lib-x86-64-linux-gnu-libc-so-6-version-glibc-2-34-not-found. I don't know your distribution so I can't provide the package name

**Comment by skypetroller** [comment]
> https://stackoverflow.com/questions/71940179/error-lib-x86-64-linux-gnu-libc-so-6-version-glibc-2-34-not-found. I don't know your distribution so I can't provide the package name

Thank you. i'm just stupid

**Comment by rxri** [comment]
That's fine that you didn't know! Don't be hard on yourself. In the end it's good that you resolved this

**Comment by GitEin11** [comment]
pls lower the version of glibc to 2.31
