### ISSUE TITLE
When I clear all cache from my mac, it also deletes marketplace, extensions and settings

### ISSUE THREAD

**Issue by kutawhat** [spicetify/spicetify-cli#2661]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.24.756.g7a7fc7f0
- Spicetify version: 2.27.1
```

### 📝 Description

When I clear all cache from my mac using scrypt, it also deletes marketplace, extensions and settings. There's a folder Local Storage under path:
`/Users/UserName/Library/Caches/com.spotify.client/Browser/Local Storage `

So deleting this folder will cause the above problem. It would be nice if you could replace this data in another place instead of Caches. Or help me avoid that issue, please.

**Comment by rxri** [comment]
Not a bug and local storage is not a cache. It’s used by developers because browsers allows us to use it as a place to store data
