### ISSUE TITLE
Enable devtools in watch mode

### ISSUE THREAD

**Issue by jeroentvb** [spicetify/spicetify-cli#2662]
### 📝 Provide a description of the new feature

It would be awesome to automatically have the devtools be enabled when starting spicetify in watch mode.

Currently I have to enter `spicetify enable-devtools` and `spicetify watch -e`, which restarts spotify twice. And if not done fast enough devtools will be disabled again.

**Comment by rxri** [comment]
Use „always_enable_devtools_ config key

**Comment by jeroentvb** [comment]
Ah, I wasn't aware tis existed. Thanks!
