### ISSUE TITLE
[Lyrics plus] Locale error

### ISSUE THREAD

**Issue by Inovvia** [spicetify/spicetify-cli#2672]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 
Spotify for Windows (64 bit)
1.2.25.1011.g0348b2ea
xpui_2023-11-20_1700498575257_0348b2e
cef_118.7.1+g99817d2+chromium-118.0.5993.119
- Spicetify version: spicetify v2.27.1
```

### 📝 Description

1. Enable lyrics plus
2. Spicetify apply
Expected: Spotify works
Actual: Error occured

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/70137651/11d0482e-4baf-4de7-962f-993fd21dc555)

**Comment by rxri** [comment]
Per https://github.com/spicetify/spicetify-cli/releases/tag/v2.27.1, `1.2.25` is not a supported version  thus means that we're not providing support for it. Please downgrade to at least `1.2.24`
