### ISSUE TITLE
shrink window in with full app display enabled

### ISSUE THREAD

**Issue by RealLittlemrh** [spicetify/spicetify-cli#2677]
### 📝 Provide a description of the new feature

When full app display is enabled it shows just the current song, why not use that and shrinking it further than the current limit of the window to create a "mini-player" (what I mean by this is just for spotify to show a small screen of what is playing on top of my screen sort of like video pop-outs.

**Comment by rxri** [comment]
FullAppDisplay wasn’t intended to serve this purpose. Use popupLyrics if you want to see lyrics
