### ISSUE TITLE
Spotify stuck on black screen after installing Spicetify

### ISSUE THREAD

**Issue by eugene32155500** [spicetify/spicetify-cli#2679]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Latest 
- Spicetify version: 2.27.2
- OS: Windows 11
```

### 📝 Description

Spotify stuck on black screen after applying spicetify. I already tried reinstalling Spotify and Spicetify and nothing helps.

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/115146296/53de3601-0a07-4667-ba3e-8578287b28f6)

**Comment by rxri** [comment]
Latest doesn’t say much. If you’re on 1.2.25, then uninstall and install Spotify then run `spicetify backup apply`

**Comment by eugene32155500** [comment]
> Latest doesn’t say much. If you’re on 1.2.25, then uninstall and install Spotify then run `spicetify backup apply`

yeah im on 1.2.25,tried to run this command but its still doesnt help
