### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by NesChrome** [spicetify/spicetify-cli#2680]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: latest (i think)
- Spicetify version: latest too (i think)
```

### 📝 Description

Spotify updated and i re-installed spicetify with the following command in powershell : "spicetify backup apply"
and the error comes

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/105519787/e98bf0aa-f1fc-441f-ae06-2daf6eb1988f)

**Comment by afonsojramos** [comment]
Please provide the proper versions, thanks!

**Comment by NesChrome** [comment]
How can i see which versions i'm using , i didn't provided because i didn't knew how to see which ones they are

**Comment by rxri** [comment]
Upgrade to latest spicetify `spicetify update` or `spicetify upgrade`. Uninstall spotify, install spotify and run `spicetify backup apply`. Issue is not related to our patches
