### ISSUE TITLE
spicetify apply is appending /Apps to the spotify_path

### ISSUE THREAD

**Issue by Catobato** [spicetify/spicetify-cli#2681]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.22
- Spicetify version: 2.27.1
- Linux distro: NixOS
- NixOS version: 24.05
```

### 📝 Description

when running the command spicetify apply it seems to append my file path for spotify with /Apps 

-  /run/current-system/sw/bin/spotify --> /run/current-system/sw/bin/spotify/Apps

changed the spotify_path to a couple of random paths and it seems to also append /Apps

- /home/catobato/.bashrc -->- /home/catobato/.bashrc/Apps

also tried reinstalling spotify and rebooting
side note: when running /run/current-system/sw/bin/spotify it does open spotify

### 📸 Screenshots

![20231126_08h57m35s_grim](https://github.com/spicetify/spicetify-cli/assets/42500566/3e7b0ee1-2e5f-45bb-909b-ad374bd5f1e4)

**Comment by rxri** [comment]
`spotify_path` is a folder where spotify is installed, not the path to binary

**Comment by Catobato** [comment]
corrected it and replaced it with a path to folder.

**Comment by Catobato** [comment]
my bad should of figured that one out but even after changing it to a path to a folder i seem to still get the same result I tried with 
/run/current-system/sw/bin --> /run/current-system/sw/bin/Apps
/run/current-system/sw/etc --> /run/current-system/sw/bin/Apps 
/home --> /home/Apps 
![20231126_10h07m16s_grim](https://github.com/spicetify/spicetify-cli/assets/42500566/9c5b8ebf-8e8a-424a-94a0-ba704c959359)
ill assume this is still my error and ill try messing with versions of spotify and spicetify to see if it works

**Comment by rxri** [comment]
That's how it's supposed to work. You need to provide actual path to where spotify installation is located e.g. on windows it's `%appdata%\Spotify`
![image](https://github.com/spicetify/spicetify-cli/assets/9348108/99ce8015-5ae0-4b38-bb66-55c5ee7e1722)
on linux it depends so you need to find this directory by yourself
