### ISSUE TITLE
Spotify stuck on black screen after applying Spicetify

### ISSUE THREAD

**Issue by eugene32155500** [spicetify/spicetify-cli#2682]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.25
- Spicetify version: 2.27.2
```

### 📝 Description

Spotify is getting stuck on black screen after applying Spicetify

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/115146296/70162b1f-19ba-406f-aebe-7b9073f57823)

**Comment by rxri** [comment]
Uninstall spotify, install it again and run `spicetify backup apply`. Please use our discord for general help next time
