### ISSUE TITLE
spicetify tries to run restore while update even if spotify is in stock state

### ISSUE THREAD

**Issue by SunsetTechuila** [spicetify/spicetify-cli#2684]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.25
- Spicetify version: 2.27.2
```

### 📝 Description

1. `spicetify restore`
2. `spicetify update`

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/115353812/0a8eb0f7-496d-411a-a315-c1f1949ab733)

**Comment by rxri** [comment]
Can't reproduce
![image](https://github.com/spicetify/spicetify-cli/assets/9348108/c64aaf75-3d35-47e7-af01-23469c3698fd)
