### ISSUE TITLE
Block KmInteraction+KmPageView+SettingsMutated_Hourly logs

### ISSUE THREAD

**Issue by ohitstom** [spicetify/spicetify-cli#2686]
### 📝 Provide a description of the new feature

just received my technical log information from spotify and so far this is the only thing i find exposing users for using spicetify

### ➕ Additional Information

![image](https://github.com/spicetify/spicetify-cli/assets/22730962/b38f3d6b-4ad1-4c19-92fc-577322cfb0fe)
![image](https://github.com/spicetify/spicetify-cli/assets/22730962/176f78ff-7557-41c2-82b9-b5e94754645b)

**Comment by rxri** [comment]
Should be blocked by https://github.com/spicetify/spicetify-cli/commit/a675c7176ec829c72644c4b412a09f220f34d38e
