### ISSUE TITLE
Shuffle+ Local Files issue

### ISSUE THREAD

**Issue by himasd** [spicetify/spicetify-cli#2689]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.22.982.g794acc0a
- Spicetify version: 2.24.2
```

### 📝 Description

Whenever you click the "Shuffle+ Local Files" option this happens, it duplicates the song 3 times and it also won't let me skip or remove any of the 3 tracks so it kinda goes into a frozen state, I have no idea what causes this
![image](https://github.com/spicetify/spicetify-cli/assets/85947246/d9fd5403-94e5-4450-a9f5-5db357ea1ecb)

### 📸 Screenshots

A image of what i'm talking about
![image](https://github.com/spicetify/spicetify-cli/assets/85947246/d4808b04-4955-4924-a598-721eeb2bc2e3)

**Comment by rxri** [comment]
Is it a thing on latest spicetify/spotify version? Since you are a few versions behind

**Comment by himasd** [comment]
> Referenc

Yes

**Comment by ohitstom** [comment]
this might be a context issue
normal:
![image](https://github.com/spicetify/spicetify-cli/assets/22730962/17ff262d-8f8c-4361-92b8-918b9809fea5)
![image](https://github.com/spicetify/spicetify-cli/assets/22730962/8809966e-5136-4291-9b60-9edcbf34e1c5)

broken:
![image](https://github.com/spicetify/spicetify-cli/assets/22730962/f986e509-c34c-44c0-93ce-401bf1bdf6c9)
![image](https://github.com/spicetify/spicetify-cli/assets/22730962/559ab190-f35b-42af-a4e0-14e54244f31f)

**Comment by rxri** [comment]
Is context even needed for local files? Because it works just fine when context is not set
