### ISSUE TITLE
( Its a valid path ) error ~/.local/share/spotify-launcher/install/usr/share/spotify/ does not exist or is not a valid path. Please manually set "spotify_path" in config-xpui.ini to correct directory of Spotify.

### ISSUE THREAD

**Issue by t101804** [spicetify/spicetify-cli#2690]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Using spotify from spotify-launcher
- Spicetify version: 2.27.2
```

### 📝 Description

I have a valid folder ~/.local/share/spotify-launcher/install/usr/share/spotify/ and i put this on the config and then it shows 'error ~/.local/share/spotify-launcher/install/usr/share/spotify/ does not exist or is not a valid path. Please manually set "spotify_path" in config-xpui.ini to correct directory of Spotify.'

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/113588203/be3be5f4-370a-42da-a251-0c6eb63f12f4)

**Comment by t101804** [comment]
![image](https://github.com/spicetify/spicetify-cli/assets/113588203/90597e32-a6f3-481f-9d1d-55e22074c882)
its a valid path

**Comment by rxri** [comment]
You should use absolute path so instead of using an alias `~` change it to your home directory
