### ISSUE TITLE
spicetify override by system

### ISSUE THREAD

**Issue by mas-hash** [spicetify/spicetify-cli#2698]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.225.1011.0
- Spicetify version:1.2.25.1011.g0348b2ea
```

### 📝 Description

hi so i installed my spicetify client by power shell (admin) and installed spotify from web (like with the setup installation) and it works perfect for the day but when i open the spotify for the next day the spicetify goes off and when i try to open the spotify client first few seconds a progress bar pops up stating that retrieving data and that's when i found out that windows automatically overrides my browser installed spotify client which ultimately leads to removal of spicetify client so my query is there any possible ways to stop this override because its not handy to install spicetify client everyday i hear songs

**Comment by mas-hash** [comment]
did u read the first line which said that installed spotify from web?

**Comment by rxri** [comment]
> client first few seconds a progress bar pops up stating that retrieving data

I'm first time hearing that so it's most likely something something on your end which we can't help you with, I'm sorry

**Comment by mas-hash** [comment]
oky :(
