### ISSUE TITLE
Lyrics Plus Not Available

### ISSUE THREAD

**Issue by OyJohny** [spicetify/spicetify-cli#2699]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify macOS (Apple Silicon) 版
1.2.25.1011.g0348b2ea
- Spicetify version:v2.27.2
```

### 📝 Description

Unable to load

### 📸 Screenshots

<img width="1450" alt="image" src="https://github.com/spicetify/spicetify-cli/assets/50914611/162c6465-1a5e-49f1-b075-6b43720d73f9">

**Comment by rxri** [comment]
You're either rate-limited or there's no lyrics on Musixmatch (which Lyrics-plus uses as provider)

**Comment by Julymycin** [comment]
> You're either rate-limited or there's no lyrics on Musixmatch (which Lyrics-plus uses as provider)

But it seems that the internal Spotify lyrics service works well as on the screenshot, which lyric plus should use as provider too?

**Comment by OyJohny** [comment]
> You're either rate-limited or there's no lyrics on Musixmatch (which Lyrics-plus uses as provider)
No either rate-limited
There's have lyrics on Musixmatch
The fault lies on the Lyrics-plus，and can‘t be resolved

**Comment by rxri** [comment]
> > You're either rate-limited or there's no lyrics on Musixmatch (which Lyrics-plus uses as provider)
> > No either rate-limited
> > There's have lyrics on Musixmatch
> > The fault lies on the Lyrics-plus，and can‘t be resolved

Okay, then you are rate-limited or something was on their end, because I can't reproduce your issue in Lyrics Plus. If you want, you can switch to Spotify provider as first choice in settings
