### ISSUE TITLE
Hovering a SubMenu doesn't hide existing open menu

### ISSUE THREAD

**Issue by duffey** [spicetify/spicetify-cli#2700]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bit) 1.2.25.1011.g0348b2ea
- Spicetify version: Spicetify v2.27.2
```

### 📝 Description

1. Register a SubMenu [as described on the Spicetify website](https://spicetify.app/docs/development/api-wrapper/classes/menu/#submenu).
2. Hover over a Spotify-created submenu.
3. Hover over your submenu.
4. The Spotify submenu is not hidden.
5. Expected: The Spotify submenu is hidden.

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/661081/55a7c74b-08f3-4787-b68b-a8ffe84aabb3)

**Comment by rxri** [comment]
Not a bug, neither ever was a feature. We don't use their module or code to close their submenus when you open yours.
