### ISSUE TITLE
Revert #2701

### ISSUE THREAD

**Issue by ohitstom** [spicetify/spicetify-cli#2711]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
N.A
```

### 📝 Description

This is an incredibly stupid idea, half of the 'private' methods and props are REQUIRED to properly handle snacks.
You've turnt a singular regex into multiple and now you will have to handle stuff individually.

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/22730962/9154a35c-7192-48fb-bc47-24d35c8e39ea)
![image](https://github.com/spicetify/spicetify-cli/assets/22730962/478e5f05-8630-45b8-8283-4b0117944101)

**Comment by ohitstom** [comment]
what about props, queues, states

> It works as expected after testing this pull request after it was merged. `Updater` methods will be added back with #2707

**Comment by rxri** [comment]
Notistack module doesn't expose private methods either. Grigory made right thing removing private methods, even Updater isn't exposed but we will expose it for specific use-cases

**Comment by ohitstom** [comment]
> Notistack module doesn't expose private methods either. Grigory made right thing removing private methods, even Updater isn't exposed but we will expose it for specific use-cases

this isnt notistack.

**Comment by rxri** [comment]
This is notistack. MUI Snackbar component doesn't provide `SnackbarProvider`, which is only available via notistack

**Comment by ohitstom** [comment]
> This is notistack. MUI Snackbar component doesn't provide `SnackbarProvider`, which is only available via notistack

explain to me the negatives of keeping these private methods in, they WORK, and are used by Spotify themselves.
You are turning one line of regex into 5, and not allowing devs proper access to default props, queues, and states.

**Comment by ohitstom** [comment]
are you going to reimplement queue handling? dismissle handling? etc? these are vital functions

**Comment by ohitstom** [comment]
Why are you ignoring props and all the handling functions, these are exposed by notistack and work perfectly fine.
The props being especially important

**Comment by rxri** [comment]
Please show me where it's exposed because it's literally not 🙏 
![image](https://github.com/spicetify/spicetify-cli/assets/9348108/ffc6aecb-b586-4faf-8a7d-33f6dc8f675c)

**Comment by ohitstom** [comment]
https://github.com/iamhosseindhv/notistack/blob/a61155adc85443f01dfc8818b6b6653edbd83288/src/SnackbarProvider/SnackbarProvider.tsx#L221

this line down.

**Comment by rxri** [comment]
![image](https://github.com/spicetify/spicetify-cli/assets/9348108/41f2ce52-e396-413b-9d60-595092c79f52)
This is my last message in this conversation

**Comment by ohitstom** [comment]
> ![image](https://private-user-images.githubusercontent.com/9348108/289192993-41f2ce52-e396-413b-9d60-595092c79f52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwNzA5MjYsIm5iZiI6MTcwMjA3MDYyNiwicGF0aCI6Ii85MzQ4MTA4LzI4OTE5Mjk5My00MWYyY2U1Mi1lMzk2LTQxM2ItOWQ2MC01OTUwOTJjNzlmNTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDhUMjEyMzQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzFkMTJmZDhmMmE4OTc1YzUxOTM3N2M4ZmI2YjE4YjY2ZDdmOWI2ZmEwNzNkNzFjMzA5YTMxMjlkMjRjNjc2NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1rjdJhxHm28Bg0AYt1C4bBP6m9cU6B26ptdi5S_pTIA) This is my last message in this conversation

https://github.com/iamhosseindhv/notistack/blob/a61155adc85443f01dfc8818b6b6653edbd83288/src/SnackbarProvider/SnackbarProvider.tsx#L221

**Comment by ohitstom** [comment]
![image](https://github.com/spicetify/spicetify-cli/assets/22730962/2900617d-0ac8-400a-be3e-03f28f91101b)
there is so much evidence of this stuff being used, its all useful and there is no reason to remove it.

**Comment by rxri** [comment]
The conversation goes nowhere, because you don't seem to understand the code you look at. I'm not also going to discuss something with person that is abusing caps lock (which most likely means you're showing your temper). Unless I get sandbox link with the evidence that you can use these functions, I'm not backing off this decision. You mention that we break the existing addons in process, however the only function used from the removed ones that I saw is `updater.enqueueSetState()` to clean queue/snacks by Delusoire. Quick github search shows that no one uses them. The mui snackbar doesn't expose these functions either. This issue will be now closed and locked because you don't know when to stop. If you will ever want to send this sandbox link, you can do it via emailing `me@ririxi.dev`, or my telegram that you can find in my readme.

**Comment by rxri** [comment]
Conversation is not going to be unlocked, however, after some discussions between devs, your use case (you probably want to use in `pure.js`) is valid, and that's my only and final time I will expose private functions from module that didn't account it. Next time please be more polite, and share your use case which will be grateful and most likely in your favor
