### ISSUE TITLE
[What's New Feed] Compact/grid view and dismiss option

### ISSUE THREAD

**Issue by guiltlab** [spicetify/spicetify-cli#2714]
### 📝 Provide a description of the new feature

With the recent break of New Releases custom app due to Spotify changes, users have been redirected to the What's New section. This is working very well in terms of getting new releases - no problem in accuracy of the feature.

Unfortunately, Spotify's What's New feed suffers from two major limitations which the new releases custom app didn't have:
- the list is very clunky when you have lots of followed artists, and you need to scroll a lot. In full screen 1080p, I can only display 5 releases at a time, after zooming out. Before, with the New Releases grid-like view you could have ~20-25 in a single display which was a lot more practical.
- you cannot dismiss releases that you're not interested in/already checked out, which was possible thanks to https://github.com/spicetify/spicetify-cli/pull/2328

It would be great if we could have a grid/compact view and the ability to hide releases as well with the What's New feed. Thank you :pray:

**Comment by ohitstom** [comment]
I dont see why we would modify Spotify own features in such a way, we have never done so nor will.

**Comment by guiltlab** [comment]
> I dont see why we would modify Spotify own features in such a way, we have never done so nor will.

Well, I was suggesting modifying What's New because it was said [here](https://github.com/spicetify/spicetify-cli/issues/2678) that fixing New Releases was not really planned, so it I thought adapting What's New was the only realistic option. But of course fixing the custom app is fine by me !! Thank you !

**Comment by afonsojramos** [comment]
I think this was a very reasonable ticket if `New Releases` was truly unfixable. Especially since just with a few Albums/EPs/Singles filters, the usability would improve greatly! But I suppose that if we manage to get New Releases working again we won't need this.

**Comment by ohitstom** [comment]
> I think this was a very reasonable ticket if `New Releases` was truly unfixable. Especially since just with a few Albums/EPs/Singles filters, the usability would improve greatly! But I suppose that if we manage to get New Releases working again we won't need this.

yes but it's also a hard ask and something this project has never been about, this would fit the usecase of a third party extension not part of the CLI.....

**Comment by afonsojramos** [comment]
That's fair for sure, not the right place to ask. Thanks @guiltlab @ohitstom! Hopefully we can get New Releases back on track!
