### ISSUE TITLE
Network Problems

### ISSUE THREAD

**Issue by avanishkasar** [spicetify/spicetify-cli#2720]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 
- Spicetify version:
2.28.1
```

### 📝 Description

i have been trying to download spicetify from 2 network providing company vodafone and jio(indian),and the link in the commands given both powershell and cmd are just not able to open the link for market placenor the actual spicetify download link for github,only the vodaphone network could open it

### 📸 Screenshots

iwr -useb https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.ps1 | iex
Invoke-WebRequest: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
![Screenshot 2023-12-12 214707](https://github.com/spicetify/spicetify-cli/assets/151715253/84d26851-d648-4bbd-88f9-f1710ad7bf41)

**Comment by rxri** [comment]
Issue is on your end because your network cannot access `githubusercontent.com`. Please try with VPN/proxy or Cloudflare WARP
