### ISSUE TITLE
Cannot detect prefs file location error on Fedora, spotify installed via flatpack

### ISSUE THREAD

**Issue by ThisIsDevolper** [spicetify/spicetify-cli#2724]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.25.1011.g0348b2ea
- Spicetify version: v2.28.1
```

### 📝 Description

I tried installing spicetify following the guide (https://spicetify.app/docs/advanced-usage/installation/), but when trying to do anything (for example spicetify restart) i get this error "error Cannot detect Spotify "prefs" file location. Please manually set "prefs_path" in config-xpui.ini". I also tried putting my (verified) prefs path in the config file, but it did nothing; as I said I did everything the guide told me to, or at least I think so.

This is my config file

  GNU nano 7.2                                              /home/the_devolper/.config/spicetify/config-xpui.ini                                                        
[AdditionalOptions]
sidebar_config        = 1
home_config           = 1
experimental_features = 1
extensions            =
custom_apps           =

[Patch]

[Setting]
prefs_path             = /home/the_devolper/.var/app/com.spotify.Client/config/spotify/prefs
spotify_path           = /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify/
inject_theme_js        = 1
overwrite_assets       = 0
spotify_launch_flags   =
check_spicetify_update = 1
prefs_path             =
current_theme          =
color_scheme           =
inject_css             = 1
replace_colors         = 1
always_enable_devtools = 0

[Preprocesses]
disable_sentry     = 1
disable_ui_logging = 1
remove_rtl_rule    = 1
expose_apis        = 1

; DO NOT CHANGE!
[Backup]
version =
with    =

**Comment by SunsetTechuila** [comment]
![image](https://github.com/spicetify/spicetify-cli/assets/115353812/cd57acbd-ce90-40cd-ac74-8d6d1f51f318)

**Comment by ThisIsDevolper** [comment]
to me this feels like an actual bug, but not a problem, I'll go there, thanks

**Comment by rxri** [comment]
It's not a bug. The path provided on our docs is an example for specifically manjaro. You should find the path to spotify by yourself with e.g. `flatpak --installations`

**Comment by ThisIsDevolper** [comment]
I checked and that should be the right path; also i used the commands in the guide (I didn't change anything as I saw I had the same path as the guide, so I'm sure I ran the commands correctly)

**Comment by PureTryOut** [comment]
I have the same problem, the path I've set is correct (I've verified). Permissions are 644, so properly accessible by my user.
Different distro (Alpine Linux) but still Flatpak so it shouldn't really matter.
