### ISSUE TITLE
link `.encore-*` color variables to spicetify color variables

### ISSUE THREAD

**Issue by SunsetTechuila** [spicetify/spicetify-cli#2728]
### 📝 Provide a description of the new feature

some of them are already linked, but mostly incorrect

### ➕ Additional Information

![image](https://github.com/spicetify/spicetify-cli/assets/115353812/47625ad2-8adf-4787-8944-e8b7be0f00ea)

**Comment by SunsetTechuila** [comment]
linking them directly instead of replacing colors by value will also resolve #1958

**Comment by rxri** [comment]
why closed?
