### ISSUE TITLE
[Bug] Album Art within UI elements not updating without hard refresh of UI or soft refresh of panels.

### ISSUE THREAD

**Issue by jedinjapan** [spicetify/spicetify-cli#2729]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.26.1187
- Spicetify version: 2.28.1
```

### 📝 Description

Updates to the Now Playing image are not triggering a refresh in the interface. This affects:

- Playbar Album Art
- Now playing view sidebar
- Playlist backgrounds

The bottom left Now Playing Album Art, as well as progress bar will not update, no matter how much time is given without triggering a manual refresh of the UI (easily achieved by changing theme). After which the progress bar and image will match only until the end of the current song. 

The Now Playing side panel will refresh each time it is re-opened. 
The background art of the current playlist behaves the same, and will change after reloaded by clicking again.

In the attached image, I have started a playlist, opened the side panel, then clicked the playlist, resulting in 3 different Album Arts for the "Now Playing" song, with only the last being accurate till end of song. The Progress bar is non-functional as it has exceeded the current song length. (Theme is "comfy)

Tested with all extensions, themes and snippets removed before posting, and seeing similar behavior. Uninstalling Spicetify, no issues with tracks updating the Album Art in vanilla spotify. Reinstalling Spicetify, no extensions, etc, and the problem immediately returns.

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/24239829/7cfa7b80-edc1-4f6c-a017-ad26e35566c6)

**Comment by SunsetTechuila** [comment]
not spicetify issue
most likely your backup is messed up, run spotify installer and then do `spicetify backup apply`
if that doesn't help, ask for help on our discord support server

**Comment by jedinjapan** [comment]
Thank you for the direction. I will check with discord, but followed instructions above and ran the spotify windows installer, and entered this exact command already, however based on your advice I did this again to the same results:

Vanilla spotify on first launch after install works fine.
Post-spicetify command, Playbar/Album art no longer functioning, issues as described above.

Will update this issue with any solution provided in the discord.

**Comment by jedinjapan** [comment]
Update for future users with this issue to aid in resolving it (workaround for this bug really):

I must disagree with the claim above: the issue is in Spicetify somewhere. I have not yet cleared the data from my recycle bin for the manual uninstall, so if there is a log or a file within that would be useful to the devs, please reach out to me so I can post it here.

Performing a full uninstall by removing %appdata%\spicetify and %localappdata\spicetify and reinstalling from PowerShell resolved this issue by wiping the slate clean for Spicetify. 

Vanilla Spotify functioned fine in all instances, and after a complete uninstall spicetify no longer presented with this issue.
