### ISSUE TITLE
Stuck on "setting upp

### ISSUE THREAD

**Issue by f-iturburu** [spicetify/spicetify-cli#2730]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 

Spotify for Windows (64 bits)
1.2.26.1187.g36b715a1

- Spicetify version: 2.28.1
```

### 📝 Description

Stucked on "setting up..." while Spicetify Marketplace

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/110144425/19cd2e3f-cc2f-425a-b881-f88f10f4b03f)

![image](https://github.com/spicetify/spicetify-cli/assets/110144425/971748f0-7205-44c5-9d2d-94f6f0687111)

**Comment by TheChilledBuffalo** [comment]
Wrong repo mate, head over to the the [marketplace repo](https://github.com/spicetify/spicetify-marketplace) and open an issue there.

Side Note: Can't seem to reproduce the issue.

**Comment by f-iturburu** [comment]
I'm so sorry, thanks for the advice.
