### ISSUE TITLE
installation problem occuring

### ISSUE THREAD

**Issue by tchhhh123** [spicetify/spicetify-cli#2731]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 
- Spicetify version:
```

### 📝 Description

I have been using spicetify since 3 months but suddenly then it stopped working.To fix it I tried to install it again but still the issue occured so i left it.Fast forward to since two weeks,I have been trying to install it and powershell doesn't identify it as a progamme and shows me this message.please do tell any solution

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/137778834/13a240ff-40bc-49b9-86da-7b0609685590)

**Comment by rxri** [comment]
You already created ticket on discord server
