### ISSUE TITLE
spotify playlists not showing up despite restarting, updating and etc

### ISSUE THREAD

**Issue by fawnyeo** [spicetify/spicetify-cli#2735]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bit)
1.2.26.1187.g36b715a1
- Spicetify version:Spicetify v2.27.1
```

### 📝 Description

spicetify is able to work as per usual, but i am unable to locate my playlists in the side bar, and can only do so in the home page. 

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/102406279/4332a6f0-d39b-4f8c-a1e5-064cf28aec6c)

**Comment by rxri** [comment]
That’s not spicetify related. Also, `v2.2.71` doesn’t support `1.2.26` Uninstall, install spotify again, upgrade spicetify and do `spicetify backup apply`
