### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by Skorflex** [spicetify/spicetify-cli#2737]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Last one via the website (not microsoft store)
- Spicetify version: Last one via the website
```

### 📝 Description

When I launch the script this appear, I think its because my username of Windows is "Mathéo" with a "é" and not a "e" 

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/118776041/9e79f5f4-1481-4614-a69b-11953ec0a3c5)

**Comment by SunsetTechuila** [comment]
this is not a script issue and nothing can be done
