### ISSUE TITLE
can't apply catppuccin-macchiato theme

### ISSUE THREAD

**Issue by ryannewcomer** [spicetify/spicetify-cli#2743]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bit)
1.2.26.1187.g36b715a1
- Spicetify version:v2.28.1
```

### 📝 Description

i had clone the theme and copy them to my config dir /theme file. then chage current_theme to catppuccin-macchiato. then `spicetify apply`. then this is shown:
![image](https://github.com/spicetify/spicetify-cli/assets/88273136/d9bddfbe-0ae7-40a2-bea9-a1f92a61a9ac)
my full config:
ini `Settings
prefs_path                    C:\Users\ryanh\AppData\Roaming\Spotify\prefs
inject_css                    1
replace_colors                1
overwrite_assets              1
spotify_launch_flags
check_spicetify_upgrade       0
spotify_path                  C:\Users\ryanh\AppData\Roaming\Spotify
current_theme                 catppuccin-macchiato
color_scheme                  Base
check_spicetify_update        1
inject_theme_js               1
always_enable_devtools        0

Preprocesses
disable_sentry                1
disable_ui_logging            1
remove_rtl_rule               1
expose_apis                   1
disable_upgrade_check         1

AdditionalFeatures
extensions
custom_apps                   marketplace
sidebar_config                1
home_config                   1
experimental_features         1

Backup
version                       1.2.26.1187.g36b715a1
with                          2.28.1`

### 📸 Screenshots

![Screenshot 2023-12-30 123434](https://github.com/spicetify/spicetify-cli/assets/88273136/7e484f8d-8cb6-480d-b382-92674bfd1d02)

**Comment by SunsetTechuila** [comment]
not a spicetify issue

![image](https://github.com/spicetify/spicetify-cli/assets/115353812/1d98e466-82d7-4fb1-a17e-c03d67d6f86c)
