### ISSUE TITLE
Play/Pause button in fullAppDisplay extension stuck on pause icon (2 lines)

### ISSUE THREAD

**Issue by 1to5pc** [spicetify/spicetify-cli#2752]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1:1.2.26.1187.g36b715a1
- Spicetify version: 2.29.1
```

### 📝 Description

After launching the extension, the Play/Pause button remains stuck on the pause icon. The button still works, but stops updating when the song is playing (aka Pause button being displayed).
If the song is paused and then if the extension is launched the button displays the play symbol and when pressed reverts to the pause icon until the song is paused and extension relaunched.

### 📸 Screenshots

When the song is paused and extension is launched:
![Screenshot from 2024-01-06 07-12-01](https://github.com/spicetify/spicetify-cli/assets/80444139/8f8751db-3bb7-42e6-8ab9-2f7f42d4b380)
After the song resumes playing and when the song is paused once more:
![Screenshot from 2024-01-06 07-12-12](https://github.com/spicetify/spicetify-cli/assets/80444139/55004606-af70-479e-9293-8c877db1649f)

**Comment by rxri** [comment]
fix will be available in the next spicetify release. sorry for that 😄
