### ISSUE TITLE
Option to style sneak-keys from keyboardShortcuts

### ISSUE THREAD

**Issue by roman-balzer** [spicetify/spicetify-cli#2755]
### 📝 Provide a description of the new feature

Hey, I wanted to style the sneak-keys from keyboardShortcuts. However, I cannot use customCss, since the sneak-keys have a shadow-roots, also I cannot override the styles in the js file, since I do not find it locally on my machine... (please point me to it if it's somewhere)

Would be awesome if the sneak-keys could use customProperties (`var(--my-property`) for styles, these will be passed down through a shadow root.

**Comment by rxri** [comment]
You can use custom css with `!important` at the end so your style will be more important than the one defined in extension

**Comment by Delusoire** [comment]
> ### 📝 Provide a description of the new feature
> Hey, I wanted to style the sneak-keys from keyboardShortcuts. However, I cannot use customCss, since the sneak-keys have a shadow-roots, also I cannot override the styles in the js file, since I do not find it locally on my machine... (please point me to it if it's somewhere)
> 
> Would be awesome if the sneak-keys could use customProperties (`var(--my-property`) for styles, these will be passed down through a shadow root.
> 
> ### ➕ Additional Information
> _No response_

I suspect that you're referring to this extension: https://github.com/Delusoire/spicetify-extensions/tree/main/extensions/keyboard-shortcuts, as it is the only extension that uses the shadow dom.
If that is the case you can style the `sneak-key`s directly by using this css selector: `sneak-overlay::part(key)`
