### ISSUE TITLE
expose ability to assign context menus without react

### ISSUE THREAD

**Issue by ohitstom** [spicetify/spicetify-cli#2757]
### 📝 Provide a description of the new feature

This is surely something spotify have a function for internally, the reason this would be beneficial is that i want to add a right click context menu item to a `Spicetify.Topbar.Button` which means i cant use a react component to render it since its using the spice api!

maybe theres something missing that i can do on my end?

### ➕ Additional Information
only current way im aware of
```js
return Spicetify.React.createElement(
	Spicetify.ReactComponent.ContextMenu,
	{
		offset: [0, 12],
		trigger: "click",
		placement: "top",
		menu: Spicetify.React.createElement(menuWrapper), // Spicetify.ReactComponent.Menu
	},
	Spicetify.React.createElement("div to assign to")
);
```

**Comment by rxri** [comment]
Stop thinking that every component can be used without React
cc. https://github.com/spicetify/spicetify-cli/pull/2776#issuecomment-1904762028

**Comment by ohitstom** [comment]
> Stop thinking that every component can be used without React cc. [#2776 (comment)](https://github.com/spicetify/spicetify-cli/pull/2776#issuecomment-1904762028)

whoa no need to be hostile, also this is quite literally the first issue ive opened with a request like this?

**Comment by rxri** [comment]
Second one actually but whatever
