### ISSUE TITLE
Cant Logout

### ISSUE THREAD

**Issue by M0rph1neee** [spicetify/spicetify-cli#2761]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bit)
1.2.26.1187.g36b715a1

- Spicetify version:Spicetify v2.29.1
```

### 📝 Description

Why I cant logout after im using spicetify?

**Comment by rxri** [comment]
Not spicetify related. We do not change the behavior of any authentication methods. If you cannot logout and think that it's spicetify's problem, restore spicetify with `spicetify restore` and logout, and if that doesn't work - uninstall spotify and install it again

**Comment by M0rph1neee** [comment]
ooh its work, thank you XD
