### ISSUE TITLE
Error installing 

### ISSUE THREAD

**Issue by Ociosity** [spicetify/spicetify-cli#2766]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 8.8.1
- Spicetify version: 2.3.0
OS: Windows 7
I3 530
GT 240/320 OEM
10GB DDR3
```

### 📝 Description

Ran the installer and it throws this error when I try to run the spicetify command afterwards
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime.asmstdcall()
        /opt/hostedtoolcache/go/1.21.5/x64/src/runtime/sys_windows_amd64.s:65 +0x75 fp=0x22fca0 sp=0x22fc80 pc=0x468a15
rax     0x0
rbx     0x9941e0
rcx     0x9e7f20
rdi     0x7fffffde000
rsi     0x22fea0
rbp     0x22fde0
rsp     0x22fc78
r8      0x0
r9      0x22fee0
r10     0x9b9d78
r11     0x21
r12     0x22fec0
r13     0x1
r14     0x993b80
r15     0x0
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/156525942/9b1c6269-11fb-42ad-bc55-21cc060b8a65)

**Comment by rxri** [comment]
Well, we can't really help with that, since it's not something we can fix. It looks like windows 7-specific error from golang
