### ISSUE TITLE
Update command ignores norestart

### ISSUE THREAD

**Issue by Protonosgit** [spicetify/spicetify-cli#2767]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.26.1187.g36b715a1
- Spicetify version: 2.30.0
- windows 10
```

### 📝 Description

The spicetify update command ignores the -n flag and restarts 2 times during update proccess.

**Comment by rxri** [comment]
because it has to. Update command executes `restore` and `apply` command automatically so it needs to restart. Not a bug.

**Comment by Protonosgit** [comment]
In earlier versions this was possible and it should be at least reduced to one restart

**Comment by rxri** [comment]
It cannot be reduced to one restart. Earlier versions did not have this behavior. Upgrade command before was only updating spicetify and it was it, so in this case `norestart` flag did nothing
