### ISSUE TITLE
Spicetify won't connect to Spotify

### ISSUE THREAD

**Issue by FireDragons52** [spicetify/spicetify-cli#2768]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 2.26.1187
- Spicetify version: 2.30.0
```

### 📝 Description

I tried setting up Spicetify and it couldn't find the Spotify path, so I went into the config-kpui.ini file myself and tried setting it. Due to the fact that I downloaded Spotify from the Windows store, it's located in the WindowsApps folder, I unlocked the folder, copied the path into the config file, and it gave me an error of "error [filepath] is not a valid path. Please manually set "spotify_path" in config-xpui.ini to correct directory of Spotify.". Is this just an issue because I have the microsoft store app?

**Comment by rxri** [comment]
Yes, it’s because of it
