### ISSUE TITLE
work on spotify verison 1.2.26.1187.g36b715a1 (aur verison)

### ISSUE THREAD

**Issue by etherbiswas** [spicetify/spicetify-cli#2771]
### 📝 Provide a description of the new feature

Spicetify would work on newer versions of Spotify 

### ➕ Additional Information

Rolling release distros like arch run newer versions of Spotify. Partial downgrade may lead to system instability and this is generally a bad practice for security. Older Spotify version like 1.1.x can be installed using downgrade but even then it is very buggy.

**Comment by rxri** [comment]
Spicetify works from 1.2.0 to 1.2.28 (and probably 1.2.29 - didn’t test though), so I don’t understand your issue
