### ISSUE TITLE
TV Mode plugin not working correctly on specific song

### ISSUE THREAD

**Issue by Humper04** [spicetify/spicetify-cli#2773]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.29.605.g66a43ceb
- Spicetify version: 2.30.0
```

### 📝 Description

Missing track delay in Ajustments Menu from TV Mode for songs without exact lyrics, other songs work normal. Uploaded some screenshots.  If you need more information, just ask me.

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/69055766/01e1476b-a7c4-4191-ae34-b5106cdd6905)
![image](https://github.com/spicetify/spicetify-cli/assets/69055766/8dddea65-85d4-4a2b-a334-f5f6029a7b72)

![image](https://github.com/spicetify/spicetify-cli/assets/69055766/474979d2-0df5-4a28-aee6-7fb6b1a043a5)
![image](https://github.com/spicetify/spicetify-cli/assets/69055766/bbdf5038-bbf4-4f9f-acc7-f1121cb5d3f9)
![image](https://github.com/spicetify/spicetify-cli/assets/69055766/8dd6681c-5594-47ff-8977-91aef062fb83)
![image](https://github.com/spicetify/spicetify-cli/assets/69055766/c201b175-5360-4166-b058-40a5474e8867)

**Comment by rxri** [comment]
Not a bug. It's simply musixmatch (the lyrics provider) not having the lyrics synced

**Comment by Humper04** [comment]
Then why am I missing certain options?

**Comment by rxri** [comment]
If song doesn't have lyrics, it will not have Adjustment button because it's to make lyrics more synced manually

**Comment by Humper04** [comment]
Ah oké, this explains more. Thank you.
