### ISSUE TITLE
TypeError: Cannot set properties of undefined (setting 'ReduxStore')

### ISSUE THREAD

**Issue by adriankarlen** [spicetify/spicetify-cli#2781]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 
Spotify for Windows (64 bit)
1.2.29.605.g66a43ceb
xpui_2024-01-15_1705312536455_66a43ce
cef_120.2.3+g7d89c0c+chromium-120.0.6099.199
Runtime: Alloy
- Spicetify version: 2.30.0
```

### 📝 Description

When trying to launch a spiced spotify the app does not load. When looking through the console log, the error message i the title appears.

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/113891532/91f9639c-ff91-4443-bd9c-610d49cc7cf8)
![image](https://github.com/spicetify/spicetify-cli/assets/113891532/cd4aef8c-71bc-45c2-9b56-2a3a094067b2)

**Comment by rxri** [comment]
What you need to do is: uninstall spotify, uninstall spicetify and install them again
