### ISSUE TITLE
Now Playing View not showing

### ISSUE THREAD

**Issue by Kirito-Emo** [spicetify/spicetify-cli#2783]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.26.1187.g36b715a1 (Flatpak version)
- Spicetify version: 2.30.0

- Spicetify theme: Dribbblish (Catppuccin-Mocha)
- Extensions: Beatiful Lyrics / Adblock / GoToSong / Full App Display Modified / Spotify Genres / Japanese Romaji Lyrics

- OS: Fedora Linux 39
- Kernel: 6.6.12-200
- Desktop Environment: GNOME 45.3
```

### 📝 Description

Hi everyone!
Firstly I want to thank you all for this project, it's marvelous and I love it.

I would just like to report a bug that I'm encountering recently (in the last weeks).
Specifically, the "Now Playing View" icon has disappeared from the playback bar.
Furthermore, the right sidebar behaves strangely, sometimes it is shown other times it disappears (like glitching) even though it should be shown.

I tried to run the `spicetify config extensions webnowplaying.js` command, obviously as a last resort, but without obtaining any changes (because my Spotify installation is the Flatpak one and not the Web-based one).

Do you know how I can solve this behavior? I really liked the Now Playing feature.
Thank you all in advance

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/76470231/a33f4bba-8957-4358-b65f-959600ca6a7a)

**Comment by rxri** [comment]
This is unfortunately, not related to cli itself. The glitching sidebar can be caused by theme you use and also try searching for NPV in experimental features, if it's not there - try reinstalling your spotify

**Comment by Kirito-Emo** [comment]
Hi, thanks for the quick answer.

I didn't find any NPV feature in experimental and I already tried to reinstall both spotify and spicetify (after the `spicetify restore` command).
I also tried with different themes and, sadly, the glitch is always there.

One thing I noticed is that, after uninstalling and reinstalling Spotify, the "Now Playing View" button is returned.
Furthermore, I tested the button with classic Spotify and it works perfectly ( as you can see in the following image), after applying the customization from Spicetify it doesn't anymore.

![Screenshot from 2024-01-25 15-53-01](https://github.com/spicetify/spicetify-cli/assets/76470231/536f0423-b1e5-4ae0-bc76-0319a20f9cb3)

I also enabled these experimental features (shown in following image) but the button continues to not work as it should do.

![Screenshot from 2024-01-25 16-18-50](https://github.com/spicetify/spicetify-cli/assets/76470231/eef9c938-539b-44e3-9693-c621c5203ba6)

**Comment by rxri** [comment]
We do not modify the components by default. So anything that is broken is on Spotify's fault (corrupted xpui etc etc). As I can see, you're on linux version that can be funky sometimes because it's not officially supported and rarely updated. There's nothing we can do about it. Am so sorry...
but yeah, that's not our fault that NPV is not working properly

**Comment by Kirito-Emo** [comment]
I understand... The strange thing is that with the original Spotify (without applying spicetify) the button works and the sidebar is correctely visualized. The problem arise only when applying the custom CSS and JS.
Do you think it can be related to something?

P.S. How can I search NPV? Because with only "NPV" it doesn't show anything, but maybe with some other words I can find the feature

@rxri

**Comment by rxri** [comment]
Well, from what I remember it's not a experimental feature anymore in 1.2.26 
![image](https://github.com/spicetify/spicetify-cli/assets/9348108/4a56b887-94db-4781-ad24-7eb5533753f5)
and you should be able to enable it from settings

**Comment by Kirito-Emo** [comment]
Yeah, I'd already enabled it in settings, I was hoping for some more hope.

Btw, I did these steps half an hour ago and obtained the hoped result:

```zsh
# restoring spotify
spicetify restore

# removing config files
rm -rf ~/.spicetify
rm -rf ~/.config/spicetify
```

> at this point Spotify was totally cleaned, but the button didn't go as expected, so...
>

```zsh
# uninstalling flatpak spotify
flatpak uninstall spotify
```

> logged out from session to apply all changes without incurring into annoyances
>

```zsh
# reinstalling flatpak spotify
flatpak install spotify

# reinstalling spicetify/marketplace
curl -fsSL https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.sh | sh
curl -fsSL https://raw.githubusercontent.com/spicetify/spicetify-marketplace/main/resources/install.sh | sh

# giving permissions
sudo chmod a+wr /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify
sudo chmod a+wr -R /var/lib/flatpak/app/com.spotify.Client/x86_64/stable/active/files/extra/share/spotify/Apps

# doing a backup and applying changes
spicetify backup apply
```

at this point all the previously installed extensions and themes were already installed and all worked fine.

![image](https://github.com/spicetify/spicetify-cli/assets/76470231/ce5cda45-2eaa-47e4-9df5-c979be1065b6)

Hoping these steps would help someone else who runs into this problem

You can mark this thread as resolved.
