### ISSUE TITLE
Spicetify apply doesn't work

### ISSUE THREAD

**Issue by haseebabid72** [spicetify/spicetify-cli#2784]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: latest flatpak (1.2.26.1187.g36b715a1)
- Spicetify version:2.30.0
```

### 📝 Description

I just installed spicetify using the [Instructions](https://spicetify.app/docs/advanced-usage/installation/) and at the end of the installation I got BOM: read /home/activator/.var/app/com.spotify.Client/config/spotify/: is a directory.
I get the same error when trying to install any other theme. and using spicetify apply command.

### 📸 Screenshots

![Screenshot_20240126_023815](https://github.com/spicetify/spicetify-cli/assets/149780265/715447d7-08a5-4b37-b30a-9b6ef24facc7)

**Comment by rxri** [comment]
You most likely have the `prefs_path` linked to the folder and not `prefs` file.
