### ISSUE TITLE
Spotify wrapped

### ISSUE THREAD

**Issue by hypesss** [spicetify/spicetify-cli#2790]
### 📝 Provide a description of the new feature

Not a feature request, sorry. I just needed one question to be answered and didn't know where to ask it. Does Spicetify track Spotify Wrapped or whatever they use to calculate those things? If I used it all year, would I get the Wrapped summary at the end of the year? Probably a dumb question or something, but I don't know.

### ➕ Additional Information

sorry again if im wasting peoples times just question i had love this app

**Comment by rxri** [comment]
Spicetify does not modify any code related to Wrappeds. Spotify tracks your usage with and on their servers and just shows you the data at the end of the year.

**Comment by hypesss** [comment]
> Spicetify does not modify any code related to Wrappeds. Spotify tracks your usage with and on their servers and just shows you the data at the end of the year.

thank for that fast reply :)
