### ISSUE TITLE
Search Bar for "Experimental Features" doesn't work

### ISSUE THREAD

**Issue by AngelLok1328** [spicetify/spicetify-cli#2793]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.29.605.g66a43ceb
- Spicetify version: 2.30.0
```

### 📝 Description

When I try to search for some Experimental features it doesn't sort them by word which I am looking for.

### 📸 Screenshots

[https://youtu.be/c4ErIZiHskM](url)

**Comment by rxri** [comment]
It has been fixed with https://github.com/spicetify/spicetify-cli/commit/e6a51face4b1cf112b99d3d57d6c8f07103b60c0 commit. Please wait for next spicetify release
