### ISSUE TITLE
search section

### ISSUE THREAD

**Issue by senolfndk** [spicetify/spicetify-cli#2795]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
-Spotify:1.2.30.1135.g02fef27a
-Spicetify:v2.30.0 (2023-01-11)
```

### 📝 Description

Marketplace does not appear in the new search section

### 📸 Screenshots

![Ekran görüntüsü 2024-02-01 175504](https://github.com/spicetify/spicetify-cli/assets/52818836/490aeea7-644c-41c4-a1b9-dad64328b9cc)

**Comment by rxri** [comment]
huh, section page you mean? You clearly enabled some experimental feature for searching so this page does not exist. Not a bug, not an issue

**Comment by senolfndk** [comment]
![Ekran görüntüsü 2024-02-01 180049](https://github.com/spicetify/spicetify-cli/assets/52818836/f9c20880-8701-4f22-bc05-9431ce41deeb)

**Comment by rxri** [comment]
Like I said, you enabled experimental feature that we nor marketplace supports. We do not support features that weren't enabled for everyone

**Comment by senolfndk** [comment]
hmm ok
