### ISSUE TITLE
UI proeblem. (Full screen toggle button)

### ISSUE THREAD

**Issue by Suyog-Rijal** [spicetify/spicetify-cli#2798]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bit) 1.2.29.605.g66a43ceb
- Spicetify version: v2.30.0
```

### 📝 Description

In the button the UI is not correctly displayed. The full screen toggle button is not appearing. Sometimes it randomly show but cannot click the button. It says buy premium.

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/115134619/033ee31b-c918-4788-9a93-a5a0f3304361)

**Comment by rxri** [comment]
Spicetify doesn’t modify UI elements nor interact with premium features by default. You’re most likely using an extension causing this problem
