### ISSUE TITLE
problem in installing spicetify

### ISSUE THREAD

**Issue by phucleeuwu** [spicetify/spicetify-cli#2799]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.30.1135.g02fef27a
- Spicetify version: 2.30.0
```

### 📝 Description

I just delete, reinstall spotify (not spicetify) and install spicetify this happen  

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/125681538/646350dc-bf03-4a1c-8ff6-d9eb0efbcacf)

**Comment by rxri** [comment]
Ignore it.

**Comment by phucleeuwu** [comment]
@rxri how?

**Comment by rxri** [comment]
Like I said, ignore it. Spicetify is already installed and you got this error in cleanup process. That's it

**Comment by phucleeuwu** [comment]
@rxri this is my spotify, no marketplace
![image](https://github.com/spicetify/spicetify-cli/assets/125681538/1091f2c1-a5f8-472c-b4dc-9041296f6ae8)

**Comment by rxri** [comment]
Install marketplace with the second script listed on our docs
