### ISSUE TITLE
Every TopBar Button from Extensions disappear after opening native lyrics page

### ISSUE THREAD

**Issue by lplawlor** [spicetify/spicetify-cli#2800]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bit) 1.2.30.1135.g02fef27a
- Spicetify version: 2.30.0
```

### 📝 Description

With the [Full App Display](https://spicetify.app/docs/advanced-usage/extensions#full-app-display) extension enabled, opening the Lyrics (from the vanilla microphone button in the bottom right) and closing it makes the Full App Display button (top left) disappear.

Its worth noting that I have the custom [Lyrics Plus](https://spicetify.app/docs/advanced-usage/custom-apps#lyrics-plus) app installed to fix this, but the issue was occurring before it was installed.

### 📸 Screenshots

Before opening Lyrics, the Full App Display button is visible next to the Back/Forward buttons:
![button_showing](https://github.com/spicetify/spicetify-cli/assets/60618151/59e44cb8-0da6-4696-8ffc-8cce5ddbde12)

After opening then closing the vanilla Lyrics page:
![button_gone](https://github.com/spicetify/spicetify-cli/assets/60618151/ee921fb3-7120-4eaf-bd1b-8573f3e56437)

**Comment by lplawlor** [comment]
@rxri Thanks! I have updated Spicetify to v2.31.0, but the issue persists for me. I've disabled all other themes and apps, but the button disappears after opening the native lyrics page even with just the Full App Display extension enabled.

Is this something on my end only? Or is this issue persistent on your installation as well?

**Comment by rxri** [comment]
`spicetify restore backup apply`

**Comment by lplawlor** [comment]
Yep, I've already run that. I just ran it again to double check, and the issue persists. Are you not experiencing the issue anymore?

**Comment by rxri** [comment]
I was testing it few times while creating the pull request and I couldn't reproduce the issue anymore

**Comment by lplawlor** [comment]
Hmm. I'll give it a go on another system later, and if it works over there I'll just have to reinstall Spotify and Spicetify altogether on my main system.

**Comment by rxri** [comment]
I'm testing it right now as well with the fix applied and yeah, I cannot reproduce it. The icons are just there

**Comment by lplawlor** [comment]
So I've completely uninstalled then reinstalled Spotify and Spicetify twice now, and the behaviour is strange. The bug is gone at first, but reappears later. Here's the commands I ran in order:

_Install (selecting default Y to install Marketplace):_
`iwr -useb https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.ps1 | iex`

_Install and apply the fullAppDisplay extension:_
```
spicetify extensions fullAppDisplay.js
spicetify restore backup apply
```

At this point, the bug is gone. Opening the native lyrics page and closing it does not remove the Full App Display button. It's worth noting that Spotify is not automatically restarting since reinstalling Spicetify, but that may just be the default behaviour I can't recall.

_Install and apply the Lyrics Plus custom app:_
```
spicetify config custom_apps lyrics-plus
spicetify restore backup apply
```

It's at this point that the bug reappears. The button disappears when the native lyrics page is opened and closed.

_Uninstall the Lyrics Plus app:_
```
spicetify config custom_apps lyrics-plus-
spicetify restore backup apply
```

What I find really bizarre is that the bug still persists now, even though the Lyrics Plus app is gone and we're back to just the Marketplace and Full App Display installed.

**Comment by rxri** [comment]
I cannot reproduce this issue and I tested it with Lyrics Plus a lot of times because I had to fix observer loop when going to different page from Lyrics Plus specifically. It would be cool if you would join our discord server (link in readme) so we can troubleshoot it further together
