### ISSUE TITLE
Spicetify.Topbar.Button broken in new update

### ISSUE THREAD

**Issue by ohitstom** [spicetify/spicetify-cli#2802]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.30
- Spicetify version: 2.31.0
```

### 📝 Description

unmapped class, and structure change

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/22730962/f9ee73f6-c779-4b31-a4e6-68c787d3db06)

**Comment by rxri** [comment]
Works just fine. Only css must be mapped and class be changed to have the spotify style
![image](https://github.com/spicetify/spicetify-cli/assets/9348108/67ced306-1815-4672-8e33-461c079a6acf)

**Comment by ohitstom** [comment]
> Works just fine. Only css must be mapped ![image](https://private-user-images.githubusercontent.com/9348108/301981900-67ced306-1815-4672-8e33-461c079a6acf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5MTIzMDcsIm5iZiI6MTcwNjkxMjAwNywicGF0aCI6Ii85MzQ4MTA4LzMwMTk4MTkwMC02N2NlZDMwNi0xODE1LTQ2NzItOGUzMy00NjFjMDc5YTZhY2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDJUMjIxMzI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWE0MTFlZjJlMDkzNjhkYTk2MjJhY2Q1OWJjNjE0OTg2OTlhMzIyMzJmMzY2NTBkZTUxNTkwYThiYWU2NTUwMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.oOjh0QWELaWHbpqvBUaGqjaOZHTLItn-A8OOQas8Jw0)

why close it if it still breaks functionality, might as well keep it open so it can be tracked with a css map pr?
![image](https://github.com/spicetify/spicetify-cli/assets/22730962/02d61672-8ecb-486f-81ae-62c8818f709e)
