### ISSUE TITLE
Error in the Tracks to edges extension

### ISSUE THREAD

**Issue by kaub01** [spicetify/spicetify-cli#2811]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.30.1135.g02fef27a
- Spicetify version: v2.31.1
```

### 📝 Description

When I tried to move some tracks to the top of the playlist using the tracks to edges extension, I got an error saying "Failed to move tracks".

### 📸 Screenshots

![Screenshot 2024-02-09 201057](https://github.com/spicetify/spicetify-cli/assets/133030841/6e686777-8fc5-4f83-ac77-5696775bb5d7)

**Comment by rxri** [comment]
since you use external extension and it's not made by us, you need to contact developer of it. not a cli bug or issue
