### ISSUE TITLE
Lyrics Plus X Beautiful Lyrics

### ISSUE THREAD

**Issue by GODDASUR** [spicetify/spicetify-cli#2813]
### 📝 Provide a description of the new feature

You guys can make it even better if you guys collab with each other.

**Comment by rxri** [comment]
No lol. Spotify to this day doesn't have rasterization enabled for GPUs so animations would take high cpu usage, beautiful lyrics gets its lyrics from Apple Music (private backend basically) - lyrics-plus do not. Won't happen really
