### ISSUE TITLE
PlaybarClock isn’t working…

### ISSUE THREAD

**Issue by ashton-jiffy** [spicetify/spicetify-cli#2814]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.30
- Spicetify version: v.2.31.1
```

### 📝 Description

The playbarclock snippet isn’t showing up on my player, i even reinstalled it and it still isn’t showing.

i even checked the command line but it says that it’s not found.

### 📸 Screenshots

https://media.discordapp.net/attachments/842819014941212682/1205801739140341860/image.png?ex=65d9b161&is=65c73c61&hm=5eeb0ab96929099168dd4084524eeca2e0685df82210eeb10ac45e1f081461ae&

https://media.discordapp.net/attachments/842819014941212682/1205181820136857610/image.png?ex=65d77009&is=65c4fb09&hm=d70a1a8997762c09800f0171bf471fb2a16e1d2f80021826c3289f7199871ce6&

**Comment by rxri** [comment]
This is not official extension. Not a cli bug or issue. Closing

**Comment by ashton-jiffy** [comment]
It was working days back
