### ISSUE TITLE
cant see lyrics-plus configurator in top right menu under profile icon

### ISSUE THREAD

**Issue by N0tBLUE** [spicetify/spicetify-cli#2815]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (32 bit) - 1.2.30.1135.g02fef27a
Spicetify -  v2.31.1
```

### 📝 Description

after recent update i cannot see lyrics-plus config 
before i could see it 
but now i cannot

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/74755694/5049512a-380e-46b4-bd2d-6bb3ac7da70a)
![image](https://github.com/spicetify/spicetify-cli/assets/74755694/2bf0ace5-b637-4608-a03a-d64ee3f4fc56)

**Comment by rxri** [comment]
Reinstall spotify and reinstall spicetify (ofc cleanup any left over files before installing these again)

**Comment by N0tBLUE** [comment]
how do i fresh install spotify and spicetify
