### ISSUE TITLE
new release broke contextMenu

### ISSUE THREAD

**Issue by ohitstom** [spicetify/spicetify-cli#2816]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (64 bit)
1.2.30.1135.g02fef27a
Spicetify v2.31.2
xpui_2024-01-29_1706560054673_02fef27
cef_120.2.3+g7d89c0c+chromium-120.0.6099.199
Runtime: Alloy
```

### 📝 Description

i havent changed anything in my extension:
https://github.com/ohitstom/spicetify-extensions/tree/main/playbarClock

yet im getting the errors described in the screenshots below, this doesnt seem to be an issue with my code but something thats changed in the wrapper?

IMPORTANT:
if i rerun the code AFTER right clicking on any context menu then the code works fine, im guessing you guys are using webpack definitions now and the function needs some sort of prop that isn't accessible until triggered in-app before hand

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/22730962/1211ab6d-1465-47dc-8223-1b2a82923cc4)
![image](https://github.com/spicetify/spicetify-cli/assets/22730962/6cf6d3f2-8154-4686-b5a9-d7a41fd37ebb)

**Comment by rxri** [comment]
Okay so it's not really a bug. Since context is created when Context Menu is opened so you need to manually assign context before to make it work without opening Context Menu first:
```javascript
if (!Spicetify.ContextMenuV2._context) Spicetify.ContextMenuV2._context = Spicetify.React.createContext({});
```
This has to be done outside `React.memo` of course...

**Comment by ohitstom** [comment]
> Okay so it's not really a bug. Since context is created when Context Menu is opened so you need to manually assign context before to make it work without opening Context Menu first:
> 
> ```js
> if (!Spicetify.ContextMenuV2._context) Spicetify.ContextMenuV2._context = Spicetify.React.createContext({});
> ```
> 
> This has to be done outside `React.memo` of course... If you wouldn't use ReactDOM.render, this wouldn't be necessary basically

im confused i thought this new system was to keep compatibility with old codebases yet this is an example of it not and you are expecting me to change my code? can this not be changed in the wrapper itself instead of expecting devs to use that line because its not very explicit

**Comment by rxri** [comment]
You're the only one developer that I know, that use some hacky ways avoiding proper way to render elements and you are surprised that something breaks and from what I have seen since the release with ContextMenuV2, only your extension(s) broke. We cannot set it because react is exposed later on, but we will discuss if we will set it later in code perhaps, but at this moment, it's on you

**Comment by ohitstom** [comment]
> You're the only one developer that I know, that use some hacky ways avoiding proper way to render elements and you are surprised that something breaks and from what I have seen since the release with ContextMenuV2, only your extension(s) broke. We cannot set it because react is exposed later on, but we will discuss if we will set it later in code perhaps, but at this moment, it's on you

how is this hacky? contextmenu is a react component so im going to use react.render...
