### ISSUE TITLE
Empty prop obj when using ContextMenuV2 Item on Spicetify.ReactComponent.Menu instance

### ISSUE THREAD

**Issue by harbassan** [spicetify/spicetify-cli#2819]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.30.1135.g02fef27a
- Spicetify version: v2.31.2
```

### 📝 Description

This occurs on all of the custom Menu components, and I would expect it to return the uris as normal when using ArtistMenu etc. If there is a simple fix I can do to make this work then let me know, but because its related to the context im assuming there isn't.

**Comment by rxri** [comment]
Use `Spicetify.ContextMenuV2._context` to get the props you want
