### ISSUE TITLE
Live Reload Problems

### ISSUE THREAD

**Issue by Teenarp2003** [spicetify/spicetify-cli#2821]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.26.1187-1
- Spicetify version:2.31.2
```

### 📝 Description

`spicetify watch -s ` used to work fine until spotify update. 
Since the recent update it does not restart the client anymore. I tried with multiple variants of the client to no avail.  
its keeps getting stuck on this screen. Never restarting. 

`spicetify restart` is the only command now capable of restarting the client. 

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/93932501/e390963b-86a7-4f4a-9423-4c983e188c5f)

**Comment by rxri** [comment]
This is not related to cli though. We did not change anything in last releases in debugger and restart behavior, so that's most likely not working on your end which we can't really fix... sorry

**Comment by Teenarp2003** [comment]
okay i ll try reinstalling my whole setup sometime. Thanks for your time.

**Comment by Teenarp2003** [comment]
Update: Yes the problem was on my end. I installed spicetify multiple times through different methods. Reinstalling fixed the problem

**Comment by rxri** [comment]
> Update: Yes the problem was on my end. I installed spicetify multiple times through different methods. Reinstalling fixed the problem

@Teenarp2003, with issue on your end I meant that this issue is random and there is nothing you can do to fix it, it's just that spicetify cannot connect to spotify's devtools websocket or the websocket doesn't react on sent commands

**Comment by Teenarp2003** [comment]
Yes, of course. I understand
