### ISSUE TITLE
evrytime i hover some buttons spotify just crash 

### ISSUE THREAD

**Issue by sinadz** [spicetify/spicetify-cli#2824]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 
- Spicetify version:
Spotify for Windows (64 bit)
1.2.30.1135.g02fef27a
Spicetify v2.31.2
Theme: Hazy / Base
Extensions: adblock.js, beautiful-lyrics.js, theme.js
Custom apps: marketplace
```

### 📝 Description

evrytime i hover search , marketplace , home , musics in playlist , this happens

![Screenshot 2024-02-13 145924](https://github.com/spicetify/spicetify-cli/assets/107113434/fd123047-6684-4186-8be7-5c5b2a3173be)

these are the buttons i cant hover

### 📸 Screenshots

![Screenshot 2024-02-13 144333](https://github.com/spicetify/spicetify-cli/assets/107113434/0cdd92fa-07fe-4f17-98bd-35024c4bd14d)

**Comment by rxri** [comment]
Has been already fixed. Reinstall Spotify (with cleaning any leftovers) and to make sure, uninstall and install spicetify too
