### ISSUE TITLE
pop up lyrics freezes upon minmize spotify

### ISSUE THREAD

**Issue by mazenR** [spicetify/spicetify-cli#2827]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: latest
- Spicetify version:latest
```

### 📝 Description

pop up lyrics freezes upon minmize spotify 

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/115876717/17b55de1-3f13-4b23-a333-01c370104ed0)

**Comment by rxri** [comment]
There’s not something like latest. This has been already fixed. Reinstall spicetify if you are on 2.31.2

**Comment by Steinadler177** [comment]
I'm facing a simliar problem. The pop up lyrics freezes when minimize spotify main window. It keeps frezze even if I reopen mainwindow (not restart the whole app). Then close pop up and re-open it can make it work again.

Spotify Windows（64 bit） version
1.2.33.1042.g26c92729
Spicetify v2.36.0
Theme: BurntSienna / Base
Extensions: adblock.js, songstats.js, bookmark.js, oneko.js, CoverAmbience.js, playing-source.js, popupLyrics.js
Custom apps: marketplace

**Comment by JasonLovesDoggo** [comment]
I face the same issue. As soon as I Alt+Tab it freezes. 

Spotify for Windows (64 bit)
1.2.33.1042.g26c92729
Spicetify v2.36.2
Theme: Bloom / comfy
Extensions: volumePercentageWrapper.js, playlistIntersection.js, power-bar.js, QueueTime.js, section-marker.js, phraseToPlaylist.js, spotifyGenres.js, made-for-you-shortcut.js, popupLyrics.js, theme.js
Custom apps: marketplace

**Comment by rxri** [comment]
https://github.com/spicetify/spicetify-cli/issues/2749#issuecomment-2028110120
Please read the information from this link, unless this issue is non-existent

**Comment by Steinadler177** [comment]
[Trace-20240402T141536.zip](https://github.com/spicetify/spicetify-cli/files/14836514/Trace-20240402T141536.zip)


> [#2749 (comment)](https://github.com/spicetify/spicetify-cli/issues/2749#issuecomment-2028110120) Please read the information from this link, otherwise I cannot acknowledge this issue since I cannot reproduce it.

Please find the performance report here. I checked it, it was a little messed up by cat(oneko)... Tell me if you need a cleaner one.

What I did with the performance report:
I start with song playing and lyrics tab closed. Then I open the tab, it works correctly. I switch my focus to dev window(so spotify main window still showing), the tab is still working fine. Then I minimized the main window, lyrics tab freezed. I open the main window back, but the tab is still freezing. I closed the tab and reopen it, it works. Minimized the main window, it freezes again.

**Comment by rxri** [comment]
Add popupLyrics to the config and do not install it via marketplace.
`spicetify config extensions popupLyrics.js`, remove it from marketplace and `spicetify apply`. Then do this report again

**Comment by Steinadler177** [comment]
> Most likely, yes. I think it's a default browser behavior... and if it's from local file it won't put massive restrictions...? I don't know and I don't wanna dig into this more xd

I agree. But I also suggest to add this in readme file / somewhere so people know how to install it correctly

**Comment by zubairmh** [comment]
> Add popupLyrics to the config and do not install it via marketplace. `spicetify config extensions popupLyrics.js`, remove it from marketplace and run `spicetify apply`, then do this report again if it still happens

can confirm this fixes the issue, unsure why marketplace variant wouldn't work
