### ISSUE TITLE
Error while installing spicetify marketplace

### ISSUE THREAD

**Issue by TheDarkKnight69** [spicetify/spicetify-cli#2828]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows 1.2.5.1006.g22820f93
- Spicetify version: 2.31.2
```

### 📝 Description

I try to install spicetify using the guide provided. It says installation sucessful. I try to install spicetify-marketplace but it fails(?). From that point on I am hit with errors and exceptions.

I use Windows 7, but I have used spicetify with Spotify for over a year now. 

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/91176991/cbab1205-4606-4130-a91b-0c5f50439626)

**Comment by rxri** [comment]
Looks like windows 7. Golang since some version I think either dropped win7 support or they broke something on this version of windows so it’s out of our hands

**Comment by TheDarkKnight69** [comment]
is there any version i can revert back to where this is not a problem?

**Comment by rxri** [comment]
That I can't tell you because I don't know
