### ISSUE TITLE
Lyrics Plus no funciona 

### ISSUE THREAD

**Issue by JxseDelRey** [spicetify/spicetify-cli#2830]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.31.1205.g4d59ad7c
- Spicetify version: Spicetify v2.31.2
```

### 📝 Description

No aparecen las letras de Genius, Karaoke, Synced

### 📸 Screenshots

![Captura de pantalla 2024-02-14 161034](https://github.com/spicetify/spicetify-cli/assets/153209219/9d70b8dc-8d11-4881-b98e-e2aed1e5a5fd)

**Comment by rxri** [comment]
Downgrade spotify to at least `1.2.30`.
