### ISSUE TITLE
I'm having two fullscreen buttons and i already installed one

### ISSUE THREAD

**Issue by ashton-jiffy** [spicetify/spicetify-cli#2831]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.31.1205.g4d59ad7c
- Spicetify version: v2.31.2
```

### 📝 Description

Left (Normal Fullscreen) and Right (daksh2k's fullscreen extension)

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/67291514/52521ee3-adfc-4c45-a7b1-c3f2b4471518)

![image_2024-02-14_220808233](https://github.com/spicetify/spicetify-cli/assets/67291514/767889d7-6e05-45e5-a7e6-1bf864905b0a)

**Comment by rxri** [comment]
One is from premium (adblock spoofs your user as premium), and other from dasksh2k. The custom full screen extension probably has an option to replace it or there is a snippet to remove the normal button. Not a bug, not an issue in cli
