### ISSUE TITLE
Tippy does not follow spotify theming

### ISSUE THREAD

**Issue by ohitstom** [spicetify/spicetify-cli#2832]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (64 bit)
1.2.31.1205.g4d59ad7c
Spicetify v2.31.2
xpui_2024-02-09_1707492707686_4d59ad7
cef_121.3.6+gbbcaed4+chromium-121.0.6167.139
Runtime: Alloy
```

### 📝 Description

new update broke this

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/22730962/b12c24b2-24af-48e9-9241-fcd1ba3945dc)

**Comment by rxri** [comment]
use `TooltipWrapper` (react component btw) and this won't happen again

**Comment by rxri** [comment]
css should be fixed by https://github.com/spicetify/spicetify-cli/commit/53b1ff08f268c86cef834fda230c7b867f251414

**Comment by rxri** [comment]
bruh i can't click right button

**Comment by ohitstom** [comment]
bruh what??? this is the default tippy thing assigned to playbar buttons??
