### ISSUE TITLE
topbar right not being appended

### ISSUE THREAD

**Issue by ohitstom** [spicetify/spicetify-cli#2833]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (64 bit)
1.2.31.1205.g4d59ad7c
Spicetify v2.31.2
xpui_2024-02-09_1707492707686_4d59ad7
cef_121.3.6+gbbcaed4+chromium-121.0.6167.139
Runtime: Alloy
```

### 📝 Description

new update broke topbar rightside buttons main-noConnection-button doesnt exist anymore

**Comment by rxri** [comment]
https://github.com/spicetify/spicetify-cli/pull/2826 already fixes it...

**Comment by ohitstom** [comment]
> #2826 already fixes it...

ah i see that wasnt really mentioned in its description i assumed that fixes the other issue feel free to close this
