### ISSUE TITLE
client crashing on loadup

### ISSUE THREAD

**Issue by ohitstom** [spicetify/spicetify-cli#2834]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (64 bit)
1.2.31.1205.g4d59ad7c
Spicetify v2.31.2
xpui_2024-02-09_1707492707686_4d59ad7
cef_121.3.6+gbbcaed4+chromium-121.0.6167.139
Runtime: Alloy
```

### 📝 Description

doesnt happen every boot

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/22730962/c00cf775-16e4-4173-bd69-7130104a36d0)

**Comment by rxri** [comment]
With .2 can’t reproduce

**Comment by ohitstom** [comment]
> With .2 can’t reproduce 

can't reproducing doesn't mean you should close the issue? like I said it's not a consistent thing and it's clearly a wrapper problem outside of my own control whilst I'm on the latest versions...

**Comment by rxri** [comment]
I reload Spotify a lot of times right now and not a single time I encountered this issue. I will look into it again and try to implement failsafe but still
