### ISSUE TITLE
Marketplace Devtools Error.

### ISSUE THREAD

**Issue by TheDarkKnight69** [spicetify/spicetify-cli#2835]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows 1.2.5.1006.g22820f93
- Spicetify version: 2.14.2
```

### 📝 Description

I installed the newest version of marketplace as well as 0.9.0. But it gives me the error "Unexpected error occured please try again".
On opening the console log, I see this

![image](https://github.com/spicetify/spicetify-cli/assets/91176991/d7dec812-1592-42a8-bd7a-03564f3b48c2)

**Comment by rxri** [comment]
We don’t provide support for older cli versions
