### ISSUE TITLE
Lyrics dont show up on Lyric-Plus

### ISSUE THREAD

**Issue by BlackChadhar** [spicetify/spicetify-cli#2837]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.31.1205.g4d59ad7c
- Spicetify version: v2.31.3
```

### 📝 Description

Lyric-Plus is just not working after updating both Spotify and Spicetify to the latest verion. Tried reinstalling as well. Also quick question: Do I need to install the folder in the custom apps directory of Spicetify or just enabling it from the console will work as it was working fine till a couple hours ago and I just checked that I never downloaded anything online but simple enabled it using the spicetify command and it was working great

### 📸 Screenshots

![Screenshot 2024-02-15 154308](https://github.com/spicetify/spicetify-cli/assets/118986712/5f97922d-a7c2-4c65-931a-7b232800d0b7)

**Comment by TecEash1** [comment]
Downgrade to v2.30 for now for the fix:
https://upgrade.scdn.co/upgrade/client/win32-x86_64/spotify_installer-1.2.30.1135.g02fef27a-399.exe

**Comment by BlackChadhar** [comment]
> Downgrade to v2.30 for now for the fix: https://upgrade.scdn.co/upgrade/client/win32-x86_64/spotify_installer-1.2.30.1135.g02fef27a-399.exe

Wont it auto update back up though ?

**Comment by TecEash1** [comment]
It shouldn't. If you have the version installed from the Microsoft store then maybe, that might cause issues. Otherwise normally there's a button to update after.

**Comment by BlackChadhar** [comment]
> It shouldn't. If you have the version installed from the Microsoft store then maybe, that might cause issues. Otherwise normally there's a button to update after.

I see. Will try and update. Thanks <3

**Comment by ohitstom** [comment]
why was this issue closed its still an issue? @rxri

**Comment by ohitstom** [comment]
![image](https://github.com/spicetify/spicetify-cli/assets/22730962/37bef9a5-1aec-41cb-acda-c981e4229833)

**Comment by rxri** [comment]
Because the warning for this is in the release notes. I don’t want this repo spammed with the same issue which we are aware of

**Comment by BlackChadhar** [comment]
> Downgrade to v2.30 for now for the fix: https://upgrade.scdn.co/upgrade/client/win32-x86_64/spotify_installer-1.2.30.1135.g02fef27a-399.exe

Just auto updating and messing up again so ig will just wait

**Comment by mccalltristan** [comment]
Yea downgrading works but it auto updates after a while.

**Comment by Leo-Smith666** [comment]
Same issue bro

**Comment by Leo-Smith666** [comment]
Spotify always updates automatically (cannot be cancelled), and after each update, it needs to be reinstalled. Recently, after installing Lyrics Plus, the lyrics cannot be displayed
