### ISSUE TITLE
spicetify not connecting to spotify after fresh install

### ISSUE THREAD

**Issue by Gaga021217** [spicetify/spicetify-cli#2845]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.31.1205.g4d59ad7c
- Spicetify version: v2.31.3
```

### 📝 Description

I've been using spicetify for years now. I reinstall my windows (and with it, spicetify) about every six months, and had no issue with it before.

Although the spotify version is above what's supported, it worked until right before I reinstalled windows, so I wouldn't think thats the problem.

I installed spicetify, and tried `spicetify restart` to see if it works properly. In PS, it looks like it completed successfully, but the app didn't actually restart. It does focus spotify though, as it would after it restarted. Applying themes also doesn't work. It's as if it's not connected to spotify (and yet it is, because it knows which app to focus). 

I installed spotify from the downloaded exe, not from the microsoft store. I tried to reinstall both Spotify and Spicetify, but it didn't fix anything. Everything is installed in the default location.

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/73666503/56ee7c83-cea5-4fde-874d-5a282d2eab8a)

**Comment by rxri** [comment]
Not a bug not an issue in cli. Looks like maybe your spotify path is wrong or you didn’t apply. Please check out our discord server (link in readme) and ask for help there since it’s a user error 😊
