### ISSUE TITLE
Lyrics plus problem

### ISSUE THREAD

**Issue by kacperro721** [spicetify/spicetify-cli#2848]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.31.1205.g4d59ad7c
- Spicetify version: 2.31.3
```

### 📝 Description

Lyrics plus is not working for me, does anyone have the same problem as me?

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/160322360/78ff9933-26e4-426c-84fd-d011a3c00019)

**Comment by rxri** [comment]
Duplicate of https://github.com/spicetify/spicetify-cli/issues/2844
