### ISSUE TITLE
spicetify wont load the lyrics

### ISSUE THREAD

**Issue by BLKMRGE** [spicetify/spicetify-cli#2850]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.31.1205
- Spicetify version: v2.31.3
```

### 📝 Description

i tried changing the musixmatch token but still wont work, pls help

### 📸 Screenshots

![Screenshot (1)](https://github.com/spicetify/spicetify-cli/assets/133867175/2da15b51-a634-47cf-9a3f-0b6606d01297)

**Comment by rxri** [comment]
Duplicate of https://github.com/spicetify/spicetify-cli/issues/2844
