### ISSUE TITLE
Windows Defender reports Spicetify as malicious 

### ISSUE THREAD

**Issue by Tayzar02** [spicetify/spicetify-cli#2851]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bit) 1.2.31.1205.g4d59ad7c

- Spicetify version: v2.31.3
```

### 📝 Description

Received a report from Windows Defender this morning flagging Spicetify as malicious. Defender report is attached.

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/74204456/89115665-310b-4391-8b8e-a2880d75e566)

**Comment by rxri** [comment]
False positive. We cannot do anything about it unless someone buys us signing certificate 🤷‍♀️
