### ISSUE TITLE
Is there any way to update Spicetify without having it re-apply?  

### ISSUE THREAD

**Issue by stevehoek** [spicetify/spicetify-cli#2852]
### 📝 In-app way to update Spicetify without applying config to Spotify

It seems like spicetify update/upgrade command now restores spotify to default, clears backup, then re-applies.
I recall that had to be a separate intentional command in the past.
How can I update Spicetify without having it re-apply?

**Comment by rxri** [comment]
No, it's not possible. This decision has been made for convenience for our users
