### ISSUE TITLE
lyrics plus not working

### ISSUE THREAD

**Issue by NeuralNetDev** [spicetify/spicetify-cli#2856]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.31.1205.g4d59ad7c
- Spicetify version: 2.32.1
```

### 📝 Description

I understand that the issue referenced [here](https://github.com/spicetify/spicetify-cli/issues/2844) was fixed a couple days ago and it did work for me about 15 hours ago but when I tried to use lyrics plus again today, I get a loading animation and then the cute face telling me it couldn't find anything. I don't know if anyone else is getting this but I thought I'd mention it in case it isn't just me.
I have tried updating spicetify and restarting spotify and even re-applying the backup but it refuses to work.

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/78045343/c54e1f7b-09dc-4fc8-924e-a0cffe091939)

**Comment by rxri** [comment]
Refresh token.
