### ISSUE TITLE
Lyrics Plus not working

### ISSUE THREAD

**Issue by gqrge** [spicetify/spicetify-cli#2858]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (64 bit)
1.2.31.1205.g4d59ad7c
Spicetify v2.32.1
```

### 📝 Description

Lyrics Plus randomly stopped working so I reinstalled and this is what happens.

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/95545409/eb8dd66e-93df-4e71-8f2c-96d20749a5a7)
![image](https://github.com/spicetify/spicetify-cli/assets/95545409/bc93a2fe-f019-4d8f-8fc0-d16d07691207)
![image](https://github.com/spicetify/spicetify-cli/assets/95545409/3e915b75-5871-40da-9f0c-0b1e5c6af524)

**Comment by rxri** [comment]
Cannot reproduce. Everything works fine. Make sure `cors-proxy.spicetify.app` is not blocked

**Comment by gqrge** [comment]
> Cannot reproduce. Everything works fine. Make sure `cors-proxy.spicetify.app` is not blocked

how do i do that

**Comment by matthewyuc** [comment]
its not working for me too how do i makethat unblocked 😭
