### ISSUE TITLE
Spotify v1.2.32 blanks on startup if custom apps used

### ISSUE THREAD

**Issue by RWCoding58** [spicetify/spicetify-cli#2861]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.32.985.g3be2709c
- Spicetify version: 2.32.1
```

### 📝 Description

1. Enable any custom apps (lyrics-plus, marketplace, stats etc)
2. Apply patches to Spotify
3. Spotify gets stuck on a blank screen when launched

I have tested various combinations for the config:
- marketplace and lyrics-plus (broken)
- only marketplace (broken)
- only lyrics-plus (broken)
- no custom apps (works)

and can confirm that it is not a specific custom app causing the issue, but rather the existence of any of them.

### 📸 Screenshots

![Screenshot 2024-02-26 at 16 46 47@2x](https://github.com/spicetify/spicetify-cli/assets/87898490/b2ee617e-bb69-4b9b-8ec8-a3ededd873af)
Spotify when launched (it's blue because of the theme I'm using)

**Comment by ohitstom** [comment]
Sounds like your backup data corrupted at some point (you have an old version of Spotifys xpui on the new version of Spotify)

try a fresh install of Spotify and run `spicetify backup apply` and get back to us

**Comment by RWCoding58** [comment]
Nope, still broken

It's probably worth mentioning that I'm using SpotX-Bash, although I have tested that it works before applying Spicetify

**Comment by ohitstom** [comment]
> Nope, still broken
> 
> It's probably worth mentioning that I'm using SpotX-Bash, although I have tested that it works before applying Spicetify

we do not support or encourage using spotX with spicetify as they modify xpui in a contradictory manor.

use one or the other and keep in mind spicetify is capable of everything spotX is, you do not need both.

**Comment by RWCoding58** [comment]
I mean, Spotify does still work with both Spicetify and Spot-X, even 1.2.32 works as long as there are no custom apps enabled (extensions, themes etc work fine)

**Comment by ohitstom** [comment]
> I mean, Spotify does still work with both Spicetify and Spot-X, even 1.2.32 works as long as there are no custom apps enabled (extensions, themes etc work fine)

refer to my previous comment

**Comment by Salman7236** [comment]
> Nope, still broken
> 
> It's probably worth mentioning that I'm using SpotX-Bash, although I have tested that it works before applying Spicetify

Facing the same issue on 1.2.32. And I don't have spotx, only spicetify.

**Comment by RWCoding58** [comment]
Here's the screenshot of the console (with marketplace and lyrics-plus enabled):
![Screenshot 2024-02-26 at 21 17 37@2x](https://github.com/spicetify/spicetify-cli/assets/87898490/ed50f5bd-5139-40b8-bd20-81d9992c2f8c)

Unfortunately, GitHub doesn't seem to allow attaching JavaScript files, so I can't attatch the two xpui files
