### ISSUE TITLE
Marketplace 'No page was found'

### ISSUE THREAD

**Issue by mikobeng** [spicetify/spicetify-cli#2865]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (64 bit)
1.2.31.1205.g4d59ad7c
Spicetify v2.32.1
Theme: Bloom / darkmono
Extensions: group-session.js, CoverAmbience.js, imaged-folders.js, fullAppDisplay.js, beautiful-lyrics.js, playNextWrapper.js, QueueTime.js
Custom apps: marketplace, lyrics-plus, ncs-visualizer
```

### 📝 Description

For extensions that were made by spicetify in the marketplace, when clicking on them to find more details, it returns 'No page was found'.

This can be quite problematic when the description gets cut off.

Perhaps set the link to the extensions listed here: https://spicetify.app/docs/advanced-usage/extensions/

**Comment by rxri** [comment]
Then you have incorrectly set the config. Not an issue, not a bug. Please visit our discord server for general help
