### ISSUE TITLE
most of the song lyrics not working

### ISSUE THREAD

**Issue by Y2KL** [spicetify/spicetify-cli#2868]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: last
- Spicetify version: last
```

### 📝 Description

it works for some song and some not and like when it works for one and i try to make it again and then the lyrics disappear

**Comment by rxri** [comment]
Last and last is not a valid option. With this issue, go to our discord server because this has been fixed in latest spicetify
