### ISSUE TITLE
[core] can't switch devices or logout

### ISSUE THREAD

**Issue by iPixelGalaxy** [spicetify/spicetify-cli#2869]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [x] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.32.997.g4c6498b6
- Spicetify version: v2.33.0
```

### 📝 Description

Try to switch devices. Video of the issue: https://ipixelgalaxy.com/TempFiles/Spicetify%20Device%20Issue.mp4

**Comment by rxri** [comment]
Not related to spicetify. Reinstall Spotify

**Comment by ohitstom** [comment]
> Reinstalled Spotify and all spicetify files in local appdata and roaming, no extensions running spotify clean install installed spotify 1.2.31 and issue is still present with latest spicetify, any logs I can provide?

I did notice spicetify was preventing me from logging out, is this the same for you?

**Comment by iPixelGalaxy** [comment]
> > Reinstalled Spotify and all spicetify files in local appdata and roaming, no extensions running spotify clean install installed spotify 1.2.31 and issue is still present with latest spicetify, any logs I can provide?
> 
> I did notice spicetify was preventing me from logging out, is this the same for you?
> 
> as for logs if you run spicetify enable-devtools from console you can inspect element for errors

actually yea logging out is broken for me as well

**Comment by ohitstom** [comment]
> actually yea logging out is broken for me as well

@rxri I don't think this issue should have been closed he showed proof of unaltered Spotify not having this issue, and the logging out sounds like a similar issue

**Comment by Arimodu** [comment]
Hello, same issue here after updating from 2.32.1 to 2.33.0, logging out is also broken as well after spicetify update, as a sidenote can I downgrade or am I just stuck on this version now?

**Comment by ohitstom** [comment]
> Hello, same issue here after updating from 2.32.1 to 2.33.0, logging out is also broken as well after spicetify update, as a sidenote can I downgrade or am I just stuck on this version now?

you can downgrade using command `$v="2.32.1"; Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.ps1" | Invoke-Expression`

**Comment by Arimodu** [comment]
Thank you, after downgrade it works again

**Comment by rxri** [comment]
I think logging out is related to logging functions somehow - which is stupid to say the least, and connecting to devices could be also related to this. Until I will not confirm it for 100% this issue stays closed. Will check on it in few hours

**Comment by rxri** [comment]
@iPixelGalaxy I'm sharing the binary with inlcuded fix. Please let me know if that fixes the issue for you. To apply the fixed version run: `spicetify restore backup apply` after replacing binary inside `%localappdata%\spicetify`
[spicetify-2.33.1-Dev.zip](https://github.com/spicetify/spicetify-cli/files/14437722/spicetify-2.33.1-Dev.zip)

**Comment by iPixelGalaxy** [comment]
> @iPixelGalaxy I'm sharing the binary with included fix. Please let me know if that fixes the issue for you. To apply the fixed version run: `spicetify restore backup apply` after replacing binary inside `%localappdata%\spicetify` [spicetify-2.33.1-Dev.zip](https://github.com/spicetify/spicetify-cli/files/14437722/spicetify-2.33.1-Dev.zip) (64-bit version)

It does seem to work, however I'm not sure if that's because it's fixed or because the CSS map is malformed according to the binary
![image](https://github.com/spicetify/spicetify-cli/assets/42526028/5c1076eb-45cb-4d05-adbb-12de8ebdeb78)

**Comment by iPixelGalaxy** [comment]
@rxri I built the binary myself from the fix/logging branch, and yes it does indeed seem to resolve both issues

https://github.com/spicetify/spicetify-cli/assets/42526028/685b141f-be22-4318-8757-fe535835051c

it does seem to be finicky once I swap a device once, I'm going to do a little testing, but I'm guessing that might be an issue with mismatched spotify versions on these devices

**Comment by iPixelGalaxy** [comment]
After compiling the new build for all my devices (my macbook included) and updating to latest spotify build, the issue does seem to be resolved 🥳

**Comment by rxri** [comment]
> > @iPixelGalaxy I'm sharing the binary with included fix. Please let me know if that fixes the issue for you. To apply the fixed version run: `spicetify restore backup apply` after replacing binary inside `%localappdata%\spicetify` [spicetify-2.33.1-Dev.zip](https://github.com/spicetify/spicetify-cli/files/14437722/spicetify-2.33.1-Dev.zip) (64-bit version)
> 
> It does seem to work, however I'm not sure if that's because it's fixed or because the CSS map is malformed according to the binary ![image](https://private-user-images.githubusercontent.com/42526028/308666289-5c1076eb-45cb-4d05-adbb-12de8ebdeb78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNDU5MjksIm5iZiI6MTcwOTE0NTYyOSwicGF0aCI6Ii80MjUyNjAyOC8zMDg2NjYyODktNWMxMDc2ZWItNDVjYi00ZDA1LWFkYmItMTJkZThlYmRlYjc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDE4NDAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjNjY4MTZiZjRjYmE4YTg4ZmJlZWJlYjJkOTU1OGJlNWY3OTdkYzE5MmI4ZmRmYmRjNGE3MTIxOWRjMzc3MTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RkSFeBLvZFzuDVe2xblxirNlInBGaIgSbDxKkl7EGEQ)

yeah but it uses local one instead so it doesn't matter really.
either way, good that it works
Spotify relies on logging methods to properly perform other functions, and it's so funny. "Great company" basically
