### ISSUE TITLE
Pantalla negra en spotify cuando inicia 

### ISSUE THREAD

**Issue by JxseDelRey** [spicetify/spicetify-cli#2872]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 
- Spicetify version:
```

### 📝 Description

Cuando actualice el spotify a su ultima version me cuando abre no pasa de la pantalla en negro 

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/153209219/676b3105-1355-4759-ab8d-30f2a7411824)

**Comment by rxri** [comment]
Update spicetify to latest
