### ISSUE TITLE
lyrics-plus is not working for me 

### ISSUE THREAD

**Issue by DarkKnight45** [spicetify/spicetify-cli#2874]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.26.1187.g36b715a1
- Spicetify version: 2.29.1
```

### 📝 Description

please help me i have tried so many times its not working

### 📸 Screenshots

![Screenshot (12)](https://github.com/spicetify/spicetify-cli/assets/98516085/79fc1363-cc65-4431-95a5-c7eb08bfb4f2)

**Comment by iPixelGalaxy** [comment]
Is there a specific reason you're on those versions of spotify/spicetify? If not, you should update spotify and spicetify.
To update spotify hit the menu button at the top (triple dot), Help -> About Spotify, click "Download update", in powershell type "spicetify update" afterwards, it should also auto patch your spotify.

From person experience in the past, I don't think the "Karaoke" mode on lyrics plus works that well, try the "Synced" or "Unsynced" tabs.

**Comment by rxri** [comment]
Refresh token
