### ISSUE TITLE
WebNowPlaying Plugin: Cannot access 'WNPReduxWebSocket' before initialization

### ISSUE THREAD

**Issue by Archius0** [spicetify/spicetify-cli#2876]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bit) | 1.2.32.997.g4c6498b6
- Spicetify version: 2.33.2
```

### 📝 Description

I'm attempting to create a WebNowPlaying websocket server for a Stream Deck plugin I'm creating, however I noticed that WebNowPlaying isn't loading at all. I can connect to the websocket on Postman and client-sided JavaScript, but cannot get Spotify to connect.
I would imagine this is possible without Rainmeter as long as I create my own websocket server, right?

### 📸 Screenshots

![Screenshot_20240303_062451](https://github.com/spicetify/spicetify-cli/assets/122315514/a471a7d1-53b6-4a54-b974-7a8a53e1550b)
![Screenshot_20240303_062641](https://github.com/spicetify/spicetify-cli/assets/122315514/f0b6881b-e9d3-4c95-a98f-b15712166b68)

**Comment by rxri** [comment]
Cannot reproduce. Add `webnowplaying.js` to the `extensions` in the config, and do not install it via marketplace. However, you won't be able to use it without Rainmeter plugin because it's designed only for that, and that only, unless ofc you do the same communication
