### ISSUE TITLE
lyrics-plus extreme cpu usage

### ISSUE THREAD

**Issue by nxtalex** [spicetify/spicetify-cli#2877]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: newest
- Spicetify version: newest
```

### 📝 Description

pretty simple, lyrics plus uses 20% + cpu , that not good, it happened to a lot of other people as well so not my problem

**Comment by rxri** [comment]
I think you're talking about Beautiful Lyrics, not lyrics-plus. Beautiful Lyrics is not official extension. It will use your CPU because Spotify has hardware acceleration disabled and animations, needs to be calculated somehow

**Comment by nxtalex** [comment]
> I think you're talking about Beautiful Lyrics, not lyrics-plus. Beautiful Lyrics is not official extension. It will use your CPU because Spotify has hardware acceleration disabled, and animations needs to be calculated somehow

i am using full screen extension, and that extension usees lyrics plus extension, when i take it off it works fine. idk what to say 😕

**Comment by rxri** [comment]
Problem with `lyrics-plus` is that it cannot use that much, by design. We don't even use `requestAnimationFrame` or `setTimeouts` to change UI. Generally, without any debug or performance logs I won't be able to say that it's lyrics-plus' fault since I cannot reproduce this issue

**Comment by ameliorability** [comment]
Same issue, here are screenshots with CPU usage

With lyrics-plus DISABLED: 
![image](https://github.com/spicetify/spicetify-cli/assets/141889580/0edc1570-6ada-4cbf-b526-d057cb7acfe6)

With lyrics-plus ENABLED but not being used:
![image](https://github.com/spicetify/spicetify-cli/assets/141889580/726e7350-5271-4fbe-8326-2710e50cc741)

With lyrics-plus ENABLED and being used: 
![image](https://github.com/spicetify/spicetify-cli/assets/141889580/314ef314-5786-40d8-b2a4-4607841b0408)

But thank you rxri and other wonderful developers for this wonderful extension :)

**Comment by rxri** [comment]
Like I said in my second message, I need performance logs or anything useful, since as mentioned in my previous comment, it's at around ~7% for me, so I cannot "debug" it. I'm sorry. I recommend trying when you don't have themes and extensions installed, and just lyrics-plus

**Comment by SKDemon820** [comment]
Hey, I don't have logs rn but just wanted to report that I also have the same issue.  The CPU usage by Spotify Helper jumps from 15% (open) or <1% (minimized) to >200% when the lyrics-plus panel is open (it's fine when it's closed), I attached a video showing it (I have other stuff installed in the video but I later tested with all extensions and themes deleted and it still occured).  I updated Spotify, Spicetify, and Lyrics-plus to the latest last night, and noticed the issue today when I minimized Spotify with the panel opened and my laptop's entire keyboard became significantly warm over about an hour.

I don't really have much experience with reporting this kind of stuff, if possible what exactly can I save and submit to help debug it?

https://github.com/spicetify/spicetify-cli/assets/62918850/7c8b39e9-801f-41ee-b170-99fb4b00cdce

**Comment by InsanityPrelude** [comment]
Well, this is frustrating.  I've managed to acquire Performance Data showing this issue using DevTools, but I can't actually save the trace from it.  There's a bug affecting DevTools right now relating to DevTools not being exempt from File Access permissions, so it's not possible for me to save it, and it simply returns "Failed to save timeline: The request is not allowed by the user agent or the platform in the current context. (NotAllowedError)" unfortunately.  

In the interim, here's the screenshot I was able to produce.  In it, I started the recording while viewing Spotify in Desktop mode looking at the Marketplace.  At 3 seconds I switched into "Lyrics" view, and then I switched out at 10 seconds and alternated in and out every 5 seconds afterwards.  There's clearly something going on, but unfortunately I don't think I know enough to figure it out.  I'm not even smart enough to figure out whether some unhinged maniac actually named all these functions by pouring out a can of alphabet soup or if I'm just not loading a source mapping file correctly.

![image](https://github.com/spicetify/spicetify-cli/assets/38642020/4e23530b-7ed4-4c18-b85e-b8f50fd0902c)

Zooming in, the best I can figure out is that the function designated "L" is being called in a loop thousands of times continuously.

I'm going to see if I can do anything about the File Access Permissions for DevTools so I can just upload a performance trace when the problem is occurring.

**Comment by samuelawachie** [comment]
This is definitely a problem and it's affecting me too (on Linux Zorin; latest versions of both Spotify (apt) and Spicetify).
CPU usage spikes by 30% when you open the lyrics page or using any extensions that depend on it (like FullScreen by dash2k)
You needn't even play any song. Just opening/clicking the lyrics button to open the lyrics page causes it.
And of course, all the attendant issues with temperature, fans spinning, performance/lagging, and an exasperated user.
/: Need a fix, please.

**Comment by rxri** [comment]
@InsanityPrelude use remote debugging port:
Run spotify with: `--remote-debugging-port=9222`, then in your browser `chrome://inspect` or `edge://inspect`, then inspect Spotify, go to Performance tab and do whatever you did to reproduce it and save performance report

**Comment by rxri** [comment]
I still cannot reproduce it:

```
Spotify for Windows (32 bit)
1.2.32.997.g4c6498b6
Spicetify vDev
xpui_2024-02-23_1708709925614_4c6498b
cef_121.3.15+g4d3b0b4+chromium-121.0.6167.184
Runtime: Chrome
```

**Comment by ohitstom** [comment]
i think some more information from these guys would be helpful, specifically their full spotify version info as well as their system architecture (amd, nvidia, etc)

**Comment by InsanityPrelude** [comment]
That's a reasonable thought.  It might be something unusual like it only affecting AMD processors, Windows 11, a specific version of Spotify, etc.  Here's my info.

Spotify for Windows (64 bit)
1.2.32.997.g4c6498b6
Spicetify v2.33.2
Theme: marketplace
Extensions: fullScreenWrapper.js
Custom apps: marketplace, lyrics-plus
xpui_2024-02-23_1708709925614_4c6498b
cef_121.3.15+g4d3b0b4+chromium-121.0.6167.184
Runtime: Alloy

OS Name:                  Microsoft Windows 11 Home
OS Version:                10.0.22621 N/A Build 22621
System Model:           X670 AORUS ELITE AX
Processor:                  AMD Ryzen 7 7800 X3D 8-Core Processor

**Comment by rxri** [comment]
You can find my build here: https://pcpartpicker.com/list/gnrTDZ (without the RX 570 listed)

**Comment by rxri** [comment]
> > Runtime: Alloy
> 
> 
> 
> could you try forcing your spotify to run with chromium and not alloy using the flag `--enable-chrome-runtime`

I did not have this issue on Alloy runtime either. Chrome runtime just has more APIs enabled

**Comment by InsanityPrelude** [comment]
I've just rebooted Spotify with that argument.  The same issue still occurs for me.

It's easy to tell even without devtools, because my computer runs silently until I open "Lyrics" and then the CPU fan starts up and takes off.  Can't seem to access DevTools in this mode though.

**Comment by ohitstom** [comment]
> I've just rebooted Spotify with that argument. The same issue still occurs for me.
> 
> It's easy to tell even without devtools, because my computer runs silently until I open "Lyrics" and then the CPU fan starts up and takes off. Can't seem to access DevTools in this mode though.

are you using integrated graphics? (the 3d part of your cpu), the other people having issues here seem to mention laptops alot which often use integrated graphics

**Comment by rxri** [comment]
> then in your browser chrome://inspect or edge://inspect, then inspect Spotify, go to Performance tab and do whatever you did to reproduce it and save performance report

**Comment by InsanityPrelude** [comment]
> > I've just rebooted Spotify with that argument. The same issue still occurs for me.
> > It's easy to tell even without devtools, because my computer runs silently until I open "Lyrics" and then the CPU fan starts up and takes off. Can't seem to access DevTools in this mode though.
> 
> are you using integrated graphics? (the 3d part of your cpu), the other people having issues here seem to mention laptops alot which often use integrated graphics

I'm not, I'm using an RTX 2080.  I just checked the GPU for the process and it's not using the iGPU as far as I can tell.

I'll try rxri's suggestion now.

**Comment by ohitstom** [comment]
can confirm the issue on my device, ~5% idle, jumps to 20-30% on the lyrics page

**Comment by rxri** [comment]
![image](https://github.com/spicetify/spicetify-cli/assets/9348108/083ef862-0927-4614-b9ba-c172492af161)
Is the rasterization hardware accelerated for you both?

**Comment by InsanityPrelude** [comment]
![image](https://github.com/spicetify/spicetify-cli/assets/38642020/dd60459d-a2ac-4af3-a7f5-96536143e6c5)
It It does appear to be, yes.

**Comment by ohitstom** [comment]
[Trace-20240307T172643.zip](https://github.com/spicetify/spicetify-cli/files/14527844/Trace-20240307T172643.zip)
here is my trace, based on the trace i dont believe its a rendering issue but here is my rasterization stuff anyways:
![image](https://github.com/spicetify/spicetify-cli/assets/22730962/3f249a55-504e-428e-b462-915d18509aad)

**Comment by InsanityPrelude** [comment]
[Trace-20240307T122824.json](https://github.com/spicetify/spicetify-cli/files/14527858/Trace-20240307T122824.json)
Hah, funny enough I was just able to also retrieve a Trace log.  I've attached it here as well.

**Comment by ohitstom** [comment]
![image](https://github.com/spicetify/spicetify-cli/assets/22730962/d9033a25-63c3-456a-a6bf-9d0faccd819e)
it looks like every 0.1ms its removing and re-adding a child over and over and over and over again?

**Comment by rxri** [comment]
The most funny thing is that it's from React scheduler code

**Comment by ohitstom** [comment]
i could be wrong but i believe this to be the culprit (at least partly)?
![image](https://github.com/spicetify/spicetify-cli/assets/22730962/eb9b066f-aa9a-4838-8369-5a8efe9d9805)

i just took another performance sample with the page already open sitting there doing nothing (Not even playing a song) yet this function keeps being called

**Comment by rxri** [comment]
holy shit... i know why this keeps happening
