### ISSUE TITLE
[Lyrics Plus] Full screen UI messed up

### ISSUE THREAD

**Issue by LoganWolfie** [spicetify/spicetify-cli#2881]
### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (64 bit)
1.2.32.997.g4c6498b6

Spicetify v2.33.2
```

### 📝 Description

The Lyrics Plus full screen UI is completly messed up on my vertical monitor and on the horizontal monitor the side bars start scrolling down and some of the song information, shuffle, skip, etc features are overlapped / dimmed or out of place.

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/72407034/fb377b2a-8f0f-4f09-8471-89973d52a95e)
![image](https://github.com/spicetify/spicetify-cli/assets/72407034/0f70c052-342a-41c5-b31d-fef01a54a40d)

**Comment by ohitstom** [comment]
this is an issue with your theme

**Comment by rxri** [comment]
Theme issue

**Comment by LoganWolfie** [comment]
> Theme issue

It's not. 
![image](https://github.com/spicetify/spicetify-cli/assets/72407034/8f8b9b4c-822f-4f92-8d43-b2000e6040f2)

**Comment by LoganWolfie** [comment]
> this is an issue with your theme

Yeah it's definetly not.

**Comment by ohitstom** [comment]
> > this is an issue with your theme
> 
> Yeah it's definetly not. 

it definitely is, check your snippets as well

**Comment by ohitstom** [comment]
> > > this is an issue with your theme
> > 
> > Yeah it's definetly not. 
> 
> it definitely is, check your snippets as well

also correct me if I'm wrong but none of those screenshots are custom apps or extensions we maintain?

**Comment by LoganWolfie** [comment]
I deleted all mods but lyrics plus and it still doesn’t work. 

I found out who made this fullscreen mod didn’t realize it wasn’t you guys but they use lyrics plus for the mod and only worked with lyrics plus so I just assumed you guys had made it.

**Comment by ohitstom** [comment]
> I deleted all mods but lyrics plus and it still doesn’t work. 
> 
> I found out who made this fullscreen mod didn’t realize it wasn’t you guys but they use lyrics plus for the mod and only worked with lyrics plus so I just assumed you guys had made it. 

I would suggest opening an issue on the creators repo 🤙

**Comment by LoganWolfie** [comment]
Yeah I did that. Someone else already did a while ago and it doesn’t seem like they really care for it cause they don’t work with vertical monitors :/
