### ISSUE TITLE
Loopy Loop doesn't work

### ISSUE THREAD

**Issue by Agent-bonio** [spicetify/spicetify-cli#2883]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.32.997.g4c6498b6
- Spicetify version: v2.33.2
```

### 📝 Description

Even though I right-clicked on the song's progress bar, the menu does not appear. There is also no information about this anywhere

**Comment by rxri** [comment]
and it won't work because this extension requires full rewrite since we changed the Context Menu APIs
This includes `bookmark.js` extension as well

**Comment by telqr** [comment]
this is ongoing for me aswell

**Comment by ohitstom** [comment]
> and it won't work because this extension requires full rewrite since we changed the Context Menu APIs This affects `bookmark.js` extension as well

is it even possible to bind a new context menu to an existing div anymore? i was looking at the helper and the react components all require you to make a new element to bind it to, if you could point me to a function or component that can achieve this i'd be more than happy to do this tonight

**Comment by rxri** [comment]
with some hacky workarounds you probably could, but these extensions should have used React from the beginning. I have no idea why it has been made the way it is

**Comment by ohitstom** [comment]
> with some hacky workarounds you probably could, but these extensions should have used React from the beginning. I have no idea why it has been made the way it is

we could push a hacky fix until v3 tbh lol

**Comment by rxri** [comment]
> > with some hacky workarounds you probably could, but these extensions should have used React from the beginning. I have no idea why it has been made the way it is
> 
> we could push a hacky fix until v3 tbh lol

Generally, we want to remove these extensions because of the low userbase. Since we pushed ContextMenuV2, only recently, two or three people started asking why these do not work on discord. to be decided

**Comment by ohitstom** [comment]
> > > with some hacky workarounds you probably could, but these extensions should have used React from the beginning. I have no idea why it has been made the way it is
> > 
> > 
> > we could push a hacky fix until v3 tbh lol
> 
> Generally, we want to remove these extensions because of the low userbase. Since we pushed ContextMenuV2, only recently, two or three people started asking why these do not work on discord. to be decided

oh i was just about to open a pr fixing it, maybe fix it until v3 and remove them in v3? up to you i can trash the pr if you want

**Comment by rxri** [comment]
if you want to push fix, go ahead, i will merge it

**Comment by EpicE-123OmegaFan** [comment]
was this ever fixed?
also it doesnt work for me

**Comment by ZichRuby** [comment]
I guess it's still not working.

**Comment by Leafaine** [comment]
It is still not working :(
