### ISSUE TITLE
Fatal Get unexpected EOF spicetify-2.33.2-darwin-arm64.tar.gz

### ISSUE THREAD

**Issue by tario-you** [spicetify/spicetify-cli#2887]
### 🔍 Have you checked Spicetify.app page for your issue?

- [x] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.32.997.g4c6498b6
- Spicetify version: 2.27.2 (current version)
```

### 📝 Description

running "spicetify upgrade" in terminal

### 📸 Screenshots

<img width="550" alt="Screenshot 2024-03-10 at 11 31 06" src="https://github.com/spicetify/spicetify-cli/assets/60311384/2e356d75-33ac-491b-8b6b-9419c97c6b14">

**Comment by rxri** [comment]
Just use install script
