### ISSUE TITLE
lyrics-plus not working

### ISSUE THREAD

**Issue by heetood** [spicetify/spicetify-cli#2889]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.32.997.g4c6498b6
- Spicetify version: 2.33.2
```

### 📝 Description

the lyrics-plus isn't working. i checked some old discussions and saw something about refreshing the musixmatch token but can't find that button

### 📸 Screenshots

![lyrics1](https://github.com/spicetify/spicetify-cli/assets/162911091/5d307ee4-768b-42fc-b0fb-d80ae848582f)
![lyrics2](https://github.com/spicetify/spicetify-cli/assets/162911091/9432d264-b41b-40d9-b4a6-0a3e4da79725)

**Comment by rxri** [comment]
You have old version of lyrics-plus I believe. I recommend uninstalling spicetify (https://spicetify.app/docs/advanced-usage/uninstallation) and installing it again via install script so you get latest files. Not a bug, not an issue

**Comment by heetood** [comment]
thanks for the quick response your help got it working now.
