### ISSUE TITLE
Follow all artists from a specific playlist 

### ISSUE THREAD

**Issue by uugaabuugaa** [spicetify/spicetify-cli#2901]
### 📝 Provide a description of the new feature

I don't know if this is the right place to ask this but from the extensive features here I think it's possible to have an extension or app to follow all unfollowed artists from a specific playlist(s). 

### ➕ Additional Information

I've found only [this](http://www.nativenoise.co.za/spotify/follow-all-artists/) to do something similar. However it doesn't work on specific playlists or big playlists so it's kinda useless. However it has an option to check/uncheck unwanted artists which is cool.

**Comment by rxri** [comment]
Request it  discord server
