### ISSUE TITLE
Spotify new update UI seems to compress the sidebar items plus the playlists as well after installing Spicetify

### ISSUE THREAD

**Issue by DuskyRick** [spicetify/spicetify-cli#2903]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows (32 bit) 1.2.33.1039.g8ddb5918
- Spicetify version: Spicetify v2.34.0
```

### 📝 Description

Following a recent Spotify update, I had to upgrade both SpotX and Spicetify. However, post-installation of Spicetify, the sidebar items appear compressed, as if glued together, which is also true for the main menu options, ranging from playlists to artists. The main menu options have become unclickable.

### 📸 Screenshots

![img-2024-03-13-14-52-49](https://github.com/spicetify/spicetify-cli/assets/84189794/dadf816c-03d5-4e08-b10e-cf4b1b04d426)

**Comment by lt-tim** [comment]
I have the same issue on V2.34.0
![image](https://github.com/spicetify/spicetify-cli/assets/141122452/43171e5f-0d8d-42d6-8a9d-5d8081fabb54)

**Comment by lt-tim** [comment]
I cant normally click on any of the ablum, text is also overlapped. Even without theme applied.

**Comment by DuskyRick** [comment]
> Known issue. Will be fixed in next release

Thanks! Also thanks you for this wonderful project you guys have

**Comment by GeorgeGedox** [comment]
Just updated to v2.34.1, the sidebar spacing is fixed but everything else is still messed up
