### ISSUE TITLE
New version comes with Trojan

### ISSUE THREAD

**Issue by iOddishGX** [spicetify/spicetify-cli#2904]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spicetify version: 2.34.0
```

### 📝 Description

After update/installation a trojan known as Wacatac.B!ml is installed on the computer.
I tried to update and install and both installed this file.

### 📸 Screenshots

![w2](https://github.com/spicetify/spicetify-cli/assets/75219312/0d75aaf1-fad8-4d3b-9213-90b1526b049a)

**Comment by rxri** [comment]
No it doesn’t. It’s false positive.
