### ISSUE TITLE
Spicetify Shows Random icons

### ISSUE THREAD

**Issue by K3NOXOFFICIAL** [spicetify/spicetify-cli#2906]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.17.834.g26ee1129
- Spicetify version: 2.34.1
```

### 📝 Description

Spicetify Shows Wrong icons and some icons are missing completely.
I already reinstalled spicetify, spotify tried it without any plugins and themes.
Top buttons are showing the wrong icons and the shuffle button is complettly missing.

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/46091052/3b092285-b811-4f25-a2b8-0a00a9c777f1)
![image](https://github.com/spicetify/spicetify-cli/assets/46091052/1ec31b20-8400-45be-a6d8-d74617d421d4)

**Comment by rxri** [comment]
Looks like theme related.
