### ISSUE TITLE
Search bar losing focus after a few seconds

### ISSUE THREAD

**Issue by SkyeWong** [spicetify/spicetify-cli#2909]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (64 bit)
1.2.33.1039.g8ddb5918
Spicetify v2.34.1
Theme: Bloom / comfy
Extensions: loopyLoop.js, adblock.js, SleepTimer.js, fullScreenWrapper.js, theme.js
Custom apps: marketplace, stats, lyrics-plus
```

### 📝 Description

When I type in the spotify search bar

**Comment by rxri** [comment]
Theme issue
