### ISSUE TITLE
[core] Add support for flatpak's user folder

### ISSUE THREAD

**Issue by Heus-Sueh** [spicetify/spicetify-cli#2914]
### 📝 Provide a description of the new feature

Add support for this spotify flatpak location: `~/local/share/flatpak/app/com.spotify.Client`

### ➕ Additional Information

I believe this is the location that some flatpaks are installed on immutable distros

I'm on Fedora Sericea and Spotify wasn't in `var/lib/flatpak/app` for some reason and I found it in the home in `.local/share/flatpak/app`

**Comment by rxri** [comment]
Just set it manually in your config then. We do not need to add this path as “potential location” for it to work

**Comment by Heus-Sueh** [comment]
> Just set it manually in your config as spotify path then. We do not need to add this path as “potential location” for it to work

I would like users not to have to manually put this directory in the config file and not encounter the problems I have because this directory is not documented on the site

this directory `~/.local/share/flatpak/app` would be where per-user apps are installed, different from apps installed on the entire system such as `var/lib/flatpak`

I checked the `config.go` file in the `utils` folder here and found the [list of potentials](https://github.com/spicetify/spicetify-cli/blob/master/src/utils/config.go#L306) spotify directories, would there be any problem if I made the pull request adding this directory I mentioned?
