### ISSUE TITLE
[core/wrapper] expose mui components

### ISSUE THREAD

**Issue by ohitstom** [spicetify/spicetify-cli#2917]
### 📝 Provide a description of the new feature

as per the screenshot below it looks like a list of lots of mui core components (or similarly named):
https://mui.com/material-ui/

maybe im misunderstanding i guess but the list is super similar and if spotify are using some variation of material ui exposing the components would be so so helpful

### ➕ Additional Information

![image](https://github.com/spicetify/spicetify-cli/assets/22730962/95f1ed4b-a922-43b8-98e1-31b8c304636e)

**Comment by Delusoire** [comment]
Not mui, those components seem to be written with styled-components, afaik mui isn't based on styled-components.

**Comment by Delusoire** [comment]
https://github.com/Delusoire/bespoke-stdlib/blob/main/src/expose/webpack.ts#L141-L156

**Comment by ohitstom** [comment]
> Not mui, those components seem to be written with styled-components, afaik mui isn't based on styled-components.

ah okay the naming just seemed similar so I was being hopeful 😞

**Comment by ohitstom** [comment]
> https://github.com/Delusoire/bespoke-stdlib/blob/main/src/expose/webpack.ts#L141-L148

will this expose `tabs` from that list?
