### ISSUE TITLE
[Lyrics Plus] Genius lyrics doesn't show in the provider's list

### ISSUE THREAD

**Issue by CheraHamza** [spicetify/spicetify-cli#2918]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.31.1205.g4d59ad7c
- Spicetify version: 2.35.1
```

### 📝 Description

1- Open Lyrics-plus from the menu, but Genius lyrics are nowhere to be found 

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/73847973/6f800db8-d64f-4778-acd7-b9da31489939)
![image](https://github.com/spicetify/spicetify-cli/assets/73847973/5dfec026-3178-4101-a8db-1c7346f6112b)

**Comment by rxri** [comment]
Please read the description of the provider inside Lyrics Plus config. It’s intentional and it’s disabled in Spotify versions 1.2.31 and higher

**Comment by CheraHamza** [comment]
> Please read the description of the provider inside Lyrics Plus config. It’s intentional and it’s disabled in Spotify versions 1.2.31 and higher

Why is that? And can I enable it, or do I need to downgrade my Spotify?

**Comment by rxri** [comment]
Downgrade Spotify if you want it back
