### ISSUE TITLE
My buttons are tightly packed together

### ISSUE THREAD

**Issue by Sansh1j1u** [spicetify/spicetify-cli#2919]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.33.1042.g26c92729
- Spicetify version:2.35.1
```

### 📝 Description

After updating my Spotify, I no longer had Spotify, so I reinstalled Spotify and installed it together. After installing Spotify and opening it, it turned out like this

### 📸 Screenshots

![屏幕截图 2024-03-24 090940](https://github.com/spicetify/spicetify-cli/assets/151978267/ab31f7e4-d53c-481b-95a0-fce6fa3125e5)

![image](https://github.com/spicetify/spicetify-cli/assets/151978267/36645f03-f780-4d15-92bb-071dcd4dadb8)

**Comment by rxri** [comment]
You definitely not have applied spicetify as this has been already resolved. `spicetify apply`, if that doesn't work - reinstall spotify and run `spicetify backup apply`

**Comment by Sansh1j1u** [comment]
> You definitely not have applied spicetify as this has been already resolved. Run `spicetify apply`, if that doesn't work - reinstall spotify and run `spicetify backup apply`

I did everything you said, but it still doesn't work

**Comment by rxri** [comment]
1. Uninstall spotify
2. Remove spicetify (https://spicetify.app/docs/advanced-usage/uninstallation)
3. Install spotify
4. Install spicetify
5. Run `spicetify backup apply`
