### ISSUE TITLE
Black Screen when playing song directly from discography, search or artist "popular" page.

### ISSUE THREAD

**Issue by muhammadfahmi28** [spicetify/spicetify-cli#2920]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.33.1042.g26c92729
- Spicetify version: v2.35.1
Spotify for Windows (64 bit)
1.2.33.1042.g26c92729
Spicetify v2.35.1
Theme: marketplace / dark
Extensions: beautiful-lyrics.js, romaji-convert.js, extractor.js, romajin.js, shuffle+.js, popupLyrics.js
Custom apps: marketplace
xpui_2024-03-21_1711040982767_26c9272
cef_122.1.8+g40272b5+chromium-122.0.6261.69
Runtime: Chrome
```

### 📝 Description

Steps to reproduce:
1. Open an artis page
2. On discography section, click "Show all"
3. Play any song

I was also get random black screen when I just installed for the first time.

Playing from playlist is OK.
Devtools error:
```
vendor~xpui.js:1 Error: Please wrap your component in RemoteConfig Provider
    at e.Delegate.provider (vendor~xpui.js:1:1413554)
    at e.Delegate.getValue (vendor~xpui.js:1:1421317)
    at l (vendor~xpui.js:1:1414479)
    at d (xpui.js:1:225133)
    at Ta (vendor~xpui.js:1:2309119)
    at Tc (vendor~xpui.js:1:2365974)
    at El (vendor~xpui.js:1:2355126)
    at yl (vendor~xpui.js:1:2355054)
    at gl (vendor~xpui.js:1:2354917)
    at al (vendor~xpui.js:1:2351724)
```
    
Also sometimes I see 404 or 403 in console, and unresponsive marketplace with popup warning 403, I dont know if it connected or not.

The error occured even before I installed any theme and add-on

### 📸 Screenshots
![image](https://github.com/spicetify/spicetify-cli/assets/79831020/bf747164-368b-4bee-83db-b17082fcbdfe)
![image](https://github.com/spicetify/spicetify-cli/assets/79831020/acbf5bfe-b722-42c9-94ba-1469b76da956)
![image](https://github.com/spicetify/spicetify-cli/assets/79831020/b3f90a88-b043-4394-9e20-d462616dcf29)

edit:
I tried to use "spotify restore" then "spotify upgrade"
the problem dissapear
then i install spotify-marketplace
then I got the problem again

**Comment by rxri** [comment]
Looks like corrupted spotify installation. I cannot reproduce it on my end. 
![image](https://github.com/spicetify/spicetify-cli/assets/9348108/5296ba43-0243-4bb6-9063-2961fbbce45a)

**Comment by muhammadfahmi28** [comment]
update:
I tried to use "spotify restore" then "spotify upgrade"
the problem dissapear
then i install spotify-marketplace
then I got the problem again

**Comment by muhammadfahmi28** [comment]
It was actually my second installation of spotify+spicetify

I just redownload the installer and reinstalled spotify+spicetify third-time, with nothing else opened this time . 
Now everything works perfectly.

thank you. sorry for the problem.
