### ISSUE TITLE
cant use themes on spicetfy

### ISSUE THREAD

**Issue by ppers** [spicetify/spicetify-cli#2924]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:i dont know the specific version but I just got the app today
- Spicetify version:v2.36.0

I'm using windows 10
```

### 📝 Description

so i wanted to get themes on spotify and when I installed it it showed the extensions, but nothing else not the snippets not the themes nothing but the marketplace and extensions.

**Comment by rxri** [comment]
Get help on our discord server
