### ISSUE TITLE
[Pop-up Lyrics] Make MacOS version have a border radius to match PIP videos

### ISSUE THREAD

**Issue by ocreturner** [spicetify/spicetify-cli#2929]
### 📝 Provide a description of the new feature

its currently 0 border radius for windows. I'd like to ask for the Mac version to have a **rounder border** that imitates the picture-in-picture for YouTube videos

**Comment by rxri** [comment]
PiP window is managed by Spotify, not us. Border is not 0, because the windows border actually lies in DWM - on windows 11 it's rounded, on windows 10 it's not. There probably is a way to control that but is not worth the time
