### ISSUE TITLE
Opening Queue gives an error screen

### ISSUE THREAD

**Issue by TheDarkKnight69** [spicetify/spicetify-cli#2930]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.25
- Spicetify version:
```

### 📝 Description

Opening the queue or anything gives me an error screen.
"Something went wrong. Try reloading". I just started getting this error today after weeks of undisturbed usage.

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/91176991/e122f38d-2d06-4081-9ac4-91f4ecc3ab50)

**Comment by rxri** [comment]
No error inside console. Reinstall everything
