### ISSUE TITLE
Marketplace not showing top row

### ISSUE THREAD

**Issue by znicuuu** [spicetify/spicetify-cli#2936]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify für Windows (64 Bit)
1.2.34.783.g923721d9
Spicetify v2.36.2
Theme: Hazy / Base
Extensions: playbarClock.js, quickQueue.js, spicetify-playlist-labels.js, volumePercentage.js, playlist-icons.js, beautiful-lyrics.js, theme.js
Custom apps: marketplace, better-local-files
```

### 📝 Description

Marketplace top row for switching between Extensions, Addons etc. is not showing since new spotify update.

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/73033465/d7a76649-03cc-4ba7-be44-6ce3498f6424)

**Comment by rxri** [comment]
Most likely theme issue
![image](https://github.com/spicetify/spicetify-cli/assets/9348108/c3b70dfb-4865-4390-83cc-d1acc0048ed8)
