### ISSUE TITLE
Unable to uninstall webnowplaying

### ISSUE THREAD

**Issue by heartpops** [spicetify/spicetify-cli#2937]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.33.1042
- Spicetify version: v2.36.2
```

### 📝 Description

Hi, so I have a strange issue that probably has an easy fix but I haven't been able to sort it out. I tried downloading the webnowplaying from marketplace and I got this error that seemed self-explanatory but got an error in powershell (`warning Config "extensions" unchanged: webnowplaying.js is not on the list.`). I've tried variations of the command (`spicetify config extensions webnowplaying.js-`) but can't quite get it.

### 📸 Screenshots

![Screenshot 2024-04-03 184836](https://github.com/spicetify/spicetify-cli/assets/121929523/b75ef187-0a50-4fad-865c-904694e6fc5d)
![Screenshot 2024-04-03 181201](https://github.com/spicetify/spicetify-cli/assets/121929523/69f67a38-b2f2-4db1-8358-64d8d27b1878)

**Comment by rxri** [comment]
If you install via marketplace then you uninstall via marketplace

**Comment by heartpops** [comment]
The problem I can’t access the marketplace, there’s no way to close the warning overlay so it’s not possible to access anything in the player.

**Comment by rxri** [comment]
1. Run `spicetify enable-devtools`
2. Right click somewhere in spotify
3. Click `Inspect Element` and go to `Console` tab
4. Run `Marketplace.reset("extensions")`
