### ISSUE TITLE
css padding not functioning

### ISSUE THREAD

**Issue by GamerAseemm** [spicetify/spicetify-cli#2938]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: latest
- Spicetify version: latest
```

### 📝 Description

idk how to produce

### 📸 Screenshots
![2024-04-04 14_19_20-MoonDeity - One Chance](https://github.com/spicetify/spicetify-cli/assets/123302794/edc37019-013d-439b-97ed-48f9e4f3d222)

**Comment by rxri** [comment]
You clearly are not on latest spicetify version. Uninstall spotify, install it again, update spicetify and run “spicetify backup apply”
