### ISSUE TITLE
error while installation

### ISSUE THREAD

**Issue by anshul-jpg** [spicetify/spicetify-cli#2941]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:1.2.34.783 
- Spicetify version:2.36.2
```

### 📝 Description

Do you want to abort the installation process to avoid any issues?
[Y] Yes  [N] No  [?] Help (default is "Y"): n
Installing spicetify...
Fetching the latest spicetify version... > OK
Downloading spicetify v2.36.2... > OK
Extracting spicetify... > OK
Making spicetify available in the PATH... > OK
Remove-Item : An object at the specified path C:\Users\WIN10~1 does not exist.
At line:144 char:5
+     Remove-Item -Path $archivePath -Force -ErrorAction 'SilentlyConti ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Remove-Item], PSArgumentException
    + FullyQualifiedErrorId : Argument,Microsoft.PowerShell.Commands.RemoveItemCommand

### 📸 Screenshots

![Screenshot (9)](https://github.com/spicetify/spicetify-cli/assets/72707297/ec7078c5-4dde-463a-a6bc-d28f531a0937)

**Comment by rxri** [comment]
Ignore

**Comment by anshul-jpg** [comment]
so i can't use it?

**Comment by rxri** [comment]
huh? It already installed wdym. Just ignore this error

**Comment by anshul-jpg** [comment]
![Screenshot (10)](https://github.com/spicetify/spicetify-cli/assets/72707297/0a494ec9-a6cb-4ade-9c75-7ea7c4adc4e5)
then there is no marketplace here

**Comment by rxri** [comment]
Install it with second script listed on our website...?
