### ISSUE TITLE
Weird roll bar at the bottom

### ISSUE THREAD

**Issue by MMMMMoris** [spicetify/spicetify-cli#2943]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.34.783.g923721d9 (latest)
- Spicetify version: v2.36.2
```

### Weird roll bar appeared at the bottom after upgrading Spicetify to the latest version.
![image](https://github.com/spicetify/spicetify-cli/assets/63332824/d4e6bd93-e6f9-4561-bf10-1f93ae00051b)

**Comment by rxri** [comment]
That’s not cli related. Dribblish is a broken theme
