### ISSUE TITLE
Is it possible to customize components?

### ISSUE THREAD

**Issue by MMMMMoris** [spicetify/spicetify-cli#2944]
### I don't like this player list with a skeleton as cover.
I failed to find ways to remove "You top mixes" part from my Home page.
Coming here to seek solutions to customize components of Home page.
There seems to be no extension achieved to do so.
![image](https://github.com/spicetify/spicetify-cli/assets/63332824/706eb08c-04fc-4af3-9786-f840f3b11227)

**Comment by rxri** [comment]
No you cannot modify components per se. You can hide the highlighted card with css, or JavaScript probably

**Comment by rxri** [comment]
And don’t create issues to ask for help. Discord server exists just for that purpose

**Comment by MMMMMoris** [comment]
> And don’t create issues to ask for help. Discord server exists just for that purpose

Sorry about that.
