### ISSUE TITLE
Lyrics NOT showing on full screen

### ISSUE THREAD

**Issue by abirabedinkhan** [spicetify/spicetify-cli#2946]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.34.783.g923721d9
- Spicetify version: 2.36.2
```

### 📝 Description

![image](https://github.com/spicetify/spicetify-cli/assets/67215274/21263b27-77ea-4299-b895-752fec830904)
When I click on the beautiful lyrics button it doesn't show up. Also not showing on full screen.

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/67215274/267084b8-fa62-49fe-a8e5-d4de953f7d2c)
![image](https://github.com/spicetify/spicetify-cli/assets/67215274/aa04d3fa-f4a0-48e5-b959-f2a0d481b15a)
![image](https://github.com/spicetify/spicetify-cli/assets/67215274/57a73001-a711-4cfc-9ad5-7014f68f3f62)

**Comment by rxri** [comment]
Beautiful Fullscreen is not our extension tho

**Comment by abirabedinkhan** [comment]
i removed it and still does the same thing

**Comment by rxri** [comment]
...? It's not our extension, you should contact the developer of it since it's out of our hands.
