### ISSUE TITLE
Spicetified-Spotify suddenly laggy, all but unusable

### ISSUE THREAD

**Issue by Coldblackice** [spicetify/spicetify-cli#2950]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows x64 1.2.34.783g923721d9
- Spicetify version: 2.36.2 (fully updated + refreshed, multiple times)

- Windows 10 Pro x64
- i9 9900K @ 5GHz
- 32GB RAM
- EVGA 3080 / HW acceleration enabled (also disabled as troubleshooting)
- 1TB NVMe
- No other processes competing for any resource
```

### 📝 Description

As of today, Spicetified Spotify is barely usable: massively unresponsive, lengthy delays in actions/clicking, trying to play anything is probably a 15-second delay. Windows Resource Monitor shows Spotify is writing massive amounts of data, constantly, to files here:

`%LocalAppData%\Spotify\Users\...-user\primary.ldb\X0267XX.ldb` (XX a 2-digit number, incrementing every few seconds, all preceding files continuing to get written to constantly/synchronously, 20+ files, each being written at ~300KB/sec.

Further, when exiting Spotify, even after the GUI disappears like an exit, music continues to play in the background requiring a `taskkill /f` to close all the still-running instances of Spotify.exe

Multiple restarts + Spicetify refreshes have been to no avail, still the same issue.

**Comment by rxri** [comment]
That’s not spicetify related
