### ISSUE TITLE
Fixing romaji Japanese translation 

### ISSUE THREAD

**Issue by GildasEdraE** [spicetify/spicetify-cli#2951]
### 📝 Provide a description of the new feature

**In some lyrics(synced/unsynced)**, if you translate **Furigana** into _Romaji_, there are several words that do not match the original lyrics. 

For example, a word that is quite often encountered, **futari becomes ni nin**,I know that the meaning is the same, but this doesn't match the lyrics.

and another thing is that some _**letters cannot be translated into romaji**_.

**Comment by rxri** [comment]
This is an issue with library we’re using so nothing to do on our end

**Comment by GildasEdraE** [comment]
Ok

**Comment by GildasEdraE** [comment]
May be I'm going Delete lyrics plus custom app temporarily and Search another extension
