### ISSUE TITLE
Missing symbol for custom app React Element

### ISSUE THREAD

**Issue by JerbearGC** [spicetify/spicetify-cli#2955]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (64 bit)
1.2.35.663.gb699649e

Spicetify: v2.36.3
Theme: Sleek / UltraBlack
Extensions: adblock.js, volumePercentage.js, playbarClock.js, sleepTimer.js, spotifyGenres.js, fullScreenWrapper.js, fullAlbumDate.js, made-for-you-shortcut.js
Custom apps: marketplace, lyrics-plus
```

### 📝 Description

So, spotify updated on my side. I ran spicetify backup apply as the spicetify version was already v2.26.3.

When I ran it it showed this: 
![image](https://github.com/spicetify/spicetify-cli/assets/166412725/82a2f449-adfd-4097-8cdf-e669aef85126)

So I followed its instructions

The missing symbol, idk what that means but that is the point of my issue raising

I thought it might link to this:
![image](https://github.com/spicetify/spicetify-cli/assets/166412725/542ec0ad-527b-456d-b039-d81154fb9825)

(Pressed lyrics button, no lyrics ;-;)

and I've already made it such that the lyrics button was linked to lyrics-plus (can't show because experimental features is on fallback mode) :
![image](https://github.com/spicetify/spicetify-cli/assets/166412725/94bf9276-4506-472e-ad1a-7ab4ba458be9)

anyway hope its fixed by people who know how to code (I mean everyone who brought Spicetify to life and I MEAN EVERYONE)

thanks for listening/reading and please don't dismiss my issue (even if I put it in the wrong place (sorry if I did))

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/166412725/3bc7aeca-dd71-4073-a17b-89ef45fa63e1)

![image](https://github.com/spicetify/spicetify-cli/assets/166412725/73a1c43a-fec6-412b-8c2a-54d9130092b3)

![image](https://github.com/spicetify/spicetify-cli/assets/166412725/8a78fa19-81f9-4843-9b85-a9ae7f1747ca)

**Comment by rxri** [comment]
Per compatibility section in [latest release](https://github.com/spicetify/spicetify-cli/releases/tag/v2.36.3), we do not support Spotify 1.2.35. Downgrade for the time being

**Comment by JerbearGC** [comment]
TYSM, I thought no one would respond (would be kinda a bummer if you were a bot)

Would like to ask tho, how do I downgrade?

**Comment by rxri** [comment]
https://docs.google.com/spreadsheets/d/1wztO1L4zvNykBRw7X4jxP8pvo11oQjT0O5DvZ_-S4Ok

**Comment by JerbearGC** [comment]
Thanks again!

**Comment by rxri** [comment]
Like I said in my first message, 1.2.35 probably changed a code little so our regex to add custom apps do not work anymore - that's why it's unsupported at this moment.
About Genius, it is disabled for 1.2.31 and higher because of internal Spotify changes

**Comment by JerbearGC** [comment]
ahhh I see, thanks for answering!
