### ISSUE TITLE
sidebar colouring incorrect

### ISSUE THREAD

**Issue by ohitstom** [spicetify/spicetify-cli#2964]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (64 bit)
1.2.35.663.gb699649e
Spicetify v2.36.4
xpui_2024-04-05_1712324573103_b699649
cef_122.1.13+gde5b724+chromium-122.0.6261.130
Runtime: Chrome
```

### 📝 Description

when starting spotify with no filters enabled in the sidebar the colours are all wrong - this is not a theme issue and is present with zero addons or otherwise.

I believe this is a similar issue to #2962

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/22730962/054f7da5-f78e-4771-b32b-143573664476)
![image](https://github.com/spicetify/spicetify-cli/assets/22730962/2fe37617-a663-4ca9-b4e9-832eda681348)

**Comment by rxri** [comment]
Already fixed via https://github.com/spicetify/spicetify-cli/commit/84273d1e1666613c6f3fc410d70194c7d9f06a6f
