### ISSUE TITLE
A hello Kitty animation will always be displayed in the window

### ISSUE THREAD

**Issue by todayisyokult** [spicetify/spicetify-cli#2965]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify macOS (Apple Silicon) 版 1.2.35.663.gb699649e

- Spicetify version:Spicetify v2.36.4

- market place version 1.0.1
```

### 📝 Description

After updating to the latest version, it will appear when switching to market place, home page, and search.

### 📸 Screenshots

<img width="715" alt="image" src="https://github.com/spicetify/spicetify-cli/assets/125634462/e9851ed5-7d33-4f46-aa9b-ad7530e19558">

**Comment by rxri** [comment]
That’s not a thing in normal spotify

**Comment by ohitstom** [comment]
this is an option you have enabled in the comfy theme
