### ISSUE TITLE
Update v2.36.4 doesn't support full screen

### ISSUE THREAD

**Issue by RA-L-PH** [spicetify/spicetify-cli#2968]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [x] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.35.663
- Spicetify version:2.36.4
```

### 📝 Description

on clicking the enter full-screen button it displays a blank screen without entering fullscreen

**Comment by rxri** [comment]
Works just fine. If you're using built-in FAD from spotify, then it's premium only. If you're using the FAD from spicetify - most likely you have old version of it
