### ISSUE TITLE
cant open song settings

### ISSUE THREAD

**Issue by Albrt0** [spicetify/spicetify-cli#2969]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 2.36.2
- Spicetify version:2.36.2
- system win 11
- cpu amd ryzen 5 7600
- motherboard A620M Gaming X
- ram kingston DDR-5 5200mhz 2x16GB
- storage Lexar SSD NM620 1TB
```

### 📝 Description

when i try to open setting of any song spotify just crashes and restarts 

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/166955131/45214623-83b7-4807-8a49-9f0a97de31d1)

**Comment by rxri** [comment]
You don't have latest spicetify version so no supported, and also you did not provide valid Spotify version

**Comment by Albrt0** [comment]
Spotify for Windows (32-bit version)
1.2.30.1135.g02fef27a

**Comment by Albrt0** [comment]
> You don't have latest spicetify version so no support, and also you did not provide valid Spotify version

updating did not help

**Comment by rxri** [comment]
That's not related to spicetify though.
Reinstall spotify and run `spicetify backup apply`
or it's extension's fault that you have.

**Comment by Albrt0** [comment]
> That's not related to spicetify though. Reinstall spotify and run `spicetify backup apply` or it's extension's fault that you have.

your right its because of extension but idk which one

**Comment by Albrt0** [comment]
> > That's not related to spicetify though. Reinstall spotify and run `spicetify backup apply` or it's extension's fault that you have.
> 
> your right its because of extension but idk which one

update its because of theme retroblur
