### ISSUE TITLE
Spicetify reinstalling after launching Spotify.

### ISSUE THREAD

**Issue by bananstache** [spicetify/spicetify-cli#2970]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bit)
1.2.35.663.gb699649e
- Spicetify version:
```

### 📝 Description

I use the script to install spicetify "iwr -useb https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.ps1 | iex" Spotify launches like normal. Then I open and reopen spotify, and for some reason it opens the spotify installer. This removes spicetify. And no, when I relaunch spotify without spicetify, it does not open the spotify installer.

**Comment by rxri** [comment]
Not a bug not an issue. Solution can be found on discord
