### ISSUE TITLE
lyrics

### ISSUE THREAD

**Issue by 20klyra** [spicetify/spicetify-cli#2971]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: downloaded from the website
- Spicetify version:
2.36.5
```

### 📝 Description

the beautiful lyrics aren't working at all. I tried updating, deleting, reinstalling and retry the extension but nothing won't work.

### 📸 Screenshots

![Screenshot 2024-04-20 011815](https://github.com/spicetify/spicetify-cli/assets/167582103/c9115ca3-c5b6-4ecd-947f-c843d6407c7f)

**Comment by rxri** [comment]
Not related to cli. https://github.com/surfbryce/beautiful-lyrics/issues/340
