### ISSUE TITLE
Album art not rounded

### ISSUE THREAD

**Issue by WhatClient** [spicetify/spicetify-cli#2975]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (64 bit)
1.2.35.663.gb699649e
Spicetify: v2.36.5
Theme: marketplace
Extensions: adblock.js, volumePercentage.js, popupLyrics.js
Custom apps: marketplace, lyrics-plus
```

### 📝 Description

Album cover art is rounded on the top but not the bottom seems to have started fropm spotify version 1.2.33.1039.g8ddb5918

### 📸 Screenshots

![Capture](https://github.com/spicetify/spicetify-cli/assets/81391354/400e011b-aa72-4270-bafd-55298f1e6970)

**Comment by rxri** [comment]
It never was rounded. It’s not cli related
