### ISSUE TITLE
broken icons after 2.36.6

### ISSUE THREAD

**Issue by kushagra-xo** [spicetify/spicetify-cli#2976]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.31.1205.g4d59ad7c (flatpak)
- Spicetify version: 2.36.6 (aur)
```

### 📝 Description

broken icons

### 📸 Screenshots

![Screenshot_20240422_212538](https://github.com/spicetify/spicetify-cli/assets/106916795/b617471b-a82f-4fbb-9ba1-1d5357829591)

**Comment by rxri** [comment]
Yeah I thought so because I tested the icon component on 1.2.31 before pushing the update
