### ISSUE TITLE
Bug Beautiful Lyrics or lyrics not open on the page

### ISSUE THREAD

**Issue by Fandyfr** [spicetify/spicetify-cli#2980]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bit) 1.2.35.663.gb699649e
- Spicetify version: v2.36.6
```

## **Bug New after updating**
> Bug spicetify Not open the lyrics

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/135007919/3b4881b1-7b82-4c3e-9eae-fdb87d2700ff)
![image](https://github.com/spicetify/spicetify-cli/assets/135007919/67f50d72-bfe8-4c94-b177-6236dc117d19)

**Comment by rxri** [comment]
Not cli related

**Comment by Fandyfr** [comment]
is cli + marketplace

**Comment by rxri** [comment]
No it's not. Beautiful Lyrics is not our extension. Here's the issue url for this: https://github.com/surfbryce/beautiful-lyrics/issues/340
