### ISSUE TITLE
Error when opening extensions (Something went wrong)

### ISSUE THREAD

**Issue by Foxxify1** [spicetify/spicetify-cli#2985]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.35.663.gb699649e
- Spicetify version: v2.36.8
```

### 📝 Description

When I click on a number of extensions (Full App Display, Lyrics, Statistics, etc.) I recieve the error "Something went wrong". This has been happening for maybe a month. I try to stay on top of updating Spicetify. Are there any possible troubleshooting steps I can take?

### 📸 Screenshots

![Something went wrong](https://github.com/spicetify/spicetify-cli/assets/105825997/fc559ae7-3996-4a7b-a06a-d1a9d201355a)

**Comment by rxri** [comment]
Corrupted spotify installation

**Comment by Foxxify1** [comment]
Thanks. I had to reinstall both Spotify and Spicetify to get it to work.
