### ISSUE TITLE
Acces to "custom apps" path was declined

### ISSUE THREAD

**Issue by Benjiexe** [spicetify/spicetify-cli#2987]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: latest
- Spicetify version: latest
```

### 📝 Description

Idk why it says that (picture) and i dont know how to give acces either. 
very cool if someone could help.

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/166851911/befaf32d-ab6a-45ad-ba66-f7e499a65551)

**Comment by Benjiexe** [comment]
![chrome_iR0GSxMoQ1 translated](https://github.com/spicetify/spicetify-cli/assets/166851911/23ed665e-8aac-4901-895a-10d9bcdb4d13)

**Comment by rxri** [comment]
Well... your permissions are fucked up basically. Nothing on our end.

**Comment by Benjiexe** [comment]
the thing is sometimes it works and i had it several times installed and it worked fine really not a problem from spicetify?
