### ISSUE TITLE
Cant Download again after trying to reinstall

### ISSUE THREAD

**Issue by HimmlischesIQ** [spicetify/spicetify-cli#2989]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify für Windows (64 Bit)
1.2.35.663.gb699649e
Spicetify v2.36.8

AMD Ryzen 5 5600X
ASUS PRIME B550M-A
ASUS DUAL RTX 3060 OC V2 LHR
```

### 📝 Description

PS C:\Users\HimmlischesIQ> iwr -useb https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.ps1 | iex
Checking if your PowerShell version is compatible... > OK
Checking if the script wasn't ran as Administrator... > OK
Installing spicetify...
Fetching the latest spicetify version...Invoke-RestMethod : {"message":"API rate limit exceeded for [redacted]. (But here's the good news: Authenticated
requests get a higher rate limit. Check out the documentation for more
details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
In Zeile:88 Zeichen:24
+ ... stRelease = Invoke-RestMethod -Uri 'https://api.github.com/repos/spic ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
PS C:\Users\HimmlischesIQ>

**Comment by rxri** [comment]
You're ratelimited. Wait a few minutes. And do not share your IP address

**Comment by HimmlischesIQ** [comment]
Ok, i just fixxed it when i was just manually deleting the "spicetify" folder in local appdata. TY

**Comment by chessnuts12** [comment]
i js used a vpn on chile
