### ISSUE TITLE
Spotify not automatically restarting when installed as flatpak

### ISSUE THREAD

**Issue by luxbe** [spicetify/spicetify-cli#2991]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.31.1205.g4d59ad7c (Flatpak)
- Spicetify version: 2.36.8
```

### 📝 Description

Install the Spotify Flatpak
Setup spicetify according to the docs
With Spotify running, run `spicetify apply` or a similar command that should trigger Spotify to restart
Spotify closes but does not restart automatically

The problem is within `EvalSpotifyRestart` in `restart.go`. Here the filepath to the Spotify application is constructed and opened. This however is not possible when the application is installed as a Flatpak, because the application itself is not executable directly. Instead `flatpak run com.spotify.Client ...` should be called.

**Comment by rxri** [comment]
There's no reliable way of detecting `flatpak` installations since you can choose the directory by yourself and it can be named whatever. We will probably do something about it in `v3` but as of right now - we won't consider fixing it because it would also require handling all exceptions. Sorry!
