### ISSUE TITLE
Beautiful Lyrics misplacement/blank/not showing

### ISSUE THREAD

**Issue by emnsxyz24** [spicetify/spicetify-cli#2992]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.35.663.gb699649e
- Spicetify version:v2.36.8
```

### 📝 Description

so the beautiful lyrics not showing correctly (blank space) but showing on "Now playing view" look at the picture i attach. the lyrics shown at the right side of the spotify, i don't know is it bug or what i hope there's a fix for this

### 📸 Screenshots

![Screenshot 2024-04-29 144901](https://github.com/spicetify/spicetify-cli/assets/83565196/404f46a1-a8da-4668-b05b-15eef53651a4)

**Comment by rxri** [comment]
Beautiful Lyrics has nothing to do with CLI. Developer's fault, not ours.
