### ISSUE TITLE
v2.36.8 black screen when applied to 1.2.35.663

### ISSUE THREAD

**Issue by working-name** [spicetify/spicetify-cli#2993]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.35.663
- Spicetify version: v2.36.8
```

### 📝 Description

Ran spicetify (as I did the last 2 times this happened on macOS and windows), and then I got a black screen. You usually close these threads and paste the same crap: reinstall spotify and do `backup apply` and some other ones `restore backup apply`. Neither commands fix it. 

Once you apply spicetify it breaks Spotify. If you do a `restore`, you still get a black screen, which makes me think you're not really restoring the unmodified app, there's something wrong with spicetify. It's probably holding on to a dumb previous version that's actually modified.

The only way to get this going again - learned from experience - is to obliterate the spicetify folder, and the spotify app and re-download it, then get spicetify going again, try to find my template, add the no ads thing... ugh. It gets old.

Can you do something about it?

#2682 #2679 #2639 #2624 #2555 #2458 #1649 #1625 #1570 #1542 #1475 #1466 ... and so on

### 📸 Screenshots

<img width="799" alt="image" src="https://github.com/spicetify/spicetify-cli/assets/16505052/6fff1c3e-2f46-4c69-b0de-45a6c969fdff">

**Comment by rxri** [comment]
There's no issue with spicetify on `1.2.35` meaning you're looking for help. Since you need one, please join our discord server because we do not provide support here.

**Comment by working-name** [comment]
Wow, you're really fast at attempting to recreate bugs!

I'm submitting a bug report, not asking for help. I know how to fix it, as I said. I don't think it's a feasible workflow to reinstall spicetify every time there's a spotify update. 

Spicetify is no doubt caching busted versions of spotify and fails to fully apply modifications. So maybe give it a look?

**Comment by rxri** [comment]
I already told you that it's not an issue with Spicetify.
This version is known to work correctly with the version you're mentioning because I also use it on the version the version mentioned and `1.2.36` (higher one). This bug report is invalid then.
Spicetify backups the unmodified files of clean installation, it does not store modified files so, if you somehow managed to backup modified files - that's not our fault.

**Comment by working-name** [comment]
This is a misunderstanding. I said spicetify is caching screwed up versions of spotify and incorrectly applying modifications. It can't even restore Spotify back to a working condition!

I didn't say a fresh install of spicetify applied to a fresh install of spotify HAS A BUG. And this is what you're saying right now, which I agree with, because that's how you fix the issue, as I stated in my initial post.

**Comment by Delusoire** [comment]
Mind sharing more than just: `This broken? Need fix`.
For this to be a proper bug report, we need a report of the steps that you took when trying to "use" and "repair" spicetify.
You can start by showing us the CLI output of the aforementioned commands.

**Comment by rxri** [comment]
That's again not our fault. Spicetify checks the version of backup and the installed version and will throw an error if you're trying to restore the backup to higher version
![image](https://github.com/spicetify/spicetify-cli/assets/9348108/2be350d9-2840-4991-8404-ca35f4645200)
This is clearly a user fault, I do not know what you typed into the terminal, so I can't really tell you exactly what you screwed up.

**Comment by ohitstom** [comment]
he's not reporting a bug as far as I can tell and is instead saying the entire current system for backups is broken because of his own user error (backing up an old version of Spotify and restoring into it on a newer version of Spotify)

**Comment by working-name** [comment]
> Mind sharing more than just: `This broken? Need fix`. For this to be a proper bug report, we need a report of the steps that you took when trying to "use" and "repair" spicetify. You can start by showing us the CLI output of the aforementioned commands.

Fair. I can't get you the output of the commands because I didn't save that. What I can tell you is I didn't see an error. It proceeded as usual, but resulted in a black screen.

Here's what I can pull from the scrolling buffer.

### After I re-downloaded Spotify, and obliterated ~/Library/Application Support/ and ~/Library/Prefernces/ ... stuff related to Spotify. I didn't touch spicetify's folder. Ran `backup apply` [as instructed](https://github.com/spicetify/spicetify-cli/issues/2682#issuecomment-1826809614).

```
% sudo spicetify backup apply
Password:
spicetify v2.36.8
info Spicetify up-to-date
info There is available backup.
info Clear current backup:
success Backup is cleared.
Backing up app files:
OK
Extracting:
OK
Preprocessing:
info Fetching remote CSS map for newer compatible tag version: master
OK
OK
success Everything is ready, you can start applying now!
Copying raw assets:
OK
Overwriting themed assets:
OK
success Custom CSS is updated
Applying additional modifications:
OK
Transferring extensions:
success 15:36:34 All extensions are updated.
OK
success Spotify is spiced up!
```

Started Spotify, black screen.

```
% sudo spicetify restore
spicetify v2.36.8
info Spicetify up-to-date
success Spotify is restored
```

Spotify still has a black screen. Can't open console, no options to do anything, tried troubleshooting from help, disabled acceleration, reload. No change. I thought maybe I didn't upgrade spicetify?

```
% sudo spicetify upgrade
spicetify v2.36.8
Fetch latest release info:
OK
info Current version: 2.36.8
info Latest release: 2.36.8
success Already up-to-date.
```

@rxri No error on restore, it does it, but then spotify has a black screen. I wish you'd read what I typed...

So I don't see exactly where spicetify had a chance to store a borked version because of user error, if I am to trust the output of your tool, stating that it cleared the prior backup. Therefore it should have backed up the official, clean Spotify, which opened fine and was able to log in.

**Comment by rxri** [comment]
Your fault is that you're running spicetify in sudo - when you're not supposed to.

**Comment by working-name** [comment]
> Like I have said, you cannot restore to higher version if backup was made on lower version so I don't know what happened here, but that's not our fault. Though, he is blaming us that spicetify cannot restore stock spotify, which is untrue because like I have mentioned in my second message;
> 
> > Spicetify backups the unmodified files of clean installation, it does not store modified files so, if you somehow managed to backup modified files - that's not our fault

Nothing was modified between commands.

**Comment by working-name** [comment]
> Your fault is that you're running spicetify as sudo (root) - when you're not supposed to. It literally breaks permissions of modified files

So... that only matters when you "upgrade" spicetify?

**Comment by rxri** [comment]
You're not supposed to use `sudo` with spicetify, EVER. It matters in every single situation. You should run `spicetify` as your own account, not as root. Running spicetify with `sudo` causes every single modified file by `spicetify` to be owned by `root` which your account does not have access to read causing black screen in Spotify client

**Comment by working-name** [comment]
Okay, perfect. It is my fault, I apologize. Thanks for the tip.

```shell
% sudo rm -rf /Applications/Spotify.app

# change ownership
% sudo chown -R user:staff ~user/.spicetify
% sudo chown -R user:staff ~user/.config/spicetify

#re-downloaded official Spotify app. App opens, session still exists.

# backup apply
% spicetify backup apply
spicetify v2.36.8
info Spicetify up-to-date
info There is available backup.
info Clear current backup:
success Backup is cleared.
Backing up app files:
OK
Extracting:
OK
Preprocessing:
info Fetching remote CSS map for newer compatible tag version: master
OK
OK
success Everything is ready, you can start applying now!
Copying raw assets:
OK
Overwriting themed assets:
OK
success Custom CSS is updated
Applying additional modifications:
OK
Transferring extensions:
success 16:13:05 All extensions are updated.
OK
success Spotify is spiced up!

# Spotify opens ok.
```

**Comment by rxri** [comment]
Thank you for apologizing. Continue enjoying spicetify as you did before ^^
