### ISSUE TITLE
lyrics-plus not loading on latest version of spicetify on Mac, similar to #980

### ISSUE THREAD

**Issue by Sinhran** [spicetify/spicetify-cli#2994]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for macOS (Intel)
1.2.35.663.gb699649e
- Spicetify version:v2.36.8
```

### 📝 Description

Upon clicking the lyrics-plus icon, instead of showing lyrics, "Something went wrong" page appears. The latest version of spicetify is already installed. The "Something went wrong" page persists if I click any other tab after clicking on lyrics-plus. I changed the theme as one of the issues mentioned that as solution but the issue persists.

### 📸 Screenshots

<img width="307" alt="image" src="https://github.com/spicetify/spicetify-cli/assets/78912276/160280d5-bee3-4636-a0a3-89a30d416c1f">
<img width="1440" alt="image" src="https://github.com/spicetify/spicetify-cli/assets/78912276/55b1f55b-f0c4-47f8-8177-3831352a82de">

**Comment by rxri** [comment]
Configuration error. Support is available on our discord server
