### ISSUE TITLE
Sidebar config update leaves silhouette of original playlist sidebar

### ISSUE THREAD

**Issue by AkashNama** [spicetify/spicetify-cli#2997]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: unknown
- Spicetify version: v2.36.9
```

### 📝 Description

changed sidebar config and error occurred (drear theme)

### 📸 Screenshots

<img width="239" alt="image" src="https://github.com/spicetify/spicetify-cli/assets/45539304/24d71b30-b3b3-472f-98e6-ac0a530a3a84">

**Comment by rxri** [comment]
That's a styling (theme)'s fault
