### ISSUE TITLE
[Bug] Marketplace HTTP error

### ISSUE THREAD

**Issue by SkyKingPX** [spicetify/spicetify-cli#2998]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.35.663.gb699649e
- Spicetify version: 2.36.9
```

### 📝 Description

When trying to open the Marketplace it doesn't show the tabs and shows the HTTP 403 Error.
And the Header is also bugged.

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/95442431/fd807b32-f3ee-44b3-91b8-eb301c406cba)
![image](https://github.com/spicetify/spicetify-cli/assets/95442431/06ef88fd-f7bb-4d75-8d79-6e2e6bf647a9)

**Comment by rxri** [comment]
Not related to cli. 403 means no access so it's not related to marketplace either
