### ISSUE TITLE
spicetify command doesn't work

### ISSUE THREAD

**Issue by Sxtrxx** [spicetify/spicetify-cli#2999]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.5.1006.g22820f93-1078
- Spicetify version: 2.23.1
Platform : Windows 7 64bit (i can't update it for variety of reason)
```

### 📝 Description

**install v2.32.1 (with administrator powershell)**
$v="2.32.1"; Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.ps1" | Invoke-Expression
spicetify is successfully installed!

**run any spicetify command,**
spicetify apply
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime.asmstdcall()
        /opt/hostedtoolcache/go/1.21.7/x64/src/runtime/sys_windows_amd64.s:65 +0x75 fp=0x22fca0 sp=0x22fc80 pc=0x468bf5
rax     0x0
rbx     0x995280
rcx     0x9e8fc0
rdi     0x7fffffdd000
rsi     0x22fea0
rbp     0x22fde0
rsp     0x22fc78
r8      0x0
r9      0x22fee0
r10     0x9bae18
r11     0x21
r12     0x22fec0
r13     0x1
r14     0x994c20
r15     0x0
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b

**Comment by rxri** [comment]
We do not support windows 7 anymore as versions 1.2.13 to 1.2.36 do not support this windows version either

**Comment by Sxtrxx** [comment]
it says that spicetify v2.32.1 (which the one that i try to install) support spotify 1.2.0 to 1.2.31 (spotify 1.2.5.100 run smoothly without any problem)
or maybe it's the spicetify that doesn't support the win7?.
any version which still support win7 then?

**Comment by Sxtrxx** [comment]
nvm fixed it
spicetify v2.28.1 works

thanks for the help
