### ISSUE TITLE
Manifest file is invalid Could not load manifest

### ISSUE THREAD

**Issue by Minedude33Gaming** [spicetify/spicetify-cli#3004]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Unknown
- Spicetify version: v2.36.10
```

### 📝 Description

When following the instructions to install the Lyrics+ extension, it presents me with this error message. I have checked that indeed the manifest file is spelled correctly and is a JSON file, despite these parameters, the error still persists. It prevents me from finishing the installation properly.

### 📸 Screenshots

![image_2024-05-02_183718213](https://github.com/spicetify/spicetify-cli/assets/58994664/87ecc4dc-2745-429a-bad3-3f991c3e4220)

**Comment by rxri** [comment]
Spicetify is not an extension to your chrome browser...

**Comment by Minedude33Gaming** [comment]
This is for the Lyrics+ extension, because I don't really know where else to ask help from

**Comment by rxri** [comment]
Neither the Lyrics+ is. You're not supposed to load any extension for spicetify in the browser
