### ISSUE TITLE
Original Spotify Lyrics not working😢

### ISSUE THREAD

**Issue by ani9730** [spicetify/spicetify-cli#3007]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
System Info:
Processor	13th Gen Intel(R) Core(TM) i7-13700HX   2.10 GHz
Installed RAM	16,0 GB (15,7 GB usable)
System type	64-bit operating system, x64-based processor

Spotify for Windows (64 bit):
1.2.36.959.g04bf500c
Spicetify: v2.36.10
```

### 📝 Description

In the previous version of Spotify, i was able to see popup synced lyrics in the NPV, it was working great. But now, i am getting a premium page for lyrics. So is there any fix for it?
What could be the reason for it. I saw many previous issues, but most of them are related to lyrics plus. Please confirm if this is a bug or a new change in latest update of Spotify.

### 📸 Screenshots

![Screenshot 2024-05-04 095504](https://github.com/spicetify/spicetify-cli/assets/120796659/055ef526-9e11-4566-a341-f89e72aeedd8)

**Comment by rxri** [comment]
Not related to spicetify
