### ISSUE TITLE
error in powershell when installing or others

### ISSUE THREAD

**Issue by GRHUB-OFFICIAL** [spicetify/spicetify-cli#3008]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: i dont know 
- Spicetify version: i dont know
```

### 📝 Description

I don't show the whole error because it has my IP address

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/145355536/ed23e94e-f06c-4040-b2cf-9e73febc0c74)

**Comment by rxri** [comment]
Wait some time then. Not an issue from our end
