### ISSUE TITLE
No tab are shown

### ISSUE THREAD

**Issue by Perndoe** [spicetify/spicetify-cli#3009]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.36.959
- Spicetify version: 2.36.10
```

### 📝 Description

No extensions tabs or any other whatsoever when access the marketplace

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/81963564/ee84961e-46f8-4a9c-b8ae-c238272e4896)

**Comment by rxri** [comment]
Not related to cli. Update marketplace by installing it again

**Comment by Perndoe** [comment]
> Not related to cli. Update marketplace by installing it again

Oops
(thats fast btw)
