### ISSUE TITLE
[Lyrics plus] Completly wrong lyrics

### ISSUE THREAD

**Issue by LoganWolfie** [spicetify/spicetify-cli#3013]
```Markdown
Spotify for Windows (64 bit)
1.2.36.959.g04bf500c
Spicetify v2.36.10
```

### 📝 Description

Some songs have wrong lyrics / lyrics from other songs on the album.

On "XXX. FEAT. U2." It has the lyrics for "LOVE. FEAT. ZACARI."

### 📸 Screenshots
<img width="1549" alt="image" src="https://github.com/spicetify/spicetify-cli/assets/72407034/6c9f0d10-6789-460c-82cc-8e2d385cbf0b">

**Comment by rxri** [comment]
Musixmatch’s fault
