### ISSUE TITLE
Spotify crashing

### ISSUE THREAD

**Issue by NikitaMiroshnihenko** [spicetify/spicetify-cli#3014]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Newest 
- Spicetify version: Newest
```

### 📝 Description

After the update, when I go to any playlist, Spotify crashes

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/54524849/cef130c5-fc89-47af-a7a8-386e8df3f794)

**Comment by rxri** [comment]
“Newest” doesn’t exist. Most likely isn’t related to spicetify
