### ISSUE TITLE
Shuffle+ Fails when connected to another device

### ISSUE THREAD

**Issue by VikaasVarma** [spicetify/spicetify-cli#3015]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for macOS (Apple Silicon) 1.2.37.701.ge66eb7bc
- Spicetify version: v2.36.11
```

### 📝 Description

Shuffling liked songs specifically with shuffle+ when connected to another device (my room speakers) does not work as expected. It gives the messages but does not shuffle the queue.
 - Shuffled 1613 songs
 - Spotify can't play this right now. If you have the file on your computer you can import it.

Additionally, when shuffling playlist locally with shuffle+, and then switching devices resets the queue.

**Comment by rxri** [comment]
Well, yea. We do not really support when playing on other devices, sorry. It's like a limitation
