### ISSUE TITLE
Lyrics doesn't load 

### ISSUE THREAD

**Issue by Shehapp** [spicetify/spicetify-cli#3020]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 
- Spicetify version:
```

### 📝 Description

Lyrics takes time loading and i get "Couldn't load the lyrics for this song. Try again later"

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-cli/assets/88383557/55d636b1-8cb7-465c-8174-e71f7c306fed)

**Comment by rxri** [comment]
Not cli or lyrics plus related
