### ISSUE TITLE
Page title superimposed on the selector

### ISSUE THREAD

**Issue by pagottoeros** [spicetify/spicetify-cli#3022]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bit) 1.2.37.701.ge66eb7bc
- Spicetify version: 2.36.11
```

### 📝 Description

Install a custom app (for example Reddit), open the custom app to see that the title of the page is overlaid by the selector

### 📸 Screenshots

![noRx6yWvZ7](https://github.com/spicetify/spicetify-cli/assets/69042402/b749b551-1c8a-400d-b88a-e406da5dbfef)

![o307MAqn0a](https://github.com/spicetify/spicetify-cli/assets/69042402/95eaffc5-1c71-4488-8a36-138cb2333303)

![CSuTLuVE8C](https://github.com/spicetify/spicetify-cli/assets/69042402/cc56e674-9742-4d2d-8989-ca4fd07ba814)

**Comment by rxri** [comment]
Known - won't be fixed in v2. It's related to `spcr-navigation-bar` and other things. Either way, with our components it will be fixed in v3
