### ISSUE TITLE
[lyrics plus] lyrics in sidebar\separate panel

### ISSUE THREAD

**Issue by staticanimal** [spicetify/spicetify-cli#3023]
### 📝 Provide a description of the new feature

basically a way to show the lyrics from lyrics plus either in the sidebar\now playing view like how spotify's integrated lyrics used to work or within their own separate panel to allow both the tracklist and the lyrics to be on screen simultaneously.

**Comment by rxri** [comment]
We do not have ability to add new Panel(s) because Spotify removed ability to do.
