### ISSUE TITLE
any possibility to make it compatible with WebOS armv7l architecture (on a rooted/jailbroken tv)?

### ISSUE THREAD

**Issue by llbranco** [spicetify/spicetify-cli#3025]
### 📝 Provide a description of the new feature

Since I started working on this project, and with the recent PS4 jailbreak the subject (and consequently my project) that things is on the hype
https://github.com/llbranco/PPLGPwn
https://github.com/zauceee/PPLGPwn

(demo/guide) https://www.youtube.com/watch?v=zYoesrUsIj8
a lot of  people are starting to discorver a "new world" behind a jailbroken tv
https://twitter.com/frwololo/status/1790509510148387138

is it possible to  port or make spicetify compatible to a rooted WebOs tv?
thank you

**Comment by rxri** [comment]
No. No android/webOS/iOS support ever
