### ISSUE TITLE
Genius Lyrics blank on last version

### ISSUE THREAD

**Issue by Ed3151** [spicetify/spicetify-cli#3031]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.13.661.ga588f749
- Spicetify version:2.36.11
```

### 📝 Description

Genius lyrics showing blank on this version please kindly solve the issue

**Comment by rxri** [comment]
That's not related to us? It's genius fault if it doesn't respond with anything

**Comment by Ed3151** [comment]
its not because old version is working fine

**Comment by rxri** [comment]
We did not change how genius works

**Comment by hexandcube** [comment]
Spotify uses lyrics from Musixmatch, not Genius. Looks like they've now made Lyrics a premium-only feature.

**Comment by rxri** [comment]
> Spotify uses lyrics from Musixmatch, not Genius. Looks like they've now made Lyrics a premium-only feature.

No one mentioned that they do. This issue is about lyrics-plus' provider

**Comment by Ed3151** [comment]
//const query = new URLSearchParams({ per_page: 20, q: encodeURIComponent(`${title} ${info.artist}`) });
			//const url = `https://genius.com/api/search/song?${query.toString()}`;
			
			const url = `https://genius.com/api/search/song?per_page=20&q=${encodeURIComponent(title)}%20${encodeURIComponent(info.artist)}`;
