### ISSUE TITLE
My spotify just went blank, Please help me!

### ISSUE THREAD

**Issue by samueljebaraj** [spicetify/spicetify-cli#3032]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.37.701
- Spicetify version:2.36.6
```

### 📝 Description

I installed an extension called ,"Beautiful lyrics". Since then, My spotify is like this

### 📸 Screenshots

![Screenshot (1)](https://github.com/spicetify/spicetify-cli/assets/158616598/f625607a-09e3-4c1b-8484-2ad3e73322f1)

**Comment by rxri** [comment]
Not related to spicetify. Contact the developer of this extension

**Comment by samueljebaraj** [comment]
> Not related to spicetify. Contact the developer of this extension

Is there any way to uninstall all extensions at once, without using spotify UI, but by using cmd or something?

**Comment by rxri** [comment]
If extension was installed via marketplace you need to:
1. Run `spicetify enable-devtools`
2. Right click anywhere and click `Inspect`
3. Go to console and type `Marketplace.reset("extensions")`

**Comment by samueljebaraj** [comment]
Thanks, it worked!

**Comment by jluby** [comment]
Hi - I have a similar issue but the Marketplace.reset("extensions") approach didn't work. I created custom CSS which seems to have locked my Spotify (when spicetify is applied). Any advice?

<img width="1723" alt="Screenshot 2024-07-17 at 2 52 35 PM" src="https://github.com/user-attachments/assets/170405d6-b0b5-4f6c-af6f-c1d00ec55a02">

**Comment by rxri** [comment]
> Hi - I have a similar issue but the Marketplace.reset("extensions") approach didn't work. I created custom CSS which seems to have locked my Spotify (when spicetify is applied). Any advice?
> 
> 
> 
> <img width="1723" alt="Screenshot 2024-07-17 at 2 52 35 PM" src="https://github.com/user-attachments/assets/170405d6-b0b5-4f6c-af6f-c1d00ec55a02">

Run `Marketplace.reset("snippets")` or `Marketplace.reset()`
